"""Regressions for documentation roles and prepared-schema dependency integrity.

Run: python -B -m unittest discover -s docs/testing -p 'test_documentation.py'
Fixtures are isolated beneath the repository's temporary directory.
"""

from pathlib import Path
import json
import tempfile
import unittest

from check_docs import document_role, terminology_problems, visible_lines
from database.generated_inputs import (
    HEADER, MANIFEST, authored_requirements, digest, untracked_paths,
    verify_outputs, verify_pins,
)

ROOT = Path(__file__).resolve().parents[2]
GENERATED = "libraries/schema/src/postgres/wiki/pages.generated.ts"
PRODUCER = "libraries/schema/model/storage/wiki.ts"


class DocumentationRoles(unittest.TestCase):
    def test_target_terms_but_not_implementation_evidence(self):
        source = "Public Units use the selected Entity and current Profile selector."
        self.assertTrue(terminology_problems("docs/architecture/example.md", source))
        for owner in ("reference", "releases", "testing", "legal", "operations"):
            self.assertEqual(terminology_problems(f"docs/{owner}/example.md", source), [])

    def test_generic_entity_validation_profile_and_measurement_units_remain_valid(self):
        text = "Generic Entity has optional types. Profile validation preserves measurement units."
        self.assertEqual(terminology_problems("docs/architecture/example.md", text), [])

    def test_exact_identifiers_and_destinations_are_not_target_prose(self):
        text = "Resource uses `Unit` and ``public Entity``. [Source](https://example.org/Unit)\n```ts\ninterface Unit {}\n```"
        self.assertEqual(terminology_problems("docs/architecture/example.md", text), [])

    def test_short_nested_fence_does_not_expose_source_example(self):
        text = "````md\n```ts\nUnit\n```\n````\nResource"
        self.assertEqual([line for _, line in visible_lines(text) if line], ["Resource"])
        self.assertEqual(terminology_problems("docs/architecture/example.md", text), [])

    def test_roles_preserve_historical_and_generated_owners(self):
        self.assertEqual(document_role("docs/architecture/schema-modeling.md"), "target")
        self.assertEqual(document_role("docs/reference/current-implementation.md"), "implementation")
        self.assertEqual(document_role("docs/architecture/database/capacity.md"), "generated")
        self.assertEqual(document_role("docs/releases/1.6.0.md"), "release")


class PreparedSchemaInputs(unittest.TestCase):
    def setUp(self):
        temporary = ROOT / ".temp"
        temporary.mkdir(exist_ok=True)
        self.fixture = tempfile.TemporaryDirectory(prefix="docs-input-regression-", dir=temporary)
        self.addCleanup(self.fixture.cleanup)
        self.root = Path(self.fixture.name).resolve()
        self.content = HEADER + "export const declaration = 1;\n"
        self.write(GENERATED, self.content)
        self.write(PRODUCER, "export const storage = {};\n")
        self.expected = [{"path": GENERATED, "content": self.content}]

    def write(self, name, content):
        path = self.root / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    def test_ignored_registered_output_still_requires_tracked_producer(self):
        outputs = verify_outputs(self.root, self.expected)
        prepared = {"derivatives_sha256": outputs, "producer_inputs_sha256": {PRODUCER: "hash"}}
        required = authored_requirements({GENERATED}, prepared)
        self.assertEqual(untracked_paths(self.root, required, [], {PRODUCER}), [])
        self.assertEqual(untracked_paths(self.root, required, [], set()), [PRODUCER])

    def test_unregistered_generated_file_is_rejected_even_if_bytes_match(self):
        self.write("libraries/schema/src/postgres/wiki/extra.generated.ts", self.content)
        with self.assertRaisesRegex(ValueError, "Unregistered"):
            verify_outputs(self.root, self.expected)

    def test_another_generators_tracked_snapshot_is_not_an_ignored_file_exemption(self):
        other = "libraries/schema/src/postgres/identity/auth-oauth.generated.ts"
        self.write(other, "// Generated by a separate protocol generator.\n")
        outputs = verify_outputs(self.root, self.expected, frozenset({other}))
        self.assertNotIn(other, outputs)
        prepared = {"derivatives_sha256": outputs, "producer_inputs_sha256": {PRODUCER: "hash"}}
        required = authored_requirements({GENERATED, other}, prepared)
        self.assertEqual(untracked_paths(self.root, required, [], {PRODUCER}), [other])
        with self.assertRaisesRegex(ValueError, "Unregistered"):
            verify_outputs(self.root, self.expected)

    def test_tracking_an_orphaned_model_output_does_not_hide_it(self):
        other = "libraries/schema/src/postgres/wiki/orphan.generated.ts"
        self.write(other, self.content)
        with self.assertRaisesRegex(ValueError, "Unregistered"):
            verify_outputs(self.root, self.expected, frozenset({other}))

    def test_missing_derivative_cannot_disappear_from_inventory(self):
        (self.root / GENERATED).unlink()
        with self.assertRaisesRegex(ValueError, "Missing"):
            verify_outputs(self.root, self.expected)

    def test_modified_body_or_marker_cannot_be_regenerated_into_design_metadata(self):
        for content in (self.content + "// tampered\n", "export const declaration = 1;\n"):
            with self.subTest(content=content):
                self.write(GENERATED, content)
                with self.assertRaisesRegex(ValueError, "differs from production emitter"):
                    verify_outputs(self.root, self.expected)

    def test_duplicate_or_escaping_registration_is_rejected(self):
        for expected in (self.expected * 2, [{"path": "../outside.generated.ts", "content": self.content}]):
            with self.subTest(expected=expected):
                with self.assertRaisesRegex(ValueError, "Invalid or duplicate"):
                    verify_outputs(self.root, expected)

    def test_symlink_cannot_stand_in_for_generated_storage(self):
        self.write("other.ts", self.content)
        path = self.root / GENERATED
        path.unlink()
        path.symlink_to(self.root / "other.ts")
        with self.assertRaisesRegex(ValueError, "Symlinked"):
            verify_outputs(self.root, self.expected)

    def test_other_untracked_dependency_is_not_exempt_by_suffix(self):
        extra = "libraries/schema/src/postgres/wiki/manual.generated.ts"
        self.write(extra, self.content)
        prepared = {"derivatives_sha256": {GENERATED: "hash"}, "producer_inputs_sha256": {PRODUCER: "hash"}}
        required = authored_requirements({GENERATED, extra}, prepared)
        self.assertEqual(untracked_paths(self.root, required, [], {PRODUCER}), [extra])

    def test_pinned_bytes_are_verified_without_network(self):
        name = "libraries/schema-importer/sources/schema.ttl"
        content = b"@prefix schema: <https://schema.org/> .\n"
        self.write(name, content.decode())
        self.write(MANIFEST, json.dumps({"format": 1, "sources": [{
            "file": "schema.ttl", "bytes": len(content), "sha256": digest(content),
        }]}))
        self.assertEqual(verify_pins(self.root), {name: digest(content)})
        self.write(name, "changed")
        with self.assertRaisesRegex(ValueError, "Pinned vocabulary bytes differ"):
            verify_pins(self.root)


if __name__ == "__main__":
    unittest.main()
