import { UnitReferenceConsumers } from "../unit-reference-consumers";

export const PostgreSqlSchemaFileNames = [
	"catalog-editorial.sql",
	"post-integrity.sql",
	"platform-aggregates.sql",
	"search-document-support.sql",
	"governance-integrity.sql",
	"governance-delivery.sql",
	"history-integrity.sql",
	"reference-value.sql",
	"access-identity.sql",
	"api-key-authority.sql",
	"identity-preference.sql",
	"account-identity-admission.sql",
	"connected-app.sql",
	"oauth-client-authority.sql",
	"workload-principal.sql",
	"connected-app-client.sql",
	"oauth-client-secret-policy.sql",
	"connected-installation.sql",
	"connected-user-authorization.sql",
	"oauth-grant-context.sql",
	"access-subject-policy.sql",
	"access-role.sql",
	"access-role-binding.sql",
	"access-assignment-ceiling.sql",
	"access-representation.sql",
	"access-current-policy.sql",
	"access-membership.sql",
	"access-group.sql",
	"access-group-membership.sql",
	"access-group-impact.sql",
	"account-tag-reference.sql",
	"revision-reference.sql",
	"association-proposal-authority.sql",
	"music-release-source-job.sql",
	"catalog-definition-governance.sql",
	"recommendation-build.sql",
	"content-structure-budgets.sql",
	"realm-publication-governance.sql",
	"content-metrics.sql",
	"merge-integrity.sql",
	"unit-reference-integrity.sql",
	"unit-state-read.sql",
	"organization-membership.sql",
	"participation-integrity.sql",
	"participation-follow.sql",
	"participation-private-state.sql",
	"participation-studio.sql",
	"participation-progress.sql",
	"participation-messages.sql",
	"participation-notifications.sql",
	"catalog-distribution-integrity.sql",
	"catalog-music-history.sql",
	"music-source-lifecycle.sql",
	"catalog-name-integrity.sql",
	"catalog-name-search.sql",
	"catalog-semantics-integrity.sql",
	"catalog-software-history.sql",
	"catalog-software-participation-integrity.sql",
	"catalog-source-integrity.sql",
	"catalog-structure-source.sql",
	"catalog-source-correspondence.sql",
	"catalog-source-support.sql",
	"catalog-source-dependency.sql",
	"catalog-definition-terms.sql",
	"catalog-source-application.sql",
	"catalog-source-multipart.sql",
	"catalog-source-owned-baseline.sql",
	"catalog-profile-source.sql",
	"catalog-structure-history.sql",
	"catalog-child-source.sql",
	"catalog-supporting-integrity.sql",
	"operational-runtime.sql",
	"catalog-credit-integrity.sql",
	"catalog-integrity.sql",
	"catalog-domain-integrity.sql",
	"catalog-software-context-integrity.sql",
	"operational-durability.sql",
	"content-label-policy.sql",
	"content-language-search.sql",
	"custom-theme-integrity.sql",
	"realm-tag-authority.sql",
	"tag-judgment-aggregates.sql",
	"tag-path.sql",
	"tag-path-search.sql",
	"unit-license-grant.sql",
	"unit-search-document.sql",
	"native-bootstrap.sql",
] as const;

export type PostgreSqlSchemaFileName = (typeof PostgreSqlSchemaFileNames)[number];

/**
 * Release migrations may install one atomic domain cutover while the canonical
 * PostgreSQL definitions remain split by responsibility for review and drift checks.
 */
export const PostgreSqlSchemaMigrationBundles: Readonly<Record<string, readonly PostgreSqlSchemaFileName[]>> = {
	connected_installations: ["connected-installation.sql", "connected-app-client.sql", "access-current-policy.sql"],
	connected_app_clients: ["connected-app.sql", "connected-app-client.sql"],
	workload_principals: ["workload-principal.sql", "access-current-policy.sql", "participation-integrity.sql"],
	management_authority: ["api-key-authority.sql", "access-current-policy.sql"],
	access_role_binding_readers: ["access-membership.sql", "access-role-binding.sql"],
	studio_visit_reference_values: ["unit-reference-integrity.sql", "merge-integrity.sql"],
	following_reference_values: ["unit-reference-integrity.sql", "participation-follow.sql", "platform-aggregates.sql", "merge-integrity.sql"],
	recommendation_event_reference_values: ["unit-reference-integrity.sql", "participation-private-state.sql"],
	merge_review_authority: ["merge-integrity.sql"],
	realm_member_count_decrement: ["platform-aggregates.sql"],
	recommendation_exclusion_reference_values: ["unit-reference-integrity.sql", "merge-integrity.sql"],
	favorite_reference_values: ["reference-value.sql", "unit-reference-integrity.sql", "participation-private-state.sql"],
	account_tag_reference_values: ["unit-reference-integrity.sql", "account-tag-reference.sql"],
};

export const PostgreSqlSchemaFunctionNames = [
	"touch_access_impact_fences",
	"guard_access_impact_fence",
	"guard_oauth_refresh_family",
	"oauth_grant_context_payload_is_current",
	"oauth_grant_context_is_current",
	"guard_oauth_grant_context",
	"attach_oauth_grant_context",
	"guard_oauth_token_context_link",
	"guard_oauth_token_identity",
	"connected_user_consent_owner",
	"require_connected_user_erasure",
	"guard_connected_user_connection",
	"guard_connected_user_connection_event",
	"guard_connected_user_consent",
	"guard_connected_user_consent_event",
	"guard_connected_user_consent_revision",
	"guard_connected_user_consent_member",
	"complete_connected_user_authorization",
	"guard_connected_installation_head",
	"guard_connected_installation_event",
	"guard_connected_installation_revision",
	"guard_connected_installation_member",
	"complete_connected_installation",
	"connected_app_is_eligible",
	"connected_installation_is_eligible",
	"guard_oauth_client_secret_policy",
	"guard_oauth_client_secret_event",
	"complete_oauth_client_secret_policy",
	"oauth_client_secret_is_current",
	"connected_app_client_terms_match_protocol",
	"guard_connected_app_client_head",
	"guard_connected_app_client_event",
	"guard_connected_app_client_revision",
	"guard_connected_app_client_capability",
	"complete_connected_app_client",
	"guard_workload_principal",
	"guard_workload_principal_event",
	"complete_workload_principal",
	"guard_interactive_principal_credential",
	"access_principal_account_is_eligible",
	"workload_principal_is_eligible",
	"guard_oauth_client_authority",
	"fence_oauth_client_authority",
	"guard_connected_app_head",
	"guard_connected_app_event",
	"guard_connected_app_revision",
	"guard_connected_app_capability",
	"complete_connected_app",
	"guard_account_identity_admission",
	"access_subject_is_eligible",
	"access_subject_matches_recipient",
	"access_representation_path_is_current",
	"guard_api_key_authority",
	"fence_api_key_authority",
	"guard_access_assignment_ceiling",
	"guard_access_assignment_ceiling_permission",
	"guard_access_assignment_ceiling_event",
	"complete_access_assignment_ceiling",
	"guard_identity_preference",
	"identity_preference_representations_match",
	"guard_identity_preference_representation",
	"guard_identity_preference_event",
	"complete_identity_preference",
	"fence_access_subject_policy",
	"access_representation_recipient_is_current",
	"access_representation_parent_basis_is_current",
	"access_representation_terms_narrower",
	"access_representation_lineage",
	"lock_access_representation_lineage",
	"access_representation_is_current",
	"initialize_access_representation_entity",
	"guard_access_representation_entity",
	"guard_access_representation_head",
	"guard_access_representation_event",
	"guard_access_representation_revision",
	"guard_access_representation_permission",
	"validate_access_representation_history",

	"access_role_binding_recipient_is_current",
	"lock_access_role_binding_eligibility",
	"initialize_access_role_binding_scope",
	"guard_access_role_binding_scope",
	"guard_access_role_binding_head",
	"guard_access_role_binding_event",
	"guard_access_role_binding_revision",
	"guard_access_role_binding_permission",
	"validate_access_role_binding_history",

	"initialize_access_group_membership_set",
	"guard_access_group_membership_set",
	"guard_access_group_membership_event",
	"guard_access_group_membership_head",
	"validate_access_group_membership_history",

	"guard_access_group_tree",
	"access_group_required_height",
	"guard_access_group_head",
	"guard_access_group_event",
	"refresh_access_group_ancestor_height",
	"validate_access_group_history",

	"lock_access_membership_key",
	"lock_access_membership_keys",
	"guard_access_membership_head",
	"guard_access_membership_event",
	"guard_access_membership_admission",
	"validate_access_membership_history",
	"guard_access_role_head",
	"guard_access_role_event",
	"guard_access_role_revision",
	"guard_access_role_permission",
	"validate_access_role_history",
	"reference_value_native_id",
	"guard_follow_reference",
	"guard_account_tag_reference",
	"catalog_editorial_guard",
	"catalog_editorial_capture",
	"catalog_editorial_history_guard",
	"association_proposal_guard_authority",
	"music_release_source_job_guard",
	"catalog_source_bundle_check_parts",
	"catalog_source_bundle_immutable",
	"guard_governance_delivery_referral",
	"guard_governance_report_delivery",
	"guard_governance_notice_recipient",
	"catalog_definition_review_guard",
	"recommendation_partition_guard",
	"recommendation_snapshot_guard",
	"recommendation_score_build_guard",
	"guard_native_merge_request",
	"guard_native_merge_item",
	"guard_native_merge_operation",
	"guard_merged_catalog_identity_write",
 "guard_content_language_owner",
 "assign_content_structure_slots",
 "record_recommendation_metric",
 "realm_publication_guard_governance_pointer",
 "realm_publication_project_governance_action",
 "realm_publication_guard_governance_evidence",
	"apply_post_reply_stat_delta",
	"apply_reaction_change",
	"apply_recommendation_unit_signal",
	"apply_unit_engagement_stat",
	"assert_post_targeting_allowed",
	"current_search_metadata_v1",
	"current_search_text_v1",
	"enforce_governance_decision_rule_basis",
	"enforce_post_realm_mount_targeting",
	"enforce_post_reply_targeting",
	"enforce_post_subject_targeting",
	"enforce_realm_tag_context_wiki_post",
	"enforce_realm_taxonomy_tag_query_strategy",
	"enforce_unit_reference_limits",
	"enforce_unit_revision_primary_contribution",
	"enforce_wiki_association_context_post",
	"fill_unit_search_document_identity",
	"initialize_collection_stat",
	"initialize_poll_option_vote_stat",
	"initialize_post_reply_stat",
	"initialize_realm_stat",
	"maintain_collection_item_stat",
	"maintain_poll_option_vote_stat",
	"maintain_post_reply_stats",
	"maintain_realm_member_stat",
	"maintain_reply_unit_state",
	"maintain_score_stat",
	"maintain_unit_alias_vote_stat",
	"maintain_unit_external_link_vote_stat",
	"maintain_unit_follow_stat",
	"maintain_unit_reaction_stats",
	"maintain_unit_share_stats",
	"protect_association_context_post_kind",
	"protect_governance_decision_mutation",
	"protect_governance_decision_rule_mutation",
	"protect_post_reply_identity",
	"protect_realm_tag_context_post_kind",
	"protect_unit_revision_identity",
	"refresh_book_localized_content_metric_stat",
	"refresh_book_metric_from_content_unit",
	"refresh_book_metric_from_localization",
	"refresh_book_metric_from_node",
	"refresh_book_metric_from_structure",
	"refresh_post_reply_search_count_after_kind_change",
	"refresh_unit_search_document_from_alias_stat",
	"refresh_unit_search_document_from_dependency",
	"refresh_unit_search_document_from_unit",
	"reject_immutable_history_mutation",
	"reject_merged_unit_reference",
	"reject_unit_merge_immutable_mutation",
	"remove_reply_signals_before_unit_delete",
	"require_governance_decision_on_insert",
	"resolve_canonical_unit_id",
	"set_post_reply_search_count",
	"validate_unit_merge_redirect",
	"validate_unit_merge_review",
	"catalog_child_source_projection_valid",
	"catalog_child_source_guard_occurrence",
	"catalog_child_source_guard_application",
	"catalog_child_source_guard_baseline",
	"read_unit_state",
	"maintain_platform_identity",
	"require_zone_page_post",
	"organization_membership_lock_admission",
	"organization_membership_assert_invitation_authority",
	"organization_membership_guard_invitation",
	"organization_membership_guard_member",
	"organization_membership_guard_event",
	"organization_membership_record_event",
	"catalog_structure_source_projection_valid",
	"catalog_structure_source_guard_occurrence",
	"catalog_structure_source_guard_application",
	"catalog_structure_source_guard_baseline",
	"unit_publish_platform_route",
	"unit_remove_platform_route",
	"unit_populate_reference",
	"catalog_source_application_includes_epoch",
	"catalog_require_credit_creation_context",
	"catalog_guard_source_support",
	"catalog_source_guard_dependency",
	"catalog_source_guard_binding_correspondence",
	"catalog_source_guard_child_correspondence",
	"catalog_guard_definition_term",
	"catalog_validate_profile_source",
	"catalog_validate_profile_baseline",
	"catalog_guard_music_component_head",
	"catalog_guard_music_revision_insert",
	"catalog_check_music_definition_scope",
	"catalog_guard_structure_head",
	"catalog_guard_structure_revision_insert",
	"catalog_source_guard_owned_baseline",
	"catalog_capture_structure_revision",
	"catalog_guard_structure_history",
	"catalog_validate_structure_source",
	"catalog_check_music_source_baseline",
	"catalog_guard_software_participation",
	"catalog_require_software_participation_head",
	"catalog_guard_software_participation_revision",
	"catalog_require_software_participation_revision_head",
	"catalog_validate_software_participation",
	"catalog_check_music_source_occurrence",
	"catalog_source_validate_application_change",
	"catalog_source_guard_proposal",
	"catalog_source_require_application_complete",
	"participation_guard_follow_preference",
	"maintain_recommendation_event_signals",
	"participation_guard_favorite_identity",
	"participation_guard_image_owner",
	"participation_guard_image_child",
	"participation_guard_private_history",
	"participation_guard_quota_subject",
	"participation_guard_conversation_member",
	"maintain_account_favorite_stats",
	"refresh_studio_auth_editor_candidate",
	"refresh_studio_realm_editor_candidate",
	"maintain_studio_editor_candidate_from_ownership",
	"maintain_studio_editor_candidate_from_grant",
	"maintain_studio_catalog_creator_candidate",
	"repair_studio_catalog_creator_candidates",
	"maintain_unit_progress_stats",
	"participation_guard_conversation",
	"participation_guard_message",
	"participation_guard_account_block",
	"initialize_conversation_stats",
	"maintain_message_stats",
	"message_is_unread",
	"protect_conversation_aggregate_identity",
	"protect_conversation_read_identity",
	"protect_message_aggregate_identity",
	"refresh_conversation_last_message",

	"participation_guard_self_binding",
	"participation_guard_account_kind",
	"participation_guard_entity_shape",
	"participation_guard_service",
	"participation_guard_grant",
	"participation_require_grant_event",
	"participation_guard_immutable_evidence",
	"participation_guard_presentation",
	"participation_require_presentation_revision",
	"participation_require_unerased_account",
	"prepare_notification_recipient_state",
	"maintain_notification_recipient_stat",

	"catalog_guard_distribution_member",
	"catalog_count_distribution_members",
	"catalog_guard_distribution_manifest",
	"catalog_guard_distribution_revision",
	"catalog_require_distribution_head",
	"catalog_guard_distribution_package",
	"catalog_record_music_component",
	"catalog_guard_music_history",
	"catalog_guard_music_toc_offset_append",
	"catalog_check_music_toc_attachment",
	"catalog_valid_name_date",
	"catalog_guard_named_head",
	"catalog_snapshot_named_head",
	"catalog_guard_named_history",
	"catalog_guard_name_source_identity",
	"catalog_guard_semantic_immutable",
	"catalog_guard_governed_value",
	"catalog_guard_sealed_semantic",
	"catalog_guard_semantic_revision",
	"catalog_require_semantic_head",
	"catalog_guard_semantic_head",
	"catalog_guard_definition_constraints",
	"capture_software_record_revision",
	"reject_software_revision_mutation",
	"capture_software_component_revision",
	"enforce_software_patch_target",
	"catalog_source_guard_record",
	"catalog_source_guard_immutable_evidence",
	"catalog_source_guard_mapping",
	"catalog_source_require_binding_head",
	"catalog_guard_supporting_revision",
	"catalog_guard_supporting_classification",
	"operational_enqueue_relay",

	"catalog_guard_software_context",
	"catalog_require_software_context_head",
	"catalog_guard_software_context_revision",
	"catalog_require_software_context_revision_head",
	"operational_reserve_capacity",
	"operational_account_insert",
	"operational_guard_immutable",
	"catalog_guard_credit_member",
	"catalog_count_credit_members",
	"catalog_guard_credit_header",
	"catalog_require_sealed_credit",
	"catalog_guard_installment_parent",
	"catalog_guard_fact_value",
	"catalog_guard_fact_header",
	"catalog_guard_source_snapshot",
	"catalog_publish_identity_route",
	"catalog_remove_identity_route",
	"catalog_require_definition_kind",
	"catalog_guard_definition_revision",
	"catalog_guard_definition_identity",
	"refresh_unit_search_document",
	"adjust_tag_public_position_stat",
	"enqueue_tag_expression_projection_rebuild",
	"guard_content_label_unit_merge",
	"guard_direct_tag_application_policy",
	"guard_realm_tag_path_sense_adoption",
	"guard_realm_unit_tag_path_application",
	"guard_tag_directly_applicable_transition",
	"guard_tag_expression_argument_mutation",
	"guard_tag_expression_inference_graph",
	"guard_tag_expression_inference_rule_mutation",
	"guard_tag_expression_mutation",
	"guard_tag_expression_presentation_component_mutation",
	"guard_tag_expression_presentation_mutation",
	"guard_tag_path_concept_lifecycle",
	"guard_tag_path_definition",
	"guard_tag_path_merge",
	"guard_tag_path_projection",
	"guard_tag_path_sense_binding_mutation",
	"guard_tag_path_sense_mutation",
	"guard_tag_path_vote_stat_projection",
	"guard_tag_public_position_stat_projection",
	"guard_tag_relation_path_lifecycle",
	"guard_tag_relation_graph",
	"guard_unit_license_grant_mutation",
	"guard_unit_tag_path_application",
	"guard_vocabulary_node_path_lifecycle",
	"lock_realm_tag_judgment_keys",
	"lock_tag_public_position_keys",
	"lock_vote_hot_key",
	"lock_vote_hot_keys",
	"maintain_realm_application_expression",
	"maintain_realm_expression_from_direct",
	"maintain_realm_tag_judgment_stat",
	"maintain_realm_tag_path_vote_stat",
	"maintain_realm_unit_tag_path_application_judgment_stat",
	"maintain_subject_association_judgment_stat",
	"maintain_tag_expression_inference_closure",
	"maintain_tag_path_public_state",
	"maintain_tag_path_vote_stat",
	"maintain_unit_application_expression",
	"maintain_unit_content_language_search",
	"maintain_unit_expression_from_direct",
	"maintain_unit_tag_judgment_stat",
	"maintain_unit_tag_path_application_judgment_stat",
	"project_tag_path_definition",
	"protect_custom_theme_external_live_grant",
	"protect_custom_theme_revision_package",
	"protect_realm_tag_path_application_judgment_identity",
	"protect_unit_tag_path_application_judgment_identity",
	"rebuild_tag_expression_effective_tags",
	"refresh_realm_unit_effective_tags",
	"refresh_realm_unit_expression_assertion",
	"refresh_unit_effective_tags",
	"refresh_unit_expression_assertion",
	"reject_content_label_judgment",
	"reject_custom_theme_immutable_history_mutation",
	"search_tag_suggestion_candidates",
	"search_text_candidates",
	"search_catalog_name_candidates",
	"catalog_name_matches",
	"catalog_name_has_languages",
	"seed_tag_public_position_stat",
	"tag_path_unit_is_public",
] as const;

export const PostgreSqlSchemaTriggers = [
	{ table: "access_impact_fence", name: "access_impact_fence_guard" },
	{ table: "access_impact_fence", name: "access_impact_fence_truncate_guard" },
	{ table: "access_group", name: "access_group_impact" },
	{ table: "access_group", name: "access_group_impact_truncate" },
	{ table: "access_group_tree", name: "access_group_tree_impact" },
	{ table: "access_group_tree", name: "access_group_tree_impact_truncate" },
	{ table: "access_group_membership", name: "access_group_membership_impact" },
	{ table: "access_group_membership", name: "access_group_membership_impact_truncate" },
	{ table: "access_group_membership_set", name: "access_group_membership_set_impact" },
	{ table: "access_group_membership_set", name: "access_group_membership_set_impact_truncate" },
	{ table: "access_membership", name: "access_membership_impact" },
	{ table: "access_membership", name: "access_membership_impact_truncate" },
	{ table: "access_membership_admission", name: "access_membership_admission_impact" },
	{ table: "access_membership_admission", name: "access_membership_admission_impact_truncate" },
	{ table: "access_role_binding", name: "access_role_binding_impact" },
	{ table: "access_role_binding", name: "access_role_binding_impact_truncate" },
	{ table: "access_role_binding_revision", name: "access_role_binding_revision_impact" },
	{ table: "access_role_binding_revision", name: "access_role_binding_revision_impact_truncate" },
	{ table: "access_role_binding_permission", name: "access_role_binding_permission_impact" },
	{ table: "access_role_binding_permission", name: "access_role_binding_permission_impact_truncate" },
	{ table: "access_role", name: "access_role_impact" },
	{ table: "access_role", name: "access_role_impact_truncate" },
	{ table: "access_role_revision", name: "access_role_revision_impact" },
	{ table: "access_role_revision", name: "access_role_revision_impact_truncate" },
	{ table: "access_role_permission", name: "access_role_permission_impact" },
	{ table: "access_role_permission", name: "access_role_permission_impact_truncate" },
	{ table: "access_assignment_ceiling", name: "access_assignment_ceiling_impact" },
	{ table: "access_assignment_ceiling", name: "access_assignment_ceiling_impact_truncate" },
	{ table: "access_assignment_ceiling_permission", name: "access_assignment_ceiling_permission_impact" },
	{ table: "access_assignment_ceiling_permission", name: "access_assignment_ceiling_permission_impact_truncate" },
	{ table: "access_representation", name: "access_representation_impact" },
	{ table: "access_representation", name: "access_representation_impact_truncate" },
	{ table: "access_representation_revision", name: "access_representation_revision_impact" },
	{ table: "access_representation_revision", name: "access_representation_revision_impact_truncate" },
	{ table: "access_representation_permission", name: "access_representation_permission_impact" },
	{ table: "access_representation_permission", name: "access_representation_permission_impact_truncate" },
	{ table: "oauth_refresh_family", name: "oauth_refresh_family_guard" },
	{ table: "oauth_grant_context", name: "oauth_grant_context_guard" },
	{ table: "oauth_access_token", name: "oauth_access_token_native_context" },
	{ table: "oauth_refresh_token", name: "oauth_refresh_token_native_context" },
	{ table: "oauth_access_context", name: "oauth_access_context_guard" },
	{ table: "oauth_refresh_context", name: "oauth_refresh_context_guard" },
	{ table: "oauth_access_token", name: "oauth_access_token_identity_guard" },
	{ table: "oauth_refresh_token", name: "oauth_refresh_token_identity_guard" },
	{ table: "connected_user_connection", name: "connected_user_connection_guard" },
	{ table: "connected_user_connection_event", name: "connected_user_connection_event_guard" },
	{ table: "connected_user_consent", name: "connected_user_consent_guard" },
	{ table: "connected_user_consent_event", name: "connected_user_consent_event_guard" },
	{ table: "connected_user_consent_revision", name: "connected_user_consent_revision_guard" },
	{ table: "connected_user_consent_capability", name: "connected_user_consent_capability_guard" },
	{ table: "connected_user_consent_resource", name: "connected_user_consent_resource_guard" },
	{ table: "connected_user_consent_representation", name: "connected_user_consent_representation_guard" },
	{ table: "connected_user_connection", name: "connected_user_connection_complete" },
	{ table: "connected_user_connection_event", name: "connected_user_connection_event_complete" },
	{ table: "connected_user_consent", name: "connected_user_consent_complete" },
	{ table: "connected_user_consent_event", name: "connected_user_consent_event_complete" },
	{ table: "connected_user_consent_revision", name: "connected_user_consent_revision_complete" },
	{ table: "connected_installation", name: "connected_installation_head_guard" },
	{ table: "connected_installation_event", name: "connected_installation_event_guard" },
	{ table: "connected_installation_event", name: "connected_installation_event_immutable" },
	{ table: "connected_installation_revision", name: "connected_installation_revision_guard" },
	{ table: "connected_installation_capability", name: "connected_installation_capability_guard" },
	{ table: "connected_installation_binding", name: "connected_installation_binding_guard" },
	{ table: "connected_installation_attribution", name: "connected_installation_attribution_guard" },
	{ table: "connected_installation", name: "connected_installation_head_complete" },
	{ table: "connected_installation_event", name: "connected_installation_event_complete" },
	{ table: "connected_installation_revision", name: "connected_installation_revision_complete" },
	{ table: "oauth_client_secret_policy", name: "oauth_client_secret_policy_guard" },
	{ table: "oauth_client_secret_event", name: "oauth_client_secret_event_guard" },
	{ table: "oauth_client_secret_event", name: "oauth_client_secret_event_immutable" },
	{ table: "oauth_client_secret_policy", name: "oauth_client_secret_policy_complete" },
	{ table: "oauth_client_secret_event", name: "oauth_client_secret_event_complete" },
	{ table: "connected_app_client", name: "connected_app_client_head_guard" },
	{ table: "connected_app_client_event", name: "connected_app_client_event_guard" },
	{ table: "connected_app_client_event", name: "connected_app_client_event_immutable" },
	{ table: "connected_app_client_revision", name: "connected_app_client_revision_guard" },
	{ table: "connected_app_client_capability", name: "connected_app_client_capability_guard" },
	{ table: "connected_app_client", name: "connected_app_client_head_complete" },
	{ table: "connected_app_client_event", name: "connected_app_client_event_complete" },
	{ table: "connected_app_client_revision", name: "connected_app_client_revision_complete" },
	{ table: "workload_principal", name: "workload_principal_guard" },
	{ table: "workload_principal_event", name: "workload_principal_event_guard" },
	{ table: "workload_principal_event", name: "workload_principal_event_immutable" },
	{ table: "workload_principal", name: "workload_principal_complete" },
	{ table: "workload_principal_event", name: "workload_principal_event_complete" },
	{ table: "sessions", name: "sessions_principal_kind_guard" },
	{ table: "accounts", name: "accounts_principal_kind_guard" },
	{ table: "oauth_client_authority", name: "oauth_client_authority_guard" },
	{ table: "oauth_client", name: "oauth_client_authority_fence" },
	{ table: "connected_app", name: "connected_app_head_guard" },
	{ table: "connected_app_event", name: "connected_app_event_guard" },
	{ table: "connected_app_event", name: "connected_app_event_immutable" },
	{ table: "connected_app_revision", name: "connected_app_revision_guard" },
	{ table: "connected_app_capability", name: "connected_app_capability_guard" },
	{ table: "connected_app", name: "connected_app_head_complete" },
	{ table: "connected_app_event", name: "connected_app_event_complete" },
	{ table: "connected_app_revision", name: "connected_app_revision_complete" },
	{ table: "account_identity_admission", name: "account_identity_admission_guard" },
	{ table: "api_key_authority", name: "api_key_authority_guard" },
	{ table: "apikeys", name: "apikey_authority_fence" },
	{ table: "access_assignment_ceiling", name: "access_assignment_ceiling_guard" },
	{ table: "access_assignment_ceiling_permission", name: "access_assignment_ceiling_permission_guard" },
	{ table: "access_assignment_ceiling_event", name: "access_assignment_ceiling_event_guard" },
	{ table: "access_assignment_ceiling_event", name: "access_assignment_ceiling_event_immutable" },
	{ table: "access_assignment_ceiling", name: "access_assignment_ceiling_complete" },
	{ table: "access_assignment_ceiling_event", name: "access_assignment_ceiling_event_complete" },
	{ table: "identity_preference", name: "identity_preference_guard" },
	{ table: "identity_preference_representation", name: "identity_preference_representation_guard" },
	{ table: "identity_preference_event", name: "identity_preference_event_guard" },
	{ table: "identity_preference", name: "identity_preference_complete" },
	{ table: "identity_preference_event", name: "identity_preference_event_complete" },
	{ table: "user_account_state", name: "user_account_state_authority_fence" },
	{ table: "account_enforcement", name: "account_enforcement_authority_fence" },
	{ table: "entity_participation", name: "entity_participation_authority_fence" },
	{ table: "access_subject", name: "access_representation_entity_initialize" },
	{ table: "access_representation_entity", name: "access_representation_entity_guard" },
	{ table: "access_representation", name: "access_representation_head_guard" },
	{ table: "access_representation_event", name: "access_representation_event_guard" },
	{ table: "access_representation_event", name: "access_representation_event_immutable" },
	{ table: "access_representation_revision", name: "access_representation_revision_guard" },
	{ table: "access_representation_permission", name: "access_representation_permission_guard" },
	{ table: "access_representation", name: "access_representation_head_complete" },
	{ table: "access_representation_event", name: "access_representation_event_complete" },
	{ table: "access_representation_revision", name: "access_representation_revision_complete" },
	{ table: "access_scope", name: "access_role_binding_scope_initialize" },
	{ table: "access_role_binding_scope", name: "access_role_binding_scope_guard" },
	{ table: "access_role_binding", name: "access_role_binding_head_guard" },
	{ table: "access_role_binding_event", name: "access_role_binding_event_guard" },
	{ table: "access_role_binding_event", name: "access_role_binding_event_immutable" },
	{ table: "access_role_binding_revision", name: "access_role_binding_revision_guard" },
	{ table: "access_role_binding_permission", name: "access_role_binding_permission_guard" },
	{ table: "access_role_binding", name: "access_role_binding_head_complete" },
	{ table: "access_role_binding_event", name: "access_role_binding_event_complete" },
	{ table: "access_role_binding_revision", name: "access_role_binding_revision_complete" },

	{ table: "access_membership_admission", name: "access_group_membership_set_initialize" },
	{ table: "access_group_membership_set", name: "access_group_membership_set_guard" },
	{ table: "access_group_membership", name: "access_group_membership_head_guard" },
	{ table: "access_group_membership_event", name: "access_group_membership_event_guard" },
	{ table: "access_group_membership_event", name: "access_group_membership_event_immutable" },
	{ table: "access_group_membership", name: "access_group_membership_head_complete" },
	{ table: "access_group_membership_event", name: "access_group_membership_event_complete" },

	{ table: "access_group_tree", name: "access_group_tree_guard" },
	{ table: "access_group", name: "access_group_head_guard" },
	{ table: "access_group", name: "access_group_height_refresh" },
	{ table: "access_group_event", name: "access_group_event_guard" },
	{ table: "access_group_event", name: "access_group_event_immutable" },
	{ table: "access_group", name: "access_group_head_complete" },
	{ table: "access_group_event", name: "access_group_event_complete" },

	{ table: "access_membership", name: "access_membership_head_guard" },
	{ table: "access_membership_event", name: "access_membership_event_guard" },
	{ table: "access_membership_event", name: "access_membership_event_immutable" },
	{ table: "access_membership_admission", name: "access_membership_admission_guard" },
	{ table: "access_membership_admission", name: "access_membership_admission_immutable" },
	{ table: "access_membership", name: "access_membership_head_complete" },
	{ table: "access_membership_event", name: "access_membership_event_complete" },

	{ table: "access_role", name: "access_role_head_guard" },
	{ table: "access_role_event", name: "access_role_event_guard" },
	{ table: "access_role_event", name: "access_role_event_immutable" },
	{ table: "access_role_revision", name: "access_role_revision_guard" },
	{ table: "access_role_permission", name: "access_role_permission_guard" },
	{ table: "access_role", name: "access_role_head_complete" },
	{ table: "access_role_event", name: "access_role_event_complete" },
	{ table: "access_role_revision", name: "access_role_revision_complete" },

	{ table: "reference_value", name: "reference_value_immutable" },
	{ table: "access_subject", name: "access_subject_immutable" },
	{ table: "access_scope", name: "access_scope_immutable" },
	{ table: "revision_reference", name: "revision_reference_immutable" },
	{ table: "unit_association_proposal", name: "association_proposal_authority_guard" },
	{ table: "music_release_source_job", name: "music_release_source_job_guard_trigger" },
	{ table: "catalog_source_snapshot_bundle", name: "catalog_source_bundle_parts_check" },
	{ table: "catalog_source_snapshot_bundle", name: "catalog_source_bundle_immutable" },
	{ table: "catalog_source_snapshot_part", name: "catalog_source_part_set_check" },
	{ table: "catalog_source_snapshot_part", name: "catalog_source_part_immutable" },
	{ table: "content_report_referral", name: "governance_delivery_referral_guard" },
	{ table: "governance_report_delivery", name: "governance_report_delivery_guard" },
	{ table: "governance_notice_recipient", name: "governance_notice_recipient_guard" },
	{ table: "catalog_definition_review", name: "catalog_definition_review_guard_trigger" },
	{ table: "catalog_definition_label", name: "catalog_definition_label_immutable" },
	{ table: "recommendation_snapshot_partition", name: "recommendation_snapshot_partition_guard" },
	{ table: "recommendation_snapshot", name: "recommendation_snapshot_build_guard" },
	{ table: "unit_best_score", name: "unit_best_score_build_guard" },
	{ table: "unit_merge_request", name: "native_merge_request_guard" },
	{ table: "unit_merge_reconciliation_item", name: "native_merge_item_guard" },
	{ table: "unit_merge_operation", name: "native_merge_operation_guard" },
	...(["publishing", "music", "program", "software", "entity", "grouping", "reference", "distribution"] as const).map(owner => ({ table: `${owner}_identity`, name: `${owner}_merged_identity_write_guard` })),
 {table:"unit_content_language_support",name:"content_language_owner_guard"},
 {table:"unit_content_language_search",name:"content_language_owner_guard"},
 {table:"content_structure_node",name:"content_structure_slots_assign"},
 {table:"recommendation_event",name:"recommendation_metric_on_insert"},
 {table:"realm_unit",name:"realm_publication_governance_pointer_guard"},
 {table:"content_governance_action",name:"realm_publication_governance_project"},
 {table:"content_governance_action",name:"realm_publication_governance_evidence_guard"},
 {table:"content_review_case",name:"realm_publication_governance_scope_guard"},
{"table":"post","name":"unit_search_document_from_owner"},
{"table":"video","name":"unit_search_document_from_owner"},
{"table":"audio","name":"unit_search_document_from_owner"},
{"table":"poll","name":"unit_search_document_from_owner"},
{"table":"zone","name":"unit_search_document_from_owner"},
{"table":"realm","name":"unit_search_document_from_owner"},
{"table":"realm_rule","name":"unit_search_document_from_owner"},
{"table":"custom_theme","name":"unit_search_document_from_owner"},
{"table":"collection","name":"unit_search_document_from_owner"},
{"table":"tag","name":"unit_search_document_from_owner"},
{"table":"tag_path","name":"unit_search_document_from_owner"},
{"table":"label","name":"unit_search_document_from_owner"},
	{ table: "account_enforcement_action", name: "account_enforcement_action_decision_required" },
	{ table: "audit_event", name: "audit_event_append_only" },
	{ table: "collection", name: "collection_stat_initialize" },
	{ table: "collection_item", name: "collection_item_stat_maintain" },
	{ table: "collection_item", name: "reject_merged_unit_collection_item_unit_id" },
	{ table: "content_governance_action", name: "content_governance_action_decision_required" },
	{ table: "content_structure", name: "book_localized_metric_structure_refresh" },
	{ table: "content_structure_node", name: "book_localized_metric_node_refresh" },
	{ table: "content_structure_node", name: "content_structure_node_realm_tag_query_strategy" },
	{
		table: "content_structure_node",
		name: "reject_merged_unit_content_structure_node_content_unit_id",
	},
	{
		table: "content_structure_node",
		name: "reject_merged_unit_content_structure_node_target_unit_id",
	},
	{ table: "credit_attribution", name: "reject_merged_unit_credit_attribution_source_unit_id" },
	{ table: "governance_decision", name: "governance_decision_immutable" },
	{ table: "governance_decision", name: "governance_decision_rule_basis_from_decision" },
	{ table: "governance_decision_rule", name: "governance_decision_rule_immutable" },
	{ table: "notification", name: "reject_merged_unit_notification_subject_unit_id" },
	{ table: "poll_option", name: "poll_option_vote_stat_initialize" },
	{ table: "poll_option", name: "reject_merged_unit_poll_option_target_unit_id" },
	{ table: "poll_vote", name: "poll_option_vote_stat_maintain" },
	{ table: "post", name: "book_localized_metric_post_refresh" },
	{ table: "post", name: "post_association_context_kind_protect" },
	{ table: "post", name: "post_realm_tag_context_kind" },
	{ table: "post", name: "post_reply_search_count_kind_refresh" },
	{ table: "post", name: "post_reply_stat_initialize" },
	{ table: "post", name: "post_subject_targeting_enforce" },
	{ table: "post", name: "reject_merged_unit_post_subject_unit_id" },
	{ table: "post_reply", name: "post_reply_identity_protect" },
	{ table: "post_reply", name: "post_reply_stats_maintain" },
	{ table: "post_reply", name: "post_reply_targeting_enforce" },
	{ table: "post_reply_stat", name: "post_reply_stat_search_count_set" },
	{
		table: "profile_resource_participation",
		name: "reject_merged_unit_profile_resource_participation_resource_unit",
	},
	{ table: "realm", name: "realm_stat_initialize" },
	{ table: "realm_member", name: "realm_member_stat_maintain" },
	{ table: "realm_pin", name: "reject_merged_unit_realm_pin_unit_id" },
	{ table: "realm_tag_context", name: "realm_tag_context_wiki_post" },
	{ table: "realm_unit", name: "post_realm_mount_targeting_enforce" },
	{ table: "realm_unit", name: "reject_merged_unit_realm_unit_unit_id" },
	{ table: "realm_unit_tag", name: "reject_merged_unit_realm_unit_tag_unit_id" },
	{
		table: "recommendation_exclusion",
		name: "reject_merged_unit_recommendation_exclusion_target_reference_id",
	},
	{ table: "revision_content", name: "revision_content_immutable" },
	{ table: "score", name: "reject_merged_unit_score_unit_id" },
	{ table: "score", name: "score_stat_maintain" },
	{
		table: "studio_realm_editor_candidate",
		name: "reject_merged_unit_studio_realm_editor_candidate_unit_id",
	},
	{
		table: "studio_resource_visit",
		name: "reject_merged_unit_studio_resource_visit_target_reference_id",
	},
	{ table: "subject_association", name: "reject_merged_unit_subject_association_entity_id" },
	{ table: "subject_association", name: "reject_merged_unit_subject_association_unit_id" },
	{ table: "subject_association", name: "subject_association_wiki_context_post" },
	{ table: "post", name: "reply_signals_remove_before_unit_delete" },
	{ table: "post", name: "reply_unit_state_maintain" },
	{ table: "unit_access_restriction", name: "unit_access_restriction_decision_required" },
	{ table: "unit_alias", name: "reject_merged_unit_unit_alias_unit_id" },
	{ table: "unit_alias", name: "unit_alias_reference_limits" },
	{ table: "unit_alias", name: "unit_search_document_from_alias" },
	{ table: "unit_alias_vote", name: "unit_alias_vote_stat_maintain" },
	{ table: "unit_alias_vote_stat", name: "unit_search_document_from_alias_stat" },
	{
		table: "unit_association_proposal",
		name: "reject_merged_unit_unit_association_proposal_source_unit_id",
	},
	{
		table: "unit_association_proposal",
		name: "reject_merged_unit_unit_association_proposal_target_unit_id",
	},
	{ table: "unit_association_proposal", name: "unit_association_proposal_wiki_context_post" },
	{ table: "unit_best_score", name: "reject_merged_unit_unit_best_score_unit_id" },
	{ table: "unit_external_link", name: "reject_merged_unit_unit_external_link_source_entity_id" },
	{ table: "unit_external_link", name: "reject_merged_unit_unit_external_link_unit_id" },
	{ table: "unit_external_link", name: "unit_external_link_reference_limits" },
	{ table: "unit_external_link_vote", name: "unit_external_link_vote_stat_maintain" },
	{ table: "unit_follow", name: "reject_merged_unit_unit_follow_target_reference_id" },
	{ table: "unit_follow", name: "unit_follow_reference_guard" },
	{ table: "unit_follow", name: "unit_follow_stat_maintain" },
	{ table: "unit_localization", name: "book_localized_metric_localization_refresh" },
	{ table: "unit_localization", name: "unit_search_document_from_localization" },
	{ table: "unit_localization_content_metric", name: "book_localized_metric_content_refresh" },
	{ table: "unit_merge_redirect", name: "unit_merge_redirect_immutable" },
	{ table: "unit_merge_redirect", name: "unit_merge_redirect_validate" },
	{ table: "unit_merge_request", name: "unit_merge_request_decision_required" },
	{ table: "unit_merge_review", name: "unit_merge_review_immutable" },
	{ table: "unit_merge_review", name: "unit_merge_review_validate" },
	{ table: "unit_progress", name: "reject_merged_unit_unit_progress_unit_id" },
	{ table: "unit_progress_entry", name: "reject_merged_unit_unit_progress_entry_unit_id" },
	{ table: "unit_reaction", name: "reject_merged_unit_unit_reaction_unit_id" },
	{ table: "unit_reaction", name: "unit_reaction_stats_maintain" },
	{ table: "unit_revision", name: "unit_revision_identity_immutable" },
	{ table: "unit_revision", name: "unit_revision_primary_contribution_from_revision" },
	{ table: "unit_revision_credit_attribution", name: "unit_revision_credit_attribution_immutable" },
	{ table: "unit_revision_credit_attribution", name: "unit_revision_credit_reject_merged_entity" },
	{
		table: "unit_revision_credit_attribution",
		name: "unit_revision_primary_contribution_from_credit",
	},
	{ table: "unit_revision_slot", name: "unit_revision_slot_immutable" },
	{ table: "unit_revision_tag", name: "unit_revision_tag_immutable" },
	{ table: "unit_search_document", name: "reject_merged_unit_unit_search_document_unit_id" },
	{ table: "unit_search_document", name: "unit_search_document_identity_fill" },
	{ table: "unit_share", name: "reject_merged_unit_unit_share_unit_id" },
	{ table: "unit_share", name: "unit_share_stats_maintain" },
	{ table: "unit_slug_address", name: "reject_merged_unit_unit_slug_address_scope_unit_id" },
	{ table: "unit_slug_address", name: "reject_merged_unit_unit_slug_address_target_unit_id" },
	{ table: "unit_tag", name: "reject_merged_unit_unit_tag_unit_id" },
	{ table: "user_account_state", name: "user_account_state_decision_required" },
	{ table: "zone_page", name: "zone_page_post_required" },
	{ table: "post", name: "post_zone_page_required" },
	{ table: "organization_membership_invitation", name: "organization_membership_invitation_guard" },
	{ table: "organization_membership", name: "organization_membership_guard" },
	{ table: "organization_membership_event", name: "organization_membership_event_guard" },
	{ table: "organization_membership", name: "organization_membership_event_record" },
	{ table: "music_artist_credit", name: "music_credit_creation_context" },
	{ table: "catalog_source_proposal_dependency", name: "catalog_source_dependency_guard" },
	{
		table: "software_participation_credit_source_occurrence",
		name: "software_credit_correspondence_guard",
	},
	{ table: "software_record_source_occurrence", name: "software_record_correspondence_guard" },
	{
		table: "software_component_source_occurrence",
		name: "software_component_correspondence_guard",
	},
	{ table: "catalog_source_binding_revision", name: "catalog_source_binding_correspondence_guard" },
	{
		table: "software_participation_source_occurrence",
		name: "software_context_correspondence_guard",
	},
	{ table: "catalog_definition_term", name: "catalog_definition_term_guard" },
	{ table: "catalog_definition_term_support", name: "catalog_definition_term_support_guard" },
	{ table: "music_component_source_baseline", name: "music_source_baseline_proof" },
	{ table: "catalog_source_adoption_proposal", name: "catalog_source_proposal_guard" },
	{ table: "software_participation", name: "software_participation_guard" },
	{ table: "software_participation", name: "software_participation_head_required" },
	{ table: "software_participation_revision", name: "software_participation_revision_guard" },
	{
		table: "software_participation_revision",
		name: "software_participation_revision_head_required",
	},
	{ table: "software_participation_revision", name: "software_participation_values" },
	{
		table: "software_participation_credit_source_occurrence",
		name: "software_participation_occurrence_guard",
	},
	{ table: "music_medium_identifier", name: "music_medium_identifier_record_revision" },
	{ table: "music_track_identifier", name: "music_track_identifier_record_revision" },
	{
		table: "music_component_source_occurrence",
		name: "music_component_source_occurrence_exact_history",
	},
	{
		table: "music_component_source_occurrence",
		name: "music_component_source_occurrence_immutable",
	},
	{ table: "music_source_application_change", name: "music_source_application_exact_component" },
	{ table: "account_follow_preference", name: "participation_follow_preference_guard" },
	{ table: "recommendation_event", name: "recommendation_event_signals_maintain" },
	{ table: "account_unit_tag", name: "account_tag_reference_guard" },
	{ table: "account_favorite", name: "participation_favorite_identity_guard" },
	{ table: "image_asset", name: "participation_image_owner_guard" },
	{ table: "image_object", name: "participation_image_child_guard" },
	{ table: "image_asset_presentation", name: "participation_image_child_guard" },
	{ table: "account_favorite_revision", name: "participation_private_history_guard" },
	{ table: "conversation_read", name: "participation_conversation_member_guard" },
	{ table: "conversation_participant_stat", name: "participation_conversation_member_guard" },
	{ table: "account_favorite", name: "account_favorite_stats_maintain" },
	{ table: "recommendation_event", name: "participation_private_account_guard" },
	{ table: "recommendation_exclusion", name: "participation_private_account_guard" },
	{ table: "studio_resource_visit", name: "participation_private_account_guard" },
	{ table: "studio_auth_editor_candidate", name: "participation_private_account_guard" },
	{ table: "account_favorites_state", name: "participation_private_account_guard" },
	{ table: "account_favorite", name: "participation_private_account_guard" },
	{ table: "account_favorite_revision", name: "participation_private_account_guard" },
	{ table: "account_realm_tag_subscription", name: "participation_private_account_guard" },
	{ table: "account_unit_tag", name: "participation_private_account_guard" },
	{ table: "conversation_participant_stat", name: "participation_private_account_guard" },
	{ table: "api_token_creation_reservation", name: "participation_private_account_guard" },
	{ table: "api_account_quota_binding", name: "participation_quota_subject_guard" },
	{ table: "api_token_quota_binding", name: "participation_quota_subject_guard" },
	{ table: "api_token_quota_override", name: "participation_quota_subject_guard" },
	{ table: "api_quota_rate_state", name: "participation_quota_subject_guard" },
	{ table: "api_quota_daily_usage", name: "participation_quota_subject_guard" },
	{ table: "api_quota_request_lease", name: "participation_quota_subject_guard" },

	{ table: "unit_ownership", name: "studio_editor_candidate_from_ownership" },
	{ table: "unit_access_grant", name: "studio_editor_candidate_from_grant" },
	{ table: "unit_progress", name: "unit_progress_stats_maintain" },
	{ table: "conversation", name: "participation_conversation_guard" },
	{ table: "message", name: "participation_message_guard" },
	{ table: "account_entity_block", name: "participation_account_block_guard" },
	{ table: "account_entity_block", name: "participation_private_account_guard" },
	{ table: "conversation_read", name: "participation_private_account_guard" },
	{ table: "conversation", name: "conversation_aggregate_identity_protect" },
	{ table: "conversation", name: "conversation_stats_initialize" },
	{ table: "conversation_read", name: "conversation_read_identity_protect" },
	{ table: "message", name: "message_aggregate_identity_protect" },
	{ table: "message", name: "message_stats_maintain" },

	{ table: "auth_entity", name: "participation_self_binding_guard" },
	{ table: "users", name: "participation_account_kind_guard" },
	{ table: "entity_identity", name: "participation_entity_shape_guard" },
	{ table: "service_principal", name: "participation_service_guard" },
	{ table: "participation_grant", name: "participation_grant_guard" },
	{ table: "participation_grant", name: "participation_grant_event_required" },
	{ table: "participation_grant_event", name: "participation_grant_event_immutable" },
	{ table: "entity_recovery_event", name: "entity_recovery_event_immutable" },
	{ table: "entity_presentation_revision", name: "entity_presentation_revision_immutable" },
	{ table: "entity_presentation", name: "entity_presentation_guard" },
	{ table: "entity_presentation", name: "entity_presentation_revision_required" },
	{ table: "notification", name: "notification_recipient_state_prepare" },
	{ table: "notification", name: "notification_recipient_stat_maintain" },
	{ table: "sessions", name: "participation_private_account_guard" },
	{ table: "accounts", name: "participation_private_account_guard" },
	{ table: "apikeys", name: "participation_private_account_guard" },
	{ table: "account_preference", name: "participation_private_account_guard" },
	{ table: "notification", name: "participation_private_account_guard" },
	{ table: "notification_preference", name: "participation_private_account_guard" },
	{ table: "notification_recipient_stat", name: "participation_private_account_guard" },
	{ table: "unit_progress", name: "participation_private_account_guard" },
	{ table: "unit_progress_entry", name: "participation_private_account_guard" },
	{ table: "content_structure_node_progress", name: "participation_private_account_guard" },
	{ table: "unit_access_grant", name: "participation_private_account_guard" },
	{ table: "unit_access_restriction", name: "participation_private_account_guard" },
	{ table: "unit_access_invitation", name: "participation_private_account_guard" },
	{ table: "platform_capability_grant", name: "participation_private_account_guard" },
	{ table: "account_enforcement", name: "participation_private_account_guard" },
	{ table: "participation_grant", name: "participation_evidence_truncate_guard" },
	{ table: "participation_grant_event", name: "participation_evidence_truncate_guard" },
	{ table: "entity_recovery_event", name: "participation_evidence_truncate_guard" },
	{ table: "entity_presentation_revision", name: "participation_evidence_truncate_guard" },

	{ table: "distribution_identity", name: "distribution_identity_route_publish" },
	{ table: "distribution_identity", name: "distribution_identity_route_remove" },
	{ table: "distribution_fact", name: "distribution_fact_definition_guard" },
	{
		table: "distribution_catalog_relation",
		name: "distribution_catalog_relation_definition_guard",
	},
	{
		table: "distribution_relation_participant",
		name: "distribution_relation_participant_definition_guard",
	},
	{ table: "distribution_relation_scope", name: "distribution_relation_scope_definition_guard" },
	{ table: "distribution_fact_value_node", name: "distribution_fact_value_node_value_guard" },
	{ table: "distribution_fact", name: "distribution_fact_value_guard" },
	{ table: "distribution_member", name: "distribution_member_guard" },
	{ table: "distribution_member", name: "distribution_member_count" },
	{ table: "distribution_manifest", name: "distribution_manifest_guard" },
	{ table: "distribution_revision", name: "distribution_revision_guard" },
	{ table: "distribution_package", name: "distribution_package_guard" },
	{ table: "distribution_package", name: "distribution_package_head" },
	{ table: "distribution_revision", name: "distribution_revision_head" },
	{ table: "music_component_revision", name: "music_component_revision_immutable" },
	{ table: "music_component_head", name: "music_component_head_maintained" },
	{ table: "music_component_revision", name: "music_component_revision_capture_only" },
	{ table: "music_alternative_track", name: "music_alternative_track_immutable" },
	{ table: "music_release", name: "music_release_status_scope" },
	{ table: "music_release", name: "music_release_packaging_scope" },
	{ table: "music_medium", name: "music_medium_format_scope" },
	{ table: "music_work", name: "music_work_type_scope" },
	{ table: "music_release_group", name: "music_release_group_primary_scope" },
	{ table: "music_release_group_secondary_type", name: "music_release_group_secondary_scope" },
	{ table: "music_release_presentation", name: "music_release_presentation_type_scope" },
	{ table: "music_disc_toc", name: "music_disc_toc_immutable" },
	{ table: "music_disc_toc_offset", name: "music_disc_toc_offset_immutable" },
	{ table: "music_disc_toc_offset", name: "music_disc_toc_offset_sealed" },
	{ table: "music_medium_toc", name: "music_medium_toc_complete" },
	{ table: "music_candidate_toc", name: "music_candidate_toc_complete" },
	{ table: "music_medium_attribute", name: "music_medium_attribute_record_revision" },
	{ table: "music_track_presentation", name: "music_track_presentation_record_revision" },
	{ table: "music_medium_toc", name: "music_medium_toc_record_revision" },
	{ table: "music_candidate_toc", name: "music_candidate_toc_record_revision" },
	{ table: "publishing_semantic_revision", name: "publishing_semantic_revision_immutable" },
	{ table: "publishing_catalog_relation", name: "publishing_catalog_relation_immutable" },
	{ table: "publishing_relation_participant", name: "publishing_relation_participant_immutable" },
	{ table: "publishing_relation_scope", name: "publishing_relation_scope_immutable" },
	{ table: "publishing_fact_value_node", name: "publishing_fact_value_node_governance" },
	{ table: "publishing_fact", name: "publishing_fact_sealed_semantic" },
	{
		table: "publishing_relation_participant",
		name: "publishing_relation_participant_sealed_semantic",
	},
	{ table: "publishing_relation_scope", name: "publishing_relation_scope_sealed_semantic" },
	{ table: "publishing_semantic_revision", name: "publishing_semantic_revision_governance" },
	{ table: "publishing_semantic_revision", name: "publishing_semantic_revision_head" },
	{ table: "music_semantic_revision", name: "music_semantic_revision_immutable" },
	{ table: "music_catalog_relation", name: "music_catalog_relation_immutable" },
	{ table: "music_relation_participant", name: "music_relation_participant_immutable" },
	{ table: "music_relation_scope", name: "music_relation_scope_immutable" },
	{ table: "music_fact_value_node", name: "music_fact_value_node_governance" },
	{ table: "music_fact", name: "music_fact_sealed_semantic" },
	{ table: "music_relation_participant", name: "music_relation_participant_sealed_semantic" },
	{ table: "music_relation_scope", name: "music_relation_scope_sealed_semantic" },
	{ table: "music_semantic_revision", name: "music_semantic_revision_governance" },
	{ table: "music_semantic_revision", name: "music_semantic_revision_head" },
	{ table: "program_semantic_revision", name: "program_semantic_revision_immutable" },
	{ table: "program_catalog_relation", name: "program_catalog_relation_immutable" },
	{ table: "program_relation_participant", name: "program_relation_participant_immutable" },
	{ table: "program_relation_scope", name: "program_relation_scope_immutable" },
	{ table: "program_fact_value_node", name: "program_fact_value_node_governance" },
	{ table: "program_fact", name: "program_fact_sealed_semantic" },
	{ table: "program_relation_participant", name: "program_relation_participant_sealed_semantic" },
	{ table: "program_relation_scope", name: "program_relation_scope_sealed_semantic" },
	{ table: "program_semantic_revision", name: "program_semantic_revision_governance" },
	{ table: "program_semantic_revision", name: "program_semantic_revision_head" },
	{ table: "software_semantic_revision", name: "software_semantic_revision_immutable" },
	{ table: "software_catalog_relation", name: "software_catalog_relation_immutable" },
	{ table: "software_relation_participant", name: "software_relation_participant_immutable" },
	{ table: "software_relation_scope", name: "software_relation_scope_immutable" },
	{ table: "software_fact_value_node", name: "software_fact_value_node_governance" },
	{ table: "software_fact", name: "software_fact_sealed_semantic" },
	{ table: "software_relation_participant", name: "software_relation_participant_sealed_semantic" },
	{ table: "software_relation_scope", name: "software_relation_scope_sealed_semantic" },
	{ table: "software_semantic_revision", name: "software_semantic_revision_governance" },
	{ table: "software_semantic_revision", name: "software_semantic_revision_head" },
	{ table: "entity_semantic_revision", name: "entity_semantic_revision_immutable" },
	{ table: "entity_catalog_relation", name: "entity_catalog_relation_immutable" },
	{ table: "entity_relation_participant", name: "entity_relation_participant_immutable" },
	{ table: "entity_relation_scope", name: "entity_relation_scope_immutable" },
	{ table: "entity_fact_value_node", name: "entity_fact_value_node_governance" },
	{ table: "entity_fact", name: "entity_fact_sealed_semantic" },
	{ table: "entity_relation_participant", name: "entity_relation_participant_sealed_semantic" },
	{ table: "entity_relation_scope", name: "entity_relation_scope_sealed_semantic" },
	{ table: "entity_semantic_revision", name: "entity_semantic_revision_governance" },
	{ table: "entity_semantic_revision", name: "entity_semantic_revision_head" },
	{ table: "grouping_semantic_revision", name: "grouping_semantic_revision_immutable" },
	{ table: "grouping_catalog_relation", name: "grouping_catalog_relation_immutable" },
	{ table: "grouping_relation_participant", name: "grouping_relation_participant_immutable" },
	{ table: "grouping_relation_scope", name: "grouping_relation_scope_immutable" },
	{ table: "grouping_fact_value_node", name: "grouping_fact_value_node_governance" },
	{ table: "grouping_fact", name: "grouping_fact_sealed_semantic" },
	{ table: "grouping_relation_participant", name: "grouping_relation_participant_sealed_semantic" },
	{ table: "grouping_relation_scope", name: "grouping_relation_scope_sealed_semantic" },
	{ table: "grouping_semantic_revision", name: "grouping_semantic_revision_governance" },
	{ table: "grouping_semantic_revision", name: "grouping_semantic_revision_head" },
	{ table: "reference_semantic_revision", name: "reference_semantic_revision_immutable" },
	{ table: "reference_catalog_relation", name: "reference_catalog_relation_immutable" },
	{ table: "reference_relation_participant", name: "reference_relation_participant_immutable" },
	{ table: "reference_relation_scope", name: "reference_relation_scope_immutable" },
	{ table: "reference_fact_value_node", name: "reference_fact_value_node_governance" },
	{ table: "reference_fact", name: "reference_fact_sealed_semantic" },
	{
		table: "reference_relation_participant",
		name: "reference_relation_participant_sealed_semantic",
	},
	{ table: "reference_relation_scope", name: "reference_relation_scope_sealed_semantic" },
	{ table: "reference_semantic_revision", name: "reference_semantic_revision_governance" },
	{ table: "reference_semantic_revision", name: "reference_semantic_revision_head" },
	{ table: "distribution_semantic_revision", name: "distribution_semantic_revision_immutable" },
	{ table: "distribution_catalog_relation", name: "distribution_catalog_relation_immutable" },
	{
		table: "distribution_relation_participant",
		name: "distribution_relation_participant_immutable",
	},
	{ table: "distribution_relation_scope", name: "distribution_relation_scope_immutable" },
	{ table: "distribution_fact_value_node", name: "distribution_fact_value_node_governance" },
	{ table: "distribution_fact", name: "distribution_fact_sealed_semantic" },
	{
		table: "distribution_relation_participant",
		name: "distribution_relation_participant_sealed_semantic",
	},
	{ table: "distribution_relation_scope", name: "distribution_relation_scope_sealed_semantic" },
	{ table: "distribution_semantic_revision", name: "distribution_semantic_revision_governance" },
	{ table: "distribution_semantic_revision", name: "distribution_semantic_revision_head" },
	{ table: "publishing_semantic_head", name: "publishing_semantic_head_governance" },
	{ table: "music_semantic_head", name: "music_semantic_head_governance" },
	{ table: "program_semantic_head", name: "program_semantic_head_governance" },
	{ table: "software_semantic_head", name: "software_semantic_head_governance" },
	{ table: "entity_semantic_head", name: "entity_semantic_head_governance" },
	{ table: "grouping_semantic_head", name: "grouping_semantic_head_governance" },
	{ table: "reference_semantic_head", name: "reference_semantic_head_governance" },
	{ table: "distribution_semantic_head", name: "distribution_semantic_head_governance" },
	{ table: "catalog_definition_revision", name: "catalog_definition_revision_governance" },
	{ table: "software_content", name: "software_content_history" },
	{ table: "software_version", name: "software_version_history" },
	{ table: "software_release", name: "software_release_history" },
	{ table: "software_record_revision", name: "software_record_revision_immutable" },
	{ table: "software_component_revision", name: "software_component_revision_immutable" },
	{ table: "software_patch_target", name: "software_patch_target_kind" },
	{ table: "software_release", name: "software_release_patch_kind" },
	{ table: "catalog_source_record", name: "catalog_source_record_guard" },
	{ table: "catalog_source_mapping_claim", name: "catalog_source_mapping_guard" },
	{ table: "entity_catalog_profile_revision", name: "entity_catalog_profile_revision_guard" },
	{ table: "reference_catalog_profile_revision", name: "reference_catalog_profile_revision_guard" },
	{ table: "grouping_command_revision", name: "grouping_command_revision_guard" },
	{ table: "entity_catalog_profile", name: "entity_catalog_profile_classification_guard" },
	{ table: "reference_area", name: "reference_area_classification_guard" },
	{ table: "reference_place", name: "reference_place_classification_guard" },
	{ table: "reference_event", name: "reference_event_classification_guard" },
	{ table: "reference_instrument", name: "reference_instrument_classification_guard" },
	{ table: "reference_concept", name: "reference_concept_classification_guard" },
	{ table: "grouping_class_assignment", name: "grouping_class_assignment_classification_guard" },
	{ table: "operational_outbox", name: "operational_outbox_relay" },

	{ table: "software_participation_context", name: "software_context_guard" },
	{ table: "software_participation_context", name: "software_context_head_required" },
	{ table: "software_participation_context_revision", name: "software_context_revision_guard" },
	{
		table: "software_participation_context_revision",
		name: "software_context_revision_head_required",
	},
	{ table: "software_participation_source_occurrence", name: "software_context_occurrence_guard" },
	{ table: "operational_outbox", name: "operational_outbox_account" },
	{ table: "operational_outbox", name: "operational_outbox_immutable" },
	{ table: "operational_task_intent", name: "operational_task_account" },
	{ table: "operational_task_intent", name: "operational_task_immutable" },
	{ table: "operational_application_receipt", name: "operational_receipt_account" },
	{ table: "operational_application_receipt", name: "operational_receipt_immutable" },
	{ table: "music_recording", name: "music_recording_sealed_credit_guard" },
	{ table: "music_release_group", name: "music_release_group_sealed_credit_guard" },
	{ table: "music_release", name: "music_release_sealed_credit_guard" },
	{ table: "music_track_occurrence", name: "music_track_occurrence_sealed_credit_guard" },
	{ table: "music_release_presentation", name: "music_release_presentation_sealed_credit_guard" },
	{ table: "music_alternative_track", name: "music_alternative_track_sealed_credit_guard" },
	{ table: "music_artist_credit_name", name: "music_credit_member_guard" },
	{ table: "music_artist_credit_name", name: "music_credit_member_count" },
	{ table: "music_artist_credit", name: "music_credit_header_guard" },
	{ table: "reference_area", name: "reference_area_type_vocab_guard" },
	{ table: "reference_place", name: "reference_place_type_vocab_guard" },
	{ table: "reference_instrument", name: "reference_instrument_type_vocab_guard" },
	{ table: "reference_event", name: "reference_event_type_vocab_guard" },
	{ table: "entity_catalog_profile", name: "entity_catalog_profile_type_vocab_guard" },
	{ table: "entity_catalog_profile", name: "entity_catalog_profile_gender_vocab_guard" },
	{ table: "publishing_text_version", name: "publishing_text_version_method_vocab_guard" },
	{
		table: "publishing_publication_facet",
		name: "publishing_publication_facet_definition_vocab_guard",
	},
	{ table: "publishing_serialization", name: "publishing_serialization_status_vocab_guard" },
	{ table: "publishing_installment", name: "publishing_installment_kind_vocab_guard" },
	{ table: "music_work", name: "music_work_type_vocab_guard" },
	{ table: "music_release_group", name: "music_release_group_primary_type_vocab_guard" },
	{
		table: "music_release_group_secondary_type",
		name: "music_release_group_secondary_type_type_vocab_guard",
	},
	{ table: "music_release", name: "music_release_status_vocab_guard" },
	{ table: "music_release", name: "music_release_packaging_vocab_guard" },
	{ table: "music_medium", name: "music_medium_format_vocab_guard" },
	{ table: "music_release_presentation", name: "music_release_presentation_type_vocab_guard" },
	{ table: "program_work", name: "program_work_type_vocab_guard" },
	{ table: "program_version", name: "program_version_version_type_vocab_guard" },
	{ table: "program_episode", name: "program_episode_type_vocab_guard" },
	{ table: "software_release", name: "software_release_type_vocab_guard" },
	{ table: "software_release_content", name: "software_release_content_release_type_vocab_guard" },
	{ table: "software_release_platform", name: "software_release_platform_platform_vocab_guard" },
	{ table: "software_release_medium", name: "software_release_medium_medium_type_vocab_guard" },
	{ table: "software_release_language", name: "software_release_language_channel_vocab_guard" },
	{ table: "publishing_installment", name: "publishing_installment_parent_guard" },
	{ table: "publishing_fact_value_node", name: "publishing_fact_value_node_value_guard" },
	{ table: "publishing_fact", name: "publishing_fact_value_guard" },
	{ table: "music_fact_value_node", name: "music_fact_value_node_value_guard" },
	{ table: "music_fact", name: "music_fact_value_guard" },
	{ table: "program_fact_value_node", name: "program_fact_value_node_value_guard" },
	{ table: "program_fact", name: "program_fact_value_guard" },
	{ table: "software_fact_value_node", name: "software_fact_value_node_value_guard" },
	{ table: "software_fact", name: "software_fact_value_guard" },
	{ table: "entity_fact_value_node", name: "entity_fact_value_node_value_guard" },
	{ table: "entity_fact", name: "entity_fact_value_guard" },
	{ table: "grouping_fact_value_node", name: "grouping_fact_value_node_value_guard" },
	{ table: "grouping_fact", name: "grouping_fact_value_guard" },
	{ table: "reference_fact_value_node", name: "reference_fact_value_node_value_guard" },
	{ table: "reference_fact", name: "reference_fact_value_guard" },
	{ table: "catalog_source_snapshot", name: "catalog_source_snapshot_immutable" },
	{ table: "catalog_definition", name: "catalog_definition_identity_guard" },
	{ table: "catalog_definition_revision", name: "catalog_definition_revision_guard" },
	{ table: "grouping_class_assignment", name: "grouping_class_definition_guard" },
	{ table: "publishing_identity", name: "publishing_identity_route_publish" },
	{ table: "publishing_identity", name: "publishing_identity_route_remove" },
	{ table: "publishing_fact", name: "publishing_fact_definition_guard" },
	{ table: "publishing_catalog_relation", name: "publishing_catalog_relation_definition_guard" },
	{
		table: "publishing_relation_participant",
		name: "publishing_relation_participant_definition_guard",
	},
	{ table: "publishing_relation_scope", name: "publishing_relation_scope_definition_guard" },
	{ table: "music_identity", name: "music_identity_route_publish" },
	{ table: "music_identity", name: "music_identity_route_remove" },
	{ table: "music_fact", name: "music_fact_definition_guard" },
	{ table: "music_catalog_relation", name: "music_catalog_relation_definition_guard" },
	{ table: "music_relation_participant", name: "music_relation_participant_definition_guard" },
	{ table: "music_relation_scope", name: "music_relation_scope_definition_guard" },
	{ table: "program_identity", name: "program_identity_route_publish" },
	{ table: "program_identity", name: "program_identity_route_remove" },
	{ table: "program_fact", name: "program_fact_definition_guard" },
	{ table: "program_catalog_relation", name: "program_catalog_relation_definition_guard" },
	{ table: "program_relation_participant", name: "program_relation_participant_definition_guard" },
	{ table: "program_relation_scope", name: "program_relation_scope_definition_guard" },
	{ table: "software_identity", name: "software_identity_route_publish" },
	{ table: "software_identity", name: "software_identity_route_remove" },
	{ table: "software_fact", name: "software_fact_definition_guard" },
	{ table: "software_catalog_relation", name: "software_catalog_relation_definition_guard" },
	{
		table: "software_relation_participant",
		name: "software_relation_participant_definition_guard",
	},
	{ table: "software_relation_scope", name: "software_relation_scope_definition_guard" },
	{ table: "entity_identity", name: "entity_identity_route_publish" },
	{ table: "entity_identity", name: "entity_identity_route_remove" },
	{ table: "entity_fact", name: "entity_fact_definition_guard" },
	{ table: "entity_catalog_relation", name: "entity_catalog_relation_definition_guard" },
	{ table: "entity_relation_participant", name: "entity_relation_participant_definition_guard" },
	{ table: "entity_relation_scope", name: "entity_relation_scope_definition_guard" },
	{ table: "grouping_identity", name: "grouping_identity_route_publish" },
	{ table: "grouping_identity", name: "grouping_identity_route_remove" },
	{ table: "grouping_fact", name: "grouping_fact_definition_guard" },
	{ table: "grouping_catalog_relation", name: "grouping_catalog_relation_definition_guard" },
	{
		table: "grouping_relation_participant",
		name: "grouping_relation_participant_definition_guard",
	},
	{ table: "grouping_relation_scope", name: "grouping_relation_scope_definition_guard" },
	{ table: "reference_identity", name: "reference_identity_route_publish" },
	{ table: "reference_identity", name: "reference_identity_route_remove" },
	{ table: "reference_fact", name: "reference_fact_definition_guard" },
	{ table: "reference_catalog_relation", name: "reference_catalog_relation_definition_guard" },
	{
		table: "reference_relation_participant",
		name: "reference_relation_participant_definition_guard",
	},
	{ table: "reference_relation_scope", name: "reference_relation_scope_definition_guard" },
	{
		table: "custom_theme_revision",
		name: "custom_theme_revision_package_immutable",
	},
	{
		table: "custom_theme_revision_file",
		name: "custom_theme_revision_file_immutable",
	},
	{
		table: "custom_theme_revision_review_event",
		name: "custom_theme_revision_review_event_immutable",
	},
	{
		table: "platform_capability_grant",
		name: "platform_capability_grant_custom_theme_lifecycle_guard",
	},
	{ table: "account_unit_tag", name: "account_unit_tag_application_policy_guard" },
	{ table: "realm_tag_judgment", name: "realm_tag_judgment_content_label_reject" },
	{ table: "realm_tag_judgment", name: "realm_tag_judgment_stat_maintain" },
	{ table: "realm_tag_path_sense", name: "realm_tag_path_sense_adoption_guard" },
	{ table: "realm_tag_path_vote", name: "realm_tag_path_vote_stat_maintain" },
	{ table: "realm_unit_tag", name: "realm_unit_tag_application_policy_guard" },
	{ table: "realm_unit_tag", name: "realm_unit_tag_expression_assertion_maintain" },
	{
		table: "realm_unit_tag_path_application",
		name: "realm_unit_tag_path_application_expression_maintain",
	},
	{
		table: "realm_unit_tag_path_application",
		name: "realm_unit_tag_path_application_guard",
	},
	{
		table: "realm_unit_tag_path_application_judgment",
		name: "realm_unit_tag_path_application_judgment_identity_guard",
	},
	{
		table: "realm_unit_tag_path_application_judgment",
		name: "realm_unit_tag_path_application_judgment_stat_maintain",
	},
	{ table: "subject_association_judgment", name: "subject_association_judgment_stat_maintain" },
	{ table: "tag", name: "tag_directly_applicable_transition_guard" },
	{ table: "tag", name: "tag_path_concept_lifecycle_guard" },
	{ table: "tag", name: "tag_public_position_stat_seed" },
	{ table: "tag_expression", name: "tag_expression_closure_from_definition" },
	{ table: "tag_expression", name: "tag_expression_mutation_guard" },
	{ table: "tag_expression_argument", name: "tag_expression_argument_mutation_guard" },
	{
		table: "tag_expression_group_key",
		name: "tag_expression_group_key_mutation_guard",
	},
	{
		table: "tag_expression_inference_rule",
		name: "tag_expression_closure_from_rule",
	},
	{
		table: "tag_expression_inference_rule",
		name: "tag_expression_inference_graph_guard",
	},
	{
		table: "tag_expression_inference_rule",
		name: "tag_expression_inference_rule_mutation_guard",
	},
	{
		table: "tag_expression_label_component",
		name: "tag_expression_label_component_mutation_guard",
	},
	{
		table: "tag_expression_presentation_revision",
		name: "tag_expression_presentation_mutation_guard",
	},
	{ table: "tag_path", name: "tag_path_definition_guard" },
	{ table: "tag_path", name: "tag_path_definition_project" },
	{ table: "tag_path_member", name: "tag_path_member_projection_guard" },
	{ table: "tag_path_merge", name: "tag_path_merge_guard" },
	{ table: "tag_path_sense", name: "tag_path_sense_mutation_guard" },
	{ table: "tag_path_sense_binding", name: "tag_path_sense_binding_mutation_guard" },
	{ table: "tag_path_vote", name: "tag_path_vote_stat_maintain" },
	{ table: "tag_path_vote_stat", name: "tag_path_vote_stat_projection_guard" },
	{
		table: "tag_public_position_stat",
		name: "tag_public_position_stat_projection_guard",
	},
	{ table: "tag_relation", name: "tag_relation_path_lifecycle_guard" },
	{ table: "tag_relation", name: "tag_relation_graph_guard" },
	{ table: "tag_path", name: "tag_path_public_delete_maintain" },
	{ table: "tag_path", name: "tag_path_public_state_maintain" },
	{ table: "unit_presentation_revision", name: "unit_presentation_revision_immutable" },
	{ table: "unit_content_language_support", name: "unit_content_language_search_maintain" },
	{ table: "unit_license_grant", name: "unit_license_grant_guard_mutation" },
	{ table: "unit_merge_operation", name: "unit_merge_operation_content_label_guard" },
	{ table: "unit_tag", name: "unit_tag_application_policy_guard" },
	{ table: "unit_tag", name: "unit_tag_expression_assertion_maintain" },
	{ table: "unit_tag_judgment", name: "unit_tag_judgment_content_label_reject" },
	{ table: "unit_tag_judgment", name: "unit_tag_judgment_stat_maintain" },
	{
		table: "unit_tag_path_application",
		name: "unit_tag_path_application_expression_maintain",
	},
	{ table: "unit_tag_path_application", name: "unit_tag_path_application_guard" },
	{
		table: "unit_tag_path_application_judgment",
		name: "unit_tag_path_application_judgment_identity_guard",
	},
	{
		table: "unit_tag_path_application_judgment",
		name: "unit_tag_path_application_judgment_stat_maintain",
	},
	{ table: "vocabulary_node", name: "vocabulary_node_path_lifecycle_guard" },
] as const;

export type PostgreSqlSchemaTriggerContract = {
	readonly table: string;
	readonly name: string;
	readonly timing: "BEFORE" | "AFTER" | "INSTEAD OF";
	readonly events: readonly ("DELETE" | "INSERT" | "TRUNCATE" | "UPDATE")[];
	readonly level: "ROW" | "STATEMENT";
	readonly functionName: string;
};

const CatalogTriggerOwners = [
	"publishing",
	"music",
	"program",
	"software",
	"entity",
	"grouping",
	"reference",
	"distribution",
] as const;

const CatalogSourceApplicationTables = [
	"entity_source_profile_application_change",
	"reference_source_profile_application_change",
	"catalog_source_application",
	"music_source_application_change",
	"software_source_component_application_change",
	"software_source_record_application_change",
	"software_source_context_application_change",
	"software_source_participation_application_change",
	...CatalogTriggerOwners.flatMap((owner) =>
		["semantic", "name", "authority", "identifier"].map(
			(kind) => `${owner}_source_${kind}_application_change`,
		),
	),
];

/**
 * Explicit bounded families created by canonical DO blocks. The live checker drops all
 * these identities inside its rollback transaction, requires recreation, and compares
 * complete definitions (including arguments, constraint timing and enabled status).
 */
export const PostgreSqlSchemaDynamicTriggers = [
	...["publishing","music","program","software","entity","grouping","reference","distribution"].flatMap(owner => [
		{table:`${owner}_editorial`,name:"catalog_editorial_guard"},
		{table:`${owner}_editorial`,name:"catalog_editorial_capture"},
		{table:`${owner}_editorial_revision`,name:"catalog_editorial_history_guard"},
	]),
	...CatalogTriggerOwners.map(owner => ({ table: `${owner}_identity`, name: "zz_studio_catalog_creator_candidate" })),
	...[
		"post",
		"video",
		"audio",
		"poll",
		"zone",
		"realm",
		"realm_rule",
		"custom_theme",
		"collection",
		"tag",
		"tag_path",
		"label",
	].map((table) => ({ table, name: "platform_identity_guard" })),
	...UnitReferenceConsumers.map(({ table, prefix }) => ({
		table,
		name: `unit_reference_${prefix}`,
	})),
	...["program", "publishing"].flatMap((owner) => [
		{ table: `${owner}_structure_source_occurrence`, name: "catalog_structure_source_immutable" },
		{
			table: `${owner}_structure_source_application_change`,
			name: "catalog_structure_source_immutable",
		},
		{
			table: `${owner}_structure_source_occurrence`,
			name: "catalog_structure_source_occurrence_guard",
		},
		{
			table: `${owner}_structure_source_application_change`,
			name: "catalog_structure_source_application_guard",
		},
		{
			table: `${owner}_structure_source_baseline`,
			name: "catalog_structure_source_baseline_guard",
		},
	]),
	...[
		"video",
		"audio",
		"post",
		"poll",
		"zone",
		"realm",
		"realm_rule",
		"custom_theme",
		"collection",
		"tag",
		"tag_path",
		"label",
	].flatMap((table) => [
		{ table, name: "unit_platform_route_publish" },
		{ table, name: "unit_platform_route_remove" },
	]),
	...CatalogTriggerOwners.flatMap((owner) => [
		{ table: `${owner}_fact_support`, name: "catalog_source_support_guard" },
		{ table: `${owner}_fact_support`, name: "catalog_support_correspondence_guard" },
	]),
	...CatalogTriggerOwners.flatMap((owner) =>
		["name_source_binding", "name_source_occurrence"].map((family) => ({
			table: `${owner}_${family}`,
			name: "catalog_name_correspondence_guard",
		})),
	),
	...["entity", "reference"].flatMap((owner) => [
		{ table: `${owner}_profile_source_occurrence`, name: "catalog_profile_correspondence_guard" },
		{ table: `${owner}_profile_source_occurrence`, name: "catalog_profile_source_immutable" },
		{ table: `${owner}_profile_source_occurrence`, name: "catalog_profile_source_exact" },
		{ table: `${owner}_source_profile_baseline`, name: "catalog_profile_baseline_exact" },
	]),
	...CatalogTriggerOwners.map((owner) => ({
		table: `${owner}_source_owned_baseline`,
		name: "catalog_source_baseline_guard",
	})),
	...["record", "component", "context", "participation"].map((kind) => ({
		table: `software_source_${kind}_baseline`,
		name: "catalog_source_baseline_guard",
	})),
	...["software_record_source_occurrence", "software_component_source_occurrence"].map((table) => ({
		table,
		name: "software_source_occurrence_immutable",
	})),
	...[
		"program_work",
		"program_season",
		"program_version",
		"program_episode",
		"program_episode_occurrence",
		"publishing_work",
		"publishing_text_version",
		"publishing_publication",
		"publishing_serialization",
		"publishing_text_work",
		"publishing_publication_text",
		"publishing_publication_work",
		"publishing_publication_facet",
		"publishing_release_event",
		"publishing_installment",
	].map((table) => ({ table, name: "catalog_capture_structure_revision" })),
	...["program", "publishing"].flatMap((owner) => [
		{ table: `${owner}_component_source_occurrence`, name: "catalog_child_source_immutable" },
		{
			table: `${owner}_component_source_application_change`,
			name: "catalog_child_source_immutable",
		},
		{
			table: `${owner}_component_source_occurrence`,
			name: "catalog_child_source_occurrence_guard",
		},
		{
			table: `${owner}_component_source_application_change`,
			name: "catalog_child_source_application_guard",
		},
		{ table: `${owner}_component_source_baseline`, name: "catalog_child_source_baseline_guard" },
		{ table: `${owner}_component_head`, name: "catalog_structure_head_maintained" },
		{ table: `${owner}_component_revision`, name: "catalog_structure_revision_capture_only" },
		{ table: `${owner}_component_revision`, name: "catalog_structure_history_immutable" },
		{ table: `${owner}_component_source_occurrence`, name: "catalog_structure_history_immutable" },
		{ table: `${owner}_component_source_occurrence`, name: "catalog_structure_source_exact" },
	]),
	...CatalogSourceApplicationTables.map((table) => ({
		table,
		name: "catalog_source_application_immutable",
	})),
	...CatalogSourceApplicationTables.filter(
		(table) => !["catalog_source_application", "music_source_application_change"].includes(table),
	).map((table) => ({ table, name: "catalog_source_application_change_guard" })),
	...["catalog_source_application"].flatMap((parent) =>
		Array.from({ length: 64 }, (_, index) => ({
			table: `${parent}_p${String(index).padStart(2, "0")}`,
			name: "catalog_source_application_complete",
		})),
	),
	...[
		"catalog_source_snapshot",
		"catalog_source_binding_revision",
		"catalog_source_check_receipt",
	].map((table) => ({ table, name: "catalog_source_evidence_guard" })),
	...[
		"catalog_source_mapping_claim",
		"catalog_source_binding_revision",
		...CatalogTriggerOwners.map((owner) => `${owner}_source_binding`),
	].flatMap((parent) =>
		Array.from({ length: 64 }, (_, index) => ({
			table: `${parent}_p${String(index).padStart(2, "0")}`,
			name: "catalog_source_binding_head_required",
		})),
	),
	...CatalogTriggerOwners.flatMap((owner) => [
		...["named_form", "identifier_claim", "name_authority"].flatMap((suffix) => [
			{ table: `${owner}_${suffix}`, name: "catalog_named_head_guard" },
			{ table: `${owner}_${suffix}`, name: "catalog_named_head_snapshot" },
			{ table: `${owner}_${suffix}_revision`, name: "catalog_named_history_guard" },
		]),
		...["name_source_binding", "name_source_occurrence"].map((suffix) => ({
			table: `${owner}_${suffix}`,
			name: "catalog_name_source_guard",
		})),
	]),
	...[
		"music_work",
		"music_recording",
		"music_release_group",
		"music_release",
		"music_release_candidate",
		"music_medium",
		"music_track_occurrence",
		"music_release_label",
		"music_release_event",
		"music_release_presentation",
		"music_medium_presentation",
		"music_candidate_track",
		"music_work_language",
		"music_release_group_secondary_type",
	].map((table) => ({ table, name: `${table}_record_revision` })),
	...[
		"software_release_content",
		"software_release_platform",
		"software_release_medium",
		"software_release_language",
		"software_release_event",
		"software_patch_target",
		"software_release_animation",
	].map((table) => ({ table, name: "software_component_history" })),
] as const;

/** Exact dynamic declarations permitted by the static manifest check. */
export const PostgreSqlSchemaDynamicTriggerTemplates = [
	"CREATE TRIGGER catalog_editorial_guard BEFORE INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_editorial_guard(%L)",
	"CREATE TRIGGER catalog_editorial_capture AFTER INSERT OR UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_editorial_capture(%L)",
	"CREATE TRIGGER catalog_editorial_history_guard BEFORE INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_editorial_history_guard(%L)",
	"CREATE TRIGGER zz_studio_catalog_creator_candidate AFTER INSERT OR DELETE OR UPDATE OF created_by_auth_user_id, deleted_at ON public.%I FOR EACH ROW EXECUTE FUNCTION public.maintain_studio_catalog_creator_candidate()",
	"CREATE TRIGGER catalog_child_source_immutable BEFORE UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_source_guard_immutable_evidence()",
	"CREATE TRIGGER catalog_child_source_occurrence_guard BEFORE INSERT ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_child_source_guard_occurrence(%L)",
	"CREATE TRIGGER catalog_child_source_application_guard BEFORE INSERT ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_child_source_guard_application(%L)",
	"CREATE TRIGGER catalog_child_source_baseline_guard BEFORE INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_child_source_guard_baseline(%L)",
	"CREATE TRIGGER platform_identity_guard BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.maintain_platform_identity()",
	"CREATE TRIGGER %I BEFORE INSERT OR UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.unit_populate_reference(%L,%L,%L)",
	"CREATE TRIGGER catalog_structure_source_immutable BEFORE UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_source_guard_immutable_evidence()",
	"CREATE TRIGGER catalog_structure_source_occurrence_guard BEFORE INSERT ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_structure_source_guard_occurrence(%L)",
	"CREATE TRIGGER catalog_structure_source_application_guard BEFORE INSERT ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_structure_source_guard_application(%L)",
	"CREATE TRIGGER catalog_structure_source_baseline_guard BEFORE INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_structure_source_guard_baseline(%L)",
	"CREATE TRIGGER unit_platform_route_publish AFTER INSERT OR UPDATE OF id,routing_generation ON public.%I FOR EACH ROW EXECUTE FUNCTION public.unit_publish_platform_route(%L)",
	"CREATE TRIGGER unit_platform_route_remove AFTER DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.unit_remove_platform_route(%L)",
	"CREATE TRIGGER catalog_name_correspondence_guard BEFORE INSERT ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_source_guard_child_correspondence(%L)",
	"CREATE TRIGGER catalog_support_correspondence_guard BEFORE INSERT ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_source_guard_child_correspondence(%L)",
	"CREATE TRIGGER catalog_profile_correspondence_guard BEFORE INSERT ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_source_guard_child_correspondence(%L)",
	"CREATE TRIGGER catalog_source_support_guard BEFORE UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_guard_source_support()",
	"CREATE TRIGGER catalog_profile_source_immutable BEFORE UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_source_guard_immutable_evidence()",
	"CREATE TRIGGER catalog_profile_source_exact BEFORE INSERT ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_validate_profile_source(%L)",
	"CREATE TRIGGER catalog_profile_baseline_exact BEFORE INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_validate_profile_baseline(%L)",
	"CREATE TRIGGER catalog_structure_head_maintained BEFORE INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_guard_structure_head(%L)",
	"CREATE TRIGGER catalog_structure_revision_capture_only BEFORE INSERT ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_guard_structure_revision_insert()",
	"CREATE TRIGGER catalog_source_baseline_guard BEFORE INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_source_guard_owned_baseline(%L,%L)",
	"CREATE TRIGGER catalog_source_baseline_guard BEFORE INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_source_guard_owned_baseline(%L)",
	"CREATE TRIGGER software_source_occurrence_immutable BEFORE UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_source_guard_immutable_evidence()",
	"CREATE TRIGGER catalog_capture_structure_revision AFTER INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_capture_structure_revision(%L,%L,%L)",
	"CREATE TRIGGER catalog_structure_history_immutable BEFORE UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_guard_structure_history()",
	"CREATE TRIGGER catalog_structure_source_exact BEFORE INSERT ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_validate_structure_source(%L)",
	"CREATE TRIGGER catalog_source_application_change_guard BEFORE INSERT ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_source_validate_application_change()",
	"CREATE TRIGGER catalog_source_application_immutable BEFORE UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_source_guard_immutable_evidence()",
	"CREATE CONSTRAINT TRIGGER catalog_source_application_complete AFTER INSERT ON %s DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.catalog_source_require_application_complete()",
	"CREATE TRIGGER catalog_source_evidence_guard BEFORE UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_source_guard_immutable_evidence()",
	"CREATE CONSTRAINT TRIGGER catalog_source_binding_head_required AFTER INSERT OR UPDATE ON %s DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.catalog_source_require_binding_head()",
	"CREATE TRIGGER catalog_named_head_guard BEFORE INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_guard_named_head()",
	"CREATE TRIGGER catalog_named_head_snapshot AFTER INSERT OR UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_snapshot_named_head()",
	"CREATE TRIGGER catalog_named_history_guard BEFORE INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_guard_named_history(%L)",
	"CREATE TRIGGER catalog_name_source_guard BEFORE UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_guard_name_source_identity()",
	"CREATE TRIGGER %I AFTER INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_record_music_component(%L,%L)",
	"CREATE TRIGGER software_component_history AFTER INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.capture_software_component_revision(%L,%L)",
] as const;

export const PostgreSqlSchemaTriggerContracts =
	[] as const satisfies readonly PostgreSqlSchemaTriggerContract[];

export type PostgreSqlSchemaView = {
	readonly name: `current_${string}`;
	readonly relOptions: readonly string[];
	readonly columns: readonly { readonly name: string; readonly dataType: string }[];
};

export const PostgreSqlSchemaViews = [] as const satisfies readonly PostgreSqlSchemaView[];
