export const PostgreSqlSchemaFileNames = [
	"catalog-distribution-integrity.sql",
	"catalog-music-history.sql",
	"catalog-name-integrity.sql",
	"catalog-semantics-integrity.sql",
	"catalog-software-history.sql",
	"catalog-software-participation-integrity.sql",
	"catalog-source-integrity.sql",
	"catalog-source-application.sql",
	"catalog-supporting-integrity.sql",
	"operational-runtime.sql",

	"catalog-credit-integrity.sql",
	"catalog-domain-integrity.sql",
	"catalog-integrity.sql",
	"catalog-software-context-integrity.sql",
	"operational-durability.sql",
	"book-chapter-progress.sql",
	"content-label-policy.sql",
	"content-language-search.sql",
	"custom-theme-integrity.sql",
	"entity-measurement.sql",
	"realm-tag-authority.sql",
	"tag-judgment-aggregates.sql",
	"tag-path.sql",
	"tag-path-search.sql",
	"unit-license-grant.sql",
	"unit-search-document.sql",
	"unit-variant-integrity.sql",
] as const;

export type PostgreSqlSchemaFileName = (typeof PostgreSqlSchemaFileNames)[number];

/**
 * Release migrations may install one atomic domain cutover while the canonical
 * PostgreSQL definitions remain split by responsibility for review and drift checks.
 */
export const PostgreSqlSchemaMigrationBundles = {
	catalog_context_music_evidence: [
		"catalog-software-participation-integrity.sql",
		"catalog-music-history.sql",
	],
	catalog_source_native_applications: ["catalog-source-application.sql"],
	catalog_native_source_event_batch: [
		"catalog-integrity.sql",
		"catalog-distribution-integrity.sql",
		"catalog-music-history.sql",
		"catalog-name-integrity.sql",
		"catalog-semantics-integrity.sql",
		"catalog-software-history.sql",
		"catalog-source-integrity.sql",
		"catalog-supporting-integrity.sql",
		"operational-runtime.sql",
	],
	operational_contexts_and_events: [
		"catalog-software-context-integrity.sql",
		"operational-durability.sql",
	],
	catalog_credit_streaming: ["catalog-credit-integrity.sql"],
	catalog_domain_structures: ["catalog-integrity.sql", "catalog-domain-integrity.sql"],
	catalog_value_integrity: ["catalog-integrity.sql"],
	catalog_native_foundation: ["catalog-integrity.sql"],
	unit_search_document_tombstones: ["unit-search-document.sql"],
	tag_path_semantic_model: [
		"realm-tag-authority.sql",
		"tag-judgment-aggregates.sql",
		"tag-path.sql",
		"content-label-policy.sql",
		"tag-path-search.sql",
	],
} as const satisfies Readonly<Record<string, readonly PostgreSqlSchemaFileName[]>>;

export const PostgreSqlSchemaFunctionNames = [
	"catalog_guard_software_participation",
	"catalog_require_software_participation_head",
	"catalog_guard_software_participation_revision",
	"catalog_require_software_participation_revision_head",
	"catalog_validate_software_participation",
	"catalog_check_music_source_occurrence",
	"catalog_source_validate_application_change",
	"catalog_source_require_application_complete",
	"catalog_guard_distribution_member",
	"catalog_count_distribution_members",
	"catalog_guard_distribution_manifest",
	"catalog_guard_distribution_revision",
	"catalog_require_distribution_head",
	"catalog_guard_distribution_package",
	"catalog_record_music_component",
	"catalog_guard_music_history",
	"catalog_guard_music_toc_offset_append",
	"catalog_check_music_toc_attachment",
	"catalog_valid_name_date",
	"catalog_guard_named_head",
	"catalog_snapshot_named_head",
	"catalog_guard_named_history",
	"catalog_guard_name_source_identity",
	"catalog_guard_semantic_immutable",
	"catalog_guard_governed_value",
	"catalog_guard_sealed_semantic",
	"catalog_guard_semantic_revision",
	"catalog_require_semantic_head",
	"catalog_guard_semantic_head",
	"catalog_guard_definition_constraints",
	"capture_software_record_revision",
	"reject_software_revision_mutation",
	"capture_software_component_revision",
	"enforce_software_patch_target",
	"catalog_source_guard_record",
	"catalog_source_guard_immutable_evidence",
	"catalog_source_guard_mapping",
	"catalog_source_require_binding_head",
	"catalog_guard_supporting_revision",
	"catalog_guard_supporting_classification",
	"operational_enqueue_relay",

	"catalog_guard_software_context",
	"catalog_require_software_context_head",
	"catalog_guard_software_context_revision",
	"catalog_require_software_context_revision_head",
	"operational_reserve_capacity",
	"operational_account_insert",
	"operational_guard_immutable",
	"catalog_guard_credit_member",
	"catalog_count_credit_members",
	"catalog_guard_credit_header",
	"catalog_require_sealed_credit",
	"catalog_guard_installment_parent",
	"catalog_guard_fact_value",
	"catalog_guard_fact_header",
	"catalog_guard_source_snapshot",
	"catalog_publish_identity_route",
	"catalog_remove_identity_route",
	"catalog_require_definition_kind",
	"catalog_guard_definition_revision",
	"catalog_guard_definition_identity",
	"catalog_guard_legacy_identity",
	"refresh_unit_search_document",
	"adjust_tag_public_position_stat",
	"apply_book_chapter_delta",
	"book_chapter_node_scope",
	"enforce_unit_variant_star",
	"enqueue_tag_expression_projection_rebuild",
	"guard_content_label_unit_merge",
	"guard_direct_tag_application_policy",
	"guard_entity_measurement",
	"guard_entity_variant_delete",
	"guard_entity_variant_kind_change",
	"guard_realm_tag_path_sense_adoption",
	"guard_realm_unit_tag_path_application",
	"guard_tag_directly_applicable_transition",
	"guard_tag_expression_argument_mutation",
	"guard_tag_expression_inference_graph",
	"guard_tag_expression_inference_rule_mutation",
	"guard_tag_expression_mutation",
	"guard_tag_expression_presentation_component_mutation",
	"guard_tag_expression_presentation_mutation",
	"guard_tag_path_concept_lifecycle",
	"guard_tag_path_definition",
	"guard_tag_path_merge",
	"guard_tag_path_projection",
	"guard_tag_path_sense_binding_mutation",
	"guard_tag_path_sense_mutation",
	"guard_tag_path_vote_stat_projection",
	"guard_tag_public_position_stat_projection",
	"guard_tag_relation_path_lifecycle",
	"guard_tag_relation_graph",
	"guard_unit_license_grant_mutation",
	"guard_unit_tag_path_application",
	"guard_vocabulary_node_path_lifecycle",
	"lock_realm_tag_judgment_keys",
	"lock_tag_public_position_keys",
	"lock_vote_hot_key",
	"lock_vote_hot_keys",
	"maintain_book_chapter_from_node",
	"maintain_book_chapter_from_post",
	"maintain_book_chapter_from_progress",
	"maintain_book_chapter_from_structure",
	"maintain_book_chapter_from_unit",
	"maintain_realm_application_expression",
	"maintain_realm_expression_from_direct",
	"maintain_realm_tag_judgment_stat",
	"maintain_realm_tag_path_vote_stat",
	"maintain_realm_unit_tag_path_application_judgment_stat",
	"maintain_subject_association_judgment_stat",
	"maintain_tag_expression_inference_closure",
	"maintain_tag_path_public_state",
	"maintain_tag_path_vote_stat",
	"maintain_unit_application_expression",
	"maintain_unit_content_language_search",
	"maintain_unit_expression_from_direct",
	"maintain_unit_tag_judgment_stat",
	"maintain_unit_tag_path_application_judgment_stat",
	"project_tag_path_definition",
	"protect_custom_theme_external_live_grant",
	"protect_custom_theme_revision_package",
	"protect_realm_tag_path_application_judgment_identity",
	"protect_unit_tag_path_application_judgment_identity",
	"rebuild_tag_expression_effective_tags",
	"refresh_realm_unit_effective_tags",
	"refresh_realm_unit_expression_assertion",
	"refresh_unit_effective_tags",
	"refresh_unit_expression_assertion",
	"reject_content_label_judgment",
	"reject_custom_theme_immutable_history_mutation",
	"search_tag_suggestion_candidates",
	"search_text_candidates",
	"seed_tag_public_position_stat",
	"tag_path_unit_is_public",
] as const;

export const PostgreSqlSchemaTriggers = [
	{ table: "software_participation", name: "software_participation_guard" },
	{ table: "software_participation", name: "software_participation_head_required" },
	{ table: "software_participation_revision", name: "software_participation_revision_guard" },
	{
		table: "software_participation_revision",
		name: "software_participation_revision_head_required",
	},
	{ table: "software_participation_revision", name: "software_participation_values" },
	{
		table: "software_participation_credit_source_occurrence",
		name: "software_participation_occurrence_guard",
	},
	{ table: "music_medium_identifier", name: "music_medium_identifier_record_revision" },
	{ table: "music_track_identifier", name: "music_track_identifier_record_revision" },
	{
		table: "music_component_source_occurrence",
		name: "music_component_source_occurrence_exact_history",
	},
	{
		table: "music_component_source_occurrence",
		name: "music_component_source_occurrence_immutable",
	},
	{ table: "music_source_application_change", name: "music_source_application_exact_component" },
	{ table: "distribution_identity", name: "distribution_identity_route_publish" },
	{ table: "distribution_identity", name: "distribution_identity_route_remove" },
	{ table: "distribution_fact", name: "distribution_fact_definition_guard" },
	{
		table: "distribution_catalog_relation",
		name: "distribution_catalog_relation_definition_guard",
	},
	{
		table: "distribution_relation_participant",
		name: "distribution_relation_participant_definition_guard",
	},
	{ table: "distribution_relation_scope", name: "distribution_relation_scope_definition_guard" },
	{ table: "distribution_fact_value_node", name: "distribution_fact_value_node_value_guard" },
	{ table: "distribution_fact", name: "distribution_fact_value_guard" },
	{ table: "distribution_member", name: "distribution_member_guard" },
	{ table: "distribution_member", name: "distribution_member_count" },
	{ table: "distribution_manifest", name: "distribution_manifest_guard" },
	{ table: "distribution_revision", name: "distribution_revision_guard" },
	{ table: "distribution_package", name: "distribution_package_guard" },
	{ table: "distribution_package", name: "distribution_package_head" },
	{ table: "distribution_revision", name: "distribution_revision_head" },
	{ table: "music_component_revision", name: "music_component_revision_immutable" },
	{ table: "music_disc_toc", name: "music_disc_toc_immutable" },
	{ table: "music_disc_toc_offset", name: "music_disc_toc_offset_immutable" },
	{ table: "music_disc_toc_offset", name: "music_disc_toc_offset_sealed" },
	{ table: "music_medium_toc", name: "music_medium_toc_complete" },
	{ table: "music_candidate_toc", name: "music_candidate_toc_complete" },
	{ table: "music_medium_attribute", name: "music_medium_attribute_record_revision" },
	{ table: "music_track_presentation", name: "music_track_presentation_record_revision" },
	{ table: "music_medium_toc", name: "music_medium_toc_record_revision" },
	{ table: "music_candidate_toc", name: "music_candidate_toc_record_revision" },
	{ table: "publishing_semantic_revision", name: "publishing_semantic_revision_immutable" },
	{ table: "publishing_catalog_relation", name: "publishing_catalog_relation_immutable" },
	{ table: "publishing_relation_participant", name: "publishing_relation_participant_immutable" },
	{ table: "publishing_relation_scope", name: "publishing_relation_scope_immutable" },
	{ table: "publishing_fact_value_node", name: "publishing_fact_value_node_governance" },
	{ table: "publishing_fact", name: "publishing_fact_sealed_semantic" },
	{
		table: "publishing_relation_participant",
		name: "publishing_relation_participant_sealed_semantic",
	},
	{ table: "publishing_relation_scope", name: "publishing_relation_scope_sealed_semantic" },
	{ table: "publishing_semantic_revision", name: "publishing_semantic_revision_governance" },
	{ table: "publishing_semantic_revision", name: "publishing_semantic_revision_head" },
	{ table: "music_semantic_revision", name: "music_semantic_revision_immutable" },
	{ table: "music_catalog_relation", name: "music_catalog_relation_immutable" },
	{ table: "music_relation_participant", name: "music_relation_participant_immutable" },
	{ table: "music_relation_scope", name: "music_relation_scope_immutable" },
	{ table: "music_fact_value_node", name: "music_fact_value_node_governance" },
	{ table: "music_fact", name: "music_fact_sealed_semantic" },
	{ table: "music_relation_participant", name: "music_relation_participant_sealed_semantic" },
	{ table: "music_relation_scope", name: "music_relation_scope_sealed_semantic" },
	{ table: "music_semantic_revision", name: "music_semantic_revision_governance" },
	{ table: "music_semantic_revision", name: "music_semantic_revision_head" },
	{ table: "program_semantic_revision", name: "program_semantic_revision_immutable" },
	{ table: "program_catalog_relation", name: "program_catalog_relation_immutable" },
	{ table: "program_relation_participant", name: "program_relation_participant_immutable" },
	{ table: "program_relation_scope", name: "program_relation_scope_immutable" },
	{ table: "program_fact_value_node", name: "program_fact_value_node_governance" },
	{ table: "program_fact", name: "program_fact_sealed_semantic" },
	{ table: "program_relation_participant", name: "program_relation_participant_sealed_semantic" },
	{ table: "program_relation_scope", name: "program_relation_scope_sealed_semantic" },
	{ table: "program_semantic_revision", name: "program_semantic_revision_governance" },
	{ table: "program_semantic_revision", name: "program_semantic_revision_head" },
	{ table: "software_semantic_revision", name: "software_semantic_revision_immutable" },
	{ table: "software_catalog_relation", name: "software_catalog_relation_immutable" },
	{ table: "software_relation_participant", name: "software_relation_participant_immutable" },
	{ table: "software_relation_scope", name: "software_relation_scope_immutable" },
	{ table: "software_fact_value_node", name: "software_fact_value_node_governance" },
	{ table: "software_fact", name: "software_fact_sealed_semantic" },
	{ table: "software_relation_participant", name: "software_relation_participant_sealed_semantic" },
	{ table: "software_relation_scope", name: "software_relation_scope_sealed_semantic" },
	{ table: "software_semantic_revision", name: "software_semantic_revision_governance" },
	{ table: "software_semantic_revision", name: "software_semantic_revision_head" },
	{ table: "entity_semantic_revision", name: "entity_semantic_revision_immutable" },
	{ table: "entity_catalog_relation", name: "entity_catalog_relation_immutable" },
	{ table: "entity_relation_participant", name: "entity_relation_participant_immutable" },
	{ table: "entity_relation_scope", name: "entity_relation_scope_immutable" },
	{ table: "entity_fact_value_node", name: "entity_fact_value_node_governance" },
	{ table: "entity_fact", name: "entity_fact_sealed_semantic" },
	{ table: "entity_relation_participant", name: "entity_relation_participant_sealed_semantic" },
	{ table: "entity_relation_scope", name: "entity_relation_scope_sealed_semantic" },
	{ table: "entity_semantic_revision", name: "entity_semantic_revision_governance" },
	{ table: "entity_semantic_revision", name: "entity_semantic_revision_head" },
	{ table: "grouping_semantic_revision", name: "grouping_semantic_revision_immutable" },
	{ table: "grouping_catalog_relation", name: "grouping_catalog_relation_immutable" },
	{ table: "grouping_relation_participant", name: "grouping_relation_participant_immutable" },
	{ table: "grouping_relation_scope", name: "grouping_relation_scope_immutable" },
	{ table: "grouping_fact_value_node", name: "grouping_fact_value_node_governance" },
	{ table: "grouping_fact", name: "grouping_fact_sealed_semantic" },
	{ table: "grouping_relation_participant", name: "grouping_relation_participant_sealed_semantic" },
	{ table: "grouping_relation_scope", name: "grouping_relation_scope_sealed_semantic" },
	{ table: "grouping_semantic_revision", name: "grouping_semantic_revision_governance" },
	{ table: "grouping_semantic_revision", name: "grouping_semantic_revision_head" },
	{ table: "reference_semantic_revision", name: "reference_semantic_revision_immutable" },
	{ table: "reference_catalog_relation", name: "reference_catalog_relation_immutable" },
	{ table: "reference_relation_participant", name: "reference_relation_participant_immutable" },
	{ table: "reference_relation_scope", name: "reference_relation_scope_immutable" },
	{ table: "reference_fact_value_node", name: "reference_fact_value_node_governance" },
	{ table: "reference_fact", name: "reference_fact_sealed_semantic" },
	{
		table: "reference_relation_participant",
		name: "reference_relation_participant_sealed_semantic",
	},
	{ table: "reference_relation_scope", name: "reference_relation_scope_sealed_semantic" },
	{ table: "reference_semantic_revision", name: "reference_semantic_revision_governance" },
	{ table: "reference_semantic_revision", name: "reference_semantic_revision_head" },
	{ table: "distribution_semantic_revision", name: "distribution_semantic_revision_immutable" },
	{ table: "distribution_catalog_relation", name: "distribution_catalog_relation_immutable" },
	{
		table: "distribution_relation_participant",
		name: "distribution_relation_participant_immutable",
	},
	{ table: "distribution_relation_scope", name: "distribution_relation_scope_immutable" },
	{ table: "distribution_fact_value_node", name: "distribution_fact_value_node_governance" },
	{ table: "distribution_fact", name: "distribution_fact_sealed_semantic" },
	{
		table: "distribution_relation_participant",
		name: "distribution_relation_participant_sealed_semantic",
	},
	{ table: "distribution_relation_scope", name: "distribution_relation_scope_sealed_semantic" },
	{ table: "distribution_semantic_revision", name: "distribution_semantic_revision_governance" },
	{ table: "distribution_semantic_revision", name: "distribution_semantic_revision_head" },
	{ table: "publishing_semantic_head", name: "publishing_semantic_head_governance" },
	{ table: "music_semantic_head", name: "music_semantic_head_governance" },
	{ table: "program_semantic_head", name: "program_semantic_head_governance" },
	{ table: "software_semantic_head", name: "software_semantic_head_governance" },
	{ table: "entity_semantic_head", name: "entity_semantic_head_governance" },
	{ table: "grouping_semantic_head", name: "grouping_semantic_head_governance" },
	{ table: "reference_semantic_head", name: "reference_semantic_head_governance" },
	{ table: "distribution_semantic_head", name: "distribution_semantic_head_governance" },
	{ table: "catalog_definition_revision", name: "catalog_definition_revision_governance" },
	{ table: "software_content", name: "software_content_history" },
	{ table: "software_version", name: "software_version_history" },
	{ table: "software_release", name: "software_release_history" },
	{ table: "software_record_revision", name: "software_record_revision_immutable" },
	{ table: "software_component_revision", name: "software_component_revision_immutable" },
	{ table: "software_patch_target", name: "software_patch_target_kind" },
	{ table: "software_release", name: "software_release_patch_kind" },
	{ table: "catalog_source_record", name: "catalog_source_record_guard" },
	{ table: "catalog_source_mapping_claim", name: "catalog_source_mapping_guard" },
	{ table: "entity_catalog_profile_revision", name: "entity_catalog_profile_revision_guard" },
	{ table: "reference_catalog_profile_revision", name: "reference_catalog_profile_revision_guard" },
	{ table: "grouping_command_revision", name: "grouping_command_revision_guard" },
	{ table: "entity_catalog_profile", name: "entity_catalog_profile_classification_guard" },
	{ table: "reference_area", name: "reference_area_classification_guard" },
	{ table: "reference_place", name: "reference_place_classification_guard" },
	{ table: "reference_event", name: "reference_event_classification_guard" },
	{ table: "reference_instrument", name: "reference_instrument_classification_guard" },
	{ table: "reference_concept", name: "reference_concept_classification_guard" },
	{ table: "grouping_class_assignment", name: "grouping_class_assignment_classification_guard" },
	{ table: "operational_outbox", name: "operational_outbox_relay" },

	{ table: "software_participation_context", name: "software_context_guard" },
	{ table: "software_participation_context", name: "software_context_head_required" },
	{ table: "software_participation_context_revision", name: "software_context_revision_guard" },
	{
		table: "software_participation_context_revision",
		name: "software_context_revision_head_required",
	},
	{ table: "software_participation_source_occurrence", name: "software_context_occurrence_guard" },
	{ table: "operational_outbox", name: "operational_outbox_account" },
	{ table: "operational_outbox", name: "operational_outbox_immutable" },
	{ table: "operational_task_intent", name: "operational_task_account" },
	{ table: "operational_task_intent", name: "operational_task_immutable" },
	{ table: "operational_application_receipt", name: "operational_receipt_account" },
	{ table: "operational_application_receipt", name: "operational_receipt_immutable" },
	{ table: "music_recording", name: "music_recording_sealed_credit_guard" },
	{ table: "music_release_group", name: "music_release_group_sealed_credit_guard" },
	{ table: "music_release", name: "music_release_sealed_credit_guard" },
	{ table: "music_track_occurrence", name: "music_track_occurrence_sealed_credit_guard" },
	{ table: "music_release_presentation", name: "music_release_presentation_sealed_credit_guard" },
	{ table: "music_alternative_track", name: "music_alternative_track_sealed_credit_guard" },
	{ table: "music_artist_credit_name", name: "music_credit_member_guard" },
	{ table: "music_artist_credit_name", name: "music_credit_member_count" },
	{ table: "music_artist_credit", name: "music_credit_header_guard" },
	{ table: "reference_area", name: "reference_area_type_vocab_guard" },
	{ table: "reference_place", name: "reference_place_type_vocab_guard" },
	{ table: "reference_instrument", name: "reference_instrument_type_vocab_guard" },
	{ table: "reference_event", name: "reference_event_type_vocab_guard" },
	{ table: "entity_catalog_profile", name: "entity_catalog_profile_type_vocab_guard" },
	{ table: "entity_catalog_profile", name: "entity_catalog_profile_gender_vocab_guard" },
	{ table: "publishing_text_version", name: "publishing_text_version_method_vocab_guard" },
	{
		table: "publishing_publication_facet",
		name: "publishing_publication_facet_definition_vocab_guard",
	},
	{ table: "publishing_serialization", name: "publishing_serialization_status_vocab_guard" },
	{ table: "publishing_installment", name: "publishing_installment_kind_vocab_guard" },
	{ table: "music_work", name: "music_work_type_vocab_guard" },
	{ table: "music_release_group", name: "music_release_group_primary_type_vocab_guard" },
	{
		table: "music_release_group_secondary_type",
		name: "music_release_group_secondary_type_type_vocab_guard",
	},
	{ table: "music_release", name: "music_release_status_vocab_guard" },
	{ table: "music_release", name: "music_release_packaging_vocab_guard" },
	{ table: "music_medium", name: "music_medium_format_vocab_guard" },
	{ table: "music_release_presentation", name: "music_release_presentation_type_vocab_guard" },
	{ table: "program_work", name: "program_work_type_vocab_guard" },
	{ table: "program_version", name: "program_version_version_type_vocab_guard" },
	{ table: "program_episode", name: "program_episode_type_vocab_guard" },
	{ table: "software_visual_novel", name: "software_visual_novel_length_type_vocab_guard" },
	{ table: "software_release", name: "software_release_type_vocab_guard" },
	{ table: "software_release_content", name: "software_release_content_release_type_vocab_guard" },
	{ table: "software_release_platform", name: "software_release_platform_platform_vocab_guard" },
	{ table: "software_release_medium", name: "software_release_medium_medium_type_vocab_guard" },
	{ table: "software_release_language", name: "software_release_language_channel_vocab_guard" },
	{ table: "publishing_installment", name: "publishing_installment_parent_guard" },
	{ table: "publishing_fact_value_node", name: "publishing_fact_value_node_value_guard" },
	{ table: "publishing_fact", name: "publishing_fact_value_guard" },
	{ table: "music_fact_value_node", name: "music_fact_value_node_value_guard" },
	{ table: "music_fact", name: "music_fact_value_guard" },
	{ table: "program_fact_value_node", name: "program_fact_value_node_value_guard" },
	{ table: "program_fact", name: "program_fact_value_guard" },
	{ table: "software_fact_value_node", name: "software_fact_value_node_value_guard" },
	{ table: "software_fact", name: "software_fact_value_guard" },
	{ table: "entity_fact_value_node", name: "entity_fact_value_node_value_guard" },
	{ table: "entity_fact", name: "entity_fact_value_guard" },
	{ table: "grouping_fact_value_node", name: "grouping_fact_value_node_value_guard" },
	{ table: "grouping_fact", name: "grouping_fact_value_guard" },
	{ table: "reference_fact_value_node", name: "reference_fact_value_node_value_guard" },
	{ table: "reference_fact", name: "reference_fact_value_guard" },
	{ table: "catalog_source_snapshot", name: "catalog_source_snapshot_immutable" },
	{ table: "unit", name: "catalog_legacy_identity_guard" },
	{ table: "catalog_definition", name: "catalog_definition_identity_guard" },
	{ table: "catalog_definition_revision", name: "catalog_definition_revision_guard" },
	{ table: "grouping_class_assignment", name: "grouping_class_definition_guard" },
	{ table: "publishing_identity", name: "publishing_identity_route_publish" },
	{ table: "publishing_identity", name: "publishing_identity_route_remove" },
	{ table: "publishing_fact", name: "publishing_fact_definition_guard" },
	{ table: "publishing_catalog_relation", name: "publishing_catalog_relation_definition_guard" },
	{
		table: "publishing_relation_participant",
		name: "publishing_relation_participant_definition_guard",
	},
	{ table: "publishing_relation_scope", name: "publishing_relation_scope_definition_guard" },
	{ table: "music_identity", name: "music_identity_route_publish" },
	{ table: "music_identity", name: "music_identity_route_remove" },
	{ table: "music_fact", name: "music_fact_definition_guard" },
	{ table: "music_catalog_relation", name: "music_catalog_relation_definition_guard" },
	{ table: "music_relation_participant", name: "music_relation_participant_definition_guard" },
	{ table: "music_relation_scope", name: "music_relation_scope_definition_guard" },
	{ table: "program_identity", name: "program_identity_route_publish" },
	{ table: "program_identity", name: "program_identity_route_remove" },
	{ table: "program_fact", name: "program_fact_definition_guard" },
	{ table: "program_catalog_relation", name: "program_catalog_relation_definition_guard" },
	{ table: "program_relation_participant", name: "program_relation_participant_definition_guard" },
	{ table: "program_relation_scope", name: "program_relation_scope_definition_guard" },
	{ table: "software_identity", name: "software_identity_route_publish" },
	{ table: "software_identity", name: "software_identity_route_remove" },
	{ table: "software_fact", name: "software_fact_definition_guard" },
	{ table: "software_catalog_relation", name: "software_catalog_relation_definition_guard" },
	{
		table: "software_relation_participant",
		name: "software_relation_participant_definition_guard",
	},
	{ table: "software_relation_scope", name: "software_relation_scope_definition_guard" },
	{ table: "entity_identity", name: "entity_identity_route_publish" },
	{ table: "entity_identity", name: "entity_identity_route_remove" },
	{ table: "entity_fact", name: "entity_fact_definition_guard" },
	{ table: "entity_catalog_relation", name: "entity_catalog_relation_definition_guard" },
	{ table: "entity_relation_participant", name: "entity_relation_participant_definition_guard" },
	{ table: "entity_relation_scope", name: "entity_relation_scope_definition_guard" },
	{ table: "grouping_identity", name: "grouping_identity_route_publish" },
	{ table: "grouping_identity", name: "grouping_identity_route_remove" },
	{ table: "grouping_fact", name: "grouping_fact_definition_guard" },
	{ table: "grouping_catalog_relation", name: "grouping_catalog_relation_definition_guard" },
	{
		table: "grouping_relation_participant",
		name: "grouping_relation_participant_definition_guard",
	},
	{ table: "grouping_relation_scope", name: "grouping_relation_scope_definition_guard" },
	{ table: "reference_identity", name: "reference_identity_route_publish" },
	{ table: "reference_identity", name: "reference_identity_route_remove" },
	{ table: "reference_fact", name: "reference_fact_definition_guard" },
	{ table: "reference_catalog_relation", name: "reference_catalog_relation_definition_guard" },
	{
		table: "reference_relation_participant",
		name: "reference_relation_participant_definition_guard",
	},
	{ table: "reference_relation_scope", name: "reference_relation_scope_definition_guard" },
	{
		table: "custom_theme_revision",
		name: "custom_theme_revision_package_immutable",
	},
	{
		table: "custom_theme_revision_file",
		name: "custom_theme_revision_file_immutable",
	},
	{
		table: "custom_theme_revision_review_event",
		name: "custom_theme_revision_review_event_immutable",
	},
	{ table: "content_structure", name: "book_chapter_structure_stat_maintain" },
	{ table: "content_structure_node", name: "book_chapter_node_stat_maintain" },
	{ table: "content_structure_node_progress", name: "book_chapter_progress_stat_maintain" },
	{ table: "entity", name: "entity_variant_delete_guard" },
	{ table: "entity", name: "entity_variant_kind_change_guard" },
	{ table: "entity_measurement", name: "entity_measurement_guard" },
	{ table: "post", name: "book_chapter_post_stat_maintain" },
	{
		table: "platform_capability_grant",
		name: "platform_capability_grant_custom_theme_lifecycle_guard",
	},
	{ table: "profile_unit_tag", name: "profile_unit_tag_application_policy_guard" },
	{ table: "realm_tag_judgment", name: "realm_tag_judgment_content_label_reject" },
	{ table: "realm_tag_judgment", name: "realm_tag_judgment_stat_maintain" },
	{ table: "realm_tag_path_sense", name: "realm_tag_path_sense_adoption_guard" },
	{ table: "realm_tag_path_vote", name: "realm_tag_path_vote_stat_maintain" },
	{ table: "realm_unit_tag", name: "realm_unit_tag_application_policy_guard" },
	{ table: "realm_unit_tag", name: "realm_unit_tag_expression_assertion_maintain" },
	{
		table: "realm_unit_tag_path_application",
		name: "realm_unit_tag_path_application_expression_maintain",
	},
	{
		table: "realm_unit_tag_path_application",
		name: "realm_unit_tag_path_application_guard",
	},
	{
		table: "realm_unit_tag_path_application_judgment",
		name: "realm_unit_tag_path_application_judgment_identity_guard",
	},
	{
		table: "realm_unit_tag_path_application_judgment",
		name: "realm_unit_tag_path_application_judgment_stat_maintain",
	},
	{ table: "subject_association_judgment", name: "subject_association_judgment_stat_maintain" },
	{ table: "tag", name: "tag_directly_applicable_transition_guard" },
	{ table: "tag", name: "tag_path_concept_lifecycle_guard" },
	{ table: "tag", name: "tag_public_position_stat_seed" },
	{ table: "tag_expression", name: "tag_expression_closure_from_definition" },
	{ table: "tag_expression", name: "tag_expression_mutation_guard" },
	{ table: "tag_expression_argument", name: "tag_expression_argument_mutation_guard" },
	{
		table: "tag_expression_group_key",
		name: "tag_expression_group_key_mutation_guard",
	},
	{
		table: "tag_expression_inference_rule",
		name: "tag_expression_closure_from_rule",
	},
	{
		table: "tag_expression_inference_rule",
		name: "tag_expression_inference_graph_guard",
	},
	{
		table: "tag_expression_inference_rule",
		name: "tag_expression_inference_rule_mutation_guard",
	},
	{
		table: "tag_expression_label_component",
		name: "tag_expression_label_component_mutation_guard",
	},
	{
		table: "tag_expression_presentation_revision",
		name: "tag_expression_presentation_mutation_guard",
	},
	{ table: "tag_path", name: "tag_path_definition_guard" },
	{ table: "tag_path", name: "tag_path_definition_project" },
	{ table: "tag_path_member", name: "tag_path_member_projection_guard" },
	{ table: "tag_path_merge", name: "tag_path_merge_guard" },
	{ table: "tag_path_sense", name: "tag_path_sense_mutation_guard" },
	{ table: "tag_path_sense_binding", name: "tag_path_sense_binding_mutation_guard" },
	{ table: "tag_path_vote", name: "tag_path_vote_stat_maintain" },
	{ table: "tag_path_vote_stat", name: "tag_path_vote_stat_projection_guard" },
	{
		table: "tag_public_position_stat",
		name: "tag_public_position_stat_projection_guard",
	},
	{ table: "tag_relation", name: "tag_relation_path_lifecycle_guard" },
	{ table: "tag_relation", name: "tag_relation_graph_guard" },
	{ table: "unit", name: "book_chapter_unit_stat_maintain" },
	{ table: "unit", name: "tag_path_public_delete_maintain" },
	{ table: "unit", name: "tag_path_public_state_maintain" },
	{ table: "unit_presentation_revision", name: "unit_presentation_revision_immutable" },
	{ table: "unit_content_language_support", name: "unit_content_language_search_maintain" },
	{ table: "unit_license_grant", name: "unit_license_grant_guard_mutation" },
	{ table: "unit_merge_operation", name: "unit_merge_operation_content_label_guard" },
	{ table: "unit_tag", name: "unit_tag_application_policy_guard" },
	{ table: "unit_tag", name: "unit_tag_expression_assertion_maintain" },
	{ table: "unit_tag_judgment", name: "unit_tag_judgment_content_label_reject" },
	{ table: "unit_tag_judgment", name: "unit_tag_judgment_stat_maintain" },
	{
		table: "unit_tag_path_application",
		name: "unit_tag_path_application_expression_maintain",
	},
	{ table: "unit_tag_path_application", name: "unit_tag_path_application_guard" },
	{
		table: "unit_tag_path_application_judgment",
		name: "unit_tag_path_application_judgment_identity_guard",
	},
	{
		table: "unit_tag_path_application_judgment",
		name: "unit_tag_path_application_judgment_stat_maintain",
	},
	{ table: "unit_variant", name: "unit_variant_star_enforce" },
	{ table: "vocabulary_node", name: "vocabulary_node_path_lifecycle_guard" },
] as const;

export type PostgreSqlSchemaTriggerContract = {
	readonly table: string;
	readonly name: string;
	readonly timing: "BEFORE" | "AFTER" | "INSTEAD OF";
	readonly events: readonly ("DELETE" | "INSERT" | "TRUNCATE" | "UPDATE")[];
	readonly level: "ROW" | "STATEMENT";
	readonly functionName: string;
};

const CatalogTriggerOwners = [
	"publishing",
	"music",
	"program",
	"software",
	"entity",
	"grouping",
	"reference",
	"distribution",
] as const;

/**
 * Explicit bounded families created by canonical DO blocks. The live checker drops all
 * these identities inside its rollback transaction, requires recreation, and compares
 * complete definitions (including arguments, constraint timing and enabled status).
 */
export const PostgreSqlSchemaDynamicTriggers = [
	...[
		"catalog_source_application",
		"music_source_application_change",
		"software_source_component_application_change",
		"software_source_record_application_change",
	].map((table) => ({ table, name: "catalog_source_application_immutable" })),
	...[
		"catalog_source_application",
		"music_source_application_change",
		"software_source_component_application_change",
		"software_source_record_application_change",
	].flatMap((parent) =>
		Array.from({ length: 64 }, (_, index) => ({
			table: `${parent}_p${String(index).padStart(2, "0")}`,
			name: "catalog_source_application_complete",
		})),
	),
	...[
		"catalog_source_snapshot",
		"catalog_source_binding_revision",
		"catalog_source_check_receipt",
	].map((table) => ({ table, name: "catalog_source_evidence_guard" })),
	...[
		"catalog_source_mapping_claim",
		"catalog_source_binding_revision",
		...CatalogTriggerOwners.map((owner) => `${owner}_source_binding`),
	].flatMap((parent) =>
		Array.from({ length: 64 }, (_, index) => ({
			table: `${parent}_p${String(index).padStart(2, "0")}`,
			name: "catalog_source_binding_head_required",
		})),
	),
	...CatalogTriggerOwners.flatMap((owner) => [
		...["named_form", "identifier_claim", "name_authority"].flatMap((suffix) => [
			{ table: `${owner}_${suffix}`, name: "catalog_named_head_guard" },
			{ table: `${owner}_${suffix}`, name: "catalog_named_head_snapshot" },
			{ table: `${owner}_${suffix}_revision`, name: "catalog_named_history_guard" },
		]),
		...["name_source_binding", "name_source_occurrence"].map((suffix) => ({
			table: `${owner}_${suffix}`,
			name: "catalog_name_source_guard",
		})),
	]),
	...[
		"music_work",
		"music_recording",
		"music_release_group",
		"music_release",
		"music_release_candidate",
		"music_medium",
		"music_track_occurrence",
		"music_release_label",
		"music_release_event",
		"music_release_presentation",
		"music_medium_presentation",
		"music_candidate_track",
		"music_work_language",
		"music_release_group_secondary_type",
	].map((table) => ({ table, name: `${table}_record_revision` })),
	...[
		"software_release_content",
		"software_release_platform",
		"software_release_medium",
		"software_release_language",
		"software_release_event",
		"software_patch_target",
		"software_release_animation",
	].map((table) => ({ table, name: "software_component_history" })),
] as const;

/** Exact dynamic declarations permitted by the static manifest check. */
export const PostgreSqlSchemaDynamicTriggerTemplates = [
	"CREATE TRIGGER catalog_source_application_immutable BEFORE UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_source_guard_immutable_evidence()",
	"CREATE CONSTRAINT TRIGGER catalog_source_application_complete AFTER INSERT ON %s DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.catalog_source_require_application_complete()",
	"CREATE TRIGGER catalog_source_evidence_guard BEFORE UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_source_guard_immutable_evidence()",
	"CREATE CONSTRAINT TRIGGER catalog_source_binding_head_required AFTER INSERT OR UPDATE ON %s DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.catalog_source_require_binding_head()",
	"CREATE TRIGGER catalog_named_head_guard BEFORE INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_guard_named_head()",
	"CREATE TRIGGER catalog_named_head_snapshot AFTER INSERT OR UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_snapshot_named_head()",
	"CREATE TRIGGER catalog_named_history_guard BEFORE INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_guard_named_history(%L)",
	"CREATE TRIGGER catalog_name_source_guard BEFORE UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_guard_name_source_identity()",
	"CREATE TRIGGER %I AFTER INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.catalog_record_music_component(%L,%L)",
	"CREATE TRIGGER software_component_history AFTER INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.capture_software_component_revision(%L,%L)",
] as const;

export const PostgreSqlSchemaTriggerContracts =
	[] as const satisfies readonly PostgreSqlSchemaTriggerContract[];

export type PostgreSqlSchemaView = {
	readonly name: `current_${string}`;
	readonly relOptions: readonly string[];
	readonly columns: readonly { readonly name: string; readonly dataType: string }[];
};

export const PostgreSqlSchemaViews = [] as const satisfies readonly PostgreSqlSchemaView[];
