/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainLayoutRouteImport } from './routes/_mainLayout'
import { Route as MainLayoutIndexRouteImport } from './routes/_mainLayout/index'
import { Route as MainLayoutVerifyEmailRouteImport } from './routes/_mainLayout/verify-email'
import { Route as MainLayoutThemeSwitchRouteImport } from './routes/_mainLayout/theme-switch'
import { Route as MainLayoutTest03RouteImport } from './routes/_mainLayout/test03'
import { Route as MainLayoutTest02RouteImport } from './routes/_mainLayout/test02'
import { Route as MainLayoutTestRouteImport } from './routes/_mainLayout/test'
import { Route as MainLayoutResetPasswordRouteImport } from './routes/_mainLayout/reset-password'
import { Route as MainLayoutRegisterRouteImport } from './routes/_mainLayout/register'
import { Route as MainLayoutOnboardingRouteImport } from './routes/_mainLayout/onboarding'
import { Route as MainLayoutNoticeRouteImport } from './routes/_mainLayout/notice'
import { Route as MainLayoutLoginRouteImport } from './routes/_mainLayout/login'
import { Route as MainLayoutUnitIndexRouteImport } from './routes/_mainLayout/unit/index'
import { Route as MainLayoutShelfIndexRouteImport } from './routes/_mainLayout/shelf/index'
import { Route as MainLayoutReviewIndexRouteImport } from './routes/_mainLayout/review/index'
import { Route as MainLayoutRealmIndexRouteImport } from './routes/_mainLayout/realm/index'
import { Route as MainLayoutFeedbackIndexRouteImport } from './routes/_mainLayout/feedback/index'
import { Route as MainLayoutBookIndexRouteImport } from './routes/_mainLayout/book/index'
import { Route as MainLayoutUserUnitIdRouteImport } from './routes/_mainLayout/user/$unitId'
import { Route as MainLayoutUnitUnitIdRouteImport } from './routes/_mainLayout/unit/$unitId'
import { Route as MainLayoutTagUnitIdRouteImport } from './routes/_mainLayout/tag/$unitId'
import { Route as MainLayoutShelfSearchRouteImport } from './routes/_mainLayout/shelf/search'
import { Route as MainLayoutShelfNewRouteImport } from './routes/_mainLayout/shelf/new'
import { Route as MainLayoutReviewSearchRouteImport } from './routes/_mainLayout/review/search'
import { Route as MainLayoutRemarkReviewIdRouteImport } from './routes/_mainLayout/remark/$reviewId'
import { Route as MainLayoutRealmSearchRouteImport } from './routes/_mainLayout/realm/search'
import { Route as MainLayoutRealmNewRouteImport } from './routes/_mainLayout/realm/new'
import { Route as MainLayoutInboxNotificationRouteImport } from './routes/_mainLayout/inbox/notification'
import { Route as MainLayoutFeedbackAdminRouteImport } from './routes/_mainLayout/feedback/admin'
import { Route as MainLayoutBookSearchRouteImport } from './routes/_mainLayout/book/search'
import { Route as MainLayoutBookNewRouteImport } from './routes/_mainLayout/book/new'
import { Route as BookBookIdEditRouteRouteImport } from './routes/book_/$bookId/edit/route'
import { Route as MainLayoutUserMeRouteRouteImport } from './routes/_mainLayout/user/me/route'
import { Route as MainLayoutBookBookIdRouteRouteImport } from './routes/_mainLayout/book/$bookId/route'
import { Route as BookBookIdEditIndexRouteImport } from './routes/book_/$bookId/edit/index'
import { Route as MainLayoutUserMeIndexRouteImport } from './routes/_mainLayout/user/me/index'
import { Route as MainLayoutShelfShelfIdIndexRouteImport } from './routes/_mainLayout/shelf/$shelfId/index'
import { Route as MainLayoutReviewReviewIdIndexRouteImport } from './routes/_mainLayout/review/$reviewId/index'
import { Route as MainLayoutRealmRealmIdIndexRouteImport } from './routes/_mainLayout/realm/$realmId/index'
import { Route as MainLayoutQuoteUnitIdIndexRouteImport } from './routes/_mainLayout/quote/$unitId/index'
import { Route as MainLayoutBookBookIdIndexRouteImport } from './routes/_mainLayout/book/$bookId/index'
import { Route as BookBookIdEditTagRouteImport } from './routes/book_/$bookId/edit/tag'
import { Route as BookBookIdEditChapterRouteImport } from './routes/book_/$bookId/edit/chapter'
import { Route as BookBookIdEditChapterIdRouteImport } from './routes/book_/$bookId/edit/$chapterId'
import { Route as MainLayoutUserMeReactionRouteImport } from './routes/_mainLayout/user/me/reaction'
import { Route as MainLayoutUserMeFollowRouteImport } from './routes/_mainLayout/user/me/follow'
import { Route as MainLayoutUserMeEditRouteImport } from './routes/_mainLayout/user/me/edit'
import { Route as MainLayoutUserMeBookmarkRouteImport } from './routes/_mainLayout/user/me/bookmark'
import { Route as MainLayoutUserUnitIdEditRouteImport } from './routes/_mainLayout/user/$unitId/edit'
import { Route as MainLayoutShelfBookBookIdRouteImport } from './routes/_mainLayout/shelf/book/$bookId'
import { Route as MainLayoutShelfShelfIdEditRouteImport } from './routes/_mainLayout/shelf/$shelfId/edit'
import { Route as MainLayoutReviewNewBookUnitIdRouteImport } from './routes/_mainLayout/review/new/$bookUnitId'
import { Route as MainLayoutReviewBookBookIdRouteImport } from './routes/_mainLayout/review/book/$bookId'
import { Route as MainLayoutReviewReviewIdEditRouteImport } from './routes/_mainLayout/review/$reviewId/edit'
import { Route as MainLayoutRemarkBookBookIdRouteImport } from './routes/_mainLayout/remark/book/$bookId'
import { Route as MainLayoutRealmRealmIdManageRouteImport } from './routes/_mainLayout/realm/$realmId/manage'
import { Route as MainLayoutQuoteBookBookIdRouteImport } from './routes/_mainLayout/quote/book/$bookId'
import { Route as MainLayoutQuoteUnitIdEditRouteImport } from './routes/_mainLayout/quote/$unitId/edit'
import { Route as MainLayoutBookBookIdReviewRouteImport } from './routes/_mainLayout/book/$bookId/review'
import { Route as MainLayoutBookBookIdInfoRouteImport } from './routes/_mainLayout/book/$bookId/info'
import { Route as MainLayoutBookBookIdDiscussionRouteImport } from './routes/_mainLayout/book/$bookId/discussion'
import { Route as MainLayoutBookBookIdContentRouteImport } from './routes/_mainLayout/book/$bookId/content'
import { Route as BookBookIdReadChapterIdRouteRouteImport } from './routes/book_/$bookId/read/$chapterId/route'
import { Route as MainLayoutTagDomainUnitIdRouteRouteImport } from './routes/_mainLayout/tag/domain/$unitId/route'
import { Route as MainLayoutTagBookBookIdRouteRouteImport } from './routes/_mainLayout/tag/book/$bookId/route'
import { Route as BookBookIdReadChapterIdIndexRouteImport } from './routes/book_/$bookId/read/$chapterId/index'
import { Route as MainLayoutTagDomainUnitIdIndexRouteImport } from './routes/_mainLayout/tag/domain/$unitId/index'
import { Route as MainLayoutTagBookBookIdIndexRouteImport } from './routes/_mainLayout/tag/book/$bookId/index'
import { Route as MainLayoutTagBookBookIdTagRouteRouteImport } from './routes/_mainLayout/tag/book/$bookId/tag/route'
import { Route as MainLayoutTagBookBookIdTagIndexRouteImport } from './routes/_mainLayout/tag/book/$bookId/tag/index'
import { Route as MainLayoutTagDomainUnitIdTitleTitleRouteImport } from './routes/_mainLayout/tag/domain/$unitId/title/$title'
import { Route as MainLayoutTagBookBookIdTagDomainIdRouteImport } from './routes/_mainLayout/tag/book/$bookId/tag/$domainId'

const MainLayoutRoute = MainLayoutRouteImport.update({
  id: '/_mainLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutIndexRoute = MainLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutVerifyEmailRoute = MainLayoutVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutThemeSwitchRoute = MainLayoutThemeSwitchRouteImport.update({
  id: '/theme-switch',
  path: '/theme-switch',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutTest03Route = MainLayoutTest03RouteImport.update({
  id: '/test03',
  path: '/test03',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutTest02Route = MainLayoutTest02RouteImport.update({
  id: '/test02',
  path: '/test02',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutTestRoute = MainLayoutTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutResetPasswordRoute = MainLayoutResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutRegisterRoute = MainLayoutRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutOnboardingRoute = MainLayoutOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutNoticeRoute = MainLayoutNoticeRouteImport.update({
  id: '/notice',
  path: '/notice',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutLoginRoute = MainLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutUnitIndexRoute = MainLayoutUnitIndexRouteImport.update({
  id: '/unit/',
  path: '/unit/',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutShelfIndexRoute = MainLayoutShelfIndexRouteImport.update({
  id: '/shelf/',
  path: '/shelf/',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutReviewIndexRoute = MainLayoutReviewIndexRouteImport.update({
  id: '/review/',
  path: '/review/',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutRealmIndexRoute = MainLayoutRealmIndexRouteImport.update({
  id: '/realm/',
  path: '/realm/',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutFeedbackIndexRoute = MainLayoutFeedbackIndexRouteImport.update({
  id: '/feedback/',
  path: '/feedback/',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutBookIndexRoute = MainLayoutBookIndexRouteImport.update({
  id: '/book/',
  path: '/book/',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutUserUnitIdRoute = MainLayoutUserUnitIdRouteImport.update({
  id: '/user/$unitId',
  path: '/user/$unitId',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutUnitUnitIdRoute = MainLayoutUnitUnitIdRouteImport.update({
  id: '/unit/$unitId',
  path: '/unit/$unitId',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutTagUnitIdRoute = MainLayoutTagUnitIdRouteImport.update({
  id: '/tag/$unitId',
  path: '/tag/$unitId',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutShelfSearchRoute = MainLayoutShelfSearchRouteImport.update({
  id: '/shelf/search',
  path: '/shelf/search',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutShelfNewRoute = MainLayoutShelfNewRouteImport.update({
  id: '/shelf/new',
  path: '/shelf/new',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutReviewSearchRoute = MainLayoutReviewSearchRouteImport.update({
  id: '/review/search',
  path: '/review/search',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutRemarkReviewIdRoute =
  MainLayoutRemarkReviewIdRouteImport.update({
    id: '/remark/$reviewId',
    path: '/remark/$reviewId',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutRealmSearchRoute = MainLayoutRealmSearchRouteImport.update({
  id: '/realm/search',
  path: '/realm/search',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutRealmNewRoute = MainLayoutRealmNewRouteImport.update({
  id: '/realm/new',
  path: '/realm/new',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutInboxNotificationRoute =
  MainLayoutInboxNotificationRouteImport.update({
    id: '/inbox/notification',
    path: '/inbox/notification',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutFeedbackAdminRoute = MainLayoutFeedbackAdminRouteImport.update({
  id: '/feedback/admin',
  path: '/feedback/admin',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutBookSearchRoute = MainLayoutBookSearchRouteImport.update({
  id: '/book/search',
  path: '/book/search',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutBookNewRoute = MainLayoutBookNewRouteImport.update({
  id: '/book/new',
  path: '/book/new',
  getParentRoute: () => MainLayoutRoute,
} as any)
const BookBookIdEditRouteRoute = BookBookIdEditRouteRouteImport.update({
  id: '/book_/$bookId/edit',
  path: '/book/$bookId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutUserMeRouteRoute = MainLayoutUserMeRouteRouteImport.update({
  id: '/user/me',
  path: '/user/me',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutBookBookIdRouteRoute =
  MainLayoutBookBookIdRouteRouteImport.update({
    id: '/book/$bookId',
    path: '/book/$bookId',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const BookBookIdEditIndexRoute = BookBookIdEditIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookBookIdEditRouteRoute,
} as any)
const MainLayoutUserMeIndexRoute = MainLayoutUserMeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainLayoutUserMeRouteRoute,
} as any)
const MainLayoutShelfShelfIdIndexRoute =
  MainLayoutShelfShelfIdIndexRouteImport.update({
    id: '/shelf/$shelfId/',
    path: '/shelf/$shelfId/',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutReviewReviewIdIndexRoute =
  MainLayoutReviewReviewIdIndexRouteImport.update({
    id: '/review/$reviewId/',
    path: '/review/$reviewId/',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutRealmRealmIdIndexRoute =
  MainLayoutRealmRealmIdIndexRouteImport.update({
    id: '/realm/$realmId/',
    path: '/realm/$realmId/',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutQuoteUnitIdIndexRoute =
  MainLayoutQuoteUnitIdIndexRouteImport.update({
    id: '/quote/$unitId/',
    path: '/quote/$unitId/',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutBookBookIdIndexRoute =
  MainLayoutBookBookIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MainLayoutBookBookIdRouteRoute,
  } as any)
const BookBookIdEditTagRoute = BookBookIdEditTagRouteImport.update({
  id: '/tag',
  path: '/tag',
  getParentRoute: () => BookBookIdEditRouteRoute,
} as any)
const BookBookIdEditChapterRoute = BookBookIdEditChapterRouteImport.update({
  id: '/chapter',
  path: '/chapter',
  getParentRoute: () => BookBookIdEditRouteRoute,
} as any)
const BookBookIdEditChapterIdRoute = BookBookIdEditChapterIdRouteImport.update({
  id: '/$chapterId',
  path: '/$chapterId',
  getParentRoute: () => BookBookIdEditRouteRoute,
} as any)
const MainLayoutUserMeReactionRoute =
  MainLayoutUserMeReactionRouteImport.update({
    id: '/reaction',
    path: '/reaction',
    getParentRoute: () => MainLayoutUserMeRouteRoute,
  } as any)
const MainLayoutUserMeFollowRoute = MainLayoutUserMeFollowRouteImport.update({
  id: '/follow',
  path: '/follow',
  getParentRoute: () => MainLayoutUserMeRouteRoute,
} as any)
const MainLayoutUserMeEditRoute = MainLayoutUserMeEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => MainLayoutUserMeRouteRoute,
} as any)
const MainLayoutUserMeBookmarkRoute =
  MainLayoutUserMeBookmarkRouteImport.update({
    id: '/bookmark',
    path: '/bookmark',
    getParentRoute: () => MainLayoutUserMeRouteRoute,
  } as any)
const MainLayoutUserUnitIdEditRoute =
  MainLayoutUserUnitIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => MainLayoutUserUnitIdRoute,
  } as any)
const MainLayoutShelfBookBookIdRoute =
  MainLayoutShelfBookBookIdRouteImport.update({
    id: '/shelf/book/$bookId',
    path: '/shelf/book/$bookId',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutShelfShelfIdEditRoute =
  MainLayoutShelfShelfIdEditRouteImport.update({
    id: '/shelf/$shelfId/edit',
    path: '/shelf/$shelfId/edit',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutReviewNewBookUnitIdRoute =
  MainLayoutReviewNewBookUnitIdRouteImport.update({
    id: '/review/new/$bookUnitId',
    path: '/review/new/$bookUnitId',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutReviewBookBookIdRoute =
  MainLayoutReviewBookBookIdRouteImport.update({
    id: '/review/book/$bookId',
    path: '/review/book/$bookId',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutReviewReviewIdEditRoute =
  MainLayoutReviewReviewIdEditRouteImport.update({
    id: '/review/$reviewId/edit',
    path: '/review/$reviewId/edit',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutRemarkBookBookIdRoute =
  MainLayoutRemarkBookBookIdRouteImport.update({
    id: '/remark/book/$bookId',
    path: '/remark/book/$bookId',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutRealmRealmIdManageRoute =
  MainLayoutRealmRealmIdManageRouteImport.update({
    id: '/realm/$realmId/manage',
    path: '/realm/$realmId/manage',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutQuoteBookBookIdRoute =
  MainLayoutQuoteBookBookIdRouteImport.update({
    id: '/quote/book/$bookId',
    path: '/quote/book/$bookId',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutQuoteUnitIdEditRoute =
  MainLayoutQuoteUnitIdEditRouteImport.update({
    id: '/quote/$unitId/edit',
    path: '/quote/$unitId/edit',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutBookBookIdReviewRoute =
  MainLayoutBookBookIdReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => MainLayoutBookBookIdRouteRoute,
  } as any)
const MainLayoutBookBookIdInfoRoute =
  MainLayoutBookBookIdInfoRouteImport.update({
    id: '/info',
    path: '/info',
    getParentRoute: () => MainLayoutBookBookIdRouteRoute,
  } as any)
const MainLayoutBookBookIdDiscussionRoute =
  MainLayoutBookBookIdDiscussionRouteImport.update({
    id: '/discussion',
    path: '/discussion',
    getParentRoute: () => MainLayoutBookBookIdRouteRoute,
  } as any)
const MainLayoutBookBookIdContentRoute =
  MainLayoutBookBookIdContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => MainLayoutBookBookIdRouteRoute,
  } as any)
const BookBookIdReadChapterIdRouteRoute =
  BookBookIdReadChapterIdRouteRouteImport.update({
    id: '/book_/$bookId/read/$chapterId',
    path: '/book/$bookId/read/$chapterId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MainLayoutTagDomainUnitIdRouteRoute =
  MainLayoutTagDomainUnitIdRouteRouteImport.update({
    id: '/tag/domain/$unitId',
    path: '/tag/domain/$unitId',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutTagBookBookIdRouteRoute =
  MainLayoutTagBookBookIdRouteRouteImport.update({
    id: '/tag/book/$bookId',
    path: '/tag/book/$bookId',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const BookBookIdReadChapterIdIndexRoute =
  BookBookIdReadChapterIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BookBookIdReadChapterIdRouteRoute,
  } as any)
const MainLayoutTagDomainUnitIdIndexRoute =
  MainLayoutTagDomainUnitIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MainLayoutTagDomainUnitIdRouteRoute,
  } as any)
const MainLayoutTagBookBookIdIndexRoute =
  MainLayoutTagBookBookIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MainLayoutTagBookBookIdRouteRoute,
  } as any)
const MainLayoutTagBookBookIdTagRouteRoute =
  MainLayoutTagBookBookIdTagRouteRouteImport.update({
    id: '/tag',
    path: '/tag',
    getParentRoute: () => MainLayoutTagBookBookIdRouteRoute,
  } as any)
const MainLayoutTagBookBookIdTagIndexRoute =
  MainLayoutTagBookBookIdTagIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MainLayoutTagBookBookIdTagRouteRoute,
  } as any)
const MainLayoutTagDomainUnitIdTitleTitleRoute =
  MainLayoutTagDomainUnitIdTitleTitleRouteImport.update({
    id: '/title/$title',
    path: '/title/$title',
    getParentRoute: () => MainLayoutTagDomainUnitIdRouteRoute,
  } as any)
const MainLayoutTagBookBookIdTagDomainIdRoute =
  MainLayoutTagBookBookIdTagDomainIdRouteImport.update({
    id: '/$domainId',
    path: '/$domainId',
    getParentRoute: () => MainLayoutTagBookBookIdTagRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainLayoutIndexRoute
  '/login': typeof MainLayoutLoginRoute
  '/notice': typeof MainLayoutNoticeRoute
  '/onboarding': typeof MainLayoutOnboardingRoute
  '/register': typeof MainLayoutRegisterRoute
  '/reset-password': typeof MainLayoutResetPasswordRoute
  '/test': typeof MainLayoutTestRoute
  '/test02': typeof MainLayoutTest02Route
  '/test03': typeof MainLayoutTest03Route
  '/theme-switch': typeof MainLayoutThemeSwitchRoute
  '/verify-email': typeof MainLayoutVerifyEmailRoute
  '/book/$bookId': typeof MainLayoutBookBookIdRouteRouteWithChildren
  '/user/me': typeof MainLayoutUserMeRouteRouteWithChildren
  '/book/$bookId/edit': typeof BookBookIdEditRouteRouteWithChildren
  '/book/new': typeof MainLayoutBookNewRoute
  '/book/search': typeof MainLayoutBookSearchRoute
  '/feedback/admin': typeof MainLayoutFeedbackAdminRoute
  '/inbox/notification': typeof MainLayoutInboxNotificationRoute
  '/realm/new': typeof MainLayoutRealmNewRoute
  '/realm/search': typeof MainLayoutRealmSearchRoute
  '/remark/$reviewId': typeof MainLayoutRemarkReviewIdRoute
  '/review/search': typeof MainLayoutReviewSearchRoute
  '/shelf/new': typeof MainLayoutShelfNewRoute
  '/shelf/search': typeof MainLayoutShelfSearchRoute
  '/tag/$unitId': typeof MainLayoutTagUnitIdRoute
  '/unit/$unitId': typeof MainLayoutUnitUnitIdRoute
  '/user/$unitId': typeof MainLayoutUserUnitIdRouteWithChildren
  '/book/': typeof MainLayoutBookIndexRoute
  '/feedback/': typeof MainLayoutFeedbackIndexRoute
  '/realm/': typeof MainLayoutRealmIndexRoute
  '/review/': typeof MainLayoutReviewIndexRoute
  '/shelf/': typeof MainLayoutShelfIndexRoute
  '/unit/': typeof MainLayoutUnitIndexRoute
  '/tag/book/$bookId': typeof MainLayoutTagBookBookIdRouteRouteWithChildren
  '/tag/domain/$unitId': typeof MainLayoutTagDomainUnitIdRouteRouteWithChildren
  '/book/$bookId/read/$chapterId': typeof BookBookIdReadChapterIdRouteRouteWithChildren
  '/book/$bookId/content': typeof MainLayoutBookBookIdContentRoute
  '/book/$bookId/discussion': typeof MainLayoutBookBookIdDiscussionRoute
  '/book/$bookId/info': typeof MainLayoutBookBookIdInfoRoute
  '/book/$bookId/review': typeof MainLayoutBookBookIdReviewRoute
  '/quote/$unitId/edit': typeof MainLayoutQuoteUnitIdEditRoute
  '/quote/book/$bookId': typeof MainLayoutQuoteBookBookIdRoute
  '/realm/$realmId/manage': typeof MainLayoutRealmRealmIdManageRoute
  '/remark/book/$bookId': typeof MainLayoutRemarkBookBookIdRoute
  '/review/$reviewId/edit': typeof MainLayoutReviewReviewIdEditRoute
  '/review/book/$bookId': typeof MainLayoutReviewBookBookIdRoute
  '/review/new/$bookUnitId': typeof MainLayoutReviewNewBookUnitIdRoute
  '/shelf/$shelfId/edit': typeof MainLayoutShelfShelfIdEditRoute
  '/shelf/book/$bookId': typeof MainLayoutShelfBookBookIdRoute
  '/user/$unitId/edit': typeof MainLayoutUserUnitIdEditRoute
  '/user/me/bookmark': typeof MainLayoutUserMeBookmarkRoute
  '/user/me/edit': typeof MainLayoutUserMeEditRoute
  '/user/me/follow': typeof MainLayoutUserMeFollowRoute
  '/user/me/reaction': typeof MainLayoutUserMeReactionRoute
  '/book/$bookId/edit/$chapterId': typeof BookBookIdEditChapterIdRoute
  '/book/$bookId/edit/chapter': typeof BookBookIdEditChapterRoute
  '/book/$bookId/edit/tag': typeof BookBookIdEditTagRoute
  '/book/$bookId/': typeof MainLayoutBookBookIdIndexRoute
  '/quote/$unitId/': typeof MainLayoutQuoteUnitIdIndexRoute
  '/realm/$realmId/': typeof MainLayoutRealmRealmIdIndexRoute
  '/review/$reviewId/': typeof MainLayoutReviewReviewIdIndexRoute
  '/shelf/$shelfId/': typeof MainLayoutShelfShelfIdIndexRoute
  '/user/me/': typeof MainLayoutUserMeIndexRoute
  '/book/$bookId/edit/': typeof BookBookIdEditIndexRoute
  '/tag/book/$bookId/tag': typeof MainLayoutTagBookBookIdTagRouteRouteWithChildren
  '/tag/book/$bookId/': typeof MainLayoutTagBookBookIdIndexRoute
  '/tag/domain/$unitId/': typeof MainLayoutTagDomainUnitIdIndexRoute
  '/book/$bookId/read/$chapterId/': typeof BookBookIdReadChapterIdIndexRoute
  '/tag/book/$bookId/tag/$domainId': typeof MainLayoutTagBookBookIdTagDomainIdRoute
  '/tag/domain/$unitId/title/$title': typeof MainLayoutTagDomainUnitIdTitleTitleRoute
  '/tag/book/$bookId/tag/': typeof MainLayoutTagBookBookIdTagIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof MainLayoutLoginRoute
  '/notice': typeof MainLayoutNoticeRoute
  '/onboarding': typeof MainLayoutOnboardingRoute
  '/register': typeof MainLayoutRegisterRoute
  '/reset-password': typeof MainLayoutResetPasswordRoute
  '/test': typeof MainLayoutTestRoute
  '/test02': typeof MainLayoutTest02Route
  '/test03': typeof MainLayoutTest03Route
  '/theme-switch': typeof MainLayoutThemeSwitchRoute
  '/verify-email': typeof MainLayoutVerifyEmailRoute
  '/': typeof MainLayoutIndexRoute
  '/book/new': typeof MainLayoutBookNewRoute
  '/book/search': typeof MainLayoutBookSearchRoute
  '/feedback/admin': typeof MainLayoutFeedbackAdminRoute
  '/inbox/notification': typeof MainLayoutInboxNotificationRoute
  '/realm/new': typeof MainLayoutRealmNewRoute
  '/realm/search': typeof MainLayoutRealmSearchRoute
  '/remark/$reviewId': typeof MainLayoutRemarkReviewIdRoute
  '/review/search': typeof MainLayoutReviewSearchRoute
  '/shelf/new': typeof MainLayoutShelfNewRoute
  '/shelf/search': typeof MainLayoutShelfSearchRoute
  '/tag/$unitId': typeof MainLayoutTagUnitIdRoute
  '/unit/$unitId': typeof MainLayoutUnitUnitIdRoute
  '/user/$unitId': typeof MainLayoutUserUnitIdRouteWithChildren
  '/book': typeof MainLayoutBookIndexRoute
  '/feedback': typeof MainLayoutFeedbackIndexRoute
  '/realm': typeof MainLayoutRealmIndexRoute
  '/review': typeof MainLayoutReviewIndexRoute
  '/shelf': typeof MainLayoutShelfIndexRoute
  '/unit': typeof MainLayoutUnitIndexRoute
  '/book/$bookId/content': typeof MainLayoutBookBookIdContentRoute
  '/book/$bookId/discussion': typeof MainLayoutBookBookIdDiscussionRoute
  '/book/$bookId/info': typeof MainLayoutBookBookIdInfoRoute
  '/book/$bookId/review': typeof MainLayoutBookBookIdReviewRoute
  '/quote/$unitId/edit': typeof MainLayoutQuoteUnitIdEditRoute
  '/quote/book/$bookId': typeof MainLayoutQuoteBookBookIdRoute
  '/realm/$realmId/manage': typeof MainLayoutRealmRealmIdManageRoute
  '/remark/book/$bookId': typeof MainLayoutRemarkBookBookIdRoute
  '/review/$reviewId/edit': typeof MainLayoutReviewReviewIdEditRoute
  '/review/book/$bookId': typeof MainLayoutReviewBookBookIdRoute
  '/review/new/$bookUnitId': typeof MainLayoutReviewNewBookUnitIdRoute
  '/shelf/$shelfId/edit': typeof MainLayoutShelfShelfIdEditRoute
  '/shelf/book/$bookId': typeof MainLayoutShelfBookBookIdRoute
  '/user/$unitId/edit': typeof MainLayoutUserUnitIdEditRoute
  '/user/me/bookmark': typeof MainLayoutUserMeBookmarkRoute
  '/user/me/edit': typeof MainLayoutUserMeEditRoute
  '/user/me/follow': typeof MainLayoutUserMeFollowRoute
  '/user/me/reaction': typeof MainLayoutUserMeReactionRoute
  '/book/$bookId/edit/$chapterId': typeof BookBookIdEditChapterIdRoute
  '/book/$bookId/edit/chapter': typeof BookBookIdEditChapterRoute
  '/book/$bookId/edit/tag': typeof BookBookIdEditTagRoute
  '/book/$bookId': typeof MainLayoutBookBookIdIndexRoute
  '/quote/$unitId': typeof MainLayoutQuoteUnitIdIndexRoute
  '/realm/$realmId': typeof MainLayoutRealmRealmIdIndexRoute
  '/review/$reviewId': typeof MainLayoutReviewReviewIdIndexRoute
  '/shelf/$shelfId': typeof MainLayoutShelfShelfIdIndexRoute
  '/user/me': typeof MainLayoutUserMeIndexRoute
  '/book/$bookId/edit': typeof BookBookIdEditIndexRoute
  '/tag/book/$bookId': typeof MainLayoutTagBookBookIdIndexRoute
  '/tag/domain/$unitId': typeof MainLayoutTagDomainUnitIdIndexRoute
  '/book/$bookId/read/$chapterId': typeof BookBookIdReadChapterIdIndexRoute
  '/tag/book/$bookId/tag/$domainId': typeof MainLayoutTagBookBookIdTagDomainIdRoute
  '/tag/domain/$unitId/title/$title': typeof MainLayoutTagDomainUnitIdTitleTitleRoute
  '/tag/book/$bookId/tag': typeof MainLayoutTagBookBookIdTagIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_mainLayout': typeof MainLayoutRouteWithChildren
  '/_mainLayout/login': typeof MainLayoutLoginRoute
  '/_mainLayout/notice': typeof MainLayoutNoticeRoute
  '/_mainLayout/onboarding': typeof MainLayoutOnboardingRoute
  '/_mainLayout/register': typeof MainLayoutRegisterRoute
  '/_mainLayout/reset-password': typeof MainLayoutResetPasswordRoute
  '/_mainLayout/test': typeof MainLayoutTestRoute
  '/_mainLayout/test02': typeof MainLayoutTest02Route
  '/_mainLayout/test03': typeof MainLayoutTest03Route
  '/_mainLayout/theme-switch': typeof MainLayoutThemeSwitchRoute
  '/_mainLayout/verify-email': typeof MainLayoutVerifyEmailRoute
  '/_mainLayout/': typeof MainLayoutIndexRoute
  '/_mainLayout/book/$bookId': typeof MainLayoutBookBookIdRouteRouteWithChildren
  '/_mainLayout/user/me': typeof MainLayoutUserMeRouteRouteWithChildren
  '/book_/$bookId/edit': typeof BookBookIdEditRouteRouteWithChildren
  '/_mainLayout/book/new': typeof MainLayoutBookNewRoute
  '/_mainLayout/book/search': typeof MainLayoutBookSearchRoute
  '/_mainLayout/feedback/admin': typeof MainLayoutFeedbackAdminRoute
  '/_mainLayout/inbox/notification': typeof MainLayoutInboxNotificationRoute
  '/_mainLayout/realm/new': typeof MainLayoutRealmNewRoute
  '/_mainLayout/realm/search': typeof MainLayoutRealmSearchRoute
  '/_mainLayout/remark/$reviewId': typeof MainLayoutRemarkReviewIdRoute
  '/_mainLayout/review/search': typeof MainLayoutReviewSearchRoute
  '/_mainLayout/shelf/new': typeof MainLayoutShelfNewRoute
  '/_mainLayout/shelf/search': typeof MainLayoutShelfSearchRoute
  '/_mainLayout/tag/$unitId': typeof MainLayoutTagUnitIdRoute
  '/_mainLayout/unit/$unitId': typeof MainLayoutUnitUnitIdRoute
  '/_mainLayout/user/$unitId': typeof MainLayoutUserUnitIdRouteWithChildren
  '/_mainLayout/book/': typeof MainLayoutBookIndexRoute
  '/_mainLayout/feedback/': typeof MainLayoutFeedbackIndexRoute
  '/_mainLayout/realm/': typeof MainLayoutRealmIndexRoute
  '/_mainLayout/review/': typeof MainLayoutReviewIndexRoute
  '/_mainLayout/shelf/': typeof MainLayoutShelfIndexRoute
  '/_mainLayout/unit/': typeof MainLayoutUnitIndexRoute
  '/_mainLayout/tag/book/$bookId': typeof MainLayoutTagBookBookIdRouteRouteWithChildren
  '/_mainLayout/tag/domain/$unitId': typeof MainLayoutTagDomainUnitIdRouteRouteWithChildren
  '/book_/$bookId/read/$chapterId': typeof BookBookIdReadChapterIdRouteRouteWithChildren
  '/_mainLayout/book/$bookId/content': typeof MainLayoutBookBookIdContentRoute
  '/_mainLayout/book/$bookId/discussion': typeof MainLayoutBookBookIdDiscussionRoute
  '/_mainLayout/book/$bookId/info': typeof MainLayoutBookBookIdInfoRoute
  '/_mainLayout/book/$bookId/review': typeof MainLayoutBookBookIdReviewRoute
  '/_mainLayout/quote/$unitId/edit': typeof MainLayoutQuoteUnitIdEditRoute
  '/_mainLayout/quote/book/$bookId': typeof MainLayoutQuoteBookBookIdRoute
  '/_mainLayout/realm/$realmId/manage': typeof MainLayoutRealmRealmIdManageRoute
  '/_mainLayout/remark/book/$bookId': typeof MainLayoutRemarkBookBookIdRoute
  '/_mainLayout/review/$reviewId/edit': typeof MainLayoutReviewReviewIdEditRoute
  '/_mainLayout/review/book/$bookId': typeof MainLayoutReviewBookBookIdRoute
  '/_mainLayout/review/new/$bookUnitId': typeof MainLayoutReviewNewBookUnitIdRoute
  '/_mainLayout/shelf/$shelfId/edit': typeof MainLayoutShelfShelfIdEditRoute
  '/_mainLayout/shelf/book/$bookId': typeof MainLayoutShelfBookBookIdRoute
  '/_mainLayout/user/$unitId/edit': typeof MainLayoutUserUnitIdEditRoute
  '/_mainLayout/user/me/bookmark': typeof MainLayoutUserMeBookmarkRoute
  '/_mainLayout/user/me/edit': typeof MainLayoutUserMeEditRoute
  '/_mainLayout/user/me/follow': typeof MainLayoutUserMeFollowRoute
  '/_mainLayout/user/me/reaction': typeof MainLayoutUserMeReactionRoute
  '/book_/$bookId/edit/$chapterId': typeof BookBookIdEditChapterIdRoute
  '/book_/$bookId/edit/chapter': typeof BookBookIdEditChapterRoute
  '/book_/$bookId/edit/tag': typeof BookBookIdEditTagRoute
  '/_mainLayout/book/$bookId/': typeof MainLayoutBookBookIdIndexRoute
  '/_mainLayout/quote/$unitId/': typeof MainLayoutQuoteUnitIdIndexRoute
  '/_mainLayout/realm/$realmId/': typeof MainLayoutRealmRealmIdIndexRoute
  '/_mainLayout/review/$reviewId/': typeof MainLayoutReviewReviewIdIndexRoute
  '/_mainLayout/shelf/$shelfId/': typeof MainLayoutShelfShelfIdIndexRoute
  '/_mainLayout/user/me/': typeof MainLayoutUserMeIndexRoute
  '/book_/$bookId/edit/': typeof BookBookIdEditIndexRoute
  '/_mainLayout/tag/book/$bookId/tag': typeof MainLayoutTagBookBookIdTagRouteRouteWithChildren
  '/_mainLayout/tag/book/$bookId/': typeof MainLayoutTagBookBookIdIndexRoute
  '/_mainLayout/tag/domain/$unitId/': typeof MainLayoutTagDomainUnitIdIndexRoute
  '/book_/$bookId/read/$chapterId/': typeof BookBookIdReadChapterIdIndexRoute
  '/_mainLayout/tag/book/$bookId/tag/$domainId': typeof MainLayoutTagBookBookIdTagDomainIdRoute
  '/_mainLayout/tag/domain/$unitId/title/$title': typeof MainLayoutTagDomainUnitIdTitleTitleRoute
  '/_mainLayout/tag/book/$bookId/tag/': typeof MainLayoutTagBookBookIdTagIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/notice'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/test'
    | '/test02'
    | '/test03'
    | '/theme-switch'
    | '/verify-email'
    | '/book/$bookId'
    | '/user/me'
    | '/book/$bookId/edit'
    | '/book/new'
    | '/book/search'
    | '/feedback/admin'
    | '/inbox/notification'
    | '/realm/new'
    | '/realm/search'
    | '/remark/$reviewId'
    | '/review/search'
    | '/shelf/new'
    | '/shelf/search'
    | '/tag/$unitId'
    | '/unit/$unitId'
    | '/user/$unitId'
    | '/book/'
    | '/feedback/'
    | '/realm/'
    | '/review/'
    | '/shelf/'
    | '/unit/'
    | '/tag/book/$bookId'
    | '/tag/domain/$unitId'
    | '/book/$bookId/read/$chapterId'
    | '/book/$bookId/content'
    | '/book/$bookId/discussion'
    | '/book/$bookId/info'
    | '/book/$bookId/review'
    | '/quote/$unitId/edit'
    | '/quote/book/$bookId'
    | '/realm/$realmId/manage'
    | '/remark/book/$bookId'
    | '/review/$reviewId/edit'
    | '/review/book/$bookId'
    | '/review/new/$bookUnitId'
    | '/shelf/$shelfId/edit'
    | '/shelf/book/$bookId'
    | '/user/$unitId/edit'
    | '/user/me/bookmark'
    | '/user/me/edit'
    | '/user/me/follow'
    | '/user/me/reaction'
    | '/book/$bookId/edit/$chapterId'
    | '/book/$bookId/edit/chapter'
    | '/book/$bookId/edit/tag'
    | '/book/$bookId/'
    | '/quote/$unitId/'
    | '/realm/$realmId/'
    | '/review/$reviewId/'
    | '/shelf/$shelfId/'
    | '/user/me/'
    | '/book/$bookId/edit/'
    | '/tag/book/$bookId/tag'
    | '/tag/book/$bookId/'
    | '/tag/domain/$unitId/'
    | '/book/$bookId/read/$chapterId/'
    | '/tag/book/$bookId/tag/$domainId'
    | '/tag/domain/$unitId/title/$title'
    | '/tag/book/$bookId/tag/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/notice'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/test'
    | '/test02'
    | '/test03'
    | '/theme-switch'
    | '/verify-email'
    | '/'
    | '/book/new'
    | '/book/search'
    | '/feedback/admin'
    | '/inbox/notification'
    | '/realm/new'
    | '/realm/search'
    | '/remark/$reviewId'
    | '/review/search'
    | '/shelf/new'
    | '/shelf/search'
    | '/tag/$unitId'
    | '/unit/$unitId'
    | '/user/$unitId'
    | '/book'
    | '/feedback'
    | '/realm'
    | '/review'
    | '/shelf'
    | '/unit'
    | '/book/$bookId/content'
    | '/book/$bookId/discussion'
    | '/book/$bookId/info'
    | '/book/$bookId/review'
    | '/quote/$unitId/edit'
    | '/quote/book/$bookId'
    | '/realm/$realmId/manage'
    | '/remark/book/$bookId'
    | '/review/$reviewId/edit'
    | '/review/book/$bookId'
    | '/review/new/$bookUnitId'
    | '/shelf/$shelfId/edit'
    | '/shelf/book/$bookId'
    | '/user/$unitId/edit'
    | '/user/me/bookmark'
    | '/user/me/edit'
    | '/user/me/follow'
    | '/user/me/reaction'
    | '/book/$bookId/edit/$chapterId'
    | '/book/$bookId/edit/chapter'
    | '/book/$bookId/edit/tag'
    | '/book/$bookId'
    | '/quote/$unitId'
    | '/realm/$realmId'
    | '/review/$reviewId'
    | '/shelf/$shelfId'
    | '/user/me'
    | '/book/$bookId/edit'
    | '/tag/book/$bookId'
    | '/tag/domain/$unitId'
    | '/book/$bookId/read/$chapterId'
    | '/tag/book/$bookId/tag/$domainId'
    | '/tag/domain/$unitId/title/$title'
    | '/tag/book/$bookId/tag'
  id:
    | '__root__'
    | '/_mainLayout'
    | '/_mainLayout/login'
    | '/_mainLayout/notice'
    | '/_mainLayout/onboarding'
    | '/_mainLayout/register'
    | '/_mainLayout/reset-password'
    | '/_mainLayout/test'
    | '/_mainLayout/test02'
    | '/_mainLayout/test03'
    | '/_mainLayout/theme-switch'
    | '/_mainLayout/verify-email'
    | '/_mainLayout/'
    | '/_mainLayout/book/$bookId'
    | '/_mainLayout/user/me'
    | '/book_/$bookId/edit'
    | '/_mainLayout/book/new'
    | '/_mainLayout/book/search'
    | '/_mainLayout/feedback/admin'
    | '/_mainLayout/inbox/notification'
    | '/_mainLayout/realm/new'
    | '/_mainLayout/realm/search'
    | '/_mainLayout/remark/$reviewId'
    | '/_mainLayout/review/search'
    | '/_mainLayout/shelf/new'
    | '/_mainLayout/shelf/search'
    | '/_mainLayout/tag/$unitId'
    | '/_mainLayout/unit/$unitId'
    | '/_mainLayout/user/$unitId'
    | '/_mainLayout/book/'
    | '/_mainLayout/feedback/'
    | '/_mainLayout/realm/'
    | '/_mainLayout/review/'
    | '/_mainLayout/shelf/'
    | '/_mainLayout/unit/'
    | '/_mainLayout/tag/book/$bookId'
    | '/_mainLayout/tag/domain/$unitId'
    | '/book_/$bookId/read/$chapterId'
    | '/_mainLayout/book/$bookId/content'
    | '/_mainLayout/book/$bookId/discussion'
    | '/_mainLayout/book/$bookId/info'
    | '/_mainLayout/book/$bookId/review'
    | '/_mainLayout/quote/$unitId/edit'
    | '/_mainLayout/quote/book/$bookId'
    | '/_mainLayout/realm/$realmId/manage'
    | '/_mainLayout/remark/book/$bookId'
    | '/_mainLayout/review/$reviewId/edit'
    | '/_mainLayout/review/book/$bookId'
    | '/_mainLayout/review/new/$bookUnitId'
    | '/_mainLayout/shelf/$shelfId/edit'
    | '/_mainLayout/shelf/book/$bookId'
    | '/_mainLayout/user/$unitId/edit'
    | '/_mainLayout/user/me/bookmark'
    | '/_mainLayout/user/me/edit'
    | '/_mainLayout/user/me/follow'
    | '/_mainLayout/user/me/reaction'
    | '/book_/$bookId/edit/$chapterId'
    | '/book_/$bookId/edit/chapter'
    | '/book_/$bookId/edit/tag'
    | '/_mainLayout/book/$bookId/'
    | '/_mainLayout/quote/$unitId/'
    | '/_mainLayout/realm/$realmId/'
    | '/_mainLayout/review/$reviewId/'
    | '/_mainLayout/shelf/$shelfId/'
    | '/_mainLayout/user/me/'
    | '/book_/$bookId/edit/'
    | '/_mainLayout/tag/book/$bookId/tag'
    | '/_mainLayout/tag/book/$bookId/'
    | '/_mainLayout/tag/domain/$unitId/'
    | '/book_/$bookId/read/$chapterId/'
    | '/_mainLayout/tag/book/$bookId/tag/$domainId'
    | '/_mainLayout/tag/domain/$unitId/title/$title'
    | '/_mainLayout/tag/book/$bookId/tag/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainLayoutRoute: typeof MainLayoutRouteWithChildren
  BookBookIdEditRouteRoute: typeof BookBookIdEditRouteRouteWithChildren
  BookBookIdReadChapterIdRouteRoute: typeof BookBookIdReadChapterIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_mainLayout': {
      id: '/_mainLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mainLayout/': {
      id: '/_mainLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/verify-email': {
      id: '/_mainLayout/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof MainLayoutVerifyEmailRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/theme-switch': {
      id: '/_mainLayout/theme-switch'
      path: '/theme-switch'
      fullPath: '/theme-switch'
      preLoaderRoute: typeof MainLayoutThemeSwitchRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/test03': {
      id: '/_mainLayout/test03'
      path: '/test03'
      fullPath: '/test03'
      preLoaderRoute: typeof MainLayoutTest03RouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/test02': {
      id: '/_mainLayout/test02'
      path: '/test02'
      fullPath: '/test02'
      preLoaderRoute: typeof MainLayoutTest02RouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/test': {
      id: '/_mainLayout/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof MainLayoutTestRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/reset-password': {
      id: '/_mainLayout/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof MainLayoutResetPasswordRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/register': {
      id: '/_mainLayout/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof MainLayoutRegisterRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/onboarding': {
      id: '/_mainLayout/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof MainLayoutOnboardingRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/notice': {
      id: '/_mainLayout/notice'
      path: '/notice'
      fullPath: '/notice'
      preLoaderRoute: typeof MainLayoutNoticeRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/login': {
      id: '/_mainLayout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof MainLayoutLoginRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/unit/': {
      id: '/_mainLayout/unit/'
      path: '/unit'
      fullPath: '/unit/'
      preLoaderRoute: typeof MainLayoutUnitIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/shelf/': {
      id: '/_mainLayout/shelf/'
      path: '/shelf'
      fullPath: '/shelf/'
      preLoaderRoute: typeof MainLayoutShelfIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/review/': {
      id: '/_mainLayout/review/'
      path: '/review'
      fullPath: '/review/'
      preLoaderRoute: typeof MainLayoutReviewIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/realm/': {
      id: '/_mainLayout/realm/'
      path: '/realm'
      fullPath: '/realm/'
      preLoaderRoute: typeof MainLayoutRealmIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/feedback/': {
      id: '/_mainLayout/feedback/'
      path: '/feedback'
      fullPath: '/feedback/'
      preLoaderRoute: typeof MainLayoutFeedbackIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/book/': {
      id: '/_mainLayout/book/'
      path: '/book'
      fullPath: '/book/'
      preLoaderRoute: typeof MainLayoutBookIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/user/$unitId': {
      id: '/_mainLayout/user/$unitId'
      path: '/user/$unitId'
      fullPath: '/user/$unitId'
      preLoaderRoute: typeof MainLayoutUserUnitIdRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/unit/$unitId': {
      id: '/_mainLayout/unit/$unitId'
      path: '/unit/$unitId'
      fullPath: '/unit/$unitId'
      preLoaderRoute: typeof MainLayoutUnitUnitIdRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/tag/$unitId': {
      id: '/_mainLayout/tag/$unitId'
      path: '/tag/$unitId'
      fullPath: '/tag/$unitId'
      preLoaderRoute: typeof MainLayoutTagUnitIdRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/shelf/search': {
      id: '/_mainLayout/shelf/search'
      path: '/shelf/search'
      fullPath: '/shelf/search'
      preLoaderRoute: typeof MainLayoutShelfSearchRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/shelf/new': {
      id: '/_mainLayout/shelf/new'
      path: '/shelf/new'
      fullPath: '/shelf/new'
      preLoaderRoute: typeof MainLayoutShelfNewRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/review/search': {
      id: '/_mainLayout/review/search'
      path: '/review/search'
      fullPath: '/review/search'
      preLoaderRoute: typeof MainLayoutReviewSearchRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/remark/$reviewId': {
      id: '/_mainLayout/remark/$reviewId'
      path: '/remark/$reviewId'
      fullPath: '/remark/$reviewId'
      preLoaderRoute: typeof MainLayoutRemarkReviewIdRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/realm/search': {
      id: '/_mainLayout/realm/search'
      path: '/realm/search'
      fullPath: '/realm/search'
      preLoaderRoute: typeof MainLayoutRealmSearchRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/realm/new': {
      id: '/_mainLayout/realm/new'
      path: '/realm/new'
      fullPath: '/realm/new'
      preLoaderRoute: typeof MainLayoutRealmNewRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/inbox/notification': {
      id: '/_mainLayout/inbox/notification'
      path: '/inbox/notification'
      fullPath: '/inbox/notification'
      preLoaderRoute: typeof MainLayoutInboxNotificationRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/feedback/admin': {
      id: '/_mainLayout/feedback/admin'
      path: '/feedback/admin'
      fullPath: '/feedback/admin'
      preLoaderRoute: typeof MainLayoutFeedbackAdminRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/book/search': {
      id: '/_mainLayout/book/search'
      path: '/book/search'
      fullPath: '/book/search'
      preLoaderRoute: typeof MainLayoutBookSearchRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/book/new': {
      id: '/_mainLayout/book/new'
      path: '/book/new'
      fullPath: '/book/new'
      preLoaderRoute: typeof MainLayoutBookNewRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/book_/$bookId/edit': {
      id: '/book_/$bookId/edit'
      path: '/book/$bookId/edit'
      fullPath: '/book/$bookId/edit'
      preLoaderRoute: typeof BookBookIdEditRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mainLayout/user/me': {
      id: '/_mainLayout/user/me'
      path: '/user/me'
      fullPath: '/user/me'
      preLoaderRoute: typeof MainLayoutUserMeRouteRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/book/$bookId': {
      id: '/_mainLayout/book/$bookId'
      path: '/book/$bookId'
      fullPath: '/book/$bookId'
      preLoaderRoute: typeof MainLayoutBookBookIdRouteRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/book_/$bookId/edit/': {
      id: '/book_/$bookId/edit/'
      path: '/'
      fullPath: '/book/$bookId/edit/'
      preLoaderRoute: typeof BookBookIdEditIndexRouteImport
      parentRoute: typeof BookBookIdEditRouteRoute
    }
    '/_mainLayout/user/me/': {
      id: '/_mainLayout/user/me/'
      path: '/'
      fullPath: '/user/me/'
      preLoaderRoute: typeof MainLayoutUserMeIndexRouteImport
      parentRoute: typeof MainLayoutUserMeRouteRoute
    }
    '/_mainLayout/shelf/$shelfId/': {
      id: '/_mainLayout/shelf/$shelfId/'
      path: '/shelf/$shelfId'
      fullPath: '/shelf/$shelfId/'
      preLoaderRoute: typeof MainLayoutShelfShelfIdIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/review/$reviewId/': {
      id: '/_mainLayout/review/$reviewId/'
      path: '/review/$reviewId'
      fullPath: '/review/$reviewId/'
      preLoaderRoute: typeof MainLayoutReviewReviewIdIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/realm/$realmId/': {
      id: '/_mainLayout/realm/$realmId/'
      path: '/realm/$realmId'
      fullPath: '/realm/$realmId/'
      preLoaderRoute: typeof MainLayoutRealmRealmIdIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/quote/$unitId/': {
      id: '/_mainLayout/quote/$unitId/'
      path: '/quote/$unitId'
      fullPath: '/quote/$unitId/'
      preLoaderRoute: typeof MainLayoutQuoteUnitIdIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/book/$bookId/': {
      id: '/_mainLayout/book/$bookId/'
      path: '/'
      fullPath: '/book/$bookId/'
      preLoaderRoute: typeof MainLayoutBookBookIdIndexRouteImport
      parentRoute: typeof MainLayoutBookBookIdRouteRoute
    }
    '/book_/$bookId/edit/tag': {
      id: '/book_/$bookId/edit/tag'
      path: '/tag'
      fullPath: '/book/$bookId/edit/tag'
      preLoaderRoute: typeof BookBookIdEditTagRouteImport
      parentRoute: typeof BookBookIdEditRouteRoute
    }
    '/book_/$bookId/edit/chapter': {
      id: '/book_/$bookId/edit/chapter'
      path: '/chapter'
      fullPath: '/book/$bookId/edit/chapter'
      preLoaderRoute: typeof BookBookIdEditChapterRouteImport
      parentRoute: typeof BookBookIdEditRouteRoute
    }
    '/book_/$bookId/edit/$chapterId': {
      id: '/book_/$bookId/edit/$chapterId'
      path: '/$chapterId'
      fullPath: '/book/$bookId/edit/$chapterId'
      preLoaderRoute: typeof BookBookIdEditChapterIdRouteImport
      parentRoute: typeof BookBookIdEditRouteRoute
    }
    '/_mainLayout/user/me/reaction': {
      id: '/_mainLayout/user/me/reaction'
      path: '/reaction'
      fullPath: '/user/me/reaction'
      preLoaderRoute: typeof MainLayoutUserMeReactionRouteImport
      parentRoute: typeof MainLayoutUserMeRouteRoute
    }
    '/_mainLayout/user/me/follow': {
      id: '/_mainLayout/user/me/follow'
      path: '/follow'
      fullPath: '/user/me/follow'
      preLoaderRoute: typeof MainLayoutUserMeFollowRouteImport
      parentRoute: typeof MainLayoutUserMeRouteRoute
    }
    '/_mainLayout/user/me/edit': {
      id: '/_mainLayout/user/me/edit'
      path: '/edit'
      fullPath: '/user/me/edit'
      preLoaderRoute: typeof MainLayoutUserMeEditRouteImport
      parentRoute: typeof MainLayoutUserMeRouteRoute
    }
    '/_mainLayout/user/me/bookmark': {
      id: '/_mainLayout/user/me/bookmark'
      path: '/bookmark'
      fullPath: '/user/me/bookmark'
      preLoaderRoute: typeof MainLayoutUserMeBookmarkRouteImport
      parentRoute: typeof MainLayoutUserMeRouteRoute
    }
    '/_mainLayout/user/$unitId/edit': {
      id: '/_mainLayout/user/$unitId/edit'
      path: '/edit'
      fullPath: '/user/$unitId/edit'
      preLoaderRoute: typeof MainLayoutUserUnitIdEditRouteImport
      parentRoute: typeof MainLayoutUserUnitIdRoute
    }
    '/_mainLayout/shelf/book/$bookId': {
      id: '/_mainLayout/shelf/book/$bookId'
      path: '/shelf/book/$bookId'
      fullPath: '/shelf/book/$bookId'
      preLoaderRoute: typeof MainLayoutShelfBookBookIdRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/shelf/$shelfId/edit': {
      id: '/_mainLayout/shelf/$shelfId/edit'
      path: '/shelf/$shelfId/edit'
      fullPath: '/shelf/$shelfId/edit'
      preLoaderRoute: typeof MainLayoutShelfShelfIdEditRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/review/new/$bookUnitId': {
      id: '/_mainLayout/review/new/$bookUnitId'
      path: '/review/new/$bookUnitId'
      fullPath: '/review/new/$bookUnitId'
      preLoaderRoute: typeof MainLayoutReviewNewBookUnitIdRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/review/book/$bookId': {
      id: '/_mainLayout/review/book/$bookId'
      path: '/review/book/$bookId'
      fullPath: '/review/book/$bookId'
      preLoaderRoute: typeof MainLayoutReviewBookBookIdRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/review/$reviewId/edit': {
      id: '/_mainLayout/review/$reviewId/edit'
      path: '/review/$reviewId/edit'
      fullPath: '/review/$reviewId/edit'
      preLoaderRoute: typeof MainLayoutReviewReviewIdEditRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/remark/book/$bookId': {
      id: '/_mainLayout/remark/book/$bookId'
      path: '/remark/book/$bookId'
      fullPath: '/remark/book/$bookId'
      preLoaderRoute: typeof MainLayoutRemarkBookBookIdRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/realm/$realmId/manage': {
      id: '/_mainLayout/realm/$realmId/manage'
      path: '/realm/$realmId/manage'
      fullPath: '/realm/$realmId/manage'
      preLoaderRoute: typeof MainLayoutRealmRealmIdManageRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/quote/book/$bookId': {
      id: '/_mainLayout/quote/book/$bookId'
      path: '/quote/book/$bookId'
      fullPath: '/quote/book/$bookId'
      preLoaderRoute: typeof MainLayoutQuoteBookBookIdRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/quote/$unitId/edit': {
      id: '/_mainLayout/quote/$unitId/edit'
      path: '/quote/$unitId/edit'
      fullPath: '/quote/$unitId/edit'
      preLoaderRoute: typeof MainLayoutQuoteUnitIdEditRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/book/$bookId/review': {
      id: '/_mainLayout/book/$bookId/review'
      path: '/review'
      fullPath: '/book/$bookId/review'
      preLoaderRoute: typeof MainLayoutBookBookIdReviewRouteImport
      parentRoute: typeof MainLayoutBookBookIdRouteRoute
    }
    '/_mainLayout/book/$bookId/info': {
      id: '/_mainLayout/book/$bookId/info'
      path: '/info'
      fullPath: '/book/$bookId/info'
      preLoaderRoute: typeof MainLayoutBookBookIdInfoRouteImport
      parentRoute: typeof MainLayoutBookBookIdRouteRoute
    }
    '/_mainLayout/book/$bookId/discussion': {
      id: '/_mainLayout/book/$bookId/discussion'
      path: '/discussion'
      fullPath: '/book/$bookId/discussion'
      preLoaderRoute: typeof MainLayoutBookBookIdDiscussionRouteImport
      parentRoute: typeof MainLayoutBookBookIdRouteRoute
    }
    '/_mainLayout/book/$bookId/content': {
      id: '/_mainLayout/book/$bookId/content'
      path: '/content'
      fullPath: '/book/$bookId/content'
      preLoaderRoute: typeof MainLayoutBookBookIdContentRouteImport
      parentRoute: typeof MainLayoutBookBookIdRouteRoute
    }
    '/book_/$bookId/read/$chapterId': {
      id: '/book_/$bookId/read/$chapterId'
      path: '/book/$bookId/read/$chapterId'
      fullPath: '/book/$bookId/read/$chapterId'
      preLoaderRoute: typeof BookBookIdReadChapterIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mainLayout/tag/domain/$unitId': {
      id: '/_mainLayout/tag/domain/$unitId'
      path: '/tag/domain/$unitId'
      fullPath: '/tag/domain/$unitId'
      preLoaderRoute: typeof MainLayoutTagDomainUnitIdRouteRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/tag/book/$bookId': {
      id: '/_mainLayout/tag/book/$bookId'
      path: '/tag/book/$bookId'
      fullPath: '/tag/book/$bookId'
      preLoaderRoute: typeof MainLayoutTagBookBookIdRouteRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/book_/$bookId/read/$chapterId/': {
      id: '/book_/$bookId/read/$chapterId/'
      path: '/'
      fullPath: '/book/$bookId/read/$chapterId/'
      preLoaderRoute: typeof BookBookIdReadChapterIdIndexRouteImport
      parentRoute: typeof BookBookIdReadChapterIdRouteRoute
    }
    '/_mainLayout/tag/domain/$unitId/': {
      id: '/_mainLayout/tag/domain/$unitId/'
      path: '/'
      fullPath: '/tag/domain/$unitId/'
      preLoaderRoute: typeof MainLayoutTagDomainUnitIdIndexRouteImport
      parentRoute: typeof MainLayoutTagDomainUnitIdRouteRoute
    }
    '/_mainLayout/tag/book/$bookId/': {
      id: '/_mainLayout/tag/book/$bookId/'
      path: '/'
      fullPath: '/tag/book/$bookId/'
      preLoaderRoute: typeof MainLayoutTagBookBookIdIndexRouteImport
      parentRoute: typeof MainLayoutTagBookBookIdRouteRoute
    }
    '/_mainLayout/tag/book/$bookId/tag': {
      id: '/_mainLayout/tag/book/$bookId/tag'
      path: '/tag'
      fullPath: '/tag/book/$bookId/tag'
      preLoaderRoute: typeof MainLayoutTagBookBookIdTagRouteRouteImport
      parentRoute: typeof MainLayoutTagBookBookIdRouteRoute
    }
    '/_mainLayout/tag/book/$bookId/tag/': {
      id: '/_mainLayout/tag/book/$bookId/tag/'
      path: '/'
      fullPath: '/tag/book/$bookId/tag/'
      preLoaderRoute: typeof MainLayoutTagBookBookIdTagIndexRouteImport
      parentRoute: typeof MainLayoutTagBookBookIdTagRouteRoute
    }
    '/_mainLayout/tag/domain/$unitId/title/$title': {
      id: '/_mainLayout/tag/domain/$unitId/title/$title'
      path: '/title/$title'
      fullPath: '/tag/domain/$unitId/title/$title'
      preLoaderRoute: typeof MainLayoutTagDomainUnitIdTitleTitleRouteImport
      parentRoute: typeof MainLayoutTagDomainUnitIdRouteRoute
    }
    '/_mainLayout/tag/book/$bookId/tag/$domainId': {
      id: '/_mainLayout/tag/book/$bookId/tag/$domainId'
      path: '/$domainId'
      fullPath: '/tag/book/$bookId/tag/$domainId'
      preLoaderRoute: typeof MainLayoutTagBookBookIdTagDomainIdRouteImport
      parentRoute: typeof MainLayoutTagBookBookIdTagRouteRoute
    }
  }
}

interface MainLayoutBookBookIdRouteRouteChildren {
  MainLayoutBookBookIdContentRoute: typeof MainLayoutBookBookIdContentRoute
  MainLayoutBookBookIdDiscussionRoute: typeof MainLayoutBookBookIdDiscussionRoute
  MainLayoutBookBookIdInfoRoute: typeof MainLayoutBookBookIdInfoRoute
  MainLayoutBookBookIdReviewRoute: typeof MainLayoutBookBookIdReviewRoute
  MainLayoutBookBookIdIndexRoute: typeof MainLayoutBookBookIdIndexRoute
}

const MainLayoutBookBookIdRouteRouteChildren: MainLayoutBookBookIdRouteRouteChildren =
  {
    MainLayoutBookBookIdContentRoute: MainLayoutBookBookIdContentRoute,
    MainLayoutBookBookIdDiscussionRoute: MainLayoutBookBookIdDiscussionRoute,
    MainLayoutBookBookIdInfoRoute: MainLayoutBookBookIdInfoRoute,
    MainLayoutBookBookIdReviewRoute: MainLayoutBookBookIdReviewRoute,
    MainLayoutBookBookIdIndexRoute: MainLayoutBookBookIdIndexRoute,
  }

const MainLayoutBookBookIdRouteRouteWithChildren =
  MainLayoutBookBookIdRouteRoute._addFileChildren(
    MainLayoutBookBookIdRouteRouteChildren,
  )

interface MainLayoutUserMeRouteRouteChildren {
  MainLayoutUserMeBookmarkRoute: typeof MainLayoutUserMeBookmarkRoute
  MainLayoutUserMeEditRoute: typeof MainLayoutUserMeEditRoute
  MainLayoutUserMeFollowRoute: typeof MainLayoutUserMeFollowRoute
  MainLayoutUserMeReactionRoute: typeof MainLayoutUserMeReactionRoute
  MainLayoutUserMeIndexRoute: typeof MainLayoutUserMeIndexRoute
}

const MainLayoutUserMeRouteRouteChildren: MainLayoutUserMeRouteRouteChildren = {
  MainLayoutUserMeBookmarkRoute: MainLayoutUserMeBookmarkRoute,
  MainLayoutUserMeEditRoute: MainLayoutUserMeEditRoute,
  MainLayoutUserMeFollowRoute: MainLayoutUserMeFollowRoute,
  MainLayoutUserMeReactionRoute: MainLayoutUserMeReactionRoute,
  MainLayoutUserMeIndexRoute: MainLayoutUserMeIndexRoute,
}

const MainLayoutUserMeRouteRouteWithChildren =
  MainLayoutUserMeRouteRoute._addFileChildren(
    MainLayoutUserMeRouteRouteChildren,
  )

interface MainLayoutUserUnitIdRouteChildren {
  MainLayoutUserUnitIdEditRoute: typeof MainLayoutUserUnitIdEditRoute
}

const MainLayoutUserUnitIdRouteChildren: MainLayoutUserUnitIdRouteChildren = {
  MainLayoutUserUnitIdEditRoute: MainLayoutUserUnitIdEditRoute,
}

const MainLayoutUserUnitIdRouteWithChildren =
  MainLayoutUserUnitIdRoute._addFileChildren(MainLayoutUserUnitIdRouteChildren)

interface MainLayoutTagBookBookIdTagRouteRouteChildren {
  MainLayoutTagBookBookIdTagDomainIdRoute: typeof MainLayoutTagBookBookIdTagDomainIdRoute
  MainLayoutTagBookBookIdTagIndexRoute: typeof MainLayoutTagBookBookIdTagIndexRoute
}

const MainLayoutTagBookBookIdTagRouteRouteChildren: MainLayoutTagBookBookIdTagRouteRouteChildren =
  {
    MainLayoutTagBookBookIdTagDomainIdRoute:
      MainLayoutTagBookBookIdTagDomainIdRoute,
    MainLayoutTagBookBookIdTagIndexRoute: MainLayoutTagBookBookIdTagIndexRoute,
  }

const MainLayoutTagBookBookIdTagRouteRouteWithChildren =
  MainLayoutTagBookBookIdTagRouteRoute._addFileChildren(
    MainLayoutTagBookBookIdTagRouteRouteChildren,
  )

interface MainLayoutTagBookBookIdRouteRouteChildren {
  MainLayoutTagBookBookIdTagRouteRoute: typeof MainLayoutTagBookBookIdTagRouteRouteWithChildren
  MainLayoutTagBookBookIdIndexRoute: typeof MainLayoutTagBookBookIdIndexRoute
}

const MainLayoutTagBookBookIdRouteRouteChildren: MainLayoutTagBookBookIdRouteRouteChildren =
  {
    MainLayoutTagBookBookIdTagRouteRoute:
      MainLayoutTagBookBookIdTagRouteRouteWithChildren,
    MainLayoutTagBookBookIdIndexRoute: MainLayoutTagBookBookIdIndexRoute,
  }

const MainLayoutTagBookBookIdRouteRouteWithChildren =
  MainLayoutTagBookBookIdRouteRoute._addFileChildren(
    MainLayoutTagBookBookIdRouteRouteChildren,
  )

interface MainLayoutTagDomainUnitIdRouteRouteChildren {
  MainLayoutTagDomainUnitIdIndexRoute: typeof MainLayoutTagDomainUnitIdIndexRoute
  MainLayoutTagDomainUnitIdTitleTitleRoute: typeof MainLayoutTagDomainUnitIdTitleTitleRoute
}

const MainLayoutTagDomainUnitIdRouteRouteChildren: MainLayoutTagDomainUnitIdRouteRouteChildren =
  {
    MainLayoutTagDomainUnitIdIndexRoute: MainLayoutTagDomainUnitIdIndexRoute,
    MainLayoutTagDomainUnitIdTitleTitleRoute:
      MainLayoutTagDomainUnitIdTitleTitleRoute,
  }

const MainLayoutTagDomainUnitIdRouteRouteWithChildren =
  MainLayoutTagDomainUnitIdRouteRoute._addFileChildren(
    MainLayoutTagDomainUnitIdRouteRouteChildren,
  )

interface MainLayoutRouteChildren {
  MainLayoutLoginRoute: typeof MainLayoutLoginRoute
  MainLayoutNoticeRoute: typeof MainLayoutNoticeRoute
  MainLayoutOnboardingRoute: typeof MainLayoutOnboardingRoute
  MainLayoutRegisterRoute: typeof MainLayoutRegisterRoute
  MainLayoutResetPasswordRoute: typeof MainLayoutResetPasswordRoute
  MainLayoutTestRoute: typeof MainLayoutTestRoute
  MainLayoutTest02Route: typeof MainLayoutTest02Route
  MainLayoutTest03Route: typeof MainLayoutTest03Route
  MainLayoutThemeSwitchRoute: typeof MainLayoutThemeSwitchRoute
  MainLayoutVerifyEmailRoute: typeof MainLayoutVerifyEmailRoute
  MainLayoutIndexRoute: typeof MainLayoutIndexRoute
  MainLayoutBookBookIdRouteRoute: typeof MainLayoutBookBookIdRouteRouteWithChildren
  MainLayoutUserMeRouteRoute: typeof MainLayoutUserMeRouteRouteWithChildren
  MainLayoutBookNewRoute: typeof MainLayoutBookNewRoute
  MainLayoutBookSearchRoute: typeof MainLayoutBookSearchRoute
  MainLayoutFeedbackAdminRoute: typeof MainLayoutFeedbackAdminRoute
  MainLayoutInboxNotificationRoute: typeof MainLayoutInboxNotificationRoute
  MainLayoutRealmNewRoute: typeof MainLayoutRealmNewRoute
  MainLayoutRealmSearchRoute: typeof MainLayoutRealmSearchRoute
  MainLayoutRemarkReviewIdRoute: typeof MainLayoutRemarkReviewIdRoute
  MainLayoutReviewSearchRoute: typeof MainLayoutReviewSearchRoute
  MainLayoutShelfNewRoute: typeof MainLayoutShelfNewRoute
  MainLayoutShelfSearchRoute: typeof MainLayoutShelfSearchRoute
  MainLayoutTagUnitIdRoute: typeof MainLayoutTagUnitIdRoute
  MainLayoutUnitUnitIdRoute: typeof MainLayoutUnitUnitIdRoute
  MainLayoutUserUnitIdRoute: typeof MainLayoutUserUnitIdRouteWithChildren
  MainLayoutBookIndexRoute: typeof MainLayoutBookIndexRoute
  MainLayoutFeedbackIndexRoute: typeof MainLayoutFeedbackIndexRoute
  MainLayoutRealmIndexRoute: typeof MainLayoutRealmIndexRoute
  MainLayoutReviewIndexRoute: typeof MainLayoutReviewIndexRoute
  MainLayoutShelfIndexRoute: typeof MainLayoutShelfIndexRoute
  MainLayoutUnitIndexRoute: typeof MainLayoutUnitIndexRoute
  MainLayoutTagBookBookIdRouteRoute: typeof MainLayoutTagBookBookIdRouteRouteWithChildren
  MainLayoutTagDomainUnitIdRouteRoute: typeof MainLayoutTagDomainUnitIdRouteRouteWithChildren
  MainLayoutQuoteUnitIdEditRoute: typeof MainLayoutQuoteUnitIdEditRoute
  MainLayoutQuoteBookBookIdRoute: typeof MainLayoutQuoteBookBookIdRoute
  MainLayoutRealmRealmIdManageRoute: typeof MainLayoutRealmRealmIdManageRoute
  MainLayoutRemarkBookBookIdRoute: typeof MainLayoutRemarkBookBookIdRoute
  MainLayoutReviewReviewIdEditRoute: typeof MainLayoutReviewReviewIdEditRoute
  MainLayoutReviewBookBookIdRoute: typeof MainLayoutReviewBookBookIdRoute
  MainLayoutReviewNewBookUnitIdRoute: typeof MainLayoutReviewNewBookUnitIdRoute
  MainLayoutShelfShelfIdEditRoute: typeof MainLayoutShelfShelfIdEditRoute
  MainLayoutShelfBookBookIdRoute: typeof MainLayoutShelfBookBookIdRoute
  MainLayoutQuoteUnitIdIndexRoute: typeof MainLayoutQuoteUnitIdIndexRoute
  MainLayoutRealmRealmIdIndexRoute: typeof MainLayoutRealmRealmIdIndexRoute
  MainLayoutReviewReviewIdIndexRoute: typeof MainLayoutReviewReviewIdIndexRoute
  MainLayoutShelfShelfIdIndexRoute: typeof MainLayoutShelfShelfIdIndexRoute
}

const MainLayoutRouteChildren: MainLayoutRouteChildren = {
  MainLayoutLoginRoute: MainLayoutLoginRoute,
  MainLayoutNoticeRoute: MainLayoutNoticeRoute,
  MainLayoutOnboardingRoute: MainLayoutOnboardingRoute,
  MainLayoutRegisterRoute: MainLayoutRegisterRoute,
  MainLayoutResetPasswordRoute: MainLayoutResetPasswordRoute,
  MainLayoutTestRoute: MainLayoutTestRoute,
  MainLayoutTest02Route: MainLayoutTest02Route,
  MainLayoutTest03Route: MainLayoutTest03Route,
  MainLayoutThemeSwitchRoute: MainLayoutThemeSwitchRoute,
  MainLayoutVerifyEmailRoute: MainLayoutVerifyEmailRoute,
  MainLayoutIndexRoute: MainLayoutIndexRoute,
  MainLayoutBookBookIdRouteRoute: MainLayoutBookBookIdRouteRouteWithChildren,
  MainLayoutUserMeRouteRoute: MainLayoutUserMeRouteRouteWithChildren,
  MainLayoutBookNewRoute: MainLayoutBookNewRoute,
  MainLayoutBookSearchRoute: MainLayoutBookSearchRoute,
  MainLayoutFeedbackAdminRoute: MainLayoutFeedbackAdminRoute,
  MainLayoutInboxNotificationRoute: MainLayoutInboxNotificationRoute,
  MainLayoutRealmNewRoute: MainLayoutRealmNewRoute,
  MainLayoutRealmSearchRoute: MainLayoutRealmSearchRoute,
  MainLayoutRemarkReviewIdRoute: MainLayoutRemarkReviewIdRoute,
  MainLayoutReviewSearchRoute: MainLayoutReviewSearchRoute,
  MainLayoutShelfNewRoute: MainLayoutShelfNewRoute,
  MainLayoutShelfSearchRoute: MainLayoutShelfSearchRoute,
  MainLayoutTagUnitIdRoute: MainLayoutTagUnitIdRoute,
  MainLayoutUnitUnitIdRoute: MainLayoutUnitUnitIdRoute,
  MainLayoutUserUnitIdRoute: MainLayoutUserUnitIdRouteWithChildren,
  MainLayoutBookIndexRoute: MainLayoutBookIndexRoute,
  MainLayoutFeedbackIndexRoute: MainLayoutFeedbackIndexRoute,
  MainLayoutRealmIndexRoute: MainLayoutRealmIndexRoute,
  MainLayoutReviewIndexRoute: MainLayoutReviewIndexRoute,
  MainLayoutShelfIndexRoute: MainLayoutShelfIndexRoute,
  MainLayoutUnitIndexRoute: MainLayoutUnitIndexRoute,
  MainLayoutTagBookBookIdRouteRoute:
    MainLayoutTagBookBookIdRouteRouteWithChildren,
  MainLayoutTagDomainUnitIdRouteRoute:
    MainLayoutTagDomainUnitIdRouteRouteWithChildren,
  MainLayoutQuoteUnitIdEditRoute: MainLayoutQuoteUnitIdEditRoute,
  MainLayoutQuoteBookBookIdRoute: MainLayoutQuoteBookBookIdRoute,
  MainLayoutRealmRealmIdManageRoute: MainLayoutRealmRealmIdManageRoute,
  MainLayoutRemarkBookBookIdRoute: MainLayoutRemarkBookBookIdRoute,
  MainLayoutReviewReviewIdEditRoute: MainLayoutReviewReviewIdEditRoute,
  MainLayoutReviewBookBookIdRoute: MainLayoutReviewBookBookIdRoute,
  MainLayoutReviewNewBookUnitIdRoute: MainLayoutReviewNewBookUnitIdRoute,
  MainLayoutShelfShelfIdEditRoute: MainLayoutShelfShelfIdEditRoute,
  MainLayoutShelfBookBookIdRoute: MainLayoutShelfBookBookIdRoute,
  MainLayoutQuoteUnitIdIndexRoute: MainLayoutQuoteUnitIdIndexRoute,
  MainLayoutRealmRealmIdIndexRoute: MainLayoutRealmRealmIdIndexRoute,
  MainLayoutReviewReviewIdIndexRoute: MainLayoutReviewReviewIdIndexRoute,
  MainLayoutShelfShelfIdIndexRoute: MainLayoutShelfShelfIdIndexRoute,
}

const MainLayoutRouteWithChildren = MainLayoutRoute._addFileChildren(
  MainLayoutRouteChildren,
)

interface BookBookIdEditRouteRouteChildren {
  BookBookIdEditChapterIdRoute: typeof BookBookIdEditChapterIdRoute
  BookBookIdEditChapterRoute: typeof BookBookIdEditChapterRoute
  BookBookIdEditTagRoute: typeof BookBookIdEditTagRoute
  BookBookIdEditIndexRoute: typeof BookBookIdEditIndexRoute
}

const BookBookIdEditRouteRouteChildren: BookBookIdEditRouteRouteChildren = {
  BookBookIdEditChapterIdRoute: BookBookIdEditChapterIdRoute,
  BookBookIdEditChapterRoute: BookBookIdEditChapterRoute,
  BookBookIdEditTagRoute: BookBookIdEditTagRoute,
  BookBookIdEditIndexRoute: BookBookIdEditIndexRoute,
}

const BookBookIdEditRouteRouteWithChildren =
  BookBookIdEditRouteRoute._addFileChildren(BookBookIdEditRouteRouteChildren)

interface BookBookIdReadChapterIdRouteRouteChildren {
  BookBookIdReadChapterIdIndexRoute: typeof BookBookIdReadChapterIdIndexRoute
}

const BookBookIdReadChapterIdRouteRouteChildren: BookBookIdReadChapterIdRouteRouteChildren =
  {
    BookBookIdReadChapterIdIndexRoute: BookBookIdReadChapterIdIndexRoute,
  }

const BookBookIdReadChapterIdRouteRouteWithChildren =
  BookBookIdReadChapterIdRouteRoute._addFileChildren(
    BookBookIdReadChapterIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  MainLayoutRoute: MainLayoutRouteWithChildren,
  BookBookIdEditRouteRoute: BookBookIdEditRouteRouteWithChildren,
  BookBookIdReadChapterIdRouteRoute:
    BookBookIdReadChapterIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
