export const Keys = {
  units: "units",
  unit: (id: string) => `unit:${id}`,
  realms: "realms",
  realm: (id: string) => `realm:${id}`,
  realmMembers: (id: string) => `realm-members:${id}`,
  posts: "posts",
  post: (id: string) => `post:${id}`,
  comments: "comments",
  tags: "tags",
  shelves: "shelves",
  search: "search",
  user: (id: string) => `user:${id}`,
  notifications: "notifications",
};
