import type {
	ProductClaim,
	ProductDefinition,
	ProductMedia,
	ProtocolDefinition,
} from "./productTypes";

const defineProduct = <const T extends ProductDefinition>(definition: T): T => definition;
const defaultSections = [
	"identity",
	"stage",
	"scenarios",
	"workflow",
	"capabilities",
	"boundaries",
	"faq",
	"related",
] as const;

export const PRODUCT_DEFINITIONS = [
	defineProduct({
		id: "catalog",
		slug: "catalog",
		name: "Catalog",
		pageClass: "surface",
		navGroup: "products",
		consumesCapabilities: ["history"],
		relatedProductIds: ["book", "media", "software", "series", "release", "entity", "tag"],
		implementationStatus: "documented",
		sourceDocuments: ["Outline · Catalog"],
		mediaIds: ["catalog-stage"],
		demoKind: "catalog",
		sections: defaultSections,
	}),
	defineProduct({
		id: "book",
		slug: "book",
		name: "Book",
		pageClass: "surface",
		navGroup: "products",
		consumesCapabilities: ["history", "editor", "progress"],
		relatedProductIds: [
			"gamebook",
			"release",
			"post",
			"catalog",
			"content-structure",
			"entity",
			"tag",
		],
		implementationStatus: "documented",
		sourceDocuments: ["Outline · Book", "Outline · Catalog", "User-confirmed product model"],
		mediaIds: ["book-stage"],
		demoKind: "book",
		sections: defaultSections,
	}),
	defineProduct({
		id: "gamebook",
		slug: "gamebook",
		name: "GameBook",
		pageClass: "manifestation",
		navGroup: "products",
		canonicalParentId: "book",
		consumesCapabilities: ["history", "editor", "progress"],
		manifestation: {
			formula: "Book + GameContentStructure → GameBook",
			description: "A Book presented through the optional game structure mode.",
		},
		relatedProductIds: ["book", "content-structure", "progress"],
		implementationStatus: "documented",
		sourceDocuments: ["Outline · GameBook", "User-confirmed product model"],
		mediaIds: ["gamebook-stage"],
		demoKind: "gamebook",
		sections: [
			"identity",
			"stage",
			"workflow",
			"scenarios",
			"boundaries",
			"capabilities",
			"faq",
			"related",
		],
	}),
	defineProduct({
		id: "media",
		slug: "media",
		name: "Media",
		pageClass: "surface",
		navGroup: "products",
		consumesCapabilities: ["history"],
		relatedProductIds: ["catalog", "series", "release", "entity", "tag"],
		implementationStatus: "documented",
		sourceDocuments: ["Outline · Catalog"],
		mediaIds: ["media-stage"],
		demoKind: "generic",
		sections: defaultSections,
	}),
	defineProduct({
		id: "software",
		slug: "software",
		name: "Software",
		pageClass: "surface",
		navGroup: "products",
		consumesCapabilities: ["history"],
		relatedProductIds: ["catalog", "release", "entity", "tag"],
		implementationStatus: "documented",
		sourceDocuments: ["Outline · Catalog"],
		mediaIds: ["software-stage"],
		demoKind: "generic",
		sections: defaultSections,
	}),
	defineProduct({
		id: "series",
		slug: "series",
		name: "Series",
		pageClass: "surface",
		navGroup: "products",
		consumesCapabilities: ["history"],
		relatedProductIds: ["catalog", "book", "media", "entity", "tag"],
		implementationStatus: "documented",
		sourceDocuments: ["Outline · Catalog"],
		mediaIds: ["series-stage"],
		demoKind: "generic",
		sections: defaultSections,
	}),
	defineProduct({
		id: "release",
		slug: "release",
		name: "Release",
		pageClass: "surface",
		navGroup: "products",
		consumesCapabilities: ["history"],
		relatedProductIds: ["book", "media", "software", "catalog", "entity", "tag"],
		implementationStatus: "documented",
		sourceDocuments: ["Outline · Catalog"],
		mediaIds: ["release-stage"],
		demoKind: "generic",
		sections: defaultSections,
	}),
	defineProduct({
		id: "post",
		slug: "post",
		name: "Post",
		pageClass: "surface",
		navGroup: "products",
		consumesCapabilities: ["editor", "history", "feed"],
		relatedProductIds: ["wiki", "picture", "review", "book", "entity", "tag"],
		implementationStatus: "documented",
		sourceDocuments: ["Outline · Post"],
		mediaIds: ["post-stage"],
		demoKind: "editor",
		sections: defaultSections,
	}),
	defineProduct({
		id: "wiki",
		slug: "wiki",
		name: "Wiki",
		pageClass: "manifestation",
		navGroup: "products",
		canonicalParentId: "post",
		consumesCapabilities: ["editor", "history", "feed"],
		manifestation: {
			formula: "Post(kind=WIKI) → Wiki",
			description: "A Post with the WIKI kind.",
		},
		relatedProductIds: ["post", "picture", "review", "entity", "tag"],
		implementationStatus: "documented",
		sourceDocuments: ["Outline · Wiki", "Outline · Post"],
		mediaIds: ["wiki-stage"],
		demoKind: "editor",
		sections: defaultSections,
	}),
	defineProduct({
		id: "picture",
		slug: "picture",
		name: "Picture",
		pageClass: "manifestation",
		navGroup: "products",
		canonicalParentId: "post",
		consumesCapabilities: ["editor", "history", "feed"],
		manifestation: {
			formula: "Post(kind=PICTURE) → Picture",
			description: "A Post with ordered picture media.",
		},
		relatedProductIds: ["post", "wiki", "review", "entity", "tag"],
		implementationStatus: "documented",
		sourceDocuments: ["Outline · Picture", "Outline · Post"],
		mediaIds: ["picture-stage"],
		demoKind: "generic",
		sections: defaultSections,
	}),
	defineProduct({
		id: "review",
		slug: "review",
		name: "Review",
		pageClass: "manifestation",
		navGroup: "products",
		canonicalParentId: "post",
		consumesCapabilities: ["editor", "history", "feed", "score"],
		manifestation: {
			formula: "Post(kind=REVIEW) → Review",
			description: "A Post with review semantics.",
		},
		relatedProductIds: ["post", "score", "wiki", "entity", "tag"],
		implementationStatus: "documented",
		sourceDocuments: ["Outline · Review", "Outline · Post"],
		mediaIds: ["review-stage"],
		demoKind: "editor",
		sections: defaultSections,
	}),
	defineProduct({
		id: "collection",
		slug: "collection",
		name: "Collection",
		pageClass: "surface",
		navGroup: "products",
		consumesCapabilities: ["progress", "history"],
		relatedProductIds: ["library", "catalog", "realm", "tag"],
		implementationStatus: "implemented",
		sourceDocuments: ["Outline · Collection"],
		mediaIds: ["collection-stage"],
		demoKind: "generic",
		sections: defaultSections,
	}),
	defineProduct({
		id: "library",
		slug: "library",
		name: "Library",
		pageClass: "manifestation",
		navGroup: "products",
		canonicalParentId: "collection",
		consumesCapabilities: ["progress", "history"],
		manifestation: {
			formula: "Collection[] → Library",
			description: "A personal library composed from a Profile's Collections.",
		},
		relatedProductIds: ["collection", "catalog", "progress", "tag"],
		implementationStatus: "planned",
		sourceDocuments: ["Outline · Collection", "User-confirmed product model"],
		mediaIds: ["library-stage"],
		demoKind: "generic",
		sections: defaultSections,
	}),
	defineProduct({
		id: "realm",
		slug: "realm",
		name: "Realm",
		pageClass: "surface",
		navGroup: "products",
		consumesCapabilities: ["feed"],
		relatedProductIds: ["zone", "collection", "catalog", "tag", "entity"],
		implementationStatus: "implemented",
		sourceDocuments: ["Outline · Realm"],
		mediaIds: ["realm-stage"],
		demoKind: "generic",
		sections: defaultSections,
	}),
	defineProduct({
		id: "zone",
		slug: "zone",
		name: "Zone",
		pageClass: "surface",
		navGroup: "products",
		consumesCapabilities: ["feed", "history"],
		relatedProductIds: ["feed", "realm", "tag", "collection"],
		implementationStatus: "implemented",
		sourceDocuments: ["Outline · Zone"],
		mediaIds: ["zone-stage"],
		demoKind: "zone",
		sections: [
			"identity",
			"stage",
			"workflow",
			"capabilities",
			"scenarios",
			"boundaries",
			"faq",
			"related",
		],
	}),
	defineProduct({
		id: "comment",
		slug: "comment",
		name: "Comment",
		pageClass: "surface",
		navGroup: "products",
		consumesCapabilities: ["history", "feed"],
		relatedProductIds: ["post", "review", "feed"],
		implementationStatus: "documented",
		sourceDocuments: ["Outline · Comment"],
		mediaIds: ["comment-stage"],
		demoKind: "generic",
		sections: defaultSections,
	}),
	defineProduct({
		id: "score",
		slug: "score",
		name: "Score",
		pageClass: "surface",
		navGroup: "products",
		consumesCapabilities: ["history", "feed"],
		relatedProductIds: ["review", "catalog", "feed"],
		implementationStatus: "documented",
		sourceDocuments: ["Outline · Score"],
		mediaIds: ["score-stage"],
		demoKind: "generic",
		sections: defaultSections,
	}),
	defineProduct({
		id: "content-structure",
		slug: "content-structure",
		name: "Content Structure",
		pageClass: "surface",
		navGroup: "products",
		capabilityModes: ["ContentStructure", "GameContentStructure"],
		consumesCapabilities: ["history", "editor", "api-oauth"],
		relatedProductIds: ["book", "gamebook", "history", "editor"],
		implementationStatus: "implemented",
		sourceDocuments: [
			"Outline · Content Structure",
			"Outline · GameBook",
			"User-confirmed product model",
		],
		mediaIds: ["content-structure-stage"],
		demoKind: "structure",
		sections: [
			"identity",
			"stage",
			"workflow",
			"scenarios",
			"boundaries",
			"capabilities",
			"faq",
			"related",
		],
	}),
	defineProduct({
		id: "history",
		slug: "history",
		name: "History",
		pageClass: "capability",
		navGroup: "platform",
		consumesCapabilities: [],
		relatedProductIds: ["book", "post", "zone", "content-structure"],
		implementationStatus: "documented",
		sourceDocuments: ["Outline · History", "User-confirmed product model"],
		mediaIds: ["history-stage"],
		demoKind: "history",
		sections: [
			"identity",
			"stage",
			"workflow",
			"scenarios",
			"boundaries",
			"capabilities",
			"faq",
			"related",
		],
	}),
	defineProduct({
		id: "editor",
		slug: "editor",
		name: "Editor",
		pageClass: "capability",
		navGroup: "platform",
		consumesCapabilities: ["history", "api-oauth"],
		relatedProductIds: ["post", "book", "content-structure", "history"],
		implementationStatus: "documented",
		sourceDocuments: ["Outline · Editor"],
		mediaIds: ["editor-stage"],
		demoKind: "editor",
		sections: defaultSections,
	}),
	defineProduct({
		id: "feed",
		slug: "feed",
		name: "Feed",
		pageClass: "capability",
		navGroup: "platform",
		consumesCapabilities: ["api-oauth"],
		relatedProductIds: ["post", "zone", "realm", "comment", "tag"],
		implementationStatus: "documented",
		sourceDocuments: ["Outline · Feed"],
		mediaIds: ["feed-stage"],
		demoKind: "feed",
		sections: defaultSections,
	}),
	defineProduct({
		id: "tag",
		slug: "tag",
		name: "Tag",
		pageClass: "surface",
		navGroup: "products",
		consumesCapabilities: ["history", "api-oauth"],
		relatedProductIds: ["catalog", "post", "zone", "realm", "collection"],
		implementationStatus: "implemented",
		sourceDocuments: ["Outline · Tags"],
		mediaIds: ["tag-stage"],
		demoKind: "generic",
		sections: defaultSections,
	}),
	defineProduct({
		id: "progress",
		slug: "progress",
		name: "Progress",
		pageClass: "capability",
		navGroup: "platform",
		consumesCapabilities: ["history"],
		relatedProductIds: ["book", "gamebook", "library"],
		implementationStatus: "planned",
		sourceDocuments: ["Outline · Progress", "Outline · GameBook"],
		mediaIds: ["progress-stage"],
		demoKind: "progress",
		sections: defaultSections,
	}),
	defineProduct({
		id: "entity",
		slug: "entity",
		name: "Entity",
		pageClass: "surface",
		navGroup: "products",
		capabilityModes: ["Entity", "CreditAttribution", "SubjectAttribution"],
		consumesCapabilities: ["history", "api-oauth"],
		relatedProductIds: ["book", "post", "media", "software"],
		implementationStatus: "implemented",
		sourceDocuments: [
			"Outline · Entity",
			"Schema · CreditAttribution",
			"Schema · SubjectAttribution",
			"User-confirmed product model",
		],
		mediaIds: ["entity-stage"],
		demoKind: "attribution",
		sections: [
			"identity",
			"stage",
			"workflow",
			"scenarios",
			"boundaries",
			"capabilities",
			"faq",
			"related",
		],
	}),
	defineProduct({
		id: "api-oauth",
		slug: "api-oauth",
		name: "API & OAuth",
		pageClass: "capability",
		navGroup: "platform",
		consumesCapabilities: [],
		relatedProductIds: ["content-structure", "editor", "feed", "entity"],
		implementationStatus: "documented",
		sourceDocuments: ["Outline · API", "Outline · OAuth", "Outline · MCP"],
		mediaIds: ["api-oauth-stage"],
		demoKind: "generic",
		sections: defaultSections,
	}),
] as const;

export type ProductId = (typeof PRODUCT_DEFINITIONS)[number]["id"];
export type ProductSlug = (typeof PRODUCT_DEFINITIONS)[number]["slug"];

export const PRODUCT_GROUPS = {
	products: PRODUCT_DEFINITIONS.filter((product) => product.navGroup === "products"),
	platform: PRODUCT_DEFINITIONS.filter((product) => product.navGroup === "platform"),
} as const;

export const PROTOCOL_DEFINITIONS = [
	{
		id: "unit",
		name: "Unit",
		pageClass: "protocol",
		describedByProductIds: ["catalog", "entity"],
	},
	{
		id: "block-schema",
		name: "Block Schema",
		pageClass: "protocol",
		describedByProductIds: ["zone", "editor"],
	},
	{ id: "zone-atom", name: "Zone Atom", pageClass: "protocol", describedByProductIds: ["zone"] },
	{
		id: "cover",
		name: "Cover",
		pageClass: "protocol",
		describedByProductIds: ["catalog", "book"],
	},
	{ id: "poll", name: "Poll", pageClass: "protocol", describedByProductIds: ["post"] },
	{
		id: "issue",
		name: "Issue",
		pageClass: "protocol",
		describedByProductIds: ["series", "release"],
	},
	{
		id: "chapter",
		name: "Chapter",
		pageClass: "protocol",
		describedByProductIds: ["book", "content-structure"],
	},
] as const satisfies readonly ProtocolDefinition[];

const conceptMedia = (
	productId: ProductId,
	componentId: ProductDefinition["demoKind"],
): ProductMedia => ({
	id: `${productId}-stage`,
	productId,
	purpose: "hero",
	kind: "concept-component",
	fidelity: "concept",
	componentId,
	themes: ["light", "dark"],
	viewports: ["desktop", "mobile"],
	width: 1440,
	height: 900,
	altKey: `${productId}.stage.alt`,
	captionKey: `${productId}.stage.caption`,
	replaceable: true,
	source: "Rezics About code-native product preview",
	featureVersion: "about-v1",
});

export const PRODUCT_MEDIA = PRODUCT_DEFINITIONS.map((product) =>
	conceptMedia(product.id, product.demoKind),
);

export const PRODUCT_CLAIMS = [
	{
		id: "gamebook-parent-book",
		productId: "gamebook",
		sourceType: "user-confirmed",
		sourceReference: "Book + GameContentStructure → GameBook",
		status: "confirmed",
	},
	{
		id: "structure-two-modes",
		productId: "content-structure",
		sourceType: "outline",
		sourceReference: "Content Structure and GameBook documents",
		status: "confirmed",
	},
	{
		id: "history-published-only",
		productId: "history",
		sourceType: "user-confirmed",
		sourceReference: "History records published revisions, not draft operations",
		status: "confirmed",
	},
	{
		id: "history-locks",
		productId: "history",
		sourceType: "user-confirmed",
		sourceReference: "History includes scoped locks",
		status: "confirmed",
	},
	{
		id: "entity-implemented",
		productId: "entity",
		sourceType: "schema",
		sourceReference: "Entity and attribution tables are implemented",
		status: "confirmed",
	},
	{
		id: "credit-attribution",
		productId: "entity",
		sourceType: "user-confirmed",
		sourceReference:
			"CreditAttribution expresses author, translator and publisher relationships",
		status: "confirmed",
	},
	{
		id: "subject-attribution",
		productId: "entity",
		sourceType: "user-confirmed",
		sourceReference:
			"SubjectAttribution expresses character, protagonist and derivative relationships",
		status: "confirmed",
	},
] as const satisfies readonly ProductClaim[];

export function getProductById(id: string): ProductDefinition | undefined {
	return PRODUCT_DEFINITIONS.find((product) => product.id === id);
}

export function getProductBySlug(slug: string): ProductDefinition | undefined {
	return PRODUCT_DEFINITIONS.find((product) => product.slug === slug);
}

export function getRelatedProducts(product: ProductDefinition): ProductDefinition[] {
	return product.relatedProductIds
		.map((id) => getProductById(id))
		.filter((related): related is ProductDefinition => Boolean(related));
}

export function getConsumedCapabilities(product: ProductDefinition): ProductDefinition[] {
	return product.consumesCapabilities
		.map((id) => getProductById(id))
		.filter((capability): capability is ProductDefinition => Boolean(capability));
}
