import type { AboutLocale } from "../i18n/locales";
import type { SiteCopy } from "./productTypes";

const sharedClassNames = {
	"zh-hant": {
		surface: "載體產品",
		capability: "共享能力",
		manifestation: "產品形態",
		protocol: "內部協議",
	},
	"zh-hans": {
		surface: "载体产品",
		capability: "共享能力",
		manifestation: "产品形态",
		protocol: "内部协议",
	},
	en: {
		surface: "Product surface",
		capability: "Shared capability",
		manifestation: "Product manifestation",
		protocol: "Internal protocol",
	},
	ja: {
		surface: "プロダクト",
		capability: "共有機能",
		manifestation: "プロダクト形態",
		protocol: "内部プロトコル",
	},
	de: {
		surface: "Produktoberfläche",
		capability: "Geteilte Fähigkeit",
		manifestation: "Produktform",
		protocol: "Internes Protokoll",
	},
	ko: {
		surface: "제품 표면",
		capability: "공유 기능",
		manifestation: "제품 형태",
		protocol: "내부 프로토콜",
	},
} as const;

export const SITE_COPY = {
	"zh-hant": {
		nav: {
			products: "Products",
			platform: "Platform",
			history: "History",
			docs: "Docs",
			github: "GitHub",
			language: "語言",
			theme: "主題",
			openMenu: "開啟選單",
			closeMenu: "關閉選單",
		},
		theme: { light: "淺色", dark: "深色", toggle: "切換明暗主題" },
		status: {
			implemented: "已實作",
			documented: "已確認設計",
			planned: "規劃中",
			research: "研究中",
		},
		classes: sharedClassNames["zh-hant"],
		common: {
			conceptPreview: "概念預覽",
			conceptCaption: "以程式碼重建的可替換產品展位，後續可直接替換為同尺寸真實截圖。",
			viewProduct: "查看產品",
			viewAll: "查看全部",
			learnMore: "深入了解",
			documentation: "Outline 文件",
			sourceCode: "原始碼",
			relatedProducts: "相關產品",
			usedCapabilities: "使用的共享能力",
			noParent: "獨立產品，沒有載體父產品",
			parentProduct: "父產品",
			sourceBasis: "事實來源",
		},
		home: {
			meta: {
				title: "Rezics — 讓內容保持身份、結構與歷史",
				description: "探索 Rezics 的產品、共享能力與開放平台。",
			},
			eyebrow: "Rezics product system",
			title: "內容不只被發佈，也能保有身份、結構與歷史。",
			lead: "Rezics 把書籍、文章、媒體與社群空間放在同一套可追溯的產品系統中。這裡展示的不是抽象願景，而是每個產品如何被使用。",
			stageTitle: "從真實產品表面認識 Rezics",
			stageLead:
				"手動切換 Book、History、Content Structure 與 Zone。所有畫面都是可替換的產品展位，不會自動輪播。",
			productsTitle: "每個產品都有自己的入口",
			productsLead: "產品不是一組同款卡片。聚焦任一項目，即可看到它的實際界面、定位與狀態。",
			platformTitle: "共享能力在不同產品之間工作",
			platformLead:
				"Content Structure、History 與 Entity & Attribution 擁有自己的工作流，也清楚說明由哪些產品使用。",
			formulaTitle: "能力如何形成產品",
			formulaLead: "用可驗證的組合關係，區分載體、能力與最終產品形態。",
			historyTitle: "History 是 Rezics 的資訊骨架",
			historyLead: "欄位與區塊歷史、已發佈版本和鎖定範圍，分別適配 Book、Post 與 Zone。",
			openTitle: "從文件到原始碼都是開放入口",
			openLead: "閱讀產品文件、檢視 API，或直接參與 Rezics 的開放原始碼。",
		},
		directory: {
			meta: {
				title: "Rezics Products & Platform",
				description: "瀏覽 Rezics 的所有產品、產品形態與共享能力。",
			},
			eyebrow: "Product directory",
			title: "產品表面與平台能力，各自清楚站立。",
			lead: "所有正式產品都有獨立頁面。扁平 URL 保持穩定，真正的父子關係由產品事實與頁面內容表達。",
			productsTitle: "Products",
			platformTitle: "Platform",
			previewInstruction: "選擇一個產品查看概念界面與定位。",
		},
		product: {
			breadcrumbsHome: "首頁",
			breadcrumbsProducts: "Products",
			scenarios: "具體使用場景",
			workflow: "核心工作流",
			capabilities: "使用的共享能力",
			boundaries: "產品邊界",
			faq: "常見問題",
			statusLabel: "狀態",
			classificationLabel: "類型",
			structureTree: "Tree 模式",
			structureGame: "Game 模式",
			credit: "CreditAttribution",
			subject: "SubjectAttribution",
			publishedVersions: "已發佈版本",
			fieldHistory: "欄位歷史",
			lockScope: "鎖定範圍",
			consumers: "使用此能力的產品",
		},
		footer: {
			statement: "Rezics 是一套以內容身份、結構與歷史為核心的開放產品系統。",
			productLinks: "Products",
			platformLinks: "Platform",
			openLinks: "Open",
		},
		notFound: {
			title: "找不到這個頁面",
			body: "此連結可能已移動，或尚未成為公開產品頁。",
			back: "回到首頁",
		},
	},
	"zh-hans": {
		nav: {
			products: "Products",
			platform: "Platform",
			history: "History",
			docs: "Docs",
			github: "GitHub",
			language: "语言",
			theme: "主题",
			openMenu: "打开菜单",
			closeMenu: "关闭菜单",
		},
		theme: { light: "浅色", dark: "深色", toggle: "切换明暗主题" },
		status: {
			implemented: "已实现",
			documented: "已确认设计",
			planned: "规划中",
			research: "研究中",
		},
		classes: sharedClassNames["zh-hans"],
		common: {
			conceptPreview: "概念预览",
			conceptCaption: "用代码重建的可替换产品展位，之后可直接替换为同尺寸真实截图。",
			viewProduct: "查看产品",
			viewAll: "查看全部",
			learnMore: "深入了解",
			documentation: "Outline 文档",
			sourceCode: "源代码",
			relatedProducts: "相关产品",
			usedCapabilities: "使用的共享能力",
			noParent: "独立产品，没有载体父产品",
			parentProduct: "父产品",
			sourceBasis: "事实来源",
		},
		home: {
			meta: {
				title: "Rezics — 让内容保持身份、结构与历史",
				description: "探索 Rezics 的产品、共享能力与开放平台。",
			},
			eyebrow: "Rezics product system",
			title: "内容不只被发布，也能保有身份、结构与历史。",
			lead: "Rezics 把书籍、文章、媒体与社区空间放在同一套可追溯的产品系统中。这里展示每个产品真实的使用方式。",
			stageTitle: "从真实产品表面认识 Rezics",
			stageLead:
				"手动切换 Book、History、Content Structure 与 Zone。所有画面都是可替换的产品展位。",
			productsTitle: "每个产品都有自己的入口",
			productsLead: "聚焦任一产品，即可看到它的实际界面、定位与状态。",
			platformTitle: "共享能力在不同产品之间工作",
			platformLead:
				"Content Structure、History 与 Entity & Attribution 拥有独立工作流，并说明由哪些产品使用。",
			formulaTitle: "能力如何形成产品",
			formulaLead: "通过可验证的组合关系，区分载体、能力与最终产品形态。",
			historyTitle: "History 是 Rezics 的信息骨架",
			historyLead: "字段与区块历史、已发布版本和锁定范围，分别适配 Book、Post 与 Zone。",
			openTitle: "从文档到源代码都是开放入口",
			openLead: "阅读产品文档、查看 API，或直接参与 Rezics 的开放源代码。",
		},
		directory: {
			meta: {
				title: "Rezics Products & Platform",
				description: "浏览 Rezics 的所有产品、产品形态与共享能力。",
			},
			eyebrow: "Product directory",
			title: "产品表面与平台能力，各自清楚站立。",
			lead: "所有正式产品都有独立页面。扁平 URL 保持稳定，真实关系由产品事实表达。",
			productsTitle: "Products",
			platformTitle: "Platform",
			previewInstruction: "选择一个产品查看概念界面与定位。",
		},
		product: {
			breadcrumbsHome: "首页",
			breadcrumbsProducts: "Products",
			scenarios: "具体使用场景",
			workflow: "核心工作流",
			capabilities: "使用的共享能力",
			boundaries: "产品边界",
			faq: "常见问题",
			statusLabel: "状态",
			classificationLabel: "类型",
			structureTree: "Tree 模式",
			structureGame: "Game 模式",
			credit: "CreditAttribution",
			subject: "SubjectAttribution",
			publishedVersions: "已发布版本",
			fieldHistory: "字段历史",
			lockScope: "锁定范围",
			consumers: "使用此能力的产品",
		},
		footer: {
			statement: "Rezics 是一套以内容身份、结构与历史为核心的开放产品系统。",
			productLinks: "Products",
			platformLinks: "Platform",
			openLinks: "Open",
		},
		notFound: {
			title: "找不到这个页面",
			body: "链接可能已移动，或尚未成为公开产品页。",
			back: "返回首页",
		},
	},
	en: {
		nav: {
			products: "Products",
			platform: "Platform",
			history: "History",
			docs: "Docs",
			github: "GitHub",
			language: "Language",
			theme: "Theme",
			openMenu: "Open menu",
			closeMenu: "Close menu",
		},
		theme: { light: "Light", dark: "Dark", toggle: "Toggle color theme" },
		status: {
			implemented: "Implemented",
			documented: "Documented design",
			planned: "Planned",
			research: "Research",
		},
		classes: sharedClassNames.en,
		common: {
			conceptPreview: "Concept preview",
			conceptCaption:
				"A replaceable, code-native product stage that can later be swapped for a same-size real screenshot.",
			viewProduct: "View product",
			viewAll: "View all",
			learnMore: "Learn more",
			documentation: "Outline docs",
			sourceCode: "Source code",
			relatedProducts: "Related products",
			usedCapabilities: "Shared capabilities used",
			noParent: "Independent product with no carrier parent",
			parentProduct: "Parent product",
			sourceBasis: "Fact sources",
		},
		home: {
			meta: {
				title: "Rezics — Identity, structure, and history for content",
				description: "Explore Rezics products, shared capabilities, and its open platform.",
			},
			eyebrow: "Rezics product system",
			title: "Content can keep its identity, structure, and history.",
			lead: "Rezics brings books, posts, media, and community spaces into one traceable product system. This site shows how each product is actually used.",
			stageTitle: "Meet Rezics through product surfaces",
			stageLead:
				"Switch manually between Book, History, Content Structure, and Zone. Nothing auto-rotates.",
			productsTitle: "Every product has its own entrance",
			productsLead: "Focus any product to see its interface, role, and current status.",
			platformTitle: "Shared capabilities work across products",
			platformLead:
				"Content Structure, History, and Entity & Attribution have workflows of their own and clear consumers.",
			formulaTitle: "How capabilities form products",
			formulaLead:
				"Verified composition rules separate carriers, capabilities, and resulting product forms.",
			historyTitle: "History is Rezics’ information backbone",
			historyLead:
				"Field and block history, published versions, and scoped locks adapt to Book, Post, and Zone.",
			openTitle: "Open from documentation to source",
			openLead: "Read product documents, inspect the API, or contribute directly to Rezics.",
		},
		directory: {
			meta: {
				title: "Rezics Products & Platform",
				description:
					"Browse every Rezics product, product manifestation, and shared capability.",
			},
			eyebrow: "Product directory",
			title: "Product surfaces and platform capabilities, each with a clear role.",
			lead: "Every formal product has an independent page. Flat URLs stay stable while product facts express real relationships.",
			productsTitle: "Products",
			platformTitle: "Platform",
			previewInstruction: "Choose a product to preview its interface and role.",
		},
		product: {
			breadcrumbsHome: "Home",
			breadcrumbsProducts: "Products",
			scenarios: "Concrete scenarios",
			workflow: "Core workflow",
			capabilities: "Shared capabilities used",
			boundaries: "Product boundaries",
			faq: "Frequently asked questions",
			statusLabel: "Status",
			classificationLabel: "Class",
			structureTree: "Tree mode",
			structureGame: "Game mode",
			credit: "CreditAttribution",
			subject: "SubjectAttribution",
			publishedVersions: "Published versions",
			fieldHistory: "Field history",
			lockScope: "Lock scope",
			consumers: "Products using this capability",
		},
		footer: {
			statement:
				"Rezics is an open product system built around content identity, structure, and history.",
			productLinks: "Products",
			platformLinks: "Platform",
			openLinks: "Open",
		},
		notFound: {
			title: "Page not found",
			body: "This link may have moved or may not be a public product page.",
			back: "Back home",
		},
	},
	ja: {
		nav: {
			products: "Products",
			platform: "Platform",
			history: "History",
			docs: "Docs",
			github: "GitHub",
			language: "言語",
			theme: "テーマ",
			openMenu: "メニューを開く",
			closeMenu: "メニューを閉じる",
		},
		theme: { light: "ライト", dark: "ダーク", toggle: "配色テーマを切り替える" },
		status: {
			implemented: "実装済み",
			documented: "設計確認済み",
			planned: "計画中",
			research: "調査中",
		},
		classes: sharedClassNames.ja,
		common: {
			conceptPreview: "コンセプトプレビュー",
			conceptCaption:
				"同じサイズの実画面に差し替えられる、コードで作成したプロダクト展示です。",
			viewProduct: "プロダクトを見る",
			viewAll: "すべて見る",
			learnMore: "詳しく見る",
			documentation: "Outline ドキュメント",
			sourceCode: "ソースコード",
			relatedProducts: "関連プロダクト",
			usedCapabilities: "利用する共有機能",
			noParent: "親となるプロダクトを持たない独立機能",
			parentProduct: "親プロダクト",
			sourceBasis: "情報源",
		},
		home: {
			meta: {
				title: "Rezics — コンテンツの同一性・構造・履歴",
				description: "Rezics のプロダクトと共有機能を紹介します。",
			},
			eyebrow: "Rezics product system",
			title: "コンテンツに、同一性と構造と履歴を。",
			lead: "Rezics は本、投稿、メディア、コミュニティ空間を追跡可能な一つのプロダクト体系にまとめます。",
			stageTitle: "実際のプロダクト画面から Rezics を知る",
			stageLead:
				"Book、History、Content Structure、Zone を手動で切り替えます。自動再生はありません。",
			productsTitle: "すべてのプロダクトに独立した入口",
			productsLead: "項目を選ぶと、画面、役割、現在の状態を確認できます。",
			platformTitle: "複数のプロダクトを支える共有機能",
			platformLead: "共有機能は独自のワークフローと利用先を持ちます。",
			formulaTitle: "機能がプロダクトを形作る方法",
			formulaLead: "確認済みの組み合わせで、載体・機能・プロダクト形態を区別します。",
			historyTitle: "History は Rezics の情報基盤",
			historyLead: "フィールド履歴、公開版、ロック範囲を Book、Post、Zone に適合させます。",
			openTitle: "ドキュメントからソースまでオープン",
			openLead: "製品資料、API、オープンソースへの入口です。",
		},
		directory: {
			meta: {
				title: "Rezics Products & Platform",
				description: "Rezics の全プロダクトと共有機能を一覧できます。",
			},
			eyebrow: "Product directory",
			title: "プロダクトとプラットフォーム機能を明確に整理。",
			lead: "すべての正式プロダクトに独立ページがあります。関係性は URL ではなく製品情報で表現します。",
			productsTitle: "Products",
			platformTitle: "Platform",
			previewInstruction: "項目を選び、画面と役割を確認してください。",
		},
		product: {
			breadcrumbsHome: "ホーム",
			breadcrumbsProducts: "Products",
			scenarios: "利用シーン",
			workflow: "主要ワークフロー",
			capabilities: "利用する共有機能",
			boundaries: "プロダクトの境界",
			faq: "よくある質問",
			statusLabel: "状態",
			classificationLabel: "種類",
			structureTree: "Tree モード",
			structureGame: "Game モード",
			credit: "CreditAttribution",
			subject: "SubjectAttribution",
			publishedVersions: "公開済みバージョン",
			fieldHistory: "フィールド履歴",
			lockScope: "ロック範囲",
			consumers: "この機能を使うプロダクト",
		},
		footer: {
			statement:
				"Rezics はコンテンツの同一性、構造、履歴を中心にしたオープンなプロダクト体系です。",
			productLinks: "Products",
			platformLinks: "Platform",
			openLinks: "Open",
		},
		notFound: {
			title: "ページが見つかりません",
			body: "リンクが移動したか、まだ公開されていません。",
			back: "ホームへ戻る",
		},
	},
	de: {
		nav: {
			products: "Produkte",
			platform: "Plattform",
			history: "History",
			docs: "Doku",
			github: "GitHub",
			language: "Sprache",
			theme: "Darstellung",
			openMenu: "Menü öffnen",
			closeMenu: "Menü schließen",
		},
		theme: { light: "Hell", dark: "Dunkel", toggle: "Farbschema wechseln" },
		status: {
			implemented: "Implementiert",
			documented: "Design bestätigt",
			planned: "Geplant",
			research: "In Prüfung",
		},
		classes: sharedClassNames.de,
		common: {
			conceptPreview: "Konzeptvorschau",
			conceptCaption:
				"Eine austauschbare, im Code erstellte Produktansicht für spätere echte Screenshots gleicher Größe.",
			viewProduct: "Produkt ansehen",
			viewAll: "Alle ansehen",
			learnMore: "Mehr erfahren",
			documentation: "Outline-Dokumentation",
			sourceCode: "Quellcode",
			relatedProducts: "Verwandte Produkte",
			usedCapabilities: "Genutzte Plattformfähigkeiten",
			noParent: "Eigenständiges Produkt ohne übergeordnetes Trägerprodukt",
			parentProduct: "Übergeordnetes Produkt",
			sourceBasis: "Faktenquellen",
		},
		home: {
			meta: {
				title: "Rezics — Identität, Struktur und Verlauf für Inhalte",
				description: "Produkte und Plattformfähigkeiten von Rezics.",
			},
			eyebrow: "Rezics product system",
			title: "Inhalte behalten Identität, Struktur und Verlauf.",
			lead: "Rezics verbindet Bücher, Beiträge, Medien und Community-Bereiche in einem nachvollziehbaren Produktsystem.",
			stageTitle: "Rezics über echte Produktoberflächen kennenlernen",
			stageLead:
				"Book, History, Content Structure und Zone werden manuell gewechselt. Es gibt keinen automatischen Wechsel.",
			productsTitle: "Jedes Produkt hat einen eigenen Einstieg",
			productsLead: "Eine Auswahl zeigt Oberfläche, Rolle und aktuellen Status.",
			platformTitle: "Geteilte Fähigkeiten arbeiten produktübergreifend",
			platformLead:
				"Jede Plattformfähigkeit besitzt einen eigenen Ablauf und klar benannte Nutzer.",
			formulaTitle: "Wie Fähigkeiten Produkte formen",
			formulaLead: "Bestätigte Kombinationen trennen Träger, Fähigkeit und Produktform.",
			historyTitle: "History ist das Informationsrückgrat",
			historyLead:
				"Feldverlauf, veröffentlichte Versionen und Sperrbereiche für Book, Post und Zone.",
			openTitle: "Offen von Dokumentation bis Quellcode",
			openLead: "Produkte dokumentieren, API prüfen oder direkt beitragen.",
		},
		directory: {
			meta: {
				title: "Rezics Produkte & Plattform",
				description: "Alle Rezics-Produkte und geteilten Fähigkeiten.",
			},
			eyebrow: "Product directory",
			title: "Produktoberflächen und Plattformfähigkeiten mit klaren Rollen.",
			lead: "Jedes formale Produkt hat eine eigene Seite. Beziehungen werden durch Produktfakten statt verschachtelte URLs erklärt.",
			productsTitle: "Produkte",
			platformTitle: "Plattform",
			previewInstruction: "Produkt wählen, um Oberfläche und Rolle zu sehen.",
		},
		product: {
			breadcrumbsHome: "Start",
			breadcrumbsProducts: "Produkte",
			scenarios: "Konkrete Nutzung",
			workflow: "Kernablauf",
			capabilities: "Genutzte Plattformfähigkeiten",
			boundaries: "Produktgrenzen",
			faq: "Häufige Fragen",
			statusLabel: "Status",
			classificationLabel: "Klasse",
			structureTree: "Baummodus",
			structureGame: "Spielmodus",
			credit: "CreditAttribution",
			subject: "SubjectAttribution",
			publishedVersions: "Veröffentlichte Versionen",
			fieldHistory: "Feldverlauf",
			lockScope: "Sperrbereich",
			consumers: "Nutzende Produkte",
		},
		footer: {
			statement:
				"Rezics ist ein offenes Produktsystem für Identität, Struktur und Verlauf von Inhalten.",
			productLinks: "Produkte",
			platformLinks: "Plattform",
			openLinks: "Offen",
		},
		notFound: {
			title: "Seite nicht gefunden",
			body: "Der Link wurde möglicherweise verschoben oder ist noch nicht öffentlich.",
			back: "Zur Startseite",
		},
	},
	ko: {
		nav: {
			products: "Products",
			platform: "Platform",
			history: "History",
			docs: "Docs",
			github: "GitHub",
			language: "언어",
			theme: "테마",
			openMenu: "메뉴 열기",
			closeMenu: "메뉴 닫기",
		},
		theme: { light: "라이트", dark: "다크", toggle: "색상 테마 전환" },
		status: {
			implemented: "구현됨",
			documented: "설계 확인됨",
			planned: "계획 중",
			research: "연구 중",
		},
		classes: sharedClassNames.ko,
		common: {
			conceptPreview: "콘셉트 미리보기",
			conceptCaption:
				"나중에 같은 크기의 실제 화면으로 교체할 수 있는 코드 기반 제품 전시입니다.",
			viewProduct: "제품 보기",
			viewAll: "전체 보기",
			learnMore: "자세히 보기",
			documentation: "Outline 문서",
			sourceCode: "소스 코드",
			relatedProducts: "관련 제품",
			usedCapabilities: "사용하는 공유 기능",
			noParent: "상위 운반 제품이 없는 독립 제품",
			parentProduct: "상위 제품",
			sourceBasis: "사실 출처",
		},
		home: {
			meta: {
				title: "Rezics — 콘텐츠의 정체성, 구조, 이력",
				description: "Rezics 제품과 공유 플랫폼 기능을 살펴보세요.",
			},
			eyebrow: "Rezics product system",
			title: "콘텐츠가 정체성, 구조, 이력을 유지하도록.",
			lead: "Rezics는 책, 게시물, 미디어, 커뮤니티 공간을 추적 가능한 하나의 제품 체계로 연결합니다.",
			stageTitle: "실제 제품 표면으로 Rezics 만나기",
			stageLead:
				"Book, History, Content Structure, Zone을 직접 전환합니다. 자동 회전은 없습니다.",
			productsTitle: "모든 제품에는 독립된 입구가 있습니다",
			productsLead: "제품을 선택하면 화면, 역할, 현재 상태를 확인할 수 있습니다.",
			platformTitle: "공유 기능은 여러 제품에서 작동합니다",
			platformLead: "각 공유 기능에는 자체 작업 흐름과 명확한 사용 제품이 있습니다.",
			formulaTitle: "기능이 제품을 만드는 방식",
			formulaLead: "확인된 조합으로 운반체, 기능, 제품 형태를 구분합니다.",
			historyTitle: "History는 Rezics의 정보 뼈대입니다",
			historyLead: "필드 이력, 공개 버전, 잠금 범위를 Book, Post, Zone에 맞춥니다.",
			openTitle: "문서부터 소스 코드까지 열려 있습니다",
			openLead: "제품 문서, API, 오픈 소스 기여로 이어집니다.",
		},
		directory: {
			meta: {
				title: "Rezics Products & Platform",
				description: "Rezics의 모든 제품과 공유 기능을 살펴보세요.",
			},
			eyebrow: "Product directory",
			title: "제품 표면과 플랫폼 기능을 명확한 역할로 정리했습니다.",
			lead: "모든 정식 제품에는 독립 페이지가 있습니다. 관계는 중첩 URL이 아니라 제품 사실로 설명합니다.",
			productsTitle: "Products",
			platformTitle: "Platform",
			previewInstruction: "제품을 선택해 화면과 역할을 확인하세요.",
		},
		product: {
			breadcrumbsHome: "홈",
			breadcrumbsProducts: "Products",
			scenarios: "구체적인 사용 장면",
			workflow: "핵심 작업 흐름",
			capabilities: "사용하는 공유 기능",
			boundaries: "제품 경계",
			faq: "자주 묻는 질문",
			statusLabel: "상태",
			classificationLabel: "유형",
			structureTree: "Tree 모드",
			structureGame: "Game 모드",
			credit: "CreditAttribution",
			subject: "SubjectAttribution",
			publishedVersions: "공개 버전",
			fieldHistory: "필드 이력",
			lockScope: "잠금 범위",
			consumers: "이 기능을 사용하는 제품",
		},
		footer: {
			statement: "Rezics는 콘텐츠의 정체성, 구조, 이력을 중심으로 한 오픈 제품 체계입니다.",
			productLinks: "Products",
			platformLinks: "Platform",
			openLinks: "Open",
		},
		notFound: {
			title: "페이지를 찾을 수 없습니다",
			body: "링크가 이동했거나 아직 공개되지 않았습니다.",
			back: "홈으로 돌아가기",
		},
	},
} as const satisfies Record<AboutLocale, SiteCopy>;

export function getSiteCopy(locale: AboutLocale): SiteCopy {
	return SITE_COPY[locale];
}
