import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { eq } from "drizzle-orm";
import { Pool } from "pg";
import { z } from "zod";
import { BundleSchema, RelationRevisionSchema, SourceManifestSchema } from "@rezics/schema";
import { digest } from "@rezics/schema/identity";
import { describeVocabularyClasses } from "@rezics/schema/profiles";
import { diffVocabularies, VocabularyRegistry } from "@rezics/schema/registry";
import { SchemaSources } from "./sources";
import { validateModelRecord } from "@rezics/schema/model";
import { CompiledModelSchema } from "@rezics/schema/model/contracts";
import { generateNativeModel } from "./compiler/generate";

const root = fileURLToPath(new URL("../", import.meta.url));
const sourceRoot = resolve(root, "sources");
const bundleFile = resolve(root, "registry/bundle.json");
const [command, ...args] = process.argv.slice(2);
const readArtifact = async (file: string) => readFile(resolve(sourceRoot, file));
const json = async (file: string) => {
	const content = await readFile(file);
	if (content.byteLength > 67_108_864) throw new RangeError("Schema artifact exceeds 64 MiB");
	return JSON.parse(content.toString("utf8"));
};

async function write(path: string, value: string | Uint8Array) {
	await mkdir(dirname(path), { recursive: true });
	const temporary = `${path}.${process.pid}.tmp`;
	await writeFile(temporary, value);
	await rename(temporary, path);
}
async function writeJson(path: string, value: unknown) {
	await write(path, `${JSON.stringify(value, null, "\t")}\n`);
}

async function fetchArtifact(url: string, hash: string, file: string, maximum: number) {
	const path = resolve(sourceRoot, file);
	try {
		if (digest(await readFile(path)) === hash) return;
	} catch (error) {
		if (!(error instanceof Error && "code" in error && error.code === "ENOENT")) throw error;
	}
	if (!url.startsWith("https://")) throw new TypeError("Pinned artifact downloads require HTTPS");
	const response = await fetch(url, {
		signal: AbortSignal.timeout(30_000),
		headers: { "User-Agent": "REZICS-schema-import/1.0" },
	});
	if (!response.ok || !response.body)
		throw new Error(`Artifact download failed: ${response.status} ${file}`);
	const parts: Uint8Array[] = [];
	let length = 0;
	for await (const part of response.body) {
		length += part.byteLength;
		if (length > maximum) throw new RangeError(`Artifact too large: ${file}`);
		parts.push(part);
	}
	const bytes = Buffer.concat(parts);
	if (digest(bytes) !== hash)
		throw new TypeError(`Upstream artifact changed: ${file}; update the manifest deliberately`);
	await write(path, bytes);
}

async function compile() {
	const { bundle, model } = await generateNativeModel();
	const registry = new VocabularyRegistry(bundle);
	const descriptions = describeVocabularyClasses(registry);
	await writeJson(bundleFile, bundle);

	const terms: Record<string, Record<string, string>> = Object.create(null);
	for (const release of bundle.releases) {
		const vocabulary: Record<string, string> = Object.create(null);
		const definitions = new Set(release.definitions.map((definition) => definition.termId));
		for (const term of [...bundle.terms].sort((a, b) =>
			a.iri < b.iri ? -1 : a.iri > b.iri ? 1 : 0,
		)) {
			if (!definitions.has(term.id)) continue;
			const namespace = release.source.namespaces.find((namespace) =>
				term.iri.startsWith(namespace),
			);
			if (namespace && term.iri.length > namespace.length)
				vocabulary[term.iri.slice(namespace.length)] = term.id;
		}
		terms[release.source.key] = vocabulary;
	}
	await write(
		resolve(root, "../schema/src/generated/terms.ts"),
		`// Generated by task libraries:schema-importer:generate. Do not edit.\n/** @alpha Stable UUIDs for the complete selected vocabulary definitions. */\nexport const terms = ${JSON.stringify(terms, null, "\t")} as const;\n`,
	);
	for (const [name, schema] of [
		["bundle", BundleSchema],
		["application-model", CompiledModelSchema],
		["relation-revision", RelationRevisionSchema],
	] as const)
		await writeJson(resolve(root, `schemas/${name}.schema.json`), z.toJSONSchema(schema));
	const coverage = {
		bundleId: bundle.id,
		digest: bundle.digest,
		terms: bundle.terms.length,
		releases: bundle.releases.map((release) => ({
			key: release.source.key,
			id: release.id,
			version: release.source.version,
			sha256: release.source.sha256,
			quads: release.quadCount,
			definitions: release.definitions.length,
			labels: release.labels.length,
			unindexedLabels: release.unindexedLabels,
			retired: release.definitions.filter((definition) => definition.status === "retired").length,
		})),
		profiles: model.profiles.map((profile) => ({ key: profile.key })),
	};
	await writeJson(resolve(root, "registry/coverage.json"), coverage);
	console.info(
		JSON.stringify(
			{
				bundleId: bundle.id,
				terms: bundle.terms.length,
				releases: bundle.releases.length,
				profiles: model.profiles.length,
				vocabularyDescriptions: descriptions.length,
				quads: bundle.releases.reduce((sum, release) => sum + release.quadCount, 0),
			},
			null,
			2,
		),
	);
}

async function main() {
	if (command === "inspect-model" && args.length <= 1) {
		const model = await json(resolve(root, "registry/model.json"));
		console.info(
			JSON.stringify(
				args[0]
					? model.profiles.find((profile: { key: string }) => profile.key === args[0])
					: model,
				null,
				2,
			),
		);
		return;
	}
	if (command === "validate" && args.length === 2) {
		console.info(
			JSON.stringify(
				validateModelRecord(
					await json(resolve(root, "registry/model.json")),
					args[0]!,
					await json(resolve(args[1]!)),
				),
				null,
				2,
			),
		);
		return;
	}

	if (command === "sources" && args.length === 0) {
		console.info(JSON.stringify(SchemaSources, null, 2));
		return;
	}
	if (command === "convert") {
		if (
			args.length > 1 ||
			(args[0] !== undefined &&
				args[0] !== "all" &&
				!SchemaSources.some((source) => source.key === args[0]))
		)
			throw new TypeError(
				"Convert selects the pinned standard vocabulary bundle; content adapters have a separate CLI",
			);
		await compile();
		return;
	}
	if (command === "fetch" && args.length <= 1) {
		const key = args[0];
		const manifest = SourceManifestSchema.parse(await json(resolve(root, "sources/manifest.json")));
		const selected = manifest.sources.filter(
			(source) => key === undefined || key === "all" || source.key === key,
		);
		if (
			key !== undefined &&
			selected.length === 0 &&
			!SchemaSources.some((source) => source.key === key)
		)
			throw new TypeError(`Unknown pinned schema source: ${key}`);
		for (const source of selected) {
			await fetchArtifact(source.url, source.sha256, source.file, source.bytes);
			for (const context of source.contexts)
				await fetchArtifact(context.url, context.sha256, context.file, 1_048_576);
		}
		console.info(`Restored pinned schema inputs for ${key ?? "the vocabulary bundle"}`);
		return;
	}
	if (command === "compile" && args.length === 0) {
		await compile();
		return;
	}
	if (command === "inspect" && args.length >= 1 && args.length <= 2) {
		console.info(
			JSON.stringify(
				new VocabularyRegistry(await json(bundleFile)).describe(args[0]!, args[1]),
				null,
				2,
			),
		);
		return;
	}
	if (command === "diff" && args.length === 2) {
		console.info(
			JSON.stringify(
				diffVocabularies(
					BundleSchema.parse(await json(resolve(args[0]!))),
					BundleSchema.parse(await json(resolve(args[1]!))),
				),
				null,
				2,
			),
		);
		return;
	}
	if (command === "import" && args.length !== 0) throw new TypeError("Unexpected arguments");
	if (
		command !== "import" &&
		!(command === "export" && args.length === 1) &&
		!((command === "select" || command === "select-model") && args.length === 2)
	)
		throw new TypeError(
			"Use sources | fetch [source] | compile | inspect-model [profile] | validate <profile> <record.json> | inspect <IRI|UUID> [language] | diff <before.json> <after.json> | import | select <release-UUID> <expected-version> | select-model <model-UUID> <expected-version> | export <directory>",
		);
	const {
		createSchemaDatabase,
		exportVocabularyBundle,
		importVocabularyBundle,
		installApplicationModel,
		selectApplicationModel,
		selectVocabularyRelease,
	} = await import("./targets/postgres");
	const connectionString = process.env.REZICS_SCHEMA_DATABASE_URL;
	if (!connectionString)
		throw new TypeError("Set REZICS_SCHEMA_DATABASE_URL to the intended PostgreSQL database");
	const pool = new Pool({ connectionString, max: 2 }),
		db = createSchemaDatabase(pool);
	try {
		if (command === "import") {
			const bundle = await importVocabularyBundle(db, await json(bundleFile), readArtifact);
			await db.transaction(async (tx) => {
				await installApplicationModel(tx, await json(resolve(root, "registry/model.json")));
			});
			console.info(
				`Staged ${bundle.releases.length} vocabulary releases; selection is an explicit command`,
			);
		} else if (command === "select-model") {
			const version = await db.transaction((tx) =>
				selectApplicationModel(tx, args[0]!, Number(args[1])),
			);
			console.info(`Selected application model at version ${version}`);
		} else if (command === "select") {
			const version = await db.transaction((tx) =>
				selectVocabularyRelease(tx, args[0]!, Number(args[1])),
			);
			console.info(`Selected vocabulary release at version ${version}`);
		} else {
			const { bundle, artifacts } = await exportVocabularyBundle(db);
			const { schemaModelRelease, schemaModelHead } = await import(
				"@rezics/schema/postgres/vocabulary"
			);
			const models = await db
				.select({
					key: schemaModelHead.key,
					version: schemaModelHead.version,
					model: schemaModelRelease.body,
				})
				.from(schemaModelHead)
				.innerJoin(schemaModelRelease, eq(schemaModelHead.modelId, schemaModelRelease.id));
			const destination = resolve(args[0]!);
			await writeJson(resolve(destination, "bundle.json"), bundle);
			await writeJson(resolve(destination, "models.json"), models);
			await writeJson(resolve(destination, "sources.lock.json"), {
				format: 1,
				sources: bundle.releases.map((release) => release.source),
			});
			for (const [file, bytes] of artifacts)
				await write(resolve(destination, "sources", file), bytes);
			console.info(`Exported ${bundle.releases.length} selected releases`);
		}
	} finally {
		await pool.end();
	}
}

await main();
