import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { Pool } from "pg";
import { z } from "zod";
import {
	BundleSchema,
	ProfileSchema,
	RelationRevisionSchema,
	SourceManifestSchema,
} from "@rezics/schema";
import { compileVocabularies } from "./readers/rdf";
import { digest } from "@rezics/schema/identity";
import {
	createSchemaDatabase,
	exportVocabularyBundle,
	importVocabularyBundle,
	installProfile,
	selectVocabularyRelease,
} from "./targets/postgres";
import { compileDeclarationProfiles } from "@rezics/schema/profiles";
import { diffVocabularies, VocabularyRegistry } from "@rezics/schema/registry";
import { SchemaSources } from "./sources";
import { fetchProviderSchemas, convertProviderSchemas } from "./convert";
import { convertWikibase } from "./readers/wikibase";
import { convertIiif } from "./readers/iiif";
import { convertMediaFragment } from "./readers/media-fragments";
import { importConvertedContracts } from "./targets/contracts-postgres";
import { vocabularyStorageBindings } from "@rezics/schema/bindings";

const root = fileURLToPath(new URL("../", import.meta.url));
const sourceRoot = resolve(root, "registry/sources");
const bundleFile = resolve(root, "registry/bundle.json");
const [command, ...args] = process.argv.slice(2);
const readArtifact = async (file: string) => readFile(resolve(sourceRoot, file));
const json = async (file: string) => {
	const content = await readFile(file);
	if (content.byteLength > 67_108_864) throw new RangeError("Schema artifact exceeds 64 MiB");
	return JSON.parse(content.toString("utf8"));
};

async function write(path: string, value: string | Uint8Array) {
	await mkdir(dirname(path), { recursive: true });
	const temporary = `${path}.${process.pid}.tmp`;
	await writeFile(temporary, value);
	await rename(temporary, path);
}
async function writeJson(path: string, value: unknown) {
	await write(path, `${JSON.stringify(value, null, "\t")}\n`);
}

async function fetchArtifact(url: string, hash: string, file: string, maximum: number) {
	const path = resolve(sourceRoot, file);
	try {
		if (digest(await readFile(path)) === hash) return;
	} catch (error) {
		if (!(error instanceof Error && "code" in error && error.code === "ENOENT")) throw error;
	}
	if (!url.startsWith("https://")) throw new TypeError("Pinned artifact downloads require HTTPS");
	const response = await fetch(url, {
		signal: AbortSignal.timeout(30_000),
		headers: { "User-Agent": "REZICS-schema-import/1.0" },
	});
	if (!response.ok || !response.body)
		throw new Error(`Artifact download failed: ${response.status} ${file}`);
	const parts: Uint8Array[] = [];
	let length = 0;
	for await (const part of response.body) {
		length += part.byteLength;
		if (length > maximum) throw new RangeError(`Artifact too large: ${file}`);
		parts.push(part);
	}
	const bytes = Buffer.concat(parts);
	if (digest(bytes) !== hash)
		throw new TypeError(`Upstream artifact changed: ${file}; update the manifest deliberately`);
	await write(path, bytes);
}

async function compile() {
	const manifest = SourceManifestSchema.parse(
		await json(resolve(root, "registry/sources.lock.json")),
	);
	const bundle = await compileVocabularies(manifest, readArtifact),
		registry = new VocabularyRegistry(bundle);
	const profiles = compileDeclarationProfiles(registry);
	await writeJson(bundleFile, bundle);
	await writeJson(resolve(root, "registry/profiles.json"), profiles);
	await writeJson(
		resolve(root, "registry/storage-bindings.json"),
		vocabularyStorageBindings(registry),
	);
	const terms: Record<string, Record<string, string>> = Object.create(null);
	for (const release of bundle.releases) {
		const vocabulary: Record<string, string> = Object.create(null);
		const definitions = new Set(release.definitions.map((definition) => definition.termId));
		for (const term of [...bundle.terms].sort((a, b) =>
			a.iri < b.iri ? -1 : a.iri > b.iri ? 1 : 0,
		)) {
			if (!definitions.has(term.id)) continue;
			const namespace = release.source.namespaces.find((namespace) =>
				term.iri.startsWith(namespace),
			);
			if (namespace && term.iri.length > namespace.length)
				vocabulary[term.iri.slice(namespace.length)] = term.id;
		}
		terms[release.source.key] = vocabulary;
	}
	await write(
		resolve(root, "../schema/src/generated/terms.ts"),
		`// Generated by task libraries:schema-importer:generate. Do not edit.\n/** @alpha Stable UUIDs for the complete selected vocabulary definitions. */\nexport const terms = ${JSON.stringify(terms, null, "\t")} as const;\n`,
	);
	for (const [name, schema] of [
		["bundle", BundleSchema],
		["profile", ProfileSchema],
		["relation-revision", RelationRevisionSchema],
	] as const)
		await writeJson(resolve(root, `schemas/${name}.schema.json`), z.toJSONSchema(schema));
	const coverage = {
		bundleId: bundle.id,
		digest: bundle.digest,
		terms: bundle.terms.length,
		releases: bundle.releases.map((release) => ({
			key: release.source.key,
			id: release.id,
			version: release.source.version,
			sha256: release.source.sha256,
			quads: release.quadCount,
			definitions: release.definitions.length,
			labels: release.labels.length,
			unindexedLabels: release.unindexedLabels,
			retired: release.definitions.filter((definition) => definition.status === "retired").length,
		})),
		profiles: profiles.map((profile) => ({
			key: profile.key,
			id: profile.id,
			revisionId: profile.revisionId,
		})),
	};
	await writeJson(resolve(root, "registry/coverage.json"), coverage);
	console.info(
		JSON.stringify(
			{
				bundleId: bundle.id,
				terms: bundle.terms.length,
				releases: bundle.releases.length,
				profiles: profiles.length,
				quads: bundle.releases.reduce((sum, release) => sum + release.quadCount, 0),
			},
			null,
			2,
		),
	);
}

async function main() {
	if (command === "sources" && args.length === 0) {
		console.info(JSON.stringify(SchemaSources, null, 2));
		return;
	}
	if (command === "convert") {
		const source = args[0] ?? "all";
		if (source === "wikibase" || source === "iiif") {
			if (!args[1]) throw new TypeError("Specify an input JSON file");
			const input = await json(resolve(args[1]));
			const output = source === "wikibase" ? convertWikibase(input) : convertIiif(input);
			if (args[2]) await writeJson(resolve(args[2]), output);
			else console.info(JSON.stringify(output, null, 2));
			return;
		}
		if (source === "media-fragments") {
			if (!args[1]) throw new TypeError("Specify a media URI");
			console.info(JSON.stringify(convertMediaFragment(args[1]), null, 2));
			return;
		}
		if (source === "all" || ["bangumi", "musicbrainz", "vndb", "openlibrary"].includes(source)) {
			const contracts = await convertProviderSchemas(source);
			for (const key of [...new Set(contracts.map((contract) => contract.source))])
				await writeJson(
					resolve(root, `generated/${key}/contracts.json`),
					contracts.filter((contract) => contract.source === key),
				);
			await writeJson(resolve(root, `generated/${source}-coverage.json`), {
				sources: [...new Set(contracts.map((contract) => contract.source))],
				contracts: contracts.length,
				fields: contracts.reduce((n, c) => n + c.fields.length, 0),
			});
			console.info(
				`Converted ${contracts.length} contracts and ${contracts.reduce((n, c) => n + c.fields.length, 0)} declarations`,
			);
			if (source === "all") await compile();
			return;
		}
		if (SchemaSources.some((entry) => entry.key === source && entry.family === "vocabulary")) {
			await compile();
			return;
		}
		throw new TypeError(`Unknown schema source: ${source}`);
	}
	if (command === "fetch" && args.length <= 1) {
		const key = args[0];
		const manifest = SourceManifestSchema.parse(
			await json(resolve(root, "registry/sources.lock.json")),
		);
		const selected = manifest.sources.filter(
			(source) => key === undefined || key === "all" || source.key === key,
		);
		if (
			key !== undefined &&
			selected.length === 0 &&
			!SchemaSources.some((source) => source.key === key && source.family === "provider")
		)
			throw new TypeError(`Unknown pinned schema source: ${key}`);
		for (const source of selected) {
			await fetchArtifact(source.url, source.sha256, source.file, source.bytes);
			for (const context of source.contexts)
				await fetchArtifact(context.url, context.sha256, context.file, 1_048_576);
		}
		if (key === "all" || (key !== undefined && selected.length === 0))
			await fetchProviderSchemas(key);
		console.info(`Restored pinned schema inputs for ${key ?? "the vocabulary bundle"}`);
		return;
	}
	if (command === "compile" && args.length === 0) {
		await compile();
		return;
	}
	if (command === "inspect" && args.length >= 1 && args.length <= 2) {
		console.info(
			JSON.stringify(
				new VocabularyRegistry(await json(bundleFile)).describe(args[0]!, args[1]),
				null,
				2,
			),
		);
		return;
	}
	if (command === "diff" && args.length === 2) {
		console.info(
			JSON.stringify(
				diffVocabularies(
					BundleSchema.parse(await json(resolve(args[0]!))),
					BundleSchema.parse(await json(resolve(args[1]!))),
				),
				null,
				2,
			),
		);
		return;
	}
	if (command === "import" && args.length !== 0) throw new TypeError("Unexpected arguments");
	if (
		command !== "import" &&
		!(command === "export" && args.length === 1) &&
		!(command === "select" && args.length === 2)
	)
		throw new TypeError(
			"Use fetch | compile | inspect <IRI|UUID> [language] | diff <before.json> <after.json> | import | select <release-UUID> <expected-version> | export <directory>",
		);
	const connectionString = process.env.REZICS_SCHEMA_DATABASE_URL;
	if (!connectionString)
		throw new TypeError("Set REZICS_SCHEMA_DATABASE_URL to the intended PostgreSQL database");
	const pool = new Pool({ connectionString, max: 2 }),
		db = createSchemaDatabase(pool);
	try {
		if (command === "import") {
			const bundle = await importVocabularyBundle(db, await json(bundleFile), readArtifact);
			await importConvertedContracts(db, await convertProviderSchemas("all"));
			await db.transaction(async (tx) => {
				for (const profile of compileDeclarationProfiles(new VocabularyRegistry(bundle)))
					await installProfile(tx, profile);
			});
			console.info(
				`Staged ${bundle.releases.length} vocabulary releases; selection is an explicit command`,
			);
		} else if (command === "select") {
			const version = await db.transaction((tx) =>
				selectVocabularyRelease(tx, args[0]!, Number(args[1])),
			);
			console.info(`Selected vocabulary release at version ${version}`);
		} else {
			const { bundle, artifacts } = await exportVocabularyBundle(db);
			const destination = resolve(args[0]!);
			await writeJson(resolve(destination, "bundle.json"), bundle);
			await writeJson(resolve(destination, "sources.lock.json"), {
				format: 1,
				sources: bundle.releases.map((release) => release.source),
			});
			for (const [file, bytes] of artifacts)
				await write(resolve(destination, "sources", file), bytes);
			console.info(`Exported ${bundle.releases.length} selected releases`);
		}
	} finally {
		await pool.end();
	}
}

await main();
