nodeLinker: node-modules

npmPreapprovedPackages:
    - native-i18n

packageExtensions:
    "@astrojs/language-server@2.16.13":
        dependencies:
            typescript: "6.0.3"

yarnPath: .yarn/releases/yarn-4.17.1.cjs
