packages:
  - package/*

ignoredBuiltDependencies:
  - bcrypt

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@supabase/supabase-js'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - msw

preferFrozenLockfile: true
