-- Canonicalize the persisted BCP 47 spelling before the new constraints take effect.
ALTER TABLE "email_outbox" DROP CONSTRAINT "email_outbox_intent_check";
ALTER TABLE "profile_preference" DROP CONSTRAINT "profile_preference_interface_locale_check";
UPDATE "email_outbox" SET "locale" = 'zh' WHERE "locale" = 'zh-hant';
UPDATE "profile_preference" SET "interface_locale" = 'zh-Hant' WHERE "interface_locale" = 'zh-hant';

-- Modify "email_outbox" table
ALTER TABLE "email_outbox" ADD CONSTRAINT "email_outbox_intent_check" CHECK (((kind = 'notification'::email_outbox_kind) AND (notification_id IS NOT NULL) AND (recipient_email IS NULL) AND (locale IS NULL) AND (action_url IS NULL)) OR ((kind = ANY (ARRAY['verify_email'::email_outbox_kind, 'reset_password'::email_outbox_kind])) AND (notification_id IS NULL) AND (((status = ANY (ARRAY['pending'::email_outbox_status, 'processing'::email_outbox_status])) AND (NULLIF(btrim(recipient_email), ''::text) IS NOT NULL) AND (NULLIF(btrim(action_url), ''::text) IS NOT NULL) AND (locale = ANY (ARRAY['zh'::text, 'en'::text, 'ja'::text, 'ko'::text, 'de'::text, 'fr'::text, 'es'::text]))) OR ((status = ANY (ARRAY['accepted'::email_outbox_status, 'failed'::email_outbox_status])) AND (recipient_email IS NULL) AND (locale IS NULL) AND (action_url IS NULL)))));
-- Modify "profile_preference" table
ALTER TABLE "profile_preference" ADD CONSTRAINT "profile_preference_interface_locale_check" CHECK (interface_locale = ANY (ARRAY['en'::text, 'zh-Hant'::text, 'zh-Hans'::text, 'ja'::text, 'ko'::text, 'de'::text, 'fr'::text, 'es'::text])), DROP CONSTRAINT "profile_preference_languages_check", ADD CONSTRAINT "profile_preference_languages_check" CHECK ((cardinality(preferred_languages) > 0) AND (preferred_languages <@ ARRAY['zh'::text, 'en'::text, 'ja'::text, 'ko'::text, 'de'::text, 'fr'::text, 'es'::text]) AND (cardinality(array_positions(preferred_languages, 'zh'::text)) <= 1) AND (cardinality(array_positions(preferred_languages, 'en'::text)) <= 1) AND (cardinality(array_positions(preferred_languages, 'ja'::text)) <= 1) AND (cardinality(array_positions(preferred_languages, 'ko'::text)) <= 1) AND (cardinality(array_positions(preferred_languages, 'de'::text)) <= 1) AND (cardinality(array_positions(preferred_languages, 'fr'::text)) <= 1) AND (cardinality(array_positions(preferred_languages, 'es'::text)) <= 1)), ADD CONSTRAINT "profile_preference_chinese_content_display_check" CHECK (chinese_content_display = ANY (ARRAY['original'::text, 'hant'::text, 'hans'::text])), ALTER COLUMN "interface_locale" SET DEFAULT 'zh-Hant', ADD COLUMN "chinese_content_display" text NOT NULL DEFAULT 'original';
-- Modify "realm_rule_acceptance" table
ALTER TABLE "realm_rule_acceptance" DROP CONSTRAINT "realm_rule_acceptance_language_check", ADD CONSTRAINT "realm_rule_acceptance_language_check" CHECK ((language IS NULL) OR (language = ANY (ARRAY['zh'::text, 'en'::text, 'ja'::text, 'ko'::text, 'de'::text, 'fr'::text, 'es'::text])));
-- Modify "unit_alias" table
ALTER TABLE "unit_alias" DROP CONSTRAINT "unit_alias_language_check", ADD CONSTRAINT "unit_alias_language_check" CHECK ((language IS NULL) OR (language = ANY (ARRAY['zh'::text, 'en'::text, 'ja'::text, 'ko'::text, 'de'::text, 'fr'::text, 'es'::text])));
-- Modify "unit_localization" table
ALTER TABLE "unit_localization" DROP CONSTRAINT "unit_localization_language_check", ADD CONSTRAINT "unit_localization_language_check" CHECK (language = ANY (ARRAY['zh'::text, 'en'::text, 'ja'::text, 'ko'::text, 'de'::text, 'fr'::text, 'es'::text]));
-- Modify "unit_localization_content_metric" table
ALTER TABLE "unit_localization_content_metric" DROP CONSTRAINT "unit_localization_content_metric_language_check", ADD CONSTRAINT "unit_localization_content_metric_language_check" CHECK (language = ANY (ARRAY['zh'::text, 'en'::text, 'ja'::text, 'ko'::text, 'de'::text, 'fr'::text, 'es'::text]));
-- Modify "unit_revision_slot" table
ALTER TABLE "unit_revision_slot" DROP CONSTRAINT "unit_revision_slot_key_shape_check", ADD CONSTRAINT "unit_revision_slot_key_shape_check" CHECK (((role = 'localization'::unit_revision_slot_role) AND (slot_key = ANY (ARRAY['zh'::text, 'en'::text, 'ja'::text, 'ko'::text, 'de'::text, 'fr'::text, 'es'::text]))) OR ((role <> 'localization'::unit_revision_slot_role) AND (slot_key = ''::text)));
-- Modify "users" table
ALTER TABLE "users" DROP CONSTRAINT "users_registration_content_language_check", ADD CONSTRAINT "users_registration_content_language_check" CHECK (registration_content_language = ANY (ARRAY['zh'::text, 'en'::text, 'ja'::text, 'ko'::text, 'de'::text, 'fr'::text, 'es'::text]));
