/** Authored write ownership. Storage-only entries do not advertise a completed product API. */
export const modelWriters = [
	{
		key: "catalog.names",
		kind: "command",
		module: "services/main/src/services/catalog/names.ts",
		entry: "addCatalogName",
		tablePattern: "^(publishing|music|program|software|entity)_named_form$",
		representations: ["localized-value"],
	},
	{
		key: "catalog.relations",
		kind: "command",
		module: "services/main/src/services/catalog/storage.ts",
		entry: "createCatalogRelation",
		tablePattern: "^(publishing|music|program|software)_relation_participant$",
		representations: ["native-relation"],
	},
	{
		key: "publishing.structure",
		kind: "command",
		module: "services/main/src/services/catalog/publishing.ts",
		entry: "updatePublishingStructure",
		tablePattern: "^publishing_(publication|text_version)$",
		representations: ["column"],
	},
	{
		key: "media.representations",
		kind: "storage-contract",
		module: "libraries/schema/model/storage/media-index.ts",
		entry: "storage",
		tablePattern: "^media_representation$",
		representations: ["column"],
	},
	{
		key: "messaging.messages",
		kind: "route",
		module: "services/main/src/services/api/messages/index.ts",
		entry: "default",
		tablePattern: "^message$",
		representations: ["column"],
	},
	{
		key: "semantic.descriptions",
		kind: "command",
		module: "services/main/src/services/catalog/semantic-descriptions.ts",
		entry: "writeSemanticDescription",
		tablePattern: "^description_statement$",
		representations: ["semantic-relation"],
	},
	{
		key: "semantic.relations",
		kind: "command",
		module: "libraries/schema/src/persistence/relations.ts",
		entry: "putProfiledRelationRevision",
		tablePattern: "^schema_relation_revision$",
		representations: ["semantic-relation"],
	},
] as const;
