export const DEFAULT_MAX_DEPTH = 5;
export const DEFAULT_VISUAL_MAX_DEPTH = 4;

export const THREAD_INDENT_PX = 32;
export const AVATAR_SIZE_PX = 32;
export const AVATAR_CENTER_PX = AVATAR_SIZE_PX / 2;

export const RAIL_STROKE_PX = 2;
export const RAIL_HITBOX_PX = 12;
export const ROW_TOP_PADDING_PX = 4;
export const RAIL_GAP_PX = 4;
export const RAIL_TOP_PX =
  ROW_TOP_PADDING_PX + AVATAR_SIZE_PX + RAIL_GAP_PX;
export const AVATAR_CENTER_Y_PX = ROW_TOP_PADDING_PX + AVATAR_CENTER_PX;
export const RAIL_CAP_RADIUS_PX = RAIL_STROKE_PX;
export const TERMINAL_RAIL_HEIGHT_PX =
  AVATAR_CENTER_Y_PX - RAIL_STROKE_PX - RAIL_CAP_RADIUS_PX;
export const BRANCH_RADIUS_PX = 8;
export const TOGGLE_TOP_PX = RAIL_TOP_PX + 8;
