// Generated by scripts/generate-oauth-schema.ts from Better Auth/provider/MCP/CIMD 1.7.3. Do not edit.
// Native UUID references reuse existing accounts/sessions; assertion replay IDs retain the provider's opaque digest.
import { sql } from "drizzle-orm";
import { boolean, foreignKey, index, integer, jsonb, text, timestamp, type PgTableExtraConfigValue, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import { pgTable } from "./base";
import { sessions, users } from "./auth";

/** Provider-owned jwks protocol records; domain admission and disclosure are separate. @internal */
export const oauthJwks = pgTable("oauth_jwks", {
		id: uuid().default(sql`uuidv7()`).primaryKey(),
		publicKey: text().notNull(),
		privateKey: text().notNull(),
		createdAt: timestamp({ withTimezone: true, precision: 3, mode: "date" }).notNull(),
		expiresAt: timestamp({ withTimezone: true, precision: 3, mode: "date" }),
		alg: text(),
		crv: text(),
	}, (table): PgTableExtraConfigValue[] => [
		index("jwks_expiry_idx").on(table.expiresAt, table.id),
	],
);

/** Provider-owned oauthClient protocol records; domain admission and disclosure are separate. @internal */
export const oauthClients = pgTable("oauth_client", {
		id: uuid().default(sql`uuidv7()`).primaryKey(),
		clientId: text().notNull(),
		clientSecret: text(),
		clientDiscoveryId: text(),
		disabled: boolean(),
		skipConsent: boolean(),
		enableEndSession: boolean(),
		subjectType: text(),
		scopes: text().array(),
		clientCredentialsScopes: text().array(),
		userId: uuid(),
		createdAt: timestamp({ withTimezone: true, precision: 3, mode: "date" }),
		updatedAt: timestamp({ withTimezone: true, precision: 3, mode: "date" }),
		name: text(),
		uri: text(),
		icon: text(),
		contacts: text().array(),
		tos: text(),
		policy: text(),
		softwareId: text(),
		softwareVersion: text(),
		softwareStatement: text(),
		redirectUris: text().array().notNull(),
		postLogoutRedirectUris: text().array(),
		backchannelLogoutUri: text(),
		backchannelLogoutSessionRequired: boolean(),
		tokenEndpointAuthMethod: text(),
		applicationType: text(),
		jwks: text(),
		jwksUri: text(),
		grantTypes: text().array(),
		responseTypes: text().array(),
		requirePKCE: boolean(),
		dpopBoundAccessTokens: boolean(),
		referenceId: text(),
		metadata: jsonb().$type<unknown>(),
	}, (table): PgTableExtraConfigValue[] => [
		uniqueIndex("oauth_client_client_id_key").on(table.clientId),
		index("oauth_client_user_id_idx").on(table.userId),
		foreignKey({ name: "oauth_client_user_id_user_id_fk", columns: [table.userId], foreignColumns: [users.id] }),
	],
);

/** Provider-owned oauthResource protocol records; domain admission and disclosure are separate. @internal */
export const oauthResources = pgTable("oauth_resource", {
		id: uuid().default(sql`uuidv7()`).primaryKey(),
		identifier: text().notNull(),
		name: text().notNull(),
		accessTokenTtl: integer(),
		refreshTokenTtl: integer(),
		signingAlgorithm: text(),
		signingKeyId: text(),
		allowedScopes: text().array(),
		customClaims: jsonb().$type<unknown>(),
		dpopBoundAccessTokensRequired: boolean(),
		disabled: boolean(),
		createdAt: timestamp({ withTimezone: true, precision: 3, mode: "date" }),
		updatedAt: timestamp({ withTimezone: true, precision: 3, mode: "date" }),
		policyVersion: integer(),
		metadata: jsonb().$type<unknown>(),
	}, (table): PgTableExtraConfigValue[] => [
		uniqueIndex("oauth_resource_identifier_key").on(table.identifier),
	],
);

/** Provider-owned oauthClientResource protocol records; domain admission and disclosure are separate. @internal */
export const oauthClientResources = pgTable("oauth_client_resource", {
		id: uuid().default(sql`uuidv7()`).primaryKey(),
		clientId: text().notNull(),
		resourceId: text().notNull(),
		metadata: jsonb().$type<unknown>(),
		createdAt: timestamp({ withTimezone: true, precision: 3, mode: "date" }),
	}, (table): PgTableExtraConfigValue[] => [
		index("oauth_client_resource_client_id_idx").on(table.clientId),
		foreignKey({ name: "oauth_client_resource_client_id_oauth_client_client_id_fk", columns: [table.clientId], foreignColumns: [oauthClients.clientId] }).onDelete("cascade"),
		index("oauth_client_resource_resource_id_idx").on(table.resourceId),
		foreignKey({ name: "oauth_client_resource_resource_id_oauth_resource_identifier_fk", columns: [table.resourceId], foreignColumns: [oauthResources.identifier] }).onDelete("cascade"),
		uniqueIndex("oauth_client_resource_compound_0_key").on(table.clientId, table.resourceId),
	],
);

/** Provider-owned oauthRefreshToken protocol records; domain admission and disclosure are separate. @internal */
export const oauthRefreshTokens = pgTable("oauth_refresh_token", {
		id: uuid().default(sql`uuidv7()`).primaryKey(),
		token: text().notNull(),
		clientId: text().notNull(),
		sessionId: uuid(),
		userId: uuid().notNull(),
		referenceId: text(),
		authorizationCodeId: text(),
		resources: text().array(),
		requestedUserInfoClaims: text().array(),
		expiresAt: timestamp({ withTimezone: true, precision: 3, mode: "date" }).notNull(),
		createdAt: timestamp({ withTimezone: true, precision: 3, mode: "date" }).notNull(),
		revoked: timestamp({ withTimezone: true, precision: 3, mode: "date" }),
		rotatedAt: timestamp({ withTimezone: true, precision: 3, mode: "date" }),
		rotationReplayResponse: text(),
		rotationReplayExpiresAt: timestamp({ withTimezone: true, precision: 3, mode: "date" }),
		authTime: timestamp({ withTimezone: true, precision: 3, mode: "date" }),
		confirmation: jsonb().$type<unknown>(),
		scopes: text().array().notNull(),
	}, (table): PgTableExtraConfigValue[] => [
		uniqueIndex("oauth_refresh_token_token_key").on(table.token),
		index("oauth_refresh_token_client_id_idx").on(table.clientId),
		foreignKey({ name: "oauth_refresh_token_client_id_oauth_client_client_id_fk", columns: [table.clientId], foreignColumns: [oauthClients.clientId] }),
		index("oauth_refresh_token_session_id_idx").on(table.sessionId),
		foreignKey({ name: "oauth_refresh_token_session_id_session_id_fk", columns: [table.sessionId], foreignColumns: [sessions.id] }).onDelete("set null"),
		index("oauth_refresh_token_user_id_idx").on(table.userId),
		foreignKey({ name: "oauth_refresh_token_user_id_user_id_fk", columns: [table.userId], foreignColumns: [users.id] }),
		index("oauth_refresh_token_authorization_code_id_idx").on(table.authorizationCodeId),
		index("oauth_refresh_token_expiry_idx").on(table.expiresAt, table.id),
	],
);

/** Provider-owned oauthAccessToken protocol records; domain admission and disclosure are separate. @internal */
export const oauthAccessTokens = pgTable("oauth_access_token", {
		id: uuid().default(sql`uuidv7()`).primaryKey(),
		token: text().notNull(),
		clientId: text().notNull(),
		sessionId: uuid(),
		userId: uuid(),
		referenceId: text(),
		authorizationCodeId: text(),
		resources: text().array(),
		requestedUserInfoClaims: text().array(),
		refreshId: uuid(),
		expiresAt: timestamp({ withTimezone: true, precision: 3, mode: "date" }).notNull(),
		createdAt: timestamp({ withTimezone: true, precision: 3, mode: "date" }).notNull(),
		revoked: timestamp({ withTimezone: true, precision: 3, mode: "date" }),
		confirmation: jsonb().$type<unknown>(),
		scopes: text().array().notNull(),
	}, (table): PgTableExtraConfigValue[] => [
		uniqueIndex("oauth_access_token_token_key").on(table.token),
		index("oauth_access_token_client_id_idx").on(table.clientId),
		foreignKey({ name: "oauth_access_token_client_id_oauth_client_client_id_fk", columns: [table.clientId], foreignColumns: [oauthClients.clientId] }),
		index("oauth_access_token_session_id_idx").on(table.sessionId),
		foreignKey({ name: "oauth_access_token_session_id_session_id_fk", columns: [table.sessionId], foreignColumns: [sessions.id] }).onDelete("set null"),
		index("oauth_access_token_user_id_idx").on(table.userId),
		foreignKey({ name: "oauth_access_token_user_id_user_id_fk", columns: [table.userId], foreignColumns: [users.id] }),
		index("oauth_access_token_authorization_code_id_idx").on(table.authorizationCodeId),
		index("oauth_access_token_refresh_id_idx").on(table.refreshId),
		foreignKey({ name: "oauth_access_token_refresh_id_oauth_refresh_token_id_fk", columns: [table.refreshId], foreignColumns: [oauthRefreshTokens.id] }),
		index("oauth_access_token_expiry_idx").on(table.expiresAt, table.id),
	],
);

/** Provider-owned oauthConsent protocol records; domain admission and disclosure are separate. @internal */
export const oauthConsents = pgTable("oauth_consent", {
		id: uuid().default(sql`uuidv7()`).primaryKey(),
		clientId: text().notNull(),
		userId: uuid(),
		referenceId: text(),
		resources: text().array(),
		requestedUserInfoClaims: text().array(),
		scopes: text().array().notNull(),
		createdAt: timestamp({ withTimezone: true, precision: 3, mode: "date" }).notNull(),
		updatedAt: timestamp({ withTimezone: true, precision: 3, mode: "date" }).notNull(),
	}, (table): PgTableExtraConfigValue[] => [
		index("oauth_consent_client_id_idx").on(table.clientId),
		foreignKey({ name: "oauth_consent_client_id_oauth_client_client_id_fk", columns: [table.clientId], foreignColumns: [oauthClients.clientId] }),
		index("oauth_consent_user_id_idx").on(table.userId),
		foreignKey({ name: "oauth_consent_user_id_user_id_fk", columns: [table.userId], foreignColumns: [users.id] }),
	],
);

/** Provider-owned oauthClientAssertion protocol records; domain admission and disclosure are separate. @internal */
export const oauthClientAssertions = pgTable("oauth_client_assertion", {
		id: text().primaryKey(),
		expiresAt: timestamp({ withTimezone: true, precision: 3, mode: "date" }).notNull(),
	}, (table): PgTableExtraConfigValue[] => [
		index("oauth_client_assertion_expiry_idx").on(table.expiresAt, table.id),
	],
);

/** Model aliases for the existing plural Better Auth adapter boundary. @internal */
export const OAuthProtocolSchema = {
	jwkss: oauthJwks,
	oauthClients: oauthClients,
	oauthResources: oauthResources,
	oauthClientResources: oauthClientResources,
	oauthRefreshTokens: oauthRefreshTokens,
	oauthAccessTokens: oauthAccessTokens,
	oauthConsents: oauthConsents,
	oauthClientAssertions: oauthClientAssertions,
};
