import { sql } from "drizzle-orm";
import {
	type AnyPgColumn,
	check,
	customType,
	integer,
	jsonb,
	timestamp,
	uuid,
} from "drizzle-orm/pg-core";

import { FractionalPositionStorageMaximumBytes } from "../../ordering/contract";

/**
 * A case-sensitive fractional index for a mutable ordered sequence.
 * Values are generated by the ordering service and compared bytewise.
 */
export const fractionalIndexPosition = customType<{ data: string }>({
	dataType: () => 'text collate "C"',
});

/**
 * Protects indexed writes and index rebuilds; fractional-key syntax remains an
 * application concern because malformed-but-bounded text cannot damage storage.
 */
export const createFractionalIndexPositionByteLengthConstraint = (
	name: string,
	column: AnyPgColumn,
) => check(name, sql`octet_length(${column}) <= ${FractionalPositionStorageMaximumBytes}`);

/** A zero-based dense position for a sequence replaced atomically. */
export const ordinalPosition = () => integer();

/** A zero-based observed position in a rendered result. */
export const displayPosition = () => integer();

export const createUuidv7PrimaryKey = () => uuid().default(sql`uuidv7()`).primaryKey();

/** Every persisted instant is UTC-aware and millisecond precise. */
export const createTimestampMsColumn = () => timestamp({ withTimezone: true, precision: 3 });

export const createCreatedAtColumn = () => createTimestampMsColumn().defaultNow().notNull();

export const createUpdatedAtColumn = () =>
	createTimestampMsColumn()
		.defaultNow()
		.$onUpdate(() => new Date())
		.notNull();

/**
 * Persistence deliberately does not know the domain document shape.
 * Callers must validate unknown values with the owning product schema.
 */
export const createJsonDocumentColumn = () => jsonb().$type<unknown>();

export const createJsonObjectColumn = <
	T extends Record<string, unknown> = Record<string, unknown>,
>() => jsonb().$type<T>();

export const createJsonObjectConstraint = (name: string, column: AnyPgColumn) =>
	check(name, sql`${column} is null or jsonb_typeof(${column}) = 'object'`);
