/** Bounded schema registry for logical-ID input triggers; concrete nullable FKs remain the authority. */
export const UnitReferenceConsumers = [
	{
		table: "collection_item",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "content_report",
		id: "target_unit_id",
		prefix: "target_unit",
		optional: false,
	},
	{
		table: "content_review_case",
		id: "target_unit_id",
		prefix: "target_unit",
		optional: false,
	},
	{
		table: "content_structure",
		id: "owner_unit_id",
		prefix: "owner_unit",
		optional: false,
	},
	{
		table: "content_structure_node",
		id: "content_unit_id",
		prefix: "content_unit",
		optional: false,
	},
	{
		table: "content_structure_node",
		id: "target_unit_id",
		prefix: "target_unit",
		optional: true,
	},
	{
		table: "credit_attribution",
		id: "source_unit_id",
		prefix: "source_unit",
		optional: false,
	},
	{
		table: "custom_theme_revision",
		id: "approved_host_unit_id",
		prefix: "approved_host_unit",
		optional: true,
	},
	{
		table: "governance_decision",
		id: "authority_unit_id",
		prefix: "authority_unit",
		optional: true,
	},
	{
		table: "governance_decision",
		id: "target_unit_id",
		prefix: "target_unit",
		optional: true,
	},
	{
		table: "notification",
		id: "subject_unit_id",
		prefix: "subject_unit",
		optional: true,
	},
	{
		table: "poll_option",
		id: "target_unit_id",
		prefix: "target_unit",
		optional: true,
	},
	{
		table: "post",
		id: "subject_unit_id",
		prefix: "subject_unit",
		optional: true,
	},
	{
		table: "profile_resource_participation",
		id: "resource_unit_id",
		prefix: "resource_unit",
		optional: false,
	},
	{
		table: "realm_pin",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "realm_tag_judgment",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "realm_tag_judgment_stat",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "realm_unit",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "realm_unit_status_event",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "recommendation_unit_signal_hourly",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "score",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "score_stat",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "studio_auth_editor_candidate",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "studio_realm_editor_candidate",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "subject_association",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "unit_access_grant",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "unit_access_invitation",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "unit_access_restriction",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "unit_alias",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "unit_association_proposal",
		id: "source_unit_id",
		prefix: "source_unit",
		optional: false,
	},
	{
		table: "unit_association_proposal",
		id: "target_unit_id",
		prefix: "target_unit",
		optional: false,
	},
	{
		table: "unit_best_score",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "unit_content_language_search",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "unit_content_language_support",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "unit_custom_theme_installation",
		id: "host_unit_id",
		prefix: "host_unit",
		optional: false,
	},
	{
		table: "unit_dock",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "unit_effective_tag",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "unit_engagement_stat",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "unit_expression_assertion",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "unit_external_link",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},

	{
		table: "unit_follow_stat",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "unit_license_grant",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "unit_localization",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "unit_merge_graph_lock",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "unit_merge_reconciliation_item",
		id: "source_unit_id",
		prefix: "source_unit",
		optional: false,
	},
	{
		table: "unit_merge_reconciliation_item",
		id: "target_unit_id",
		prefix: "target_unit",
		optional: false,
	},
	{
		table: "unit_merge_redirect",
		id: "source_unit_id",
		prefix: "source_unit",
		optional: false,
	},
	{
		table: "unit_merge_redirect",
		id: "target_unit_id",
		prefix: "target_unit",
		optional: false,
	},
	{
		table: "unit_merge_request",
		id: "source_unit_id",
		prefix: "source_unit",
		optional: false,
	},
	{
		table: "unit_merge_request",
		id: "target_unit_id",
		prefix: "target_unit",
		optional: false,
	},
	{
		table: "unit_ownership",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "unit_presentation_document",
		id: "host_unit_id",
		prefix: "host_unit",
		optional: false,
	},
	{
		table: "unit_progress",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "unit_progress_entry",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "unit_reaction",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "unit_reaction_global_stat",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "unit_reaction_stat",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "unit_reference_curation_head",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "unit_revision",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "unit_revision_head",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "unit_search_document",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "unit_share",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "unit_slug_address",
		id: "scope_unit_id",
		prefix: "scope_unit",
		optional: true,
	},
	{
		table: "unit_slug_address",
		id: "target_unit_id",
		prefix: "target_unit",
		optional: false,
	},
	{
		table: "unit_status_event",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "unit_tag",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "unit_tag_judgment",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
	{
		table: "unit_tag_path_application",
		id: "unit_id",
		prefix: "unit",
		optional: false,
	},
] as const;
