import { describe, expect, test } from "bun:test";
import * as publicSchema from ".";
import * as schema from "./schema";

const expectedSchemaExports = [
  "AccountEnforcement",
  "AccountEnforcementKind",
  "AccountEnforcementState",
  "AiDisclosureMode",
  "ApiToken",
  "Book",
  "CatalogEntryKind",
  "Comment",
  "CommentPromotion",
  "ContentRating",
  "ContentStructure",
  "ContentStructureAnchor",
  "ContentStructureNode",
  "ContentTranslation",
  "ContentTranslationStatus",
  "CreditAttribution",
  "CreditAttributionEvidence",
  "EchoKV",
  "EmailVerificationContract",
  "EmailVerificationContractStatus",
  "Entity",
  "Feedback",
  "FeedbackType",
  "Game",
  "GameSystemRequirement",
  "GovernanceGrantState",
  "HistoryOutbox",
  "Jwks",
  "JwtService",
  "Link",
  "Media",
  "ModerationAction",
  "ModerationActionKind",
  "ModerationActorKind",
  "ModerationAuthority",
  "ModerationCase",
  "ModerationCaseState",
  "ModerationScope",
  "ModerationStatus",
  "ModerationTargetKind",
  "PinKind",
  "Poll",
  "PollOption",
  "PollResultVisibility",
  "PollVote",
  "PollVoteMode",
  "Post",
  "PostKind",
  "PostPollReference",
  "Realm",
  "RealmCapabilityGrant",
  "RealmMember",
  "RealmMemberState",
  "RealmRuleAcknowledgement",
  "RealmTagApplication",
  "RealmTagApplicationVote",
  "RealmTagContext",
  "ScoreAggregate",
  "ScoreEntry",
  "ScoreRealmField",
  "Series",
  "SeriesContentIndex",
  "Shelf",
  "ShelfUnit",
  "ShelfUnitRelation",
  "SlugScope",
  "SourceSite",
  "StaffAuditLog",
  "StaffGrant",
  "SubjectAttribution",
  "Subscription",
  "TagVote",
  "Unit",
  "UnitAlias",
  "UnitAliasKind",
  "UnitAliasStatus",
  "UnitAliasVote",
  "UnitCollaborator",
  "UnitExternalRef",
  "UnitFieldLock",
  "UnitHistoryClock",
  "UnitRealm",
  "UnitStatus",
  "UnitSupportLanguage",
  "UnitTag",
  "UnitTranslation",
  "UnitType",
  "UnitVisibility",
  "User",
  "UserBlock",
  "UserContentNodeProgress",
  "UserTagApplication",
  "UserUnitCollection",
  "UserUnitProgress",
  "UserUnitProgressStatus",
  "Zone",
  "ltree",
  "post_path_label_seq",
] as const;

describe("server Drizzle schema exports", () => {
  test("thin schema aggregator exports every table, enum, sequence, and custom type", () => {
    for (const exportName of expectedSchemaExports) {
      expect(schema).toHaveProperty(exportName);
    }
  });

  test("public schema index keeps runtime aliases outside the Drizzle Kit entry", () => {
    expect(publicSchema.historyOutbox).toBe(schema.HistoryOutbox);
    expect("historyOutbox" in schema).toBe(false);
  });
});
