import { mkdir, readdir, writeFile } from "node:fs/promises";
import { relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { is } from "drizzle-orm";
import { PgTable, getTableConfig } from "drizzle-orm/pg-core";
import { generateDrizzleJson } from "drizzle-kit/api-postgres";
import * as schema from "../src/postgres/index";

const root = fileURLToPath(new URL("../", import.meta.url));
const schemaRoot = resolve(root, "src/postgres");
async function files(directory: string): Promise<string[]> {
	const entries = await readdir(directory, { withFileTypes: true });
	return (
		await Promise.all(
			entries.map((entry) =>
				entry.isDirectory()
					? files(resolve(directory, entry.name))
					: Promise.resolve(
							entry.name.endsWith(".ts") &&
								!entry.name.endsWith(".test.ts") &&
								entry.name !== "index.ts"
								? [resolve(directory, entry.name)]
								: [],
						),
			),
		)
	).flat();
}
function collect(value: unknown, result: Map<string, PgTable>, seen = new Set<unknown>()) {
	if (is(value, PgTable)) {
		result.set(getTableConfig(value).name, value);
		return;
	}
	if (value === null || typeof value !== "object" || seen.has(value)) return;
	seen.add(value);
	for (const member of Object.values(value)) collect(member, result, seen);
}
const production = new Map<string, PgTable>();
collect(schema, production);
const owners = new Map<string, string>();
for (const file of await files(schemaRoot)) {
	const exported = new Map<string, PgTable>();
	collect(await import(pathToFileURL(file).href), exported);
	for (const [name, table] of exported) {
		if (production.get(name) !== table)
			throw new Error(`Table ${name} is not exported by the production schema`);
		const existing = owners.get(name),
			path = relative(root, file);
		if (!existing || path.length < existing.length) owners.set(name, path);
	}
}
const snapshot = await generateDrizzleJson(schema);
const tables = [...production.keys()].sort().map((name) => {
	const definition = snapshot.ddl.filter((entry) =>
		entry.entityType === "tables" ? entry.name === name : "table" in entry && entry.table === name,
	);
	return {
		name,
		schema: "public",
		module: owners.get(name),
		domain: owners.get(name)?.split("/")[2],
		definition,
	};
});
const directory = resolve(root, "docs/tables");
await mkdir(directory, { recursive: true });
await writeFile(
	resolve(root, "schema-catalogue.generated.json"),
	JSON.stringify(
		{ format: "rezics.schema-catalogue.v2", tableCount: tables.length, tables },
		null,
		"\t",
	) + "\n",
);
const domains = [...new Set(tables.map((table) => table.domain))].sort();
const summary = [
	"# Complete Drizzle table catalogue",
	"",
	"Generated by `task libraries:schema:catalogue`; do not edit.",
	"",
	`The production model contains **${tables.length} physical table declarations**. Partition children and indexes are not counted as tables.`,
	"",
	"| Domain | Tables |",
	"| --- | ---: |",
	...domains.map(
		(domain) =>
			`| [${domain}](${domain}.md) | ${tables.filter((table) => table.domain === domain).length} |`,
	),
];
await writeFile(resolve(directory, "README.md"), summary.join("\n") + "\n");
for (const domain of domains) {
	const output = [
		`# ${domain} tables`,
		"",
		"Generated from the production Drizzle declarations. SQL routines remain owned by the main deployment's canonical PostgreSQL manifest.",
		"",
	];
	for (const table of tables.filter((table) => table.domain === domain)) {
		output.push(
			`## ${table.name}`,
			"",
			`Declaration: [${table.module}](../../${table.module})`,
			"",
			"| Column | Type | Nullable |",
			"| --- | --- | --- |",
		);
		for (const entry of table.definition)
			if (entry.entityType === "columns")
				output.push(
					`| ${entry.name} | ${String(entry.type).replaceAll("|", "\\|")} | ${entry.notNull ? "no" : "yes"} |`,
				);
		output.push(
			"",
			"```json",
			JSON.stringify(
				table.definition.filter(
					(entry) => entry.entityType !== "columns" && entry.entityType !== "tables",
				),
				null,
				2,
			),
			"```",
			"",
		);
	}
	await writeFile(resolve(directory, `${domain}.md`), output.join("\n"));
}
console.info(`Generated ${tables.length} tables across ${domains.length} domain modules`);
