// @ts-nocheck
// 用于将扁平评论数组转换为树状结构并覆盖原 comment01.ts 文件
const fs = require('fs');
const path = require('path');

const filePath = path.resolve(__dirname, '../data/comment01.ts');

// 1. 读取原始文件内容
let fileContent;
try {
    fileContent = fs.readFileSync(filePath, 'utf-8');
} catch (e) {
    console.error(`Error reading file: ${filePath}`, e);
    process.exit(1);
}

// 2. 提取扁平数组
// This regex specifically finds the array assigned to `mockComment01`.
const match = fileContent.match(/export const mockComment01 = (\[[\s\S]*?\]);?/);

if (!match || !match[1]) {
  console.error('Could not find `mockComment01` array in the source file.');
  process.exit(1);
}
const arrayAsText = match[1];

// 3. 用 new Function 解析为 JS 对象 (比 eval 安全)
let flatComments;
try {
    flatComments = new Function(`return ${arrayAsText}`)();
} catch(e) {
    console.error('Failed to parse the flat comments array.', e);
    process.exit(1);
}


// 4. 构建树状结构
const commentMap = {};
flatComments.forEach(c => {
  commentMap[c.id] = {
    id: c.id,
    content: c.content,
    createdAt: c.time,
    author: {
      name: c.author,
      avatar: c.avatar,
    },
    likes: Math.floor(Math.random() * 20),
    replies: [],
  };
});

const treeComments = [];
flatComments.forEach(c => {
  if (c.parent_id) {
    const parent = commentMap[c.parent_id];
    if (parent) {
      // Avoid adding to parent if it's not found (data integrity issue)
      parent.replies.push(commentMap[c.id]);
    } else {
      console.warn(`Parent comment with id ${c.parent_id} not found for comment ${c.id}.`);
    }
  } else {
    treeComments.push(commentMap[c.id]);
  }
});

// 5. 生成新的导出内容
const newContent = `// This file is auto-generated by \`flatCommentsToTree.cjs\` script
// The new structure is a tree, exported as \`mockCommentTree\`
export const mockCommentTree = ${JSON.stringify(treeComments, null, 2)};
`;

// 6. 覆盖写回 comment01.ts
try {
    fs.writeFileSync(filePath, newContent, 'utf-8');
    console.log('Successfully updated `comment01.ts` with the new tree structure.');
} catch (e) {
    console.error(`Error writing to file: ${filePath}`, e);
    process.exit(1);
}
