DROP TABLE IF EXISTS "AdminWorkMergeOperation" CASCADE;
DROP TABLE IF EXISTS "WorkRealmContext" CASCADE;
DROP TABLE IF EXISTS "UnitWork" CASCADE;
DROP TABLE IF EXISTS "WorkLinkClaim" CASCADE;

DROP TYPE IF EXISTS "UnitWorkDisplayPolicy";
DROP TYPE IF EXISTS "UnitWorkRole";
DROP TYPE IF EXISTS "ClaimStatus";
