// GENERATED by @gel/generate v0.6.4

import type {Executor} from "gel";

export type TagCreateArgs = {
  readonly "name": string;
  readonly "owner": ReadonlyArray<string>;
  readonly "type": string;
};

export type TagCreateReturns = {
  "created_at": Date;
  "id": string;
  "name": string;
  "type": string;
  "updated_at": Date;
  "owner": [({
    "id": string;
  }), ...({
    "id": string;
  })[]];
  "related_by": Array<{
    "id": string;
  }>;
  "related_to": Array<{
    "id": string;
  }>;
};

export function TagCreate(client: Executor, args: TagCreateArgs): Promise<TagCreateReturns> {
  return client.queryRequiredSingle(`\
select (
    insert Tag {
        name := <str>$name,
        type := <str>$type,
        owner := (
            select User
            filter (.id in array_unpack(<array<uuid>>$owner))
        )
    }
) { 
    id,
    created_at,
    updated_at,
    owner: {
        id
    },
    name,
    type,
    related_to: {
        id
    },
    related_by: {
        id
    }
}`, args);

}
