// Generated by `bun init`

/// <reference types="vite/client" />

declare module 'virtual:uno.css';

declare module '*.svg' {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module '*.module.css' {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: {readonly [key: string]: string};
  export = classes;
}
