// NOTE: This file is auto-generated by React Cosmos.
// It imports all fixture and decorator modules, making them available to the
// React Cosmos renderer along with the renderer config.

import type { RendererConfig, UserModuleWrappers } from 'react-cosmos-core';

export const rendererConfig: RendererConfig = {
  "webSocketUrl": "ws://localhost:5050",
  "rendererUrl": "http://localhost:35002/cosmos/<fixture>"
};

const fixtures = {
  'src/app/(app)/admin/AdminDashboard.fixture.tsx': { getModule: () => import('./src/app/(app)/admin/AdminDashboard.fixture') },
  'src/app/(app)/admin/books/AdminBooks.fixture.tsx': { getModule: () => import('./src/app/(app)/admin/books/AdminBooks.fixture') },
  'src/app/(app)/admin/governance/AdminGovernance.fixture.tsx': { getModule: () => import('./src/app/(app)/admin/governance/AdminGovernance.fixture') },
  'src/app/(app)/admin/realms/AdminRealms.fixture.tsx': { getModule: () => import('./src/app/(app)/admin/realms/AdminRealms.fixture') },
  'src/app/(app)/admin/stats/AdminStats.fixture.tsx': { getModule: () => import('./src/app/(app)/admin/stats/AdminStats.fixture') },
  'src/app/(app)/admin/tags/AdminTags.fixture.tsx': { getModule: () => import('./src/app/(app)/admin/tags/AdminTags.fixture') },
  'src/app/(app)/admin/users/AdminUsers.fixture.tsx': { getModule: () => import('./src/app/(app)/admin/users/AdminUsers.fixture') },
  'src/app/(app)/book/BooksContent.fixture.tsx': { getModule: () => import('./src/app/(app)/book/BooksContent.fixture') },
  'src/app/(app)/book/[id]/BookContentTab.fixture.tsx': { getModule: () => import('./src/app/(app)/book/[id]/BookContentTab.fixture') },
  'src/app/(app)/book/[id]/BookDiscussion.fixture.tsx': { getModule: () => import('./src/app/(app)/book/[id]/BookDiscussion.fixture') },
  'src/app/(app)/book/[id]/BookInfo.fixture.tsx': { getModule: () => import('./src/app/(app)/book/[id]/BookInfo.fixture') },
  'src/app/(app)/book/[id]/BookLayoutShell.fixture.tsx': { getModule: () => import('./src/app/(app)/book/[id]/BookLayoutShell.fixture') },
  'src/app/(app)/book/[id]/BookReview.fixture.tsx': { getModule: () => import('./src/app/(app)/book/[id]/BookReview.fixture') },
  'src/app/(app)/create/CreatePage.fixture.tsx': { getModule: () => import('./src/app/(app)/create/CreatePage.fixture') },
  'src/app/(app)/e/[slug]/EntityDetail.fixture.tsx': { getModule: () => import('./src/app/(app)/e/[slug]/EntityDetail.fixture') },
  'src/app/(app)/excerpt/[id]/ExcerptDetail.fixture.tsx': { getModule: () => import('./src/app/(app)/excerpt/[id]/ExcerptDetail.fixture') },
  'src/app/(app)/feedback/FeedbackPage.fixture.tsx': { getModule: () => import('./src/app/(app)/feedback/FeedbackPage.fixture') },
  'src/app/(app)/game/[id]/GameDetail.fixture.tsx': { getModule: () => import('./src/app/(app)/game/[id]/GameDetail.fixture') },
  'src/app/(app)/inbox/conversations/Conversations.fixture.tsx': { getModule: () => import('./src/app/(app)/inbox/conversations/Conversations.fixture') },
  'src/app/(app)/inbox/notifications/Notifications.fixture.tsx': { getModule: () => import('./src/app/(app)/inbox/notifications/Notifications.fixture') },
  'src/app/(app)/poll/[id]/PollDetail.fixture.tsx': { getModule: () => import('./src/app/(app)/poll/[id]/PollDetail.fixture') },
  'src/app/(app)/r/RealmsContent.fixture.tsx': { getModule: () => import('./src/app/(app)/r/RealmsContent.fixture') },
  'src/app/(app)/r/[slug]/RealmDetailShell.fixture.tsx': { getModule: () => import('./src/app/(app)/r/[slug]/RealmDetailShell.fixture') },
  'src/app/(app)/r/[slug]/RealmSubPages.fixture.tsx': { getModule: () => import('./src/app/(app)/r/[slug]/RealmSubPages.fixture') },
  'src/app/(app)/r/[slug]/manage/RealmManage.fixture.tsx': { getModule: () => import('./src/app/(app)/r/[slug]/manage/RealmManage.fixture') },
  'src/app/(app)/search/SearchContent.fixture.tsx': { getModule: () => import('./src/app/(app)/search/SearchContent.fixture') },
  'src/app/(app)/user/[id]/UserEmptyStates.fixture.tsx': { getModule: () => import('./src/app/(app)/user/[id]/UserEmptyStates.fixture') },
  'src/app/(app)/user/[id]/UserProfile.fixture.tsx': { getModule: () => import('./src/app/(app)/user/[id]/UserProfile.fixture') },
  'src/app/(app)/user/me/bookmarks/Bookmarks.fixture.tsx': { getModule: () => import('./src/app/(app)/user/me/bookmarks/Bookmarks.fixture') },
  'src/app/(app)/user/me/edit/EditProfile.fixture.tsx': { getModule: () => import('./src/app/(app)/user/me/edit/EditProfile.fixture') },
  'src/app/(app)/user/me/follows/Follows.fixture.tsx': { getModule: () => import('./src/app/(app)/user/me/follows/Follows.fixture') },
  'src/app/(app)/user/me/reactions/MyReactions.fixture.tsx': { getModule: () => import('./src/app/(app)/user/me/reactions/MyReactions.fixture') },
  'src/app/(app)/user/me/settings/SettingsPages.fixture.tsx': { getModule: () => import('./src/app/(app)/user/me/settings/SettingsPages.fixture') },
  'src/app/(app)/z/[slug]/ZoneDetail.fixture.tsx': { getModule: () => import('./src/app/(app)/z/[slug]/ZoneDetail.fixture') },
  'src/app/(app)/z/[slug]/ZoneSubPages.fixture.tsx': { getModule: () => import('./src/app/(app)/z/[slug]/ZoneSubPages.fixture') },
  'src/app/(app)/z/[slug]/manage/ZoneManage.fixture.tsx': { getModule: () => import('./src/app/(app)/z/[slug]/manage/ZoneManage.fixture') },
  'src/app/(editor)/book/[id]/edit/BookEdit.fixture.tsx': { getModule: () => import('./src/app/(editor)/book/[id]/edit/BookEdit.fixture') },
  'src/app/(editor)/entity/new/NewEntity.fixture.tsx': { getModule: () => import('./src/app/(editor)/entity/new/NewEntity.fixture') },
  'src/app/(editor)/excerpt/new/NewExcerpt.fixture.tsx': { getModule: () => import('./src/app/(editor)/excerpt/new/NewExcerpt.fixture') },
  'src/app/(editor)/post/new/NewPost.fixture.tsx': { getModule: () => import('./src/app/(editor)/post/new/NewPost.fixture') },
  'src/app/(editor)/remark/new/NewRemark.fixture.tsx': { getModule: () => import('./src/app/(editor)/remark/new/NewRemark.fixture') },
  'src/app/(editor)/review/new/NewReview.fixture.tsx': { getModule: () => import('./src/app/(editor)/review/new/NewReview.fixture') },
  'src/app/(editor)/shelf/[id]/edit/ShelfEdit.fixture.tsx': { getModule: () => import('./src/app/(editor)/shelf/[id]/edit/ShelfEdit.fixture') },
  'src/components/BottomNav.fixture.tsx': { getModule: () => import('./src/components/BottomNav.fixture') },
  'src/components/Header.fixture.tsx': { getModule: () => import('./src/components/Header.fixture') },
  'src/components/SectionBoundary.fixture.tsx': { getModule: () => import('./src/components/SectionBoundary.fixture') },
  'src/components/ServiceUnavailableOverlay.fixture.tsx': { getModule: () => import('./src/components/ServiceUnavailableOverlay.fixture') },
  'src/components/Sidebar.fixture.tsx': { getModule: () => import('./src/components/Sidebar.fixture') },
  'src/components/book/BookCard.fixture.tsx': { getModule: () => import('./src/components/book/BookCard.fixture') },
  'src/components/post/PostCard.fixture.tsx': { getModule: () => import('./src/components/post/PostCard.fixture') },
  'src/components/post/PostFeed.fixture.tsx': { getModule: () => import('./src/components/post/PostFeed.fixture') },
  'src/components/realm/JoinButton.fixture.tsx': { getModule: () => import('./src/components/realm/JoinButton.fixture') },
  'src/components/realm/RealmCard.fixture.tsx': { getModule: () => import('./src/components/realm/RealmCard.fixture') },
  'src/components/shared/AuthDialog.fixture.tsx': { getModule: () => import('./src/components/shared/AuthDialog.fixture') },
  'src/components/shared/PagedList.fixture.tsx': { getModule: () => import('./src/components/shared/PagedList.fixture') },
  'src/components/shared/PortableTextEditor.fixture.tsx': { getModule: () => import('./src/components/shared/PortableTextEditor.fixture') },
  'src/components/shared/PortableTextView.fixture.tsx': { getModule: () => import('./src/components/shared/PortableTextView.fixture') }
};

const decorators = {
  'src/__cosmos__/cosmos.decorator.tsx': { getModule: () => import('./src/__cosmos__/cosmos.decorator') }
};

export const moduleWrappers: UserModuleWrappers = {
  lazy: true,
  fixtures,
  decorators
};
