-- 您需要先连接到 PostgreSQL，然后运行此命令来创建数据库。
-- 这个命令不能在下面的事务块中运行。
-- CREATE DATABASE library;

-- 连接到 `library` 数据库后，运行以下脚本。

BEGIN;

-- 创建一个辅助函数，用于在行更新时自动设置 `updated_at` 字段的值。
-- 这是一个在 PostgreSQL 中实现类似功能的标准模式。
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- 表: author (作者)
CREATE TABLE author (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL CHECK (length(name) > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- 表: platform (平台)
CREATE TABLE platform (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    domain TEXT UNIQUE NOT NULL CHECK (domain ~* '^[a-zA-Z0-9][a-zA-Z0-9-]{0,61}[a-zA-Z0-9](?:\.[a-zA-Z]{2,})+$'),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 为常用查询字段创建索引
CREATE INDEX idx_platform_domain ON platform(domain);


-- 表: tag (标签)
CREATE TABLE tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(99) UNIQUE NOT NULL CHECK (length(name) > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_tag_name ON tag(name);


-- 表: unit (单元，如卷、章)
-- 这是一个自引用的表，用于表示层级结构。
CREATE TABLE unit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    -- 'children' 字段通过自引用的外键实现。
    -- 如果父单元被删除，其子单元也会被级联删除。
    parent_id BIGINT REFERENCES unit(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_unit_parent_id ON unit(parent_id);

-- 为 `unit` 表创建触发器，在更新时自动修改 `updated_at`
CREATE TRIGGER trigger_unit_updated_at
BEFORE UPDATE ON unit
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();


-- 表: book (书籍)
CREATE TABLE book (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grabbed_from TEXT CHECK (grabbed_from ~* '^https?://\S+$'),
    cover TEXT CHECK (cover ~* '^https?://\S+$'),
    title VARCHAR(999) NOT NULL CHECK (length(title) > 0),
    description VARCHAR(9999) NOT NULL CHECK (length(description) > 0),
    -- SurrealQL 中的 `release` 是 PostgreSQL 的保留关键字，重命名为 `release_date`
    release_date TIMESTAMPTZ,
    last_update TIMESTAMPTZ,
    length INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_book_title ON book(title);

-- 为 `book` 表创建触发器，在更新时自动修改 `updated_at`
CREATE TRIGGER trigger_book_updated_at
BEFORE UPDATE ON book
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();


-- 连接表 (实现多对多关系)

-- 关系: book <-> author (书籍与作者)
CREATE TABLE book_author (
    book_id BIGINT NOT NULL REFERENCES book(id) ON DELETE CASCADE,
    author_id BIGINT NOT NULL REFERENCES author(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (book_id, author_id)
);

-- 关系: book <-> platform (书籍与平台)
CREATE TABLE book_platform (
    book_id BIGINT NOT NULL REFERENCES book(id) ON DELETE CASCADE,
    platform_id BIGINT NOT NULL REFERENCES platform(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (book_id, platform_id)
);

-- 关系: book <-> tag (书籍与标签)
CREATE TABLE book_tag (
    book_id BIGINT NOT NULL REFERENCES book(id) ON DELETE CASCADE,
    tag_id BIGINT NOT NULL REFERENCES tag(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (book_id, tag_id)
);

-- 关系: book <-> unit (书籍与单元)
-- 对应 `book` 表中的 `unit` 字段
CREATE TABLE book_unit (
    book_id BIGINT NOT NULL REFERENCES book(id) ON DELETE CASCADE,
    unit_id BIGINT NOT NULL REFERENCES unit(id) ON DELETE CASCADE,
    PRIMARY KEY (book_id, unit_id)
);


COMMIT;