"""Verify prepared derivatives without treating ignored files as authored inputs.

The production storage emitter supplies the exact registered output set and bytes.
All reviewed model/compiler sources, source pins and runtime recipes remain tracked.
No network, schema writes, database connection or full compiler run is required.
"""

from __future__ import annotations

import hashlib
import json
import re
import subprocess
from pathlib import Path, PurePosixPath

HEADER = "// Generated by task libraries:schema-importer:generate from reviewed model declarations. Do not edit.\n"
OUTPUT = re.compile(r"libraries/schema/src/postgres/[a-z-]+/[a-z-]+\.generated\.ts")
MANIFEST = "libraries/schema-importer/sources/manifest.json"
ADAPTER = "docs/testing/database/storage_derivatives.ts"


def local_path(root: Path, name: str) -> Path:
    relative = PurePosixPath(name)
    if (not name or relative.is_absolute() or ".." in relative.parts
            or "\\" in name or relative.as_posix() != name):
        raise ValueError(f"Unsafe dependency path: {name}")
    path = root / name
    if path.resolve() != path:
        raise ValueError(f"Symlinked dependency: {name}")
    return path


def regular_file(root: Path, name: str) -> Path:
    path = local_path(root, name)
    if not path.is_file():
        raise ValueError(f"Missing, symlinked or non-regular dependency: {name}")
    return path


def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def verify_outputs(root: Path, expected: list[dict], tracked: frozenset[str] = frozenset()) -> dict[str, str]:
    registered = {}
    for entry in expected:
        name, content = entry["path"], entry["content"]
        if not OUTPUT.fullmatch(name) or name in registered:
            raise ValueError(f"Invalid or duplicate registered derivative: {name}")
        if not content.startswith(HEADER):
            raise ValueError(f"Emitter missing generated ownership marker: {name}")
        actual = regular_file(root, name).read_bytes()
        if actual != content.encode("utf-8"):
            raise ValueError(f"Generated schema differs from production emitter: {name}; run task artifacts:generate")
        registered[name] = digest(actual)
    present = {p.relative_to(root).as_posix()
               for p in (root / "libraries/schema/src/postgres").rglob("*.generated.ts")}
    # Other generators may retain reviewed snapshots in Git (currently OAuth).
    # They remain ordinary tracked schema inputs, never an ignored-file exemption.
    unexpected = []
    for name in present - set(registered):
        data = regular_file(root, name).read_text(encoding="utf-8")
        if name not in tracked or data.startswith(HEADER):
            unexpected.append(name)
    if unexpected:
        raise ValueError("Unregistered generated schema: " + ", ".join(sorted(unexpected)))
    return dict(sorted(registered.items()))


def verify_pins(root: Path) -> dict[str, str]:
    manifest = json.loads(regular_file(root, MANIFEST).read_text(encoding="utf-8"))
    if manifest["format"] != 1:
        raise ValueError("Unsupported vocabulary manifest format")
    pins = {}
    for entry in manifest["sources"]:
        name = f"libraries/schema-importer/sources/{entry['file']}"
        if name in pins:
            raise ValueError(f"Duplicate pinned source: {name}")
        data = regular_file(root, name).read_bytes()
        if len(data) != entry["bytes"] or digest(data) != entry["sha256"]:
            raise ValueError(f"Pinned vocabulary bytes differ: {name}; restore the pinned artifact")
        pins[name] = digest(data)
    return dict(sorted(pins.items()))


def producer_inputs(root: Path) -> dict[str, str]:
    # Include the whole authored model/compiler owners, not a hand-maintained list
    # of the seven outputs. Output registration comes from storageModules itself.
    names = {
        ADAPTER, "docs/testing/database/generated_inputs.py", MANIFEST,
        "libraries/schema/src/model/contracts.ts",
        "libraries/schema/package.json", "libraries/schema/Taskfile.yml",
        "libraries/schema-importer/package.json", "libraries/schema-importer/Taskfile.yml",
        "package.json", "yarn.lock", ".yarnrc.yml", "Taskfile.yml", ".gitignore",
    }
    for directory in ("libraries/schema/model", "libraries/schema-importer/src/compiler"):
        names.update(p.relative_to(root).as_posix() for p in (root / directory).rglob("*.ts"))
    # The selected Yarn release is part of the offline recipe, not a global CLI assumption.
    config = regular_file(root, ".yarnrc.yml").read_text(encoding="utf-8")
    yarn_path = re.search(r"^yarnPath:\s*([^\s]+)\s*$", config, re.M)
    if not yarn_path:
        raise ValueError("Missing pinned Yarn runtime path")
    names.add(yarn_path.group(1))
    return {name: digest(regular_file(root, name).read_bytes()) for name in sorted(names)}


def prepared_inputs(root: Path) -> dict:
    sources = producer_inputs(root)
    pins = verify_pins(root)
    result = subprocess.run(
        ["yarn", "workspace", "@rezics/schema-importer", "exec", "tsx", str(root / ADAPTER)],
        cwd=root, capture_output=True, text=True, encoding="utf-8", timeout=60,
    )
    if result.returncode:
        raise ValueError("Cannot run read-only storage emitter; prepare workspace dependencies.\n" + result.stderr + result.stdout)
    tracked = frozenset(subprocess.check_output(
        ["git", "ls-files", "-z", "--", "libraries/schema/src/postgres"], cwd=root,
    ).decode("utf-8").split("\0"))
    outputs = verify_outputs(root, json.loads(result.stdout), tracked)
    return {
        "recipe": "task artifacts:prepare (first checkout); task artifacts:generate (offline rebuild)",
        "check": "Production emitDrizzle(storageModules), read-only exact-byte comparison",
        "producer_inputs_sha256": sources,
        "pinned_source_artifacts_sha256": pins,
        "derivatives_sha256": outputs,
    }


def untracked_paths(root: Path, required: set[str], directories: list[str], tracked: set[str]) -> list[str]:
    missing = []
    for name in sorted(required):
        path = local_path(root, name)
        if path.is_dir():
            if not any(item.startswith(name.rstrip("/") + "/") for item in tracked):
                missing.append(name + "/ (no tracked contents)")
        else:
            regular_file(root, name)
            if name not in tracked:
                missing.append(name)
    for directory in directories:
        if not any(name.startswith(directory + "/") for name in tracked):
            missing.append(directory + "/ (no tracked contents)")
    return sorted(set(missing))


def authored_requirements(required: set[str], prepared: dict) -> set[str]:
    """Exempt only exact outputs verified earlier, retaining every producer."""
    return ((required - set(prepared["derivatives_sha256"]))
            | set(prepared["producer_inputs_sha256"]))
