services:
  sequin:
    ports:
      - "7376:7376"
    environment:
      ENV: ${ENV:-development}
      SOURCE_DB_HOST: ${SOURCE_DB_HOST:-host.docker.internal}
      JOB_RUNNER_BASE_URL: ${JOB_RUNNER_BASE_URL:-http://host.docker.internal:3005}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  sequin-postgres:
    ports:
      - "7377:5432"
