import type { SearchCategory, SearchField, SearchOperator } from "@rezics/filter";

export type SearchScalarKind =
	"boolean" | "date" | "integer" | "string" | "uuid" | "realm-tag-vote";
export type SearchFacetPolicy = "none" | "meili-low-cardinality" | "postgres-authorized";
export type SearchSortPolicy = "none" | "meili" | "postgres-residual";

export interface SearchFieldDefinition {
	readonly categories: readonly SearchCategory[];
	readonly unitTypes?: readonly string[];
	readonly scalar: SearchScalarKind;
	readonly operators: readonly SearchOperator[];
	readonly facet: SearchFacetPolicy;
	readonly sort: SearchSortPolicy;
	readonly documentPath: string;
	readonly meilisearch: readonly ("equality" | "comparison")[];
	readonly residual: boolean;
	readonly applicabilityPath?: string;
}

const allCategories: readonly SearchCategory[] = [
	"units",
	"users",
	"entity",
	"tags",
	"posts",
	"realms",
	"collections",
	"reviews",
	"polls",
];
const equality = ["equals", "not-equals", "any-of", "all-of", "none-of"] as const;
const range = ["range", "exists"] as const;

export const CurrentSearchFieldRegistry: Partial<Record<SearchField, SearchFieldDefinition>> = {
	category: {
		categories: allCategories,
		scalar: "string",
		operators: equality,
		facet: "meili-low-cardinality",
		sort: "none",
		documentPath: "category",
		meilisearch: ["equality"],
		residual: false,
	},
	kind: {
		categories: ["units", "entity", "posts", "reviews"],
		scalar: "string",
		operators: equality,
		facet: "meili-low-cardinality",
		sort: "none",
		documentPath: "searchKind",
		meilisearch: ["equality"],
		residual: false,
	},
	language: {
		categories: allCategories,
		scalar: "string",
		operators: equality,
		facet: "meili-low-cardinality",
		sort: "none",
		documentPath: "languages",
		meilisearch: ["equality"],
		residual: false,
	},
	"content-rating": {
		categories: allCategories,
		scalar: "string",
		operators: equality,
		facet: "meili-low-cardinality",
		sort: "none",
		documentPath: "filters.contentRating",
		meilisearch: ["equality"],
		residual: false,
	},
	"ai-disclosure": {
		categories: allCategories,
		scalar: "string",
		operators: equality,
		facet: "meili-low-cardinality",
		sort: "none",
		documentPath: "filters.aiDisclosure",
		meilisearch: ["equality"],
		residual: false,
	},
	license: {
		categories: allCategories,
		scalar: "string",
		operators: [...equality, "exists"],
		facet: "postgres-authorized",
		sort: "none",
		documentPath: "filters.license",
		meilisearch: ["equality"],
		residual: false,
	},
	tag: {
		categories: allCategories,
		scalar: "uuid",
		operators: equality,
		facet: "postgres-authorized",
		sort: "none",
		documentPath: "filters.tagIds",
		meilisearch: ["equality"],
		residual: false,
	},
	credit: {
		categories: allCategories,
		scalar: "uuid",
		operators: equality,
		facet: "postgres-authorized",
		sort: "none",
		documentPath: "filters.creditedUnitIds",
		meilisearch: ["equality"],
		residual: false,
	},
	realm: {
		categories: allCategories,
		scalar: "uuid",
		operators: equality,
		facet: "postgres-authorized",
		sort: "none",
		documentPath: "filters.realmIds",
		meilisearch: ["equality"],
		residual: false,
	},
	"realm-tag-vote": {
		categories: allCategories,
		scalar: "realm-tag-vote",
		operators: ["matches"],
		facet: "none",
		sort: "none",
		documentPath: "filters.realmTagVoteKeys",
		meilisearch: ["equality"],
		residual: true,
	},
	zone: {
		categories: allCategories,
		scalar: "uuid",
		operators: equality,
		facet: "postgres-authorized",
		sort: "none",
		documentPath: "filters.scopeOwnerIds",
		meilisearch: [],
		residual: true,
	},
	subject: {
		categories: ["posts"],
		scalar: "uuid",
		operators: equality,
		facet: "postgres-authorized",
		sort: "none",
		documentPath: "filters.subjectId",
		meilisearch: ["equality"],
		residual: false,
	},
	target: {
		categories: ["reviews"],
		scalar: "uuid",
		operators: equality,
		facet: "postgres-authorized",
		sort: "none",
		documentPath: "filters.subjectId",
		meilisearch: ["equality"],
		residual: false,
	},
	root: {
		categories: ["posts"],
		scalar: "uuid",
		operators: equality,
		facet: "postgres-authorized",
		sort: "none",
		documentPath: "filters.rootId",
		meilisearch: ["equality"],
		residual: false,
	},
	parent: {
		categories: ["posts"],
		scalar: "uuid",
		operators: equality,
		facet: "postgres-authorized",
		sort: "none",
		documentPath: "filters.parentId",
		meilisearch: ["equality"],
		residual: false,
	},
	owner: {
		categories: ["collections"],
		scalar: "uuid",
		operators: equality,
		facet: "postgres-authorized",
		sort: "none",
		documentPath: "filters.ownerProfileIds",
		meilisearch: ["equality"],
		residual: false,
	},
	"join-policy": {
		categories: ["realms"],
		scalar: "string",
		operators: equality,
		facet: "meili-low-cardinality",
		sort: "none",
		documentPath: "filters.joinPolicy",
		meilisearch: ["equality"],
		residual: false,
	},
	multiple: {
		categories: ["polls"],
		scalar: "boolean",
		operators: ["equals", "not-equals"],
		facet: "meili-low-cardinality",
		sort: "none",
		documentPath: "filters.pollMode",
		meilisearch: [],
		residual: true,
	},
	"results-visibility": {
		categories: ["polls"],
		scalar: "string",
		operators: equality,
		facet: "meili-low-cardinality",
		sort: "none",
		documentPath: "filters.resultsVisibility",
		meilisearch: ["equality"],
		residual: false,
	},
	closed: {
		categories: ["polls"],
		scalar: "boolean",
		operators: ["equals", "not-equals"],
		facet: "meili-low-cardinality",
		sort: "none",
		documentPath: "filters.closesAt",
		meilisearch: [],
		residual: true,
	},
	"created-at": {
		categories: allCategories,
		scalar: "date",
		operators: range,
		facet: "none",
		sort: "meili",
		documentPath: "ranking.createdAt",
		meilisearch: ["comparison"],
		residual: false,
	},
	"updated-at": {
		categories: allCategories,
		scalar: "date",
		operators: range,
		facet: "none",
		sort: "meili",
		documentPath: "ranking.updatedAt",
		meilisearch: ["comparison"],
		residual: false,
	},
	"published-at": {
		categories: allCategories,
		scalar: "date",
		operators: range,
		facet: "none",
		sort: "meili",
		documentPath: "ranking.publishedAt",
		meilisearch: ["comparison"],
		residual: false,
	},
	"closes-at": {
		categories: ["polls"],
		scalar: "date",
		operators: range,
		facet: "none",
		sort: "meili",
		documentPath: "filters.closesAt",
		meilisearch: ["comparison"],
		residual: false,
	},
	"catalog-licensed": {
		categories: ["units"],
		unitTypes: ["book", "media", "software"],
		scalar: "boolean",
		operators: ["equals", "not-equals"],
		facet: "meili-low-cardinality",
		sort: "none",
		documentPath: "catalog.licensed",
		meilisearch: ["equality"],
		residual: false,
		applicabilityPath: "unitType",
	},
	"catalog-release-date": {
		categories: ["units"],
		unitTypes: ["media", "software"],
		scalar: "date",
		operators: range,
		facet: "none",
		sort: "meili",
		documentPath: "catalog.releaseAt",
		meilisearch: ["comparison"],
		residual: false,
		applicabilityPath: "unitType",
	},
	"book-isbn13": {
		categories: ["units"],
		unitTypes: ["book"],
		scalar: "string",
		operators: [...equality, "exists"],
		facet: "none",
		sort: "none",
		documentPath: "book.isbn13",
		meilisearch: ["equality"],
		residual: false,
		applicabilityPath: "unitType",
	},
	"book-publication-date": {
		categories: ["units"],
		unitTypes: ["book"],
		scalar: "date",
		operators: range,
		facet: "none",
		sort: "meili",
		documentPath: "book.publicationAt",
		meilisearch: ["comparison"],
		residual: false,
		applicabilityPath: "unitType",
	},
	"book-page-count": {
		categories: ["units"],
		unitTypes: ["book"],
		scalar: "integer",
		operators: range,
		facet: "none",
		sort: "meili",
		documentPath: "book.pageCount",
		meilisearch: ["comparison"],
		residual: false,
		applicabilityPath: "unitType",
	},
	"book-word-count": {
		categories: ["units"],
		unitTypes: ["book"],
		scalar: "integer",
		operators: range,
		facet: "none",
		sort: "none",
		documentPath: "book.wordCount",
		meilisearch: [],
		residual: true,
		applicabilityPath: "unitType",
	},
	"book-format": {
		categories: ["units"],
		unitTypes: ["book"],
		scalar: "string",
		operators: [...equality, "exists"],
		facet: "meili-low-cardinality",
		sort: "none",
		documentPath: "book.format",
		meilisearch: ["equality"],
		residual: false,
		applicabilityPath: "unitType",
	},
	"media-kind": {
		categories: ["units"],
		unitTypes: ["media"],
		scalar: "string",
		operators: equality,
		facet: "meili-low-cardinality",
		sort: "none",
		documentPath: "media.kind",
		meilisearch: ["equality"],
		residual: false,
		applicabilityPath: "unitType",
	},
	"media-release-date": {
		categories: ["units"],
		unitTypes: ["media"],
		scalar: "date",
		operators: range,
		facet: "none",
		sort: "meili",
		documentPath: "media.releaseAt",
		meilisearch: ["comparison"],
		residual: false,
		applicabilityPath: "unitType",
	},
	"media-runtime-minutes": {
		categories: ["units"],
		unitTypes: ["media"],
		scalar: "integer",
		operators: range,
		facet: "none",
		sort: "meili",
		documentPath: "media.runtimeMinutes",
		meilisearch: ["comparison"],
		residual: false,
		applicabilityPath: "unitType",
	},
	"media-episode-count": {
		categories: ["units"],
		unitTypes: ["media"],
		scalar: "integer",
		operators: range,
		facet: "none",
		sort: "none",
		documentPath: "media.episodeCount",
		meilisearch: ["comparison"],
		residual: false,
		applicabilityPath: "unitType",
	},
	"media-season-count": {
		categories: ["units"],
		unitTypes: ["media"],
		scalar: "integer",
		operators: range,
		facet: "none",
		sort: "none",
		documentPath: "media.seasonCount",
		meilisearch: ["comparison"],
		residual: false,
		applicabilityPath: "unitType",
	},
	"software-release-date": {
		categories: ["units"],
		unitTypes: ["software"],
		scalar: "date",
		operators: range,
		facet: "none",
		sort: "meili",
		documentPath: "software.releaseAt",
		meilisearch: ["comparison"],
		residual: false,
		applicabilityPath: "unitType",
	},
	"software-version-label": {
		categories: ["units"],
		unitTypes: ["software"],
		scalar: "string",
		operators: [...equality, "exists"],
		facet: "none",
		sort: "none",
		documentPath: "software.versionLabel",
		meilisearch: ["equality"],
		residual: false,
		applicabilityPath: "unitType",
	},
	"software-platform": {
		categories: ["units"],
		unitTypes: ["software"],
		scalar: "uuid",
		operators: equality,
		facet: "postgres-authorized",
		sort: "none",
		documentPath: "software.platformIds",
		meilisearch: ["equality"],
		residual: false,
		applicabilityPath: "unitType",
	},
	"software-requirement-tier": {
		categories: ["units"],
		unitTypes: ["software"],
		scalar: "string",
		operators: equality,
		facet: "meili-low-cardinality",
		sort: "none",
		documentPath: "software.requirementTiers",
		meilisearch: ["equality"],
		residual: true,
		applicabilityPath: "unitType",
	},
};

export const HistorySearchFieldRegistry = {
	"unit-id": { documentPath: "unitId", scalar: "uuid", operators: equality },
	"unit-type": { documentPath: "unitType", scalar: "string", operators: equality },
	"actor-profile-id": {
		documentPath: "filters.actorProfileId",
		scalar: "uuid",
		operators: [...equality, "exists"],
	},
	minor: {
		documentPath: "filters.minor",
		scalar: "boolean",
		operators: ["equals", "not-equals"],
	},
	"change-tag": { documentPath: "filters.tags", scalar: "string", operators: equality },
	"created-at": { documentPath: "filters.createdAt", scalar: "date", operators: range },
} as const;
