/**
 * Generate barrel file for a given directory.
 *
 * Example:
 * cd tool && bun run generate-barrel "../packages/ui/src/shadcn"
 *
 * Features:
 * - Export all .ts/.tsx files in current directory (excluding index.ts)
 * - Export subdirectories that contain index.ts
 * - Does NOT recursively flatten subdirectories
 */

import fs from "node:fs";
import path from "node:path";

const targetDir = process.argv[2];

if (!targetDir) {
  console.error("Please provide target directory.");
  process.exit(1);
}

const absPath = path.resolve(process.cwd(), targetDir);

if (!fs.existsSync(absPath)) {
  console.error(`Directory not found: ${absPath}`);
  process.exit(1);
}

const entries = fs.readdirSync(absPath, { withFileTypes: true });

const fileExports: string[] = [];
const dirExports: string[] = [];

/**
 * Export current directory files
 */
for (const entry of entries) {
  if (entry.isFile()) {
    const ext = path.extname(entry.name);
    const base = path.basename(entry.name, ext);

    if ((ext === ".ts" || ext === ".tsx") && entry.name !== "index.ts") {
      fileExports.push(`export * from './${base}';`);
    }
  }
}

/**
 * Export subdirectories (only when index.ts exists)
 */
for (const entry of entries) {
  if (entry.isDirectory()) {
    const subDirPath = path.join(absPath, entry.name);
    const subIndexPath = path.join(subDirPath, "index.ts");

    if (fs.existsSync(subIndexPath)) {
      dirExports.push(`export * from './${entry.name}';`);
    }
  }
}

/**
 * Sort (ensure stable output)
 */
fileExports.sort();
dirExports.sort();

/**
 * Merge output
 */
const output = [
  "// Auto-generated by generate-barrel",
  "",
  ...fileExports,
  ...(fileExports.length && dirExports.length ? [""] : []),
  ...dirExports,
  "",
].join("\n");

fs.writeFileSync(path.join(absPath, "index.ts"), output);

console.log(`index.ts generated in ${absPath}`);
