/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as MainLayoutRouteImport } from './_mainLayout'
import { Route as MainLayoutIndexRouteImport } from './_mainLayout/index'
import { Route as MainLayoutTokenRouteImport } from './_mainLayout/token'
import { Route as MainLayoutThemeSwitchRouteImport } from './_mainLayout/theme-switch'
import { Route as MainLayoutTest03RouteImport } from './_mainLayout/test03'
import { Route as MainLayoutTest02RouteImport } from './_mainLayout/test02'
import { Route as MainLayoutTestRouteImport } from './_mainLayout/test'
import { Route as MainLayoutResetPasswordRouteImport } from './_mainLayout/reset-password'
import { Route as MainLayoutRegisterRouteImport } from './_mainLayout/register'
import { Route as MainLayoutNoticeRouteImport } from './_mainLayout/notice'
import { Route as MainLayoutMeiliRouteImport } from './_mainLayout/meili'
import { Route as MainLayoutLoginRouteImport } from './_mainLayout/login'
import { Route as MainLayoutUnitIndexRouteImport } from './_mainLayout/unit/index'
import { Route as MainLayoutReviewIndexRouteImport } from './_mainLayout/review/index'
import { Route as MainLayoutReadlistIndexRouteImport } from './_mainLayout/readlist/index'
import { Route as MainLayoutFeedbackIndexRouteImport } from './_mainLayout/feedback/index'
import { Route as MainLayoutBookIndexRouteImport } from './_mainLayout/book/index'
import { Route as MainLayoutUserUnitIdRouteImport } from './_mainLayout/user/$unitId'
import { Route as MainLayoutUnitUnitIdRouteImport } from './_mainLayout/unit/$unitId'
import { Route as MainLayoutTagUnitIdRouteImport } from './_mainLayout/tag/$unitId'
import { Route as MainLayoutReviewReviewIdRouteImport } from './_mainLayout/review/$reviewId'
import { Route as MainLayoutRemarkReviewIdRouteImport } from './_mainLayout/remark/$reviewId'
import { Route as MainLayoutReadlistNewRouteImport } from './_mainLayout/readlist/new'
import { Route as MainLayoutReadlistReadlistIdRouteImport } from './_mainLayout/readlist/$readlistId'
import { Route as MainLayoutQuoteUnitIdRouteImport } from './_mainLayout/quote/$unitId'
import { Route as MainLayoutMiscEchokvRouteImport } from './_mainLayout/misc/echokv'
import { Route as MainLayoutFeedbackAdminRouteImport } from './_mainLayout/feedback/admin'
import { Route as MainLayoutBookNewRouteImport } from './_mainLayout/book/new'
import { Route as MainLayoutBookBookIdRouteImport } from './_mainLayout/book/$bookId'
import { Route as BookBookIdEditRouteRouteImport } from './book_/$bookId/edit/route'
import { Route as MainLayoutUserMeRouteRouteImport } from './_mainLayout/user/me/route'
import { Route as BookBookIdEditIndexRouteImport } from './book_/$bookId/edit/index'
import { Route as MainLayoutUserMeIndexRouteImport } from './_mainLayout/user/me/index'
import { Route as BookBookIdEditTagRouteImport } from './book_/$bookId/edit/tag'
import { Route as BookBookIdEditChapterRouteImport } from './book_/$bookId/edit/chapter'
import { Route as BookBookIdEditChapterIdRouteImport } from './book_/$bookId/edit/$chapterId'
import { Route as MainLayoutUserMeReactionRouteImport } from './_mainLayout/user/me/reaction'
import { Route as MainLayoutUserMeFollowRouteImport } from './_mainLayout/user/me/follow'
import { Route as MainLayoutUserMeEditRouteImport } from './_mainLayout/user/me/edit'
import { Route as MainLayoutUserMeBookmarkRouteImport } from './_mainLayout/user/me/bookmark'
import { Route as MainLayoutUserUnitIdEditRouteImport } from './_mainLayout/user/$unitId/edit'
import { Route as MainLayoutReviewNewBookUnitIdRouteImport } from './_mainLayout/review/new/$bookUnitId'
import { Route as MainLayoutReviewBookBookIdRouteImport } from './_mainLayout/review/book/$bookId'
import { Route as MainLayoutReviewReviewIdEditRouteImport } from './_mainLayout/review/$reviewId/edit'
import { Route as MainLayoutReadlistBookBookIdRouteImport } from './_mainLayout/readlist/book/$bookId'
import { Route as MainLayoutReadlistReadlistIdEditRouteImport } from './_mainLayout/readlist/$readlistId/edit'
import { Route as MainLayoutQuoteBookBookIdRouteImport } from './_mainLayout/quote/book/$bookId'
import { Route as MainLayoutQuoteUnitIdEditRouteImport } from './_mainLayout/quote/$unitId/edit'
import { Route as BookBookIdReadChapterIdRouteRouteImport } from './book_/$bookId/read/$chapterId/route'
import { Route as MainLayoutTagDomainUnitIdRouteRouteImport } from './_mainLayout/tag/domain/$unitId/route'
import { Route as MainLayoutTagBookBookIdRouteRouteImport } from './_mainLayout/tag/book/$bookId/route'
import { Route as BookBookIdReadChapterIdIndexRouteImport } from './book_/$bookId/read/$chapterId/index'
import { Route as MainLayoutTagDomainUnitIdIndexRouteImport } from './_mainLayout/tag/domain/$unitId/index'
import { Route as MainLayoutTagBookBookIdIndexRouteImport } from './_mainLayout/tag/book/$bookId/index'
import { Route as MainLayoutTagBookBookIdTagRouteRouteImport } from './_mainLayout/tag/book/$bookId/tag/route'
import { Route as MainLayoutTagBookBookIdTagIndexRouteImport } from './_mainLayout/tag/book/$bookId/tag/index'
import { Route as MainLayoutTagDomainUnitIdTitleTitleRouteImport } from './_mainLayout/tag/domain/$unitId/title/$title'
import { Route as MainLayoutTagBookBookIdTagDomainIdRouteImport } from './_mainLayout/tag/book/$bookId/tag/$domainId'

const MainLayoutRoute = MainLayoutRouteImport.update({
  id: '/_mainLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutIndexRoute = MainLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutTokenRoute = MainLayoutTokenRouteImport.update({
  id: '/token',
  path: '/token',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutThemeSwitchRoute = MainLayoutThemeSwitchRouteImport.update({
  id: '/theme-switch',
  path: '/theme-switch',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutTest03Route = MainLayoutTest03RouteImport.update({
  id: '/test03',
  path: '/test03',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutTest02Route = MainLayoutTest02RouteImport.update({
  id: '/test02',
  path: '/test02',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutTestRoute = MainLayoutTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutResetPasswordRoute = MainLayoutResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutRegisterRoute = MainLayoutRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutNoticeRoute = MainLayoutNoticeRouteImport.update({
  id: '/notice',
  path: '/notice',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutMeiliRoute = MainLayoutMeiliRouteImport.update({
  id: '/meili',
  path: '/meili',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutLoginRoute = MainLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutUnitIndexRoute = MainLayoutUnitIndexRouteImport.update({
  id: '/unit/',
  path: '/unit/',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutReviewIndexRoute = MainLayoutReviewIndexRouteImport.update({
  id: '/review/',
  path: '/review/',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutReadlistIndexRoute = MainLayoutReadlistIndexRouteImport.update({
  id: '/readlist/',
  path: '/readlist/',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutFeedbackIndexRoute = MainLayoutFeedbackIndexRouteImport.update({
  id: '/feedback/',
  path: '/feedback/',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutBookIndexRoute = MainLayoutBookIndexRouteImport.update({
  id: '/book/',
  path: '/book/',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutUserUnitIdRoute = MainLayoutUserUnitIdRouteImport.update({
  id: '/user/$unitId',
  path: '/user/$unitId',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutUnitUnitIdRoute = MainLayoutUnitUnitIdRouteImport.update({
  id: '/unit/$unitId',
  path: '/unit/$unitId',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutTagUnitIdRoute = MainLayoutTagUnitIdRouteImport.update({
  id: '/tag/$unitId',
  path: '/tag/$unitId',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutReviewReviewIdRoute =
  MainLayoutReviewReviewIdRouteImport.update({
    id: '/review/$reviewId',
    path: '/review/$reviewId',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutRemarkReviewIdRoute =
  MainLayoutRemarkReviewIdRouteImport.update({
    id: '/remark/$reviewId',
    path: '/remark/$reviewId',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutReadlistNewRoute = MainLayoutReadlistNewRouteImport.update({
  id: '/readlist/new',
  path: '/readlist/new',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutReadlistReadlistIdRoute =
  MainLayoutReadlistReadlistIdRouteImport.update({
    id: '/readlist/$readlistId',
    path: '/readlist/$readlistId',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutQuoteUnitIdRoute = MainLayoutQuoteUnitIdRouteImport.update({
  id: '/quote/$unitId',
  path: '/quote/$unitId',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutMiscEchokvRoute = MainLayoutMiscEchokvRouteImport.update({
  id: '/misc/echokv',
  path: '/misc/echokv',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutFeedbackAdminRoute = MainLayoutFeedbackAdminRouteImport.update({
  id: '/feedback/admin',
  path: '/feedback/admin',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutBookNewRoute = MainLayoutBookNewRouteImport.update({
  id: '/book/new',
  path: '/book/new',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutBookBookIdRoute = MainLayoutBookBookIdRouteImport.update({
  id: '/book/$bookId',
  path: '/book/$bookId',
  getParentRoute: () => MainLayoutRoute,
} as any)
const BookBookIdEditRouteRoute = BookBookIdEditRouteRouteImport.update({
  id: '/book_/$bookId/edit',
  path: '/book/$bookId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutUserMeRouteRoute = MainLayoutUserMeRouteRouteImport.update({
  id: '/user/me',
  path: '/user/me',
  getParentRoute: () => MainLayoutRoute,
} as any)
const BookBookIdEditIndexRoute = BookBookIdEditIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookBookIdEditRouteRoute,
} as any)
const MainLayoutUserMeIndexRoute = MainLayoutUserMeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainLayoutUserMeRouteRoute,
} as any)
const BookBookIdEditTagRoute = BookBookIdEditTagRouteImport.update({
  id: '/tag',
  path: '/tag',
  getParentRoute: () => BookBookIdEditRouteRoute,
} as any)
const BookBookIdEditChapterRoute = BookBookIdEditChapterRouteImport.update({
  id: '/chapter',
  path: '/chapter',
  getParentRoute: () => BookBookIdEditRouteRoute,
} as any)
const BookBookIdEditChapterIdRoute = BookBookIdEditChapterIdRouteImport.update({
  id: '/$chapterId',
  path: '/$chapterId',
  getParentRoute: () => BookBookIdEditRouteRoute,
} as any)
const MainLayoutUserMeReactionRoute =
  MainLayoutUserMeReactionRouteImport.update({
    id: '/reaction',
    path: '/reaction',
    getParentRoute: () => MainLayoutUserMeRouteRoute,
  } as any)
const MainLayoutUserMeFollowRoute = MainLayoutUserMeFollowRouteImport.update({
  id: '/follow',
  path: '/follow',
  getParentRoute: () => MainLayoutUserMeRouteRoute,
} as any)
const MainLayoutUserMeEditRoute = MainLayoutUserMeEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => MainLayoutUserMeRouteRoute,
} as any)
const MainLayoutUserMeBookmarkRoute =
  MainLayoutUserMeBookmarkRouteImport.update({
    id: '/bookmark',
    path: '/bookmark',
    getParentRoute: () => MainLayoutUserMeRouteRoute,
  } as any)
const MainLayoutUserUnitIdEditRoute =
  MainLayoutUserUnitIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => MainLayoutUserUnitIdRoute,
  } as any)
const MainLayoutReviewNewBookUnitIdRoute =
  MainLayoutReviewNewBookUnitIdRouteImport.update({
    id: '/review/new/$bookUnitId',
    path: '/review/new/$bookUnitId',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutReviewBookBookIdRoute =
  MainLayoutReviewBookBookIdRouteImport.update({
    id: '/review/book/$bookId',
    path: '/review/book/$bookId',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutReviewReviewIdEditRoute =
  MainLayoutReviewReviewIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => MainLayoutReviewReviewIdRoute,
  } as any)
const MainLayoutReadlistBookBookIdRoute =
  MainLayoutReadlistBookBookIdRouteImport.update({
    id: '/readlist/book/$bookId',
    path: '/readlist/book/$bookId',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutReadlistReadlistIdEditRoute =
  MainLayoutReadlistReadlistIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => MainLayoutReadlistReadlistIdRoute,
  } as any)
const MainLayoutQuoteBookBookIdRoute =
  MainLayoutQuoteBookBookIdRouteImport.update({
    id: '/quote/book/$bookId',
    path: '/quote/book/$bookId',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutQuoteUnitIdEditRoute =
  MainLayoutQuoteUnitIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => MainLayoutQuoteUnitIdRoute,
  } as any)
const BookBookIdReadChapterIdRouteRoute =
  BookBookIdReadChapterIdRouteRouteImport.update({
    id: '/book_/$bookId/read/$chapterId',
    path: '/book/$bookId/read/$chapterId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MainLayoutTagDomainUnitIdRouteRoute =
  MainLayoutTagDomainUnitIdRouteRouteImport.update({
    id: '/tag/domain/$unitId',
    path: '/tag/domain/$unitId',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutTagBookBookIdRouteRoute =
  MainLayoutTagBookBookIdRouteRouteImport.update({
    id: '/tag/book/$bookId',
    path: '/tag/book/$bookId',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const BookBookIdReadChapterIdIndexRoute =
  BookBookIdReadChapterIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BookBookIdReadChapterIdRouteRoute,
  } as any)
const MainLayoutTagDomainUnitIdIndexRoute =
  MainLayoutTagDomainUnitIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MainLayoutTagDomainUnitIdRouteRoute,
  } as any)
const MainLayoutTagBookBookIdIndexRoute =
  MainLayoutTagBookBookIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MainLayoutTagBookBookIdRouteRoute,
  } as any)
const MainLayoutTagBookBookIdTagRouteRoute =
  MainLayoutTagBookBookIdTagRouteRouteImport.update({
    id: '/tag',
    path: '/tag',
    getParentRoute: () => MainLayoutTagBookBookIdRouteRoute,
  } as any)
const MainLayoutTagBookBookIdTagIndexRoute =
  MainLayoutTagBookBookIdTagIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MainLayoutTagBookBookIdTagRouteRoute,
  } as any)
const MainLayoutTagDomainUnitIdTitleTitleRoute =
  MainLayoutTagDomainUnitIdTitleTitleRouteImport.update({
    id: '/title/$title',
    path: '/title/$title',
    getParentRoute: () => MainLayoutTagDomainUnitIdRouteRoute,
  } as any)
const MainLayoutTagBookBookIdTagDomainIdRoute =
  MainLayoutTagBookBookIdTagDomainIdRouteImport.update({
    id: '/$domainId',
    path: '/$domainId',
    getParentRoute: () => MainLayoutTagBookBookIdTagRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainLayoutIndexRoute
  '/login': typeof MainLayoutLoginRoute
  '/meili': typeof MainLayoutMeiliRoute
  '/notice': typeof MainLayoutNoticeRoute
  '/register': typeof MainLayoutRegisterRoute
  '/reset-password': typeof MainLayoutResetPasswordRoute
  '/test': typeof MainLayoutTestRoute
  '/test02': typeof MainLayoutTest02Route
  '/test03': typeof MainLayoutTest03Route
  '/theme-switch': typeof MainLayoutThemeSwitchRoute
  '/token': typeof MainLayoutTokenRoute
  '/user/me': typeof MainLayoutUserMeRouteRouteWithChildren
  '/book/$bookId/edit': typeof BookBookIdEditRouteRouteWithChildren
  '/book/$bookId': typeof MainLayoutBookBookIdRoute
  '/book/new': typeof MainLayoutBookNewRoute
  '/feedback/admin': typeof MainLayoutFeedbackAdminRoute
  '/misc/echokv': typeof MainLayoutMiscEchokvRoute
  '/quote/$unitId': typeof MainLayoutQuoteUnitIdRouteWithChildren
  '/readlist/$readlistId': typeof MainLayoutReadlistReadlistIdRouteWithChildren
  '/readlist/new': typeof MainLayoutReadlistNewRoute
  '/remark/$reviewId': typeof MainLayoutRemarkReviewIdRoute
  '/review/$reviewId': typeof MainLayoutReviewReviewIdRouteWithChildren
  '/tag/$unitId': typeof MainLayoutTagUnitIdRoute
  '/unit/$unitId': typeof MainLayoutUnitUnitIdRoute
  '/user/$unitId': typeof MainLayoutUserUnitIdRouteWithChildren
  '/book/': typeof MainLayoutBookIndexRoute
  '/feedback/': typeof MainLayoutFeedbackIndexRoute
  '/readlist/': typeof MainLayoutReadlistIndexRoute
  '/review/': typeof MainLayoutReviewIndexRoute
  '/unit/': typeof MainLayoutUnitIndexRoute
  '/tag/book/$bookId': typeof MainLayoutTagBookBookIdRouteRouteWithChildren
  '/tag/domain/$unitId': typeof MainLayoutTagDomainUnitIdRouteRouteWithChildren
  '/book/$bookId/read/$chapterId': typeof BookBookIdReadChapterIdRouteRouteWithChildren
  '/quote/$unitId/edit': typeof MainLayoutQuoteUnitIdEditRoute
  '/quote/book/$bookId': typeof MainLayoutQuoteBookBookIdRoute
  '/readlist/$readlistId/edit': typeof MainLayoutReadlistReadlistIdEditRoute
  '/readlist/book/$bookId': typeof MainLayoutReadlistBookBookIdRoute
  '/review/$reviewId/edit': typeof MainLayoutReviewReviewIdEditRoute
  '/review/book/$bookId': typeof MainLayoutReviewBookBookIdRoute
  '/review/new/$bookUnitId': typeof MainLayoutReviewNewBookUnitIdRoute
  '/user/$unitId/edit': typeof MainLayoutUserUnitIdEditRoute
  '/user/me/bookmark': typeof MainLayoutUserMeBookmarkRoute
  '/user/me/edit': typeof MainLayoutUserMeEditRoute
  '/user/me/follow': typeof MainLayoutUserMeFollowRoute
  '/user/me/reaction': typeof MainLayoutUserMeReactionRoute
  '/book/$bookId/edit/$chapterId': typeof BookBookIdEditChapterIdRoute
  '/book/$bookId/edit/chapter': typeof BookBookIdEditChapterRoute
  '/book/$bookId/edit/tag': typeof BookBookIdEditTagRoute
  '/user/me/': typeof MainLayoutUserMeIndexRoute
  '/book/$bookId/edit/': typeof BookBookIdEditIndexRoute
  '/tag/book/$bookId/tag': typeof MainLayoutTagBookBookIdTagRouteRouteWithChildren
  '/tag/book/$bookId/': typeof MainLayoutTagBookBookIdIndexRoute
  '/tag/domain/$unitId/': typeof MainLayoutTagDomainUnitIdIndexRoute
  '/book/$bookId/read/$chapterId/': typeof BookBookIdReadChapterIdIndexRoute
  '/tag/book/$bookId/tag/$domainId': typeof MainLayoutTagBookBookIdTagDomainIdRoute
  '/tag/domain/$unitId/title/$title': typeof MainLayoutTagDomainUnitIdTitleTitleRoute
  '/tag/book/$bookId/tag/': typeof MainLayoutTagBookBookIdTagIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof MainLayoutLoginRoute
  '/meili': typeof MainLayoutMeiliRoute
  '/notice': typeof MainLayoutNoticeRoute
  '/register': typeof MainLayoutRegisterRoute
  '/reset-password': typeof MainLayoutResetPasswordRoute
  '/test': typeof MainLayoutTestRoute
  '/test02': typeof MainLayoutTest02Route
  '/test03': typeof MainLayoutTest03Route
  '/theme-switch': typeof MainLayoutThemeSwitchRoute
  '/token': typeof MainLayoutTokenRoute
  '/': typeof MainLayoutIndexRoute
  '/book/$bookId': typeof MainLayoutBookBookIdRoute
  '/book/new': typeof MainLayoutBookNewRoute
  '/feedback/admin': typeof MainLayoutFeedbackAdminRoute
  '/misc/echokv': typeof MainLayoutMiscEchokvRoute
  '/quote/$unitId': typeof MainLayoutQuoteUnitIdRouteWithChildren
  '/readlist/$readlistId': typeof MainLayoutReadlistReadlistIdRouteWithChildren
  '/readlist/new': typeof MainLayoutReadlistNewRoute
  '/remark/$reviewId': typeof MainLayoutRemarkReviewIdRoute
  '/review/$reviewId': typeof MainLayoutReviewReviewIdRouteWithChildren
  '/tag/$unitId': typeof MainLayoutTagUnitIdRoute
  '/unit/$unitId': typeof MainLayoutUnitUnitIdRoute
  '/user/$unitId': typeof MainLayoutUserUnitIdRouteWithChildren
  '/book': typeof MainLayoutBookIndexRoute
  '/feedback': typeof MainLayoutFeedbackIndexRoute
  '/readlist': typeof MainLayoutReadlistIndexRoute
  '/review': typeof MainLayoutReviewIndexRoute
  '/unit': typeof MainLayoutUnitIndexRoute
  '/quote/$unitId/edit': typeof MainLayoutQuoteUnitIdEditRoute
  '/quote/book/$bookId': typeof MainLayoutQuoteBookBookIdRoute
  '/readlist/$readlistId/edit': typeof MainLayoutReadlistReadlistIdEditRoute
  '/readlist/book/$bookId': typeof MainLayoutReadlistBookBookIdRoute
  '/review/$reviewId/edit': typeof MainLayoutReviewReviewIdEditRoute
  '/review/book/$bookId': typeof MainLayoutReviewBookBookIdRoute
  '/review/new/$bookUnitId': typeof MainLayoutReviewNewBookUnitIdRoute
  '/user/$unitId/edit': typeof MainLayoutUserUnitIdEditRoute
  '/user/me/bookmark': typeof MainLayoutUserMeBookmarkRoute
  '/user/me/edit': typeof MainLayoutUserMeEditRoute
  '/user/me/follow': typeof MainLayoutUserMeFollowRoute
  '/user/me/reaction': typeof MainLayoutUserMeReactionRoute
  '/book/$bookId/edit/$chapterId': typeof BookBookIdEditChapterIdRoute
  '/book/$bookId/edit/chapter': typeof BookBookIdEditChapterRoute
  '/book/$bookId/edit/tag': typeof BookBookIdEditTagRoute
  '/user/me': typeof MainLayoutUserMeIndexRoute
  '/book/$bookId/edit': typeof BookBookIdEditIndexRoute
  '/tag/book/$bookId': typeof MainLayoutTagBookBookIdIndexRoute
  '/tag/domain/$unitId': typeof MainLayoutTagDomainUnitIdIndexRoute
  '/book/$bookId/read/$chapterId': typeof BookBookIdReadChapterIdIndexRoute
  '/tag/book/$bookId/tag/$domainId': typeof MainLayoutTagBookBookIdTagDomainIdRoute
  '/tag/domain/$unitId/title/$title': typeof MainLayoutTagDomainUnitIdTitleTitleRoute
  '/tag/book/$bookId/tag': typeof MainLayoutTagBookBookIdTagIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_mainLayout': typeof MainLayoutRouteWithChildren
  '/_mainLayout/login': typeof MainLayoutLoginRoute
  '/_mainLayout/meili': typeof MainLayoutMeiliRoute
  '/_mainLayout/notice': typeof MainLayoutNoticeRoute
  '/_mainLayout/register': typeof MainLayoutRegisterRoute
  '/_mainLayout/reset-password': typeof MainLayoutResetPasswordRoute
  '/_mainLayout/test': typeof MainLayoutTestRoute
  '/_mainLayout/test02': typeof MainLayoutTest02Route
  '/_mainLayout/test03': typeof MainLayoutTest03Route
  '/_mainLayout/theme-switch': typeof MainLayoutThemeSwitchRoute
  '/_mainLayout/token': typeof MainLayoutTokenRoute
  '/_mainLayout/': typeof MainLayoutIndexRoute
  '/_mainLayout/user/me': typeof MainLayoutUserMeRouteRouteWithChildren
  '/book_/$bookId/edit': typeof BookBookIdEditRouteRouteWithChildren
  '/_mainLayout/book/$bookId': typeof MainLayoutBookBookIdRoute
  '/_mainLayout/book/new': typeof MainLayoutBookNewRoute
  '/_mainLayout/feedback/admin': typeof MainLayoutFeedbackAdminRoute
  '/_mainLayout/misc/echokv': typeof MainLayoutMiscEchokvRoute
  '/_mainLayout/quote/$unitId': typeof MainLayoutQuoteUnitIdRouteWithChildren
  '/_mainLayout/readlist/$readlistId': typeof MainLayoutReadlistReadlistIdRouteWithChildren
  '/_mainLayout/readlist/new': typeof MainLayoutReadlistNewRoute
  '/_mainLayout/remark/$reviewId': typeof MainLayoutRemarkReviewIdRoute
  '/_mainLayout/review/$reviewId': typeof MainLayoutReviewReviewIdRouteWithChildren
  '/_mainLayout/tag/$unitId': typeof MainLayoutTagUnitIdRoute
  '/_mainLayout/unit/$unitId': typeof MainLayoutUnitUnitIdRoute
  '/_mainLayout/user/$unitId': typeof MainLayoutUserUnitIdRouteWithChildren
  '/_mainLayout/book/': typeof MainLayoutBookIndexRoute
  '/_mainLayout/feedback/': typeof MainLayoutFeedbackIndexRoute
  '/_mainLayout/readlist/': typeof MainLayoutReadlistIndexRoute
  '/_mainLayout/review/': typeof MainLayoutReviewIndexRoute
  '/_mainLayout/unit/': typeof MainLayoutUnitIndexRoute
  '/_mainLayout/tag/book/$bookId': typeof MainLayoutTagBookBookIdRouteRouteWithChildren
  '/_mainLayout/tag/domain/$unitId': typeof MainLayoutTagDomainUnitIdRouteRouteWithChildren
  '/book_/$bookId/read/$chapterId': typeof BookBookIdReadChapterIdRouteRouteWithChildren
  '/_mainLayout/quote/$unitId/edit': typeof MainLayoutQuoteUnitIdEditRoute
  '/_mainLayout/quote/book/$bookId': typeof MainLayoutQuoteBookBookIdRoute
  '/_mainLayout/readlist/$readlistId/edit': typeof MainLayoutReadlistReadlistIdEditRoute
  '/_mainLayout/readlist/book/$bookId': typeof MainLayoutReadlistBookBookIdRoute
  '/_mainLayout/review/$reviewId/edit': typeof MainLayoutReviewReviewIdEditRoute
  '/_mainLayout/review/book/$bookId': typeof MainLayoutReviewBookBookIdRoute
  '/_mainLayout/review/new/$bookUnitId': typeof MainLayoutReviewNewBookUnitIdRoute
  '/_mainLayout/user/$unitId/edit': typeof MainLayoutUserUnitIdEditRoute
  '/_mainLayout/user/me/bookmark': typeof MainLayoutUserMeBookmarkRoute
  '/_mainLayout/user/me/edit': typeof MainLayoutUserMeEditRoute
  '/_mainLayout/user/me/follow': typeof MainLayoutUserMeFollowRoute
  '/_mainLayout/user/me/reaction': typeof MainLayoutUserMeReactionRoute
  '/book_/$bookId/edit/$chapterId': typeof BookBookIdEditChapterIdRoute
  '/book_/$bookId/edit/chapter': typeof BookBookIdEditChapterRoute
  '/book_/$bookId/edit/tag': typeof BookBookIdEditTagRoute
  '/_mainLayout/user/me/': typeof MainLayoutUserMeIndexRoute
  '/book_/$bookId/edit/': typeof BookBookIdEditIndexRoute
  '/_mainLayout/tag/book/$bookId/tag': typeof MainLayoutTagBookBookIdTagRouteRouteWithChildren
  '/_mainLayout/tag/book/$bookId/': typeof MainLayoutTagBookBookIdIndexRoute
  '/_mainLayout/tag/domain/$unitId/': typeof MainLayoutTagDomainUnitIdIndexRoute
  '/book_/$bookId/read/$chapterId/': typeof BookBookIdReadChapterIdIndexRoute
  '/_mainLayout/tag/book/$bookId/tag/$domainId': typeof MainLayoutTagBookBookIdTagDomainIdRoute
  '/_mainLayout/tag/domain/$unitId/title/$title': typeof MainLayoutTagDomainUnitIdTitleTitleRoute
  '/_mainLayout/tag/book/$bookId/tag/': typeof MainLayoutTagBookBookIdTagIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/meili'
    | '/notice'
    | '/register'
    | '/reset-password'
    | '/test'
    | '/test02'
    | '/test03'
    | '/theme-switch'
    | '/token'
    | '/user/me'
    | '/book/$bookId/edit'
    | '/book/$bookId'
    | '/book/new'
    | '/feedback/admin'
    | '/misc/echokv'
    | '/quote/$unitId'
    | '/readlist/$readlistId'
    | '/readlist/new'
    | '/remark/$reviewId'
    | '/review/$reviewId'
    | '/tag/$unitId'
    | '/unit/$unitId'
    | '/user/$unitId'
    | '/book/'
    | '/feedback/'
    | '/readlist/'
    | '/review/'
    | '/unit/'
    | '/tag/book/$bookId'
    | '/tag/domain/$unitId'
    | '/book/$bookId/read/$chapterId'
    | '/quote/$unitId/edit'
    | '/quote/book/$bookId'
    | '/readlist/$readlistId/edit'
    | '/readlist/book/$bookId'
    | '/review/$reviewId/edit'
    | '/review/book/$bookId'
    | '/review/new/$bookUnitId'
    | '/user/$unitId/edit'
    | '/user/me/bookmark'
    | '/user/me/edit'
    | '/user/me/follow'
    | '/user/me/reaction'
    | '/book/$bookId/edit/$chapterId'
    | '/book/$bookId/edit/chapter'
    | '/book/$bookId/edit/tag'
    | '/user/me/'
    | '/book/$bookId/edit/'
    | '/tag/book/$bookId/tag'
    | '/tag/book/$bookId/'
    | '/tag/domain/$unitId/'
    | '/book/$bookId/read/$chapterId/'
    | '/tag/book/$bookId/tag/$domainId'
    | '/tag/domain/$unitId/title/$title'
    | '/tag/book/$bookId/tag/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/meili'
    | '/notice'
    | '/register'
    | '/reset-password'
    | '/test'
    | '/test02'
    | '/test03'
    | '/theme-switch'
    | '/token'
    | '/'
    | '/book/$bookId'
    | '/book/new'
    | '/feedback/admin'
    | '/misc/echokv'
    | '/quote/$unitId'
    | '/readlist/$readlistId'
    | '/readlist/new'
    | '/remark/$reviewId'
    | '/review/$reviewId'
    | '/tag/$unitId'
    | '/unit/$unitId'
    | '/user/$unitId'
    | '/book'
    | '/feedback'
    | '/readlist'
    | '/review'
    | '/unit'
    | '/quote/$unitId/edit'
    | '/quote/book/$bookId'
    | '/readlist/$readlistId/edit'
    | '/readlist/book/$bookId'
    | '/review/$reviewId/edit'
    | '/review/book/$bookId'
    | '/review/new/$bookUnitId'
    | '/user/$unitId/edit'
    | '/user/me/bookmark'
    | '/user/me/edit'
    | '/user/me/follow'
    | '/user/me/reaction'
    | '/book/$bookId/edit/$chapterId'
    | '/book/$bookId/edit/chapter'
    | '/book/$bookId/edit/tag'
    | '/user/me'
    | '/book/$bookId/edit'
    | '/tag/book/$bookId'
    | '/tag/domain/$unitId'
    | '/book/$bookId/read/$chapterId'
    | '/tag/book/$bookId/tag/$domainId'
    | '/tag/domain/$unitId/title/$title'
    | '/tag/book/$bookId/tag'
  id:
    | '__root__'
    | '/_mainLayout'
    | '/_mainLayout/login'
    | '/_mainLayout/meili'
    | '/_mainLayout/notice'
    | '/_mainLayout/register'
    | '/_mainLayout/reset-password'
    | '/_mainLayout/test'
    | '/_mainLayout/test02'
    | '/_mainLayout/test03'
    | '/_mainLayout/theme-switch'
    | '/_mainLayout/token'
    | '/_mainLayout/'
    | '/_mainLayout/user/me'
    | '/book_/$bookId/edit'
    | '/_mainLayout/book/$bookId'
    | '/_mainLayout/book/new'
    | '/_mainLayout/feedback/admin'
    | '/_mainLayout/misc/echokv'
    | '/_mainLayout/quote/$unitId'
    | '/_mainLayout/readlist/$readlistId'
    | '/_mainLayout/readlist/new'
    | '/_mainLayout/remark/$reviewId'
    | '/_mainLayout/review/$reviewId'
    | '/_mainLayout/tag/$unitId'
    | '/_mainLayout/unit/$unitId'
    | '/_mainLayout/user/$unitId'
    | '/_mainLayout/book/'
    | '/_mainLayout/feedback/'
    | '/_mainLayout/readlist/'
    | '/_mainLayout/review/'
    | '/_mainLayout/unit/'
    | '/_mainLayout/tag/book/$bookId'
    | '/_mainLayout/tag/domain/$unitId'
    | '/book_/$bookId/read/$chapterId'
    | '/_mainLayout/quote/$unitId/edit'
    | '/_mainLayout/quote/book/$bookId'
    | '/_mainLayout/readlist/$readlistId/edit'
    | '/_mainLayout/readlist/book/$bookId'
    | '/_mainLayout/review/$reviewId/edit'
    | '/_mainLayout/review/book/$bookId'
    | '/_mainLayout/review/new/$bookUnitId'
    | '/_mainLayout/user/$unitId/edit'
    | '/_mainLayout/user/me/bookmark'
    | '/_mainLayout/user/me/edit'
    | '/_mainLayout/user/me/follow'
    | '/_mainLayout/user/me/reaction'
    | '/book_/$bookId/edit/$chapterId'
    | '/book_/$bookId/edit/chapter'
    | '/book_/$bookId/edit/tag'
    | '/_mainLayout/user/me/'
    | '/book_/$bookId/edit/'
    | '/_mainLayout/tag/book/$bookId/tag'
    | '/_mainLayout/tag/book/$bookId/'
    | '/_mainLayout/tag/domain/$unitId/'
    | '/book_/$bookId/read/$chapterId/'
    | '/_mainLayout/tag/book/$bookId/tag/$domainId'
    | '/_mainLayout/tag/domain/$unitId/title/$title'
    | '/_mainLayout/tag/book/$bookId/tag/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainLayoutRoute: typeof MainLayoutRouteWithChildren
  BookBookIdEditRouteRoute: typeof BookBookIdEditRouteRouteWithChildren
  BookBookIdReadChapterIdRouteRoute: typeof BookBookIdReadChapterIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_mainLayout': {
      id: '/_mainLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mainLayout/': {
      id: '/_mainLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/token': {
      id: '/_mainLayout/token'
      path: '/token'
      fullPath: '/token'
      preLoaderRoute: typeof MainLayoutTokenRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/theme-switch': {
      id: '/_mainLayout/theme-switch'
      path: '/theme-switch'
      fullPath: '/theme-switch'
      preLoaderRoute: typeof MainLayoutThemeSwitchRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/test03': {
      id: '/_mainLayout/test03'
      path: '/test03'
      fullPath: '/test03'
      preLoaderRoute: typeof MainLayoutTest03RouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/test02': {
      id: '/_mainLayout/test02'
      path: '/test02'
      fullPath: '/test02'
      preLoaderRoute: typeof MainLayoutTest02RouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/test': {
      id: '/_mainLayout/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof MainLayoutTestRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/reset-password': {
      id: '/_mainLayout/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof MainLayoutResetPasswordRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/register': {
      id: '/_mainLayout/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof MainLayoutRegisterRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/notice': {
      id: '/_mainLayout/notice'
      path: '/notice'
      fullPath: '/notice'
      preLoaderRoute: typeof MainLayoutNoticeRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/meili': {
      id: '/_mainLayout/meili'
      path: '/meili'
      fullPath: '/meili'
      preLoaderRoute: typeof MainLayoutMeiliRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/login': {
      id: '/_mainLayout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof MainLayoutLoginRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/unit/': {
      id: '/_mainLayout/unit/'
      path: '/unit'
      fullPath: '/unit/'
      preLoaderRoute: typeof MainLayoutUnitIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/review/': {
      id: '/_mainLayout/review/'
      path: '/review'
      fullPath: '/review/'
      preLoaderRoute: typeof MainLayoutReviewIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/readlist/': {
      id: '/_mainLayout/readlist/'
      path: '/readlist'
      fullPath: '/readlist/'
      preLoaderRoute: typeof MainLayoutReadlistIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/feedback/': {
      id: '/_mainLayout/feedback/'
      path: '/feedback'
      fullPath: '/feedback/'
      preLoaderRoute: typeof MainLayoutFeedbackIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/book/': {
      id: '/_mainLayout/book/'
      path: '/book'
      fullPath: '/book/'
      preLoaderRoute: typeof MainLayoutBookIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/user/$unitId': {
      id: '/_mainLayout/user/$unitId'
      path: '/user/$unitId'
      fullPath: '/user/$unitId'
      preLoaderRoute: typeof MainLayoutUserUnitIdRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/unit/$unitId': {
      id: '/_mainLayout/unit/$unitId'
      path: '/unit/$unitId'
      fullPath: '/unit/$unitId'
      preLoaderRoute: typeof MainLayoutUnitUnitIdRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/tag/$unitId': {
      id: '/_mainLayout/tag/$unitId'
      path: '/tag/$unitId'
      fullPath: '/tag/$unitId'
      preLoaderRoute: typeof MainLayoutTagUnitIdRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/review/$reviewId': {
      id: '/_mainLayout/review/$reviewId'
      path: '/review/$reviewId'
      fullPath: '/review/$reviewId'
      preLoaderRoute: typeof MainLayoutReviewReviewIdRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/remark/$reviewId': {
      id: '/_mainLayout/remark/$reviewId'
      path: '/remark/$reviewId'
      fullPath: '/remark/$reviewId'
      preLoaderRoute: typeof MainLayoutRemarkReviewIdRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/readlist/new': {
      id: '/_mainLayout/readlist/new'
      path: '/readlist/new'
      fullPath: '/readlist/new'
      preLoaderRoute: typeof MainLayoutReadlistNewRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/readlist/$readlistId': {
      id: '/_mainLayout/readlist/$readlistId'
      path: '/readlist/$readlistId'
      fullPath: '/readlist/$readlistId'
      preLoaderRoute: typeof MainLayoutReadlistReadlistIdRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/quote/$unitId': {
      id: '/_mainLayout/quote/$unitId'
      path: '/quote/$unitId'
      fullPath: '/quote/$unitId'
      preLoaderRoute: typeof MainLayoutQuoteUnitIdRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/misc/echokv': {
      id: '/_mainLayout/misc/echokv'
      path: '/misc/echokv'
      fullPath: '/misc/echokv'
      preLoaderRoute: typeof MainLayoutMiscEchokvRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/feedback/admin': {
      id: '/_mainLayout/feedback/admin'
      path: '/feedback/admin'
      fullPath: '/feedback/admin'
      preLoaderRoute: typeof MainLayoutFeedbackAdminRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/book/new': {
      id: '/_mainLayout/book/new'
      path: '/book/new'
      fullPath: '/book/new'
      preLoaderRoute: typeof MainLayoutBookNewRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/book/$bookId': {
      id: '/_mainLayout/book/$bookId'
      path: '/book/$bookId'
      fullPath: '/book/$bookId'
      preLoaderRoute: typeof MainLayoutBookBookIdRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/book_/$bookId/edit': {
      id: '/book_/$bookId/edit'
      path: '/book/$bookId/edit'
      fullPath: '/book/$bookId/edit'
      preLoaderRoute: typeof BookBookIdEditRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mainLayout/user/me': {
      id: '/_mainLayout/user/me'
      path: '/user/me'
      fullPath: '/user/me'
      preLoaderRoute: typeof MainLayoutUserMeRouteRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/book_/$bookId/edit/': {
      id: '/book_/$bookId/edit/'
      path: '/'
      fullPath: '/book/$bookId/edit/'
      preLoaderRoute: typeof BookBookIdEditIndexRouteImport
      parentRoute: typeof BookBookIdEditRouteRoute
    }
    '/_mainLayout/user/me/': {
      id: '/_mainLayout/user/me/'
      path: '/'
      fullPath: '/user/me/'
      preLoaderRoute: typeof MainLayoutUserMeIndexRouteImport
      parentRoute: typeof MainLayoutUserMeRouteRoute
    }
    '/book_/$bookId/edit/tag': {
      id: '/book_/$bookId/edit/tag'
      path: '/tag'
      fullPath: '/book/$bookId/edit/tag'
      preLoaderRoute: typeof BookBookIdEditTagRouteImport
      parentRoute: typeof BookBookIdEditRouteRoute
    }
    '/book_/$bookId/edit/chapter': {
      id: '/book_/$bookId/edit/chapter'
      path: '/chapter'
      fullPath: '/book/$bookId/edit/chapter'
      preLoaderRoute: typeof BookBookIdEditChapterRouteImport
      parentRoute: typeof BookBookIdEditRouteRoute
    }
    '/book_/$bookId/edit/$chapterId': {
      id: '/book_/$bookId/edit/$chapterId'
      path: '/$chapterId'
      fullPath: '/book/$bookId/edit/$chapterId'
      preLoaderRoute: typeof BookBookIdEditChapterIdRouteImport
      parentRoute: typeof BookBookIdEditRouteRoute
    }
    '/_mainLayout/user/me/reaction': {
      id: '/_mainLayout/user/me/reaction'
      path: '/reaction'
      fullPath: '/user/me/reaction'
      preLoaderRoute: typeof MainLayoutUserMeReactionRouteImport
      parentRoute: typeof MainLayoutUserMeRouteRoute
    }
    '/_mainLayout/user/me/follow': {
      id: '/_mainLayout/user/me/follow'
      path: '/follow'
      fullPath: '/user/me/follow'
      preLoaderRoute: typeof MainLayoutUserMeFollowRouteImport
      parentRoute: typeof MainLayoutUserMeRouteRoute
    }
    '/_mainLayout/user/me/edit': {
      id: '/_mainLayout/user/me/edit'
      path: '/edit'
      fullPath: '/user/me/edit'
      preLoaderRoute: typeof MainLayoutUserMeEditRouteImport
      parentRoute: typeof MainLayoutUserMeRouteRoute
    }
    '/_mainLayout/user/me/bookmark': {
      id: '/_mainLayout/user/me/bookmark'
      path: '/bookmark'
      fullPath: '/user/me/bookmark'
      preLoaderRoute: typeof MainLayoutUserMeBookmarkRouteImport
      parentRoute: typeof MainLayoutUserMeRouteRoute
    }
    '/_mainLayout/user/$unitId/edit': {
      id: '/_mainLayout/user/$unitId/edit'
      path: '/edit'
      fullPath: '/user/$unitId/edit'
      preLoaderRoute: typeof MainLayoutUserUnitIdEditRouteImport
      parentRoute: typeof MainLayoutUserUnitIdRoute
    }
    '/_mainLayout/review/new/$bookUnitId': {
      id: '/_mainLayout/review/new/$bookUnitId'
      path: '/review/new/$bookUnitId'
      fullPath: '/review/new/$bookUnitId'
      preLoaderRoute: typeof MainLayoutReviewNewBookUnitIdRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/review/book/$bookId': {
      id: '/_mainLayout/review/book/$bookId'
      path: '/review/book/$bookId'
      fullPath: '/review/book/$bookId'
      preLoaderRoute: typeof MainLayoutReviewBookBookIdRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/review/$reviewId/edit': {
      id: '/_mainLayout/review/$reviewId/edit'
      path: '/edit'
      fullPath: '/review/$reviewId/edit'
      preLoaderRoute: typeof MainLayoutReviewReviewIdEditRouteImport
      parentRoute: typeof MainLayoutReviewReviewIdRoute
    }
    '/_mainLayout/readlist/book/$bookId': {
      id: '/_mainLayout/readlist/book/$bookId'
      path: '/readlist/book/$bookId'
      fullPath: '/readlist/book/$bookId'
      preLoaderRoute: typeof MainLayoutReadlistBookBookIdRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/readlist/$readlistId/edit': {
      id: '/_mainLayout/readlist/$readlistId/edit'
      path: '/edit'
      fullPath: '/readlist/$readlistId/edit'
      preLoaderRoute: typeof MainLayoutReadlistReadlistIdEditRouteImport
      parentRoute: typeof MainLayoutReadlistReadlistIdRoute
    }
    '/_mainLayout/quote/book/$bookId': {
      id: '/_mainLayout/quote/book/$bookId'
      path: '/quote/book/$bookId'
      fullPath: '/quote/book/$bookId'
      preLoaderRoute: typeof MainLayoutQuoteBookBookIdRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/quote/$unitId/edit': {
      id: '/_mainLayout/quote/$unitId/edit'
      path: '/edit'
      fullPath: '/quote/$unitId/edit'
      preLoaderRoute: typeof MainLayoutQuoteUnitIdEditRouteImport
      parentRoute: typeof MainLayoutQuoteUnitIdRoute
    }
    '/book_/$bookId/read/$chapterId': {
      id: '/book_/$bookId/read/$chapterId'
      path: '/book/$bookId/read/$chapterId'
      fullPath: '/book/$bookId/read/$chapterId'
      preLoaderRoute: typeof BookBookIdReadChapterIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mainLayout/tag/domain/$unitId': {
      id: '/_mainLayout/tag/domain/$unitId'
      path: '/tag/domain/$unitId'
      fullPath: '/tag/domain/$unitId'
      preLoaderRoute: typeof MainLayoutTagDomainUnitIdRouteRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/tag/book/$bookId': {
      id: '/_mainLayout/tag/book/$bookId'
      path: '/tag/book/$bookId'
      fullPath: '/tag/book/$bookId'
      preLoaderRoute: typeof MainLayoutTagBookBookIdRouteRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/book_/$bookId/read/$chapterId/': {
      id: '/book_/$bookId/read/$chapterId/'
      path: '/'
      fullPath: '/book/$bookId/read/$chapterId/'
      preLoaderRoute: typeof BookBookIdReadChapterIdIndexRouteImport
      parentRoute: typeof BookBookIdReadChapterIdRouteRoute
    }
    '/_mainLayout/tag/domain/$unitId/': {
      id: '/_mainLayout/tag/domain/$unitId/'
      path: '/'
      fullPath: '/tag/domain/$unitId/'
      preLoaderRoute: typeof MainLayoutTagDomainUnitIdIndexRouteImport
      parentRoute: typeof MainLayoutTagDomainUnitIdRouteRoute
    }
    '/_mainLayout/tag/book/$bookId/': {
      id: '/_mainLayout/tag/book/$bookId/'
      path: '/'
      fullPath: '/tag/book/$bookId/'
      preLoaderRoute: typeof MainLayoutTagBookBookIdIndexRouteImport
      parentRoute: typeof MainLayoutTagBookBookIdRouteRoute
    }
    '/_mainLayout/tag/book/$bookId/tag': {
      id: '/_mainLayout/tag/book/$bookId/tag'
      path: '/tag'
      fullPath: '/tag/book/$bookId/tag'
      preLoaderRoute: typeof MainLayoutTagBookBookIdTagRouteRouteImport
      parentRoute: typeof MainLayoutTagBookBookIdRouteRoute
    }
    '/_mainLayout/tag/book/$bookId/tag/': {
      id: '/_mainLayout/tag/book/$bookId/tag/'
      path: '/'
      fullPath: '/tag/book/$bookId/tag/'
      preLoaderRoute: typeof MainLayoutTagBookBookIdTagIndexRouteImport
      parentRoute: typeof MainLayoutTagBookBookIdTagRouteRoute
    }
    '/_mainLayout/tag/domain/$unitId/title/$title': {
      id: '/_mainLayout/tag/domain/$unitId/title/$title'
      path: '/title/$title'
      fullPath: '/tag/domain/$unitId/title/$title'
      preLoaderRoute: typeof MainLayoutTagDomainUnitIdTitleTitleRouteImport
      parentRoute: typeof MainLayoutTagDomainUnitIdRouteRoute
    }
    '/_mainLayout/tag/book/$bookId/tag/$domainId': {
      id: '/_mainLayout/tag/book/$bookId/tag/$domainId'
      path: '/$domainId'
      fullPath: '/tag/book/$bookId/tag/$domainId'
      preLoaderRoute: typeof MainLayoutTagBookBookIdTagDomainIdRouteImport
      parentRoute: typeof MainLayoutTagBookBookIdTagRouteRoute
    }
  }
}

interface MainLayoutUserMeRouteRouteChildren {
  MainLayoutUserMeBookmarkRoute: typeof MainLayoutUserMeBookmarkRoute
  MainLayoutUserMeEditRoute: typeof MainLayoutUserMeEditRoute
  MainLayoutUserMeFollowRoute: typeof MainLayoutUserMeFollowRoute
  MainLayoutUserMeReactionRoute: typeof MainLayoutUserMeReactionRoute
  MainLayoutUserMeIndexRoute: typeof MainLayoutUserMeIndexRoute
}

const MainLayoutUserMeRouteRouteChildren: MainLayoutUserMeRouteRouteChildren = {
  MainLayoutUserMeBookmarkRoute: MainLayoutUserMeBookmarkRoute,
  MainLayoutUserMeEditRoute: MainLayoutUserMeEditRoute,
  MainLayoutUserMeFollowRoute: MainLayoutUserMeFollowRoute,
  MainLayoutUserMeReactionRoute: MainLayoutUserMeReactionRoute,
  MainLayoutUserMeIndexRoute: MainLayoutUserMeIndexRoute,
}

const MainLayoutUserMeRouteRouteWithChildren =
  MainLayoutUserMeRouteRoute._addFileChildren(
    MainLayoutUserMeRouteRouteChildren,
  )

interface MainLayoutQuoteUnitIdRouteChildren {
  MainLayoutQuoteUnitIdEditRoute: typeof MainLayoutQuoteUnitIdEditRoute
}

const MainLayoutQuoteUnitIdRouteChildren: MainLayoutQuoteUnitIdRouteChildren = {
  MainLayoutQuoteUnitIdEditRoute: MainLayoutQuoteUnitIdEditRoute,
}

const MainLayoutQuoteUnitIdRouteWithChildren =
  MainLayoutQuoteUnitIdRoute._addFileChildren(
    MainLayoutQuoteUnitIdRouteChildren,
  )

interface MainLayoutReadlistReadlistIdRouteChildren {
  MainLayoutReadlistReadlistIdEditRoute: typeof MainLayoutReadlistReadlistIdEditRoute
}

const MainLayoutReadlistReadlistIdRouteChildren: MainLayoutReadlistReadlistIdRouteChildren =
  {
    MainLayoutReadlistReadlistIdEditRoute:
      MainLayoutReadlistReadlistIdEditRoute,
  }

const MainLayoutReadlistReadlistIdRouteWithChildren =
  MainLayoutReadlistReadlistIdRoute._addFileChildren(
    MainLayoutReadlistReadlistIdRouteChildren,
  )

interface MainLayoutReviewReviewIdRouteChildren {
  MainLayoutReviewReviewIdEditRoute: typeof MainLayoutReviewReviewIdEditRoute
}

const MainLayoutReviewReviewIdRouteChildren: MainLayoutReviewReviewIdRouteChildren =
  {
    MainLayoutReviewReviewIdEditRoute: MainLayoutReviewReviewIdEditRoute,
  }

const MainLayoutReviewReviewIdRouteWithChildren =
  MainLayoutReviewReviewIdRoute._addFileChildren(
    MainLayoutReviewReviewIdRouteChildren,
  )

interface MainLayoutUserUnitIdRouteChildren {
  MainLayoutUserUnitIdEditRoute: typeof MainLayoutUserUnitIdEditRoute
}

const MainLayoutUserUnitIdRouteChildren: MainLayoutUserUnitIdRouteChildren = {
  MainLayoutUserUnitIdEditRoute: MainLayoutUserUnitIdEditRoute,
}

const MainLayoutUserUnitIdRouteWithChildren =
  MainLayoutUserUnitIdRoute._addFileChildren(MainLayoutUserUnitIdRouteChildren)

interface MainLayoutTagBookBookIdTagRouteRouteChildren {
  MainLayoutTagBookBookIdTagDomainIdRoute: typeof MainLayoutTagBookBookIdTagDomainIdRoute
  MainLayoutTagBookBookIdTagIndexRoute: typeof MainLayoutTagBookBookIdTagIndexRoute
}

const MainLayoutTagBookBookIdTagRouteRouteChildren: MainLayoutTagBookBookIdTagRouteRouteChildren =
  {
    MainLayoutTagBookBookIdTagDomainIdRoute:
      MainLayoutTagBookBookIdTagDomainIdRoute,
    MainLayoutTagBookBookIdTagIndexRoute: MainLayoutTagBookBookIdTagIndexRoute,
  }

const MainLayoutTagBookBookIdTagRouteRouteWithChildren =
  MainLayoutTagBookBookIdTagRouteRoute._addFileChildren(
    MainLayoutTagBookBookIdTagRouteRouteChildren,
  )

interface MainLayoutTagBookBookIdRouteRouteChildren {
  MainLayoutTagBookBookIdTagRouteRoute: typeof MainLayoutTagBookBookIdTagRouteRouteWithChildren
  MainLayoutTagBookBookIdIndexRoute: typeof MainLayoutTagBookBookIdIndexRoute
}

const MainLayoutTagBookBookIdRouteRouteChildren: MainLayoutTagBookBookIdRouteRouteChildren =
  {
    MainLayoutTagBookBookIdTagRouteRoute:
      MainLayoutTagBookBookIdTagRouteRouteWithChildren,
    MainLayoutTagBookBookIdIndexRoute: MainLayoutTagBookBookIdIndexRoute,
  }

const MainLayoutTagBookBookIdRouteRouteWithChildren =
  MainLayoutTagBookBookIdRouteRoute._addFileChildren(
    MainLayoutTagBookBookIdRouteRouteChildren,
  )

interface MainLayoutTagDomainUnitIdRouteRouteChildren {
  MainLayoutTagDomainUnitIdIndexRoute: typeof MainLayoutTagDomainUnitIdIndexRoute
  MainLayoutTagDomainUnitIdTitleTitleRoute: typeof MainLayoutTagDomainUnitIdTitleTitleRoute
}

const MainLayoutTagDomainUnitIdRouteRouteChildren: MainLayoutTagDomainUnitIdRouteRouteChildren =
  {
    MainLayoutTagDomainUnitIdIndexRoute: MainLayoutTagDomainUnitIdIndexRoute,
    MainLayoutTagDomainUnitIdTitleTitleRoute:
      MainLayoutTagDomainUnitIdTitleTitleRoute,
  }

const MainLayoutTagDomainUnitIdRouteRouteWithChildren =
  MainLayoutTagDomainUnitIdRouteRoute._addFileChildren(
    MainLayoutTagDomainUnitIdRouteRouteChildren,
  )

interface MainLayoutRouteChildren {
  MainLayoutLoginRoute: typeof MainLayoutLoginRoute
  MainLayoutMeiliRoute: typeof MainLayoutMeiliRoute
  MainLayoutNoticeRoute: typeof MainLayoutNoticeRoute
  MainLayoutRegisterRoute: typeof MainLayoutRegisterRoute
  MainLayoutResetPasswordRoute: typeof MainLayoutResetPasswordRoute
  MainLayoutTestRoute: typeof MainLayoutTestRoute
  MainLayoutTest02Route: typeof MainLayoutTest02Route
  MainLayoutTest03Route: typeof MainLayoutTest03Route
  MainLayoutThemeSwitchRoute: typeof MainLayoutThemeSwitchRoute
  MainLayoutTokenRoute: typeof MainLayoutTokenRoute
  MainLayoutIndexRoute: typeof MainLayoutIndexRoute
  MainLayoutUserMeRouteRoute: typeof MainLayoutUserMeRouteRouteWithChildren
  MainLayoutBookBookIdRoute: typeof MainLayoutBookBookIdRoute
  MainLayoutBookNewRoute: typeof MainLayoutBookNewRoute
  MainLayoutFeedbackAdminRoute: typeof MainLayoutFeedbackAdminRoute
  MainLayoutMiscEchokvRoute: typeof MainLayoutMiscEchokvRoute
  MainLayoutQuoteUnitIdRoute: typeof MainLayoutQuoteUnitIdRouteWithChildren
  MainLayoutReadlistReadlistIdRoute: typeof MainLayoutReadlistReadlistIdRouteWithChildren
  MainLayoutReadlistNewRoute: typeof MainLayoutReadlistNewRoute
  MainLayoutRemarkReviewIdRoute: typeof MainLayoutRemarkReviewIdRoute
  MainLayoutReviewReviewIdRoute: typeof MainLayoutReviewReviewIdRouteWithChildren
  MainLayoutTagUnitIdRoute: typeof MainLayoutTagUnitIdRoute
  MainLayoutUnitUnitIdRoute: typeof MainLayoutUnitUnitIdRoute
  MainLayoutUserUnitIdRoute: typeof MainLayoutUserUnitIdRouteWithChildren
  MainLayoutBookIndexRoute: typeof MainLayoutBookIndexRoute
  MainLayoutFeedbackIndexRoute: typeof MainLayoutFeedbackIndexRoute
  MainLayoutReadlistIndexRoute: typeof MainLayoutReadlistIndexRoute
  MainLayoutReviewIndexRoute: typeof MainLayoutReviewIndexRoute
  MainLayoutUnitIndexRoute: typeof MainLayoutUnitIndexRoute
  MainLayoutTagBookBookIdRouteRoute: typeof MainLayoutTagBookBookIdRouteRouteWithChildren
  MainLayoutTagDomainUnitIdRouteRoute: typeof MainLayoutTagDomainUnitIdRouteRouteWithChildren
  MainLayoutQuoteBookBookIdRoute: typeof MainLayoutQuoteBookBookIdRoute
  MainLayoutReadlistBookBookIdRoute: typeof MainLayoutReadlistBookBookIdRoute
  MainLayoutReviewBookBookIdRoute: typeof MainLayoutReviewBookBookIdRoute
  MainLayoutReviewNewBookUnitIdRoute: typeof MainLayoutReviewNewBookUnitIdRoute
}

const MainLayoutRouteChildren: MainLayoutRouteChildren = {
  MainLayoutLoginRoute: MainLayoutLoginRoute,
  MainLayoutMeiliRoute: MainLayoutMeiliRoute,
  MainLayoutNoticeRoute: MainLayoutNoticeRoute,
  MainLayoutRegisterRoute: MainLayoutRegisterRoute,
  MainLayoutResetPasswordRoute: MainLayoutResetPasswordRoute,
  MainLayoutTestRoute: MainLayoutTestRoute,
  MainLayoutTest02Route: MainLayoutTest02Route,
  MainLayoutTest03Route: MainLayoutTest03Route,
  MainLayoutThemeSwitchRoute: MainLayoutThemeSwitchRoute,
  MainLayoutTokenRoute: MainLayoutTokenRoute,
  MainLayoutIndexRoute: MainLayoutIndexRoute,
  MainLayoutUserMeRouteRoute: MainLayoutUserMeRouteRouteWithChildren,
  MainLayoutBookBookIdRoute: MainLayoutBookBookIdRoute,
  MainLayoutBookNewRoute: MainLayoutBookNewRoute,
  MainLayoutFeedbackAdminRoute: MainLayoutFeedbackAdminRoute,
  MainLayoutMiscEchokvRoute: MainLayoutMiscEchokvRoute,
  MainLayoutQuoteUnitIdRoute: MainLayoutQuoteUnitIdRouteWithChildren,
  MainLayoutReadlistReadlistIdRoute:
    MainLayoutReadlistReadlistIdRouteWithChildren,
  MainLayoutReadlistNewRoute: MainLayoutReadlistNewRoute,
  MainLayoutRemarkReviewIdRoute: MainLayoutRemarkReviewIdRoute,
  MainLayoutReviewReviewIdRoute: MainLayoutReviewReviewIdRouteWithChildren,
  MainLayoutTagUnitIdRoute: MainLayoutTagUnitIdRoute,
  MainLayoutUnitUnitIdRoute: MainLayoutUnitUnitIdRoute,
  MainLayoutUserUnitIdRoute: MainLayoutUserUnitIdRouteWithChildren,
  MainLayoutBookIndexRoute: MainLayoutBookIndexRoute,
  MainLayoutFeedbackIndexRoute: MainLayoutFeedbackIndexRoute,
  MainLayoutReadlistIndexRoute: MainLayoutReadlistIndexRoute,
  MainLayoutReviewIndexRoute: MainLayoutReviewIndexRoute,
  MainLayoutUnitIndexRoute: MainLayoutUnitIndexRoute,
  MainLayoutTagBookBookIdRouteRoute:
    MainLayoutTagBookBookIdRouteRouteWithChildren,
  MainLayoutTagDomainUnitIdRouteRoute:
    MainLayoutTagDomainUnitIdRouteRouteWithChildren,
  MainLayoutQuoteBookBookIdRoute: MainLayoutQuoteBookBookIdRoute,
  MainLayoutReadlistBookBookIdRoute: MainLayoutReadlistBookBookIdRoute,
  MainLayoutReviewBookBookIdRoute: MainLayoutReviewBookBookIdRoute,
  MainLayoutReviewNewBookUnitIdRoute: MainLayoutReviewNewBookUnitIdRoute,
}

const MainLayoutRouteWithChildren = MainLayoutRoute._addFileChildren(
  MainLayoutRouteChildren,
)

interface BookBookIdEditRouteRouteChildren {
  BookBookIdEditChapterIdRoute: typeof BookBookIdEditChapterIdRoute
  BookBookIdEditChapterRoute: typeof BookBookIdEditChapterRoute
  BookBookIdEditTagRoute: typeof BookBookIdEditTagRoute
  BookBookIdEditIndexRoute: typeof BookBookIdEditIndexRoute
}

const BookBookIdEditRouteRouteChildren: BookBookIdEditRouteRouteChildren = {
  BookBookIdEditChapterIdRoute: BookBookIdEditChapterIdRoute,
  BookBookIdEditChapterRoute: BookBookIdEditChapterRoute,
  BookBookIdEditTagRoute: BookBookIdEditTagRoute,
  BookBookIdEditIndexRoute: BookBookIdEditIndexRoute,
}

const BookBookIdEditRouteRouteWithChildren =
  BookBookIdEditRouteRoute._addFileChildren(BookBookIdEditRouteRouteChildren)

interface BookBookIdReadChapterIdRouteRouteChildren {
  BookBookIdReadChapterIdIndexRoute: typeof BookBookIdReadChapterIdIndexRoute
}

const BookBookIdReadChapterIdRouteRouteChildren: BookBookIdReadChapterIdRouteRouteChildren =
  {
    BookBookIdReadChapterIdIndexRoute: BookBookIdReadChapterIdIndexRoute,
  }

const BookBookIdReadChapterIdRouteRouteWithChildren =
  BookBookIdReadChapterIdRouteRoute._addFileChildren(
    BookBookIdReadChapterIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  MainLayoutRoute: MainLayoutRouteWithChildren,
  BookBookIdEditRouteRoute: BookBookIdEditRouteRouteWithChildren,
  BookBookIdReadChapterIdRouteRoute:
    BookBookIdReadChapterIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
