import { SYSTEM_SHELF_SLUGS } from "./system-slugs";

/**
 * Platform-wide reserved slugs.
 *
 * Applied uniformly across every slug scope (`user`, `realm`, `tag`, `zone`,
 * `entity`, and owner-scopes). A word reserved in any scope is reserved in
 * every scope.
 *
 * When adding new platform routes, owner sub-resource types, or
 * contract-defined system slug values, add them here.
 *
 * 平台级保留 slug。
 *
 * 在每个 slug 作用域（`user`、`realm`、`tag`、`zone`、`entity` 以及
 * owner 作用域）中统一应用。在任一作用域中保留的词，在每个作用域中均被保留。
 *
 * 新增平台路由、owner 子资源类型或 contract 定义的系统 slug 值时，
 * 请在此处添加。
 */

const RESERVED: readonly string[] = [
  // ── Platform routes 平台路由 ──────────────────────────────────
  "tag",
  "tags",
  "realm",
  "realms",
  "book",
  "books",
  "shelf",
  "shelves",
  "chapter",
  "chapters",
  "search",
  "explore",
  "feed",
  "feeds",
  "trending",
  "discover",
  "browse",
  "library",
  "catalog",
  "catalogue",
  "collection",
  "collections",
  "reading",
  "readlist",
  "readlists",
  "wishlist",
  "wishlists",
  "bookmark",
  "bookmarks",
  "favorites",
  "favourites",
  "popular",
  "recent",
  "latest",
  "newest",
  "featured",
  "recommended",
  "suggestions",
  "genres",
  "category",
  "categories",
  "series",
  "author",
  "authors",
  "publisher",
  "publishers",
  "review",
  "reviews",
  "rating",
  "ratings",
  "comment",
  "comments",
  "discussion",
  "discussions",
  "forum",
  "forums",
  "thread",
  "threads",
  "post",
  "posts",
  "activity",
  "timeline",
  "notifications",
  "messages",
  "inbox",
  "invite",
  "invites",
  "invitation",
  "invitations",
  "create",
  "edit",
  "delete",
  "new",
  "upload",
  "import",
  "export",
  "download",
  "share",
  "report",

  // ── Auth / account 认证 / 账户 ────────────────────────────────
  "login",
  "logout",
  "signin",
  "sign-in",
  "signout",
  "sign-out",
  "signup",
  "sign-up",
  "register",
  "account",
  "accounts",
  "settings",
  "password",
  "profile",
  "profiles",
  "preferences",
  "confirm",
  "verify",
  "verification",
  "recovery",
  "recover",
  "reset",
  "activate",
  "deactivate",
  "unsubscribe",
  "subscribe",
  "session",
  "sessions",
  "two-factor",
  "mfa",
  "sso",

  // ── Roles / identities 角色 / 身份 ────────────────────────────
  "admin",
  "admins",
  "administrator",
  "administrators",
  "moderator",
  "moderators",
  "staff",
  "support",
  "official",
  "system",
  "root",
  "owner",
  "owners",
  "security",
  "superuser",
  "super-user",
  "manager",
  "managers",
  "editor",
  "editors",
  "reviewer",
  "reviewers",
  "curator",
  "curators",
  "member",
  "members",
  "contributor",
  "contributors",
  "operator",
  "service",
  "bot",
  "bots",

  // ── Technical 技术 ────────────────────────────────────────────
  "api",
  "graphql",
  "rest",
  "assets",
  "static",
  "cdn",
  "webhook",
  "webhooks",
  "callback",
  "callbacks",
  "oauth",
  "auth",
  "token",
  "tokens",
  "config",
  "configuration",
  "debug",
  "health",
  "healthcheck",
  "metrics",
  "monitor",
  "monitoring",
  "logs",
  "logging",
  "analytics",
  "telemetry",
  "cron",
  "worker",
  "workers",
  "queue",
  "queues",
  "cache",
  "proxy",
  "gateway",
  "internal",
  "public",
  "private",
  "staging",
  "production",
  "development",
  "sandbox",
  "console",
  "dashboard",
  "panel",
  "control",
  "embed",
  "widget",
  "widgets",
  "plugin",
  "plugins",
  "extension",
  "extensions",
  "integration",
  "integrations",
  "connect",
  "disconnect",
  "socket",
  "stream",
  "streams",
  "event",
  "events",
  "notification",
  "push",
  "pull",
  "sync",
  "backup",
  "restore",
  "migrate",
  "migration",
  "schema",
  "database",
  "server",
  "client",
  "redirect",

  // ── Navigation 导航 ───────────────────────────────────────────
  "help",
  "docs",
  "documentation",
  "about",
  "about-us",
  "terms",
  "terms-of-service",
  "privacy",
  "privacy-policy",
  "contact",
  "contact-us",
  "pricing",
  "billing",
  "status",
  "blog",
  "news",
  "changelog",
  "updates",
  "release",
  "releases",
  "release-notes",
  "faq",
  "careers",
  "jobs",
  "press",
  "media",
  "legal",
  "copyright",
  "trademark",
  "guidelines",
  "community",
  "partners",
  "affiliates",
  "developers",
  "developer",
  "sitemap",
  "robots",
  "manifest",
  "humans",
  "security-txt",
  "well-known",
  "favicon",
  "home",
  "index",
  "landing",
  "welcome",
  "getting-started",
  "onboarding",
  "tour",
  "tutorial",
  "tutorials",
  "guide",
  "guides",
  "learn",
  "education",
  "resources",
  "support-center",
  "knowledge-base",
  "wiki",
  "handbook",

  // ── Common confusable 常见易混词 ──────────────────────────────
  "me",
  "myself",
  "you",
  "null",
  "undefined",
  "none",
  "void",
  "true",
  "false",
  "test",
  "testing",
  "example",
  "sample",
  "demo",
  "anonymous",
  "deleted",
  "unknown",
  "nobody",
  "noone",
  "no-one",
  "everyone",
  "everybody",
  "anyone",
  "someone",
  "something",
  "default",
  "placeholder",
  "temp",
  "temporary",
  "unused",

  // ── Brand 品牌 ────────────────────────────────────────────────
  "rezics",
  "rezics-team",
  "rezics-official",
  "rezics-admin",
  "rezics-support",
  "rezics-bot",

  // ── Owner-path segments (under /u/:slug, /r/:slug, …) ────────
  // Type-prefix segments that appear after an owner slug. Reserved
  // globally to keep owner-scope URL parsing unambiguous.
  // 出现在 owner slug 之后的类型前缀段。全局保留，以保持
  // owner 作用域 URL 解析无歧义。
  "list",
];

export const RESERVED_SLUGS: ReadonlySet<string> = new Set([
  ...RESERVED,
  ...SYSTEM_SHELF_SLUGS,
]);
