import { t } from "elysia";

export {
  APP_LANGUAGE_SLUGS,
  APP_LANGUAGES,
  type AppLanguage,
  CONTENT_LANGUAGE_SLUGS,
  CONTENT_LANGUAGES,
  type ContentLanguage,
  contentLanguageMeta,
  DEFAULT_LANGUAGE,
  FALLBACK_LANGUAGE,
  francMinLanguageToContentLanguage,
  LANGUAGE_META,
  LANGUAGES,
  type Language,
  normalizeContentLanguage,
  normalizeLanguage,
  REZICS_LANGUAGE_REGISTRY,
} from "./language-core";

const APP_LANGUAGE_LITERALS = [
  t.Literal("zh-hant"),
  t.Literal("zh-hans"),
  t.Literal("en"),
  t.Literal("ja"),
  t.Literal("de"),
  t.Literal("ko"),
] as const;

export const appLanguageSchema = t.Union([...APP_LANGUAGE_LITERALS]);

export const contentLanguageSchema = t.Union([
  ...APP_LANGUAGE_LITERALS,
  t.Literal("am"),
  t.Literal("ar"),
  t.Literal("az"),
  t.Literal("be"),
  t.Literal("bn"),
  t.Literal("bho"),
  t.Literal("bg"),
  t.Literal("bs"),
  t.Literal("ceb"),
  t.Literal("ckb"),
  t.Literal("cs"),
  t.Literal("el"),
  t.Literal("es"),
  t.Literal("fa"),
  t.Literal("ff"),
  t.Literal("fr"),
  t.Literal("gu"),
  t.Literal("ha"),
  t.Literal("hi"),
  t.Literal("hms"),
  t.Literal("hnj"),
  t.Literal("hr"),
  t.Literal("hu"),
  t.Literal("ig"),
  t.Literal("ilo"),
  t.Literal("id"),
  t.Literal("it"),
  t.Literal("jv"),
  t.Literal("kn"),
  t.Literal("kk"),
  t.Literal("rw"),
  t.Literal("koi"),
  t.Literal("ln"),
  t.Literal("mad"),
  t.Literal("mag"),
  t.Literal("mai"),
  t.Literal("ml"),
  t.Literal("mr"),
  t.Literal("my"),
  t.Literal("nl"),
  t.Literal("ne"),
  t.Literal("ny"),
  t.Literal("pa"),
  t.Literal("ps"),
  t.Literal("mg"),
  t.Literal("pl"),
  t.Literal("pt"),
  t.Literal("qug"),
  t.Literal("ro"),
  t.Literal("rn"),
  t.Literal("ru"),
  t.Literal("si"),
  t.Literal("skr"),
  t.Literal("sco"),
  t.Literal("so"),
  t.Literal("sr"),
  t.Literal("su"),
  t.Literal("sv"),
  t.Literal("sw"),
  t.Literal("ta"),
  t.Literal("te"),
  t.Literal("tl"),
  t.Literal("th"),
  t.Literal("tr"),
  t.Literal("uk"),
  t.Literal("ur"),
  t.Literal("uz"),
  t.Literal("vi"),
  t.Literal("yo"),
  t.Literal("ms"),
  t.Literal("zu"),
  t.Literal("za"),
]);

export const languageSchema = appLanguageSchema;
