import { t } from "elysia";

export {
  APP_LANGUAGE_SLUGS,
  APP_LANGUAGES,
  type AppLanguage,
  CONTENT_LANGUAGE_SLUGS,
  CONTENT_LANGUAGES,
  type ContentLanguage,
  contentLanguageMeta,
  DEFAULT_LANGUAGE,
  FALLBACK_LANGUAGE,
  francMinLanguageToContentLanguage,
  LANGUAGE_META,
  LANGUAGES,
  type Language,
  normalizeContentLanguage,
  normalizeLanguage,
  REZICS_LANGUAGE_REGISTRY,
} from "./language-core";

const APP_LANGUAGE_LITERALS = [
  t.Literal("zh-hant"),
  t.Literal("zh-hans"),
  t.Literal("en"),
  t.Literal("ja"),
  t.Literal("de"),
  t.Literal("ko"),
] as const;

export const appLanguageSchema = t.Union(APP_LANGUAGE_LITERALS);

export const contentLanguageSchema = t.Union([
  ...APP_LANGUAGE_LITERALS,
  t.Literal("amh"),
  t.Literal("arb"),
  t.Literal("azj"),
  t.Literal("bel"),
  t.Literal("ben"),
  t.Literal("bho"),
  t.Literal("bos"),
  t.Literal("bul"),
  t.Literal("ceb"),
  t.Literal("ces"),
  t.Literal("ckb"),
  t.Literal("ell"),
  t.Literal("fra"),
  t.Literal("fuv"),
  t.Literal("guj"),
  t.Literal("hau"),
  t.Literal("hin"),
  t.Literal("hms"),
  t.Literal("hnj"),
  t.Literal("hrv"),
  t.Literal("hun"),
  t.Literal("ibo"),
  t.Literal("ilo"),
  t.Literal("ind"),
  t.Literal("ita"),
  t.Literal("jav"),
  t.Literal("kan"),
  t.Literal("kaz"),
  t.Literal("kin"),
  t.Literal("koi"),
  t.Literal("lin"),
  t.Literal("mad"),
  t.Literal("mag"),
  t.Literal("mai"),
  t.Literal("mal"),
  t.Literal("mar"),
  t.Literal("mya"),
  t.Literal("nld"),
  t.Literal("npi"),
  t.Literal("nya"),
  t.Literal("pan"),
  t.Literal("pbu"),
  t.Literal("pes"),
  t.Literal("plt"),
  t.Literal("pol"),
  t.Literal("por"),
  t.Literal("qug"),
  t.Literal("ron"),
  t.Literal("run"),
  t.Literal("rus"),
  t.Literal("sin"),
  t.Literal("skr"),
  t.Literal("som"),
  t.Literal("spa"),
  t.Literal("srp"),
  t.Literal("sun"),
  t.Literal("swe"),
  t.Literal("swh"),
  t.Literal("tam"),
  t.Literal("tel"),
  t.Literal("tgl"),
  t.Literal("tha"),
  t.Literal("tur"),
  t.Literal("ukr"),
  t.Literal("urd"),
  t.Literal("uzn"),
  t.Literal("vie"),
  t.Literal("yor"),
  t.Literal("zlm"),
  t.Literal("zul"),
  t.Literal("zyb"),
]);

export const languageSchema = appLanguageSchema;
