export const TAG_REGISTRY_LANGUAGES = [
  "zh-hant",
  "zh-hans",
  "ja",
  "en",
] as const;

export type TagRegistryLanguage = (typeof TAG_REGISTRY_LANGUAGES)[number];

export type TagRegistryEntry = Record<TagRegistryLanguage, string>;

export const TAGS = {
  "science-fiction": {
    "zh-hant": "科幻",
    "zh-hans": "科幻",
    ja: "SF",
    en: "Science Fiction",
  },
  fantasy: {
    "zh-hant": "奇幻",
    "zh-hans": "奇幻",
    ja: "ファンタジー",
    en: "Fantasy",
  },
  xuanhuan: {
    "zh-hant": "玄幻",
    "zh-hans": "玄幻",
    ja: "玄幻",
    en: "Xuanhuan",
  },
  wuxia: { "zh-hant": "武俠", "zh-hans": "武侠", ja: "武侠", en: "Wuxia" },
  xianxia: { "zh-hant": "仙俠", "zh-hans": "仙侠", ja: "仙侠", en: "Xianxia" },
  urban: { "zh-hant": "都市", "zh-hans": "都市", ja: "都市", en: "Urban" },
  romance: { "zh-hant": "戀愛", "zh-hans": "恋爱", ja: "恋愛", en: "Romance" },
  harem: { "zh-hant": "後宮", "zh-hans": "后宫", ja: "ハーレム", en: "Harem" },
  "girls-love": {
    "zh-hant": "百合",
    "zh-hans": "百合",
    ja: "百合",
    en: "Girls' Love",
  },
  "boys-love": {
    "zh-hant": "耽美",
    "zh-hans": "耽美",
    ja: "BL",
    en: "Boys' Love",
  },
  otome: { "zh-hant": "乙女", "zh-hans": "乙女", ja: "乙女", en: "Otome" },
  comedy: {
    "zh-hant": "喜劇",
    "zh-hans": "喜剧",
    ja: "コメディ",
    en: "Comedy",
  },
  drama: { "zh-hant": "劇情", "zh-hans": "剧情", ja: "ドラマ", en: "Drama" },
  "slice-of-life": {
    "zh-hant": "日常",
    "zh-hans": "日常",
    ja: "日常",
    en: "Slice of Life",
  },
  school: { "zh-hant": "校園", "zh-hans": "校园", ja: "学園", en: "School" },
  workplace: {
    "zh-hant": "職場",
    "zh-hans": "职场",
    ja: "職場",
    en: "Workplace",
  },
  history: { "zh-hant": "歷史", "zh-hans": "历史", ja: "歴史", en: "History" },
  mystery: {
    "zh-hant": "懸疑",
    "zh-hans": "悬疑",
    ja: "ミステリー",
    en: "Mystery",
  },
  detective: {
    "zh-hant": "推理",
    "zh-hans": "推理",
    ja: "推理",
    en: "Detective",
  },
  thriller: {
    "zh-hant": "驚悚",
    "zh-hans": "惊悚",
    ja: "スリラー",
    en: "Thriller",
  },
  horror: { "zh-hant": "恐怖", "zh-hans": "恐怖", ja: "ホラー", en: "Horror" },
  adventure: {
    "zh-hant": "冒險",
    "zh-hans": "冒险",
    ja: "冒険",
    en: "Adventure",
  },
  action: {
    "zh-hant": "動作",
    "zh-hans": "动作",
    ja: "アクション",
    en: "Action",
  },
  war: { "zh-hant": "戰爭", "zh-hans": "战争", ja: "戦争", en: "War" },
  military: {
    "zh-hant": "軍事",
    "zh-hans": "军事",
    ja: "ミリタリー",
    en: "Military",
  },
  sports: {
    "zh-hant": "運動",
    "zh-hans": "运动",
    ja: "スポーツ",
    en: "Sports",
  },
  music: { "zh-hant": "音樂", "zh-hans": "音乐", ja: "音楽", en: "Music" },
  food: { "zh-hant": "美食", "zh-hans": "美食", ja: "グルメ", en: "Food" },
  travel: { "zh-hant": "旅行", "zh-hans": "旅行", ja: "旅行", en: "Travel" },
  healing: { "zh-hant": "治癒", "zh-hans": "治愈", ja: "癒し", en: "Healing" },
  moe: { "zh-hant": "萌系", "zh-hans": "萌系", ja: "萌え", en: "Moe" },
  "time-travel": {
    "zh-hant": "穿越",
    "zh-hans": "穿越",
    ja: "タイムトラベル",
    en: "Time Travel",
  },
  reincarnation: {
    "zh-hant": "轉生",
    "zh-hans": "转生",
    ja: "転生",
    en: "Reincarnation",
  },
  rebirth: { "zh-hant": "重生", "zh-hans": "重生", ja: "再生", en: "Rebirth" },
  isekai: {
    "zh-hant": "異世界",
    "zh-hans": "异世界",
    ja: "異世界",
    en: "Isekai",
  },
  system: {
    "zh-hant": "系統",
    "zh-hans": "系统",
    ja: "システム",
    en: "System",
  },
  "fan-fiction": {
    "zh-hant": "同人",
    "zh-hans": "同人",
    ja: "同人",
    en: "Fan Fiction",
  },
  supernatural: {
    "zh-hant": "超自然",
    "zh-hans": "超自然",
    ja: "超自然",
    en: "Supernatural",
  },
  superpower: {
    "zh-hant": "異能",
    "zh-hans": "异能",
    ja: "異能力",
    en: "Superpower",
  },
  cultivation: {
    "zh-hant": "修真",
    "zh-hans": "修真",
    ja: "修真",
    en: "Cultivation",
  },
  court: { "zh-hant": "宮廷", "zh-hans": "宫廷", ja: "宮廷", en: "Court" },
  politics: {
    "zh-hant": "權謀",
    "zh-hans": "权谋",
    ja: "権謀",
    en: "Political Intrigue",
  },
  business: {
    "zh-hant": "商業",
    "zh-hans": "商业",
    ja: "ビジネス",
    en: "Business",
  },
  family: { "zh-hant": "家庭", "zh-hans": "家庭", ja: "家族", en: "Family" },
  youth: { "zh-hant": "青春", "zh-hans": "青春", ja: "青春", en: "Youth" },
  tragedy: { "zh-hant": "悲劇", "zh-hans": "悲剧", ja: "悲劇", en: "Tragedy" },
  suspense: {
    "zh-hant": "懸念",
    "zh-hans": "悬念",
    ja: "サスペンス",
    en: "Suspense",
  },
  crime: { "zh-hant": "犯罪", "zh-hans": "犯罪", ja: "犯罪", en: "Crime" },
  mecha: { "zh-hant": "機戰", "zh-hans": "机战", ja: "メカ", en: "Mecha" },
  idol: { "zh-hant": "偶像", "zh-hans": "偶像", ja: "アイドル", en: "Idol" },
  magic: { "zh-hant": "魔法", "zh-hans": "魔法", ja: "魔法", en: "Magic" },
  monster: { "zh-hant": "怪物", "zh-hans": "怪物", ja: "怪物", en: "Monster" },
  vampire: {
    "zh-hant": "吸血鬼",
    "zh-hans": "吸血鬼",
    ja: "吸血鬼",
    en: "Vampire",
  },
  zombie: { "zh-hant": "喪屍", "zh-hans": "丧尸", ja: "ゾンビ", en: "Zombie" },
  "post-apocalyptic": {
    "zh-hant": "末世",
    "zh-hans": "末世",
    ja: "ポストアポカリプス",
    en: "Post-Apocalyptic",
  },
  cyberpunk: {
    "zh-hant": "賽博朋克",
    "zh-hans": "赛博朋克",
    ja: "サイバーパンク",
    en: "Cyberpunk",
  },
  steampunk: {
    "zh-hant": "蒸汽朋克",
    "zh-hans": "蒸汽朋克",
    ja: "スチームパンク",
    en: "Steampunk",
  },
  "detective-noir": {
    "zh-hant": "黑色偵探",
    "zh-hans": "黑色侦探",
    ja: "ノワール探偵",
    en: "Detective Noir",
  },
  "coming-of-age": {
    "zh-hant": "成長",
    "zh-hans": "成长",
    ja: "成長",
    en: "Coming of Age",
  },
  documentary: {
    "zh-hant": "紀錄",
    "zh-hans": "纪录",
    ja: "ドキュメンタリー",
    en: "Documentary",
  },
  "short-film": {
    "zh-hant": "短片",
    "zh-hans": "短片",
    ja: "短編映画",
    en: "Short Film",
  },
  "role-playing": {
    "zh-hant": "角色扮演",
    "zh-hans": "角色扮演",
    ja: "RPG",
    en: "Role-Playing",
  },
  "action-adventure": {
    "zh-hant": "動作冒險",
    "zh-hans": "动作冒险",
    ja: "アクションアドベンチャー",
    en: "Action Adventure",
  },
  strategy: {
    "zh-hant": "策略",
    "zh-hans": "策略",
    ja: "ストラテジー",
    en: "Strategy",
  },
  simulation: {
    "zh-hant": "模擬",
    "zh-hans": "模拟",
    ja: "シミュレーション",
    en: "Simulation",
  },
  "visual-novel": {
    "zh-hant": "視覺小說",
    "zh-hans": "视觉小说",
    ja: "ビジュアルノベル",
    en: "Visual Novel",
  },
  galgame: {
    "zh-hant": "美少女遊戲",
    "zh-hans": "美少女游戏",
    ja: "ギャルゲー",
    en: "Galgame",
  },
  "dating-sim": {
    "zh-hant": "戀愛模擬",
    "zh-hans": "恋爱模拟",
    ja: "恋愛シミュレーション",
    en: "Dating Sim",
  },
  battle: { "zh-hant": "戰鬥", "zh-hans": "战斗", ja: "バトル", en: "Battle" },
  fighting: {
    "zh-hant": "格鬥",
    "zh-hans": "格斗",
    ja: "格闘",
    en: "Fighting",
  },
  shooting: {
    "zh-hant": "射擊",
    "zh-hans": "射击",
    ja: "シューティング",
    en: "Shooting",
  },
  "first-person-shooter": {
    "zh-hant": "第一人稱射擊",
    "zh-hans": "第一人称射击",
    ja: "FPS",
    en: "First-Person Shooter",
  },
  "third-person-shooter": {
    "zh-hant": "第三人稱射擊",
    "zh-hans": "第三人称射击",
    ja: "TPS",
    en: "Third-Person Shooter",
  },
  platformer: {
    "zh-hant": "平台跳躍",
    "zh-hans": "平台跳跃",
    ja: "プラットフォーマー",
    en: "Platformer",
  },
  puzzle: { "zh-hant": "解謎", "zh-hans": "解谜", ja: "パズル", en: "Puzzle" },
  roguelike: {
    "zh-hant": "肉鴿",
    "zh-hans": "肉鸽",
    ja: "ローグライク",
    en: "Roguelike",
  },
  soulslike: {
    "zh-hant": "魂系",
    "zh-hans": "魂系",
    ja: "ソウルライク",
    en: "Soulslike",
  },
  metroidvania: {
    "zh-hant": "銀河惡魔城",
    "zh-hans": "银河恶魔城",
    ja: "メトロイドヴァニア",
    en: "Metroidvania",
  },
  sandbox: {
    "zh-hant": "沙盒",
    "zh-hans": "沙盒",
    ja: "サンドボックス",
    en: "Sandbox",
  },
  "open-world": {
    "zh-hant": "開放世界",
    "zh-hans": "开放世界",
    ja: "オープンワールド",
    en: "Open World",
  },
  survival: {
    "zh-hant": "生存",
    "zh-hans": "生存",
    ja: "サバイバル",
    en: "Survival",
  },
  crafting: {
    "zh-hant": "建造",
    "zh-hans": "建造",
    ja: "クラフト",
    en: "Crafting",
  },
  management: {
    "zh-hant": "經營",
    "zh-hans": "经营",
    ja: "経営",
    en: "Management",
  },
  "city-builder": {
    "zh-hant": "城市建造",
    "zh-hans": "城市建造",
    ja: "都市建設",
    en: "City Builder",
  },
  "tower-defense": {
    "zh-hant": "塔防",
    "zh-hans": "塔防",
    ja: "タワーディフェンス",
    en: "Tower Defense",
  },
  "card-game": {
    "zh-hant": "卡牌",
    "zh-hans": "卡牌",
    ja: "カードゲーム",
    en: "Card Game",
  },
  "board-game": {
    "zh-hant": "桌遊",
    "zh-hans": "桌游",
    ja: "ボードゲーム",
    en: "Board Game",
  },
  rhythm: { "zh-hant": "音樂", "zh-hans": "音乐", ja: "リズム", en: "Rhythm" },
  racing: { "zh-hant": "競速", "zh-hans": "竞速", ja: "レース", en: "Racing" },
  "survival-horror": {
    "zh-hant": "生存恐怖",
    "zh-hans": "生存恐怖",
    ja: "サバイバルホラー",
    en: "Survival Horror",
  },
} as const satisfies Record<string, TagRegistryEntry>;

export type TagSlug = keyof typeof TAGS;
